### ISSUE TITLE
Profiler does not capture any data

### ISSUE THREAD

**Issue by djensen47** [GoogleCloudPlatform/google-cloud-go#1000]
We followed the instructions in the tutorial to the letter. And given that there really isn't much there, we're baffled why it doesn't work.

https://cloud.google.com/profiler/docs/profiling-go

We're running on GKE so we followed those instructions, which indicate that we don't need to set the projectID. However, we have tried both with and without the ProjectID.

It also turns out that we do not have an error starting the profiler, in fact we have the opposite. This is in our logs: `profiler has started`, which comes from the library: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/cfeafe7ade128e8ed6fc24296897c6a53d162ed2/profiler/profiler.go#L502

For completeness, I'll include the code but, again, it's the same as the tutorial:

```golang
if err := profiler.Start(profiler.Config{Service: "batch-service", ProjectID: "redacted", ServiceVersion: "1.3.0"}); err != nil {
	log.Println("ERROR Loading StackDriver profiler:", err)
}
```

**Comment by Nalum** [comment]
I am seeing this issue also. When `DebugLogging: true` is set I get the following error in the output:

```
failed to create a profile, will retry: rpc error: code = InvalidArgument desc = Request contains an invalid argument.
```

I can see in the APIs & Services area of GCP there are a bunch of 400 errors listed in the charts.

**Comment by aalexand** [comment]
@Nalum @djensen47 Your issues may be different.

@Nalum What's the code that enables the profiler? InvalidArgument error may come from using invalid format for the service name, see https://cloud.google.com/profiler/docs/profiling-go#svc-name-and-version.

@djensen47 Do you mind contacting me directly using aalexand at google's domain so we can debug this?

**Comment by Nalum** [comment]
@aalexand ah, thank you. That was indeed the issue.

**Comment by djensen47** [comment]
@aalexand Thanks for the help everything is working now.

For those following along. Since we're using Alpine Linux there are no ca-certificates installed by default. In order to use the Google APIs those certs need to be in place.

**Comment by aalexand** [comment]
@djensen47 Great. Can you share the command you used to install the certificates? I'll consider adding a hint to documentation.

**Comment by djensen47** [comment]
Yeah, on Alpine Linux this should work:

```
$ apk update
$ apk add --no-cache ca-certificates
```

What I did specifically was to add the following to my `Dockerfile`

```
RUN apk update \
 && apk add --no-cache ca-certificates
```
