### ISSUE TITLE
Dependency compatibility issues with google.golang.org/api and cloud.google.com/go

### ISSUE THREAD

**Issue by ChrisBartonLC** [GoogleCloudPlatform/google-cloud-go#1001]
## Client

google.golang.org/api
google.golang.org/grpc
cloud.google.com/go

## Describe Your Environment

In an AppEngine Flex Go service we use pubsub/spanner/datastore/firestore/firebase admin apis and "google.golang.org/api" for metrics and the spanner iterator and when building after running "dep init" we get this error message:

`go
src/lc-api-cover/vendor/cloud.google.com/go/firestore/query.go:163:40: too few values in struct initializer
`

We've had this message for a while and we could previously solve it using this in our Gopkg.toml but this no longer works:

    [[override]]
     name = "github.com/golang/protobuf"
     version = "~1.0.0"

## Expected Behavior

Our service builds even if we need to pin some dependencies

## Actual Behavior
Dependency compatibility issues

`go
src/lc-api-cover/vendor/cloud.google.com/go/firestore/query.go:163:40: too few values in struct initializer
`

**Comment by jadekler** [comment]
Do you have the latest version of this library? I just fixed that in https://github.com/GoogleCloudPlatform/google-cloud-go/commit/d011423af2899e53bf9981a5c0e5e54d5e7c7de2

**Comment by jadekler** [comment]
Ah! Right on. Sorry about breaking y'all!

**Comment by jba** [comment]
v0.23.0 is now released and has the fixes.
