### ISSUE TITLE
Bigquery Go client: Retry for 403, Quota Exceeded Error

### ISSUE THREAD

**Issue by ruiyang2015** [GoogleCloudPlatform/google-cloud-go#1003]
This time, we are seeing this from Bigquery client:
`Bigquery stream error while reading one row: type: *googleapi.Error, error: googleapi: Error 403: Quota exceeded: Your 878926448773 exceeded quota for tabledata.list bytes per second per project. For more information, see https://cloud.google.com/bigquery/troubleshooting-errors, quotaExceeded\" Description: BigQuery rate limit exceeded, try to wait some time and retry`
It seems the retry logic need to add this case as retry error too.
[recently, 502 and 503 got added](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/bigquery.go#L163)

**Comment by ruiyang2015** [comment]
ideally, we can add this ` reason == "quotaExceeded" ` to the list

**Comment by jba** [comment]
Which call is producing that error?

Can you confirm that `reason == "quotaExceeded"` by printing the message with `%#v`?

Retrying might not be the best solution in your case. If you're consistently at a high load, you may want to request a quota increase, or implement adaptive throttling (see [Client-Side Throttling](https://landing.google.com/sre/book/chapters/handling-overload.html)).

**Comment by ruiyang2015** [comment]
it is from tabeldata.list call

**Comment by ruiyang2015** [comment]
any update on this issue? this happens when our BigQuery Table has billions of rows, and iterate all rows may cause this issue, we already add a sleep at each pagination boundary, but occasional `quotaExceeded` error will cause the read to reset reading from beginning again.  Add retry for the quotaExceeded error will help this case.

**Comment by jba** [comment]
No update yet. I poked the internal discussion.

**Comment by jba** [comment]
I received a definitive reply from the backend team on this (Google-internal issue 111613035). The error you're seeing is a relatively long-term quota-exceeded error, and aggressive retrying would only make things worse. 

The right behavior is to retry after a longer period (a minute or more). Also, as suggested above, you may request more quota. 

You should be able to remember the page token as you iterate, and if you get an error, create a new iterator and set `RowIterator.PageInfo().Token` to the most recent page token.
