### ISSUE TITLE
BiqQuery CSV importer error reporting not helpful

### ISSUE THREAD

**Issue by retnuh** [GoogleCloudPlatform/google-cloud-go#1004]
(delete this for feature requests)

## Client*

golang 1.10 + BigQuery v0.19.0
golang 1.10.2 + BigQuery v0.22.0

## Describe Your Environment

Centos7 Docker running on Ubuntu (cross-compiled from MacOS)

## Expected Behavior

What is invalid is actually described

## Actual Behavior

Cryptic error message

`{Location: "kid=70943:mkey=customer_encrypt_cns/file-00000000"; Message: "Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 363; errors: 1. Please look into the error stream for more details."; Reason: "invalid"}`

Hi there, I have an application where I create a CSV of rows to import into BigQuery.  In production it occasionally fails with a message similar to the above.  In particular, the `Reason: "invalid"` is quite unhelpful, and I don't know what it's talking about the error stream; what error stream?

It's particularly puzzling because the same code, compiled and running on the Mac, against the same data, doesn't exhibit the error.  I've spent quite a bit of time trying to reproduce it but with no real luck.  The only thing that I have to go on is that the bad data usually seems to have non-ascii characters in the data, but again, I can't really tell what's going on because the poor error message and the fact that it works in the dev environment.

The code in question looks like this:
```
                // ...
		var b bytes.Buffer
		w := csv.NewWriter(&b)
                // ...
 
		w.Flush()
		if err := w.Error(); err != nil {
			return errors.Wrap(err, "Could not flush CSV writer")
		}

                // ...

		rs := bigquery.NewReaderSource(&b)
		rs.Schema = storySchema
		loader := table.LoaderFrom(rs)
		job, err := loader.Run(ctx)
		if err != nil {
			return errors.Wrapf(err, "creating loader job batchsize: %d", len(batch))
		}
		status, err := job.Wait(ctx)
		if err != nil {
			return errors.Wrapf(err, "waiting for upload job to finish batchsize: %d", len(batch))
		}
                // This is where error gets reported
		if err := status.Err(); err != nil {
			row := detectErrorRow(err.Error())
			return errors.Wrapf(err, "err after job wait/complete: %d %d %s %v", len(batch), row, batch[row].Filename, strings.Join(rows[row], "#"))
		}
```

* I've run this with both v0.19.0 on golang 1.10 and v0.22.0 on golang 1.10.2

**Comment by retnuh** [comment]
Hmm no I have not, I didn't even know about it.  I may try to see if I can get something from it the next time it comes up, but since I can't reproduce it in a dev environment, and we've already worked around it in prod, I'm not sure how easy that will be. 

My overall point that the error message is not helpful still stands, though.

But thanks for the tip!

**Comment by shollyman** [comment]
This looks less like an issue with the Go library specifically, and more an issue with how the backend reports some errors.  I've created an internal issue (80432918) for the BigQuery team to examine that in more detail.

**Comment by retnuh** [comment]
Yes I got the sense that the "error stream" meant errors on the backend.

**Comment by jba** [comment]
Closing, since this is a BigQuery service issue.

**Comment by dbaroncelli** [comment]
@retnuh  I had the same problem.
You can get more details, just by printing status.Errors, as @jba said

**Comment by wandermyz** [comment]
I had the same problem when using Big Query web UI.

What is 'JobStatus.Errors'? 
How do I print status and errors?

**Comment by jba** [comment]
The first value returned by `Wait` is a `JobStatus`. It has a field called `Errors`. See https://godoc.org/cloud.google.com/go/bigquery#JobStatus.

Loop over the errors and print them out:
```
status, err := job.Wait(ctx)
if err != nil { /* handle */ }
for _, e := range status.Errors {
    fmt.Printf("%+v\n", e)
}
```

**Comment by aryjazz** [comment]
you can run this command in the terminal and you should receive a more specific message.
bq --format=prettyjson show -j <JobID>
Check this link: https://stackoverflow.com/questions/52100812/bigquery-where-can-i-find-the-error-stream

**Comment by shammishailaj** [comment]
> The first value returned by `Wait` is a `JobStatus`. It has a field called `Errors`. See https://godoc.org/cloud.google.com/go/bigquery#JobStatus.
> 
> Loop over the errors and print them out:
> 
> ```
> status, err := job.Wait(ctx)
> if err != nil { /* handle */ }
> for _, e := range status.Errors {
>     fmt.Printf("%+v\n", e)
> }
> ```

Worked for me. Earlier I would have to go to the Bigquery console to see the error. Now, I can see that in my code's output directly. Thanks.
