### ISSUE TITLE
Fail to write to Bigtable with Table.ApplyBulk on GKE

### ISSUE THREAD

**Issue by aseure** [GoogleCloudPlatform/google-cloud-go#1012]
## Client

Bigtable v0.21.0.

## Describe Your Environment

Alpine Docker on GKE (`1.10.2-gke.1`) running our Go binary. Only other command in the Dockerfile is `apk add --update --no-cache ca-certificates`.

## Expected Behavior

A call to `bigtable.Table.ApplyBulk` should succeed on GKE.

## Actual Behavior

The entire process error (2nd return value of `errs, err := bigtable.Table.ApplyBulk(...)`) is consistently returning:
```
rpc error: code = Unauthenticated desc = transport: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token: net/http: timeout awaiting response headers
```
when our code is running on GKE. The exact same call, with the same parameters, succeeds when ran locally on our workstations.

Note that our implementation is calling `ApplyBulk` concurrently to send sub-parts of a 12M mutations batch, 10k at a time (because of https://github.com/GoogleCloudPlatform/google-cloud-go/issues/733). We try to send batch of 100k elements, the behavior is the same (works locally but doesn't work on GKE).

**Comment by jba** [comment]
Could you try running it locally, but from the container? Let's separate GKE from running under docker.

**Comment by garye** [comment]
@aseure, that link doesn't work for me. Is that an internal thing? I'm curious to learn more about your batching...

**Comment by aseure** [comment]
@jba We've changed our implementation to make smaller batches and it worked. I won't be able to reproduce in a local docker container anytime soon. To our understanding, it seemed that sending very large batches was the issue. If it's the case, the error is definitely too cryptic. Could it be possible that an authentication quota was reached?

@garye Yes indeed, I pasted an incorrect link. I've edited my initial message with the correct link to the appropriate PR.

**Comment by jba** [comment]
@aseure That seems plausible. I don't think we (BigTable client) can do anything about the error; it's not from the client.

**Comment by sduskis** [comment]
This was a problem on the machine itself, and not the golang client.  This is the core of the problem:

`rpc error: code = Unauthenticated desc = transport: Get http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token: net/http: timeout awaiting response headers`
