### ISSUE TITLE
not recognize audio err Unauthenticated Google Speech

### ISSUE THREAD

**Issue by SKletsov** [GoogleCloudPlatform/google-cloud-go#1013]
i am used go libraly 

i am export JSON key 
after i start application 

[root@voip_master go]# go run google.go
2018/05/30 20:59:53 failed to recognize: rpc error: code = Unauthenticated desc = transport: private key should be a PEM or plain PKSC1 or PKCS8; parse error: asn1: syntax error: sequence truncated
exit status 1

**Comment by SKletsov** [comment]
`// Sample speech-quickstart uses the Google Cloud Speech API to transcribe
// audio.
package main

import (
	"fmt"
	"io/ioutil"
	"log"

	// Imports the Google Cloud Speech API client package.
	"golang.org/x/net/context"

	speech "cloud.google.com/go/speech/apiv1"
	speechpb "google.golang.org/genproto/googleapis/cloud/speech/v1"
)

func main() {
	ctx := context.Background()

	// Creates a client.
	client, err := speech.NewClient(ctx)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}

	// Sets the name of the audio file to transcribe.
	filename := "/usr/local/freeswitch/recordings/79172752313.wav"

	// Reads the audio file into memory.
	data, err := ioutil.ReadFile(filename)
	if err != nil {
		log.Fatalf("Failed to read file: %v", err)
	}

	// Detects speech in the audio file.
	resp, err := client.Recognize(ctx, &speechpb.RecognizeRequest{
		Config: &speechpb.RecognitionConfig{
			Encoding:        speechpb.RecognitionConfig_LINEAR16,
			SampleRateHertz: 16000,
			LanguageCode:    "en-US",
		},
		Audio: &speechpb.RecognitionAudio{
			AudioSource: &speechpb.RecognitionAudio_Content{Content: data},
		},
	})
	if err != nil {
		log.Fatalf("failed to recognize: %v", err)
	}

	// Prints the results.
	for _, result := range resp.Results {
		for _, alt := range result.Alternatives {
			fmt.Printf("\"%v\" (confidence=%3f)\n", alt.Transcript, alt.Confidence)
		}
	}
}`

**Comment by jba** [comment]
That works for me. I think there must be something wrong with your application default credentials. What do you mean when you say you exported the JSON key?

**Comment by SKletsov** [comment]
[root@voip_master ~]# export GOOGLE_APPLICATION_CREDENTIALS=/usr/local/freeswitch/certs/client_secret_129010056973-tu099lv099kqonn2iebaj3nvgcl8256n.apps.googleusercontent.com\ .json

**Comment by jba** [comment]
The form of that file is odd. If type is "service_account", then there should be a "private_key" field. Did you get that file by downloading it from the Google Cloud console?

**Comment by SKletsov** [comment]
{
"installed":
{
"client_id":"12345",
"project_id":"my project",
"auth_uri":"https://accounts.google.com/o/oauth2/auth",
"token_uri":"https://accounts.google.com/o/oauth2/token",
"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
"client_secret":"very sercret",
"redirect_uris":
["urn:ietf:wg:oauth:2.0:oob","http://localhost"]
}
}

if we are used this JSON 

This ERR
root@voip_master go]# go run google.go
2018/05/30 23:08:47 Failed to create client: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: missing 'type' field in credentials
exit status 1

**Comment by jba** [comment]
That JSON also has the wrong form. Where are these files coming from?

**Comment by jadekler** [comment]
Friendly ping @SKletsov

**Comment by anwayauber** [comment]
@SKletsov you probably downloaded the JSON under "OAuth 2.0 client IDs" from your [Google Cloud Console](https://console.cloud.google.com/projectselector/home/dashboard?organizationId=0&supportedpurview=project). I made the same mistake and then manually added the 

> "type": "service_account"

field due to the error. Instead you should be creating a new ID under`Service account keys` and then use the json off of that.
