### ISSUE TITLE
Storage: enable bucket logging

### ISSUE THREAD

**Issue by guanzo** [GoogleCloudPlatform/google-cloud-go#1014]
Is there a way to enable bucket logging? 
https://cloud.google.com/storage/docs/access-logs

The google cloud python library has this functionality: [docs link](https://google-cloud-python.readthedocs.io/en/latest/storage/buckets.html#google.cloud.storage.bucket.Bucket.enable_logging)

I couldn't find anything in the documentation about logging. If the functionality isn't there yet, i'd like to submit it as a feature request.

**Comment by jba** [comment]
This was done at 122c810c72569ea143e5d54ed2b041f4b3e56200.
