### ISSUE TITLE
sub.Receive memory concerns

### ISSUE THREAD

**Issue by SebScoFr** [GoogleCloudPlatform/google-cloud-go#1016]
## Client

PubSub

## Environment

golang:latest on GKE

## Expected Behavior

sub.Receive to release memory after the execution of each goroutine.

## Actual Behavior

My program processes messages asynchronously from a PubSub subscription.
When the processing is done, memory is not released. Check the following graph from Stackdriver.

![Stackdriver](https://preview.ibb.co/jsUetJ/Screen_Shot_2018_05_31_at_16_16_02.png)

I'm still fairly new to Go but my understanding is that Receive will spawn a new goroutine for each message it processes and terminate it when the processing is done. Am I missing something obvious?

The code looks like this:
```go
client, err := pubsub.NewClient(context.Background(), "my-project-id")
if err != nil {
    log.Fatalf("Failed to create the Pub/Sub client: %v", err)
}

sub := client.Subscription("my-subscription")
sub.ReceiveSettings = pubsub.ReceiveSettings{
    MaxOutstandingMessages: 5,
    NumGoroutines: 1,
}

var mutex sync.Mutex

err = sub.Receive(context.Background(), func(ctx context.Context, m *pubsub.Message) {
    start := time.Now()
    defer m.Ack()

    // Do whatever

    elapsed := time.Since(start)
    mutex.Lock()
    log.Printf("Processed message in %s", elapsed)
    mutex.Unlock()
})
if err != nil {
    log.Fatalf("Pub/Sub Subscription failure: %v", err)
}
```

**Comment by jba** [comment]
I assume you're actually checking errors where you've written `_`. You should also check the error on `file.Close`, since you're writing the file.

**Comment by SebScoFr** [comment]
Yes, for clarity I removed part of my code here, but I check for all of those errors indeed. Nothing to report unfortunately.
