### ISSUE TITLE
Signed URLs have wrong/deprecated parameters?

### ISSUE THREAD

**Issue by IvanMartinez** [GoogleCloudPlatform/google-cloud-go#1021]
## Client

Storage

## Describe Your Environment

go version go1.10.1 darwin/amd64
google-cloud-sdk 200.0.0
cloud.google.com/go v0.23.0 0fd7230b2a7505833d5f69b75cbd6c9582401479

## Expected Behavior

Signed URLs generated with `gcloud signurl` are of the format:
```
https://storage.googleapis.com/bucket/file?x-goog-signature=...&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=service-account%2Fregion%2Fstorage%2Fgoog4_request&x-goog-date=20180605T083219Z&x-goog-expires=600&x-goog-signedheaders=host
```

## Actual Behavior

Signed URLs generated with this library are of the format:
```
https://storage.googleapis.com/bucket/file?Expires=1528119168\u0026GoogleAccessId=service-account\u0026Signature=...`
```
URL parameters don't match at all. The URLs don't work, I always get a HTTP 403 response with the following body:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to delivered-im-dev-media/test.jpg.
</Details>
</Error>
```
I get the same response if I remove all parameters or use bogus parameter names.

**Comment by IvanMartinez** [comment]
I was able to generate working URL with the library in another piece of code, so the URLs are right despite the differences.

**Comment by sbsends** [comment]
@IvanMartinez: Can you provide a working example? I am receiving the same error as you.
