### ISSUE TITLE
Firestone: real time updates to clients not supported ?

### ISSUE THREAD

**Issue by gedw99** [GoogleCloudPlatform/google-cloud-go#1024]
(delete this for feature requests)

## Describe Your Environment

Golang latest on localhost.

I read on the firestire official docs that golang client does not support real time updates to the client. Other languages do.

Can you confirm please ?
Will it be fixed ?

## Expected Behavior

e.g. Messages arrive really fast.

## Actual Behavior

e.g. Messages arrive really slowly.

**Comment by jba** [comment]
It does. See [DocumentRef.Snapshots](https://godoc.org/cloud.google.com/go/firestore#DocumentRef.Snapshots) and [Query.Snapshots](https://godoc.org/cloud.google.com/go/firestore#Query.Snapshots).

Can you point us to the doc page that said otherwise?

**Comment by zkdzegede** [comment]
@jba 

https://firebase.google.com/docs/firestore/query-data/listen

```
Note: Realtime listeners are not yet supported in the Python, Go, or PHP client libraries.
```

and when you try to view a sample

```
// Not yet supported in Go client library
```

**Comment by gedw99** [comment]
Thank you for adding that.
That is the exact source I also found the info from.

**Comment by jba** [comment]
There is an internal bug to update that page. Thanks for notifying us.

**Comment by gedw99** [comment]
@jba Ok great to hear that its the web page and not the golang SDK lacking that functionality...

**Comment by renannprado** [comment]
Can't get the realtime updates to work.

```go
snapshot, err := client.Collection("scheduledCommands").Query.Snapshots(context.Background()).Next()
```

What I'm trying to achieve is: whenever a document is added to a collection, I want to receive an event, but I can't get it to work.
