### ISSUE TITLE
Question about NullString type

### ISSUE THREAD

**Issue by AOHUA** [GoogleCloudPlatform/google-cloud-go#1028]
Expected:
Return "\<null\>" if the value is null otherwise return the string value.

Currently:
Return "\<null\>" if the value is null otherwise return the string value with double quotes.

```
// String implements Stringer.String for NullString
func (n NullString) String() string {
	if !n.Valid {
		return fmt.Sprintf("%v", "<null>")
	}
	return fmt.Sprintf("%q", n.StringVal)
}
```

What is the reason to wrap the string value with double quotes?  Thank you!

**Comment by jba** [comment]
The `String` method is for formatting, so the author felt using `%q` would be the best choice.

If you want the string to display another way, just access `n.StringVal` directly.

**Comment by jba** [comment]
You can also try using [strconv.Unquote](https://godoc.org/strconv#Unquote), which should be the inverse of `%q`.
