### ISSUE TITLE
Firestore: Ability to bypass Cloud Firestore Rules

### ISSUE THREAD

**Issue by zkdzegede** [GoogleCloudPlatform/google-cloud-go#1029]
(delete this for feature requests)

I originally commented here: https://github.com/firebase/firebase-ios-sdk/issues/469

## Client

- I am using this library directly similar to [Golang examples](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/firestore/apiv1beta1/firestore_client_example_test.go)

## Describe Your Environment

- Golang client on mac or docker (for development), linux for production.
- e.g. go run main.go 
- Note I am *not* aiming to use this as a 'server client', but rather as a full client that will be sent out to users when in production.  I only mention this because it was suggested I use IAM elsewhere, and I don't think that solves the issue.

## Expected Behavior

Rules
```
match /device/{document=**} {
    allow read, write: if request.auth.uid == resource.data.owner;
}
```

- Cloud Firestore Rules prevents unwanted access through JS SDK
- Cloud Firestore Rules prevents unwanted access through REST (curl)
- Cloud Firestore Rules prevents unwanted access through [Golang examples](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/firestore/apiv1beta1/firestore_client_example_test.go)

## Actual Behavior

- ✅  JS SDK requires the proper authentication per my rules 
- ✅  REST (curl) requires the proper authentication per my rules
- ❌  The [Golang examples](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/firestore/apiv1beta1/firestore_client_example_test.go) is able to bypass my rules and read the whole Firestore even though I did zero authentication.

**Comment by zkdzegede** [comment]
Here's how I was able to bypass my rules, for both "get documents from collection" and "stream specific document".

```
func main() {
	docs()
	fmt.Println("************************************")
	for {
		err := listen()
		if err != nil {
			fmt.Println("listen error:", err)
		}
	}
}

func docs() {
	fmt.Println("start: doc")
	ctx := context.Background()
	c, err := firestore.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
		fmt.Println("client error:", err)
	}

	req := &firestorepb.ListDocumentsRequest{
			Parent: `projects/<yourproject>/databases/(default)/documents`,
			CollectionId: "device",
	}
	fmt.Println("req:", req)
	it := c.ListDocuments(ctx, req)
	fmt.Println("it:", it)
	for {
		resp, err := it.Next()
		if err == iterator.Done {
			fmt.Println("it error:", err)
			break
		}
		if err != nil {
			// TODO: Handle error.
			fmt.Println("resp error:", err)
		}
		// TODO: Use resp.
		_ = resp
		fmt.Println("resp:", resp)
	}
}

func listen() (err error) {
	fmt.Println("start: listen")
	ctx := context.Background()
	fmt.Println("ctx:", ctx)

	c, err := firestore.NewClient(ctx)
	if err != nil {
		// TODO: Handle error.
		fmt.Println("client error:", err)
		return err
	}
	fmt.Println("client:", c)
	stream, err := c.Listen(ctx)
	if err != nil {
		// TODO: Handle error.
		fmt.Println("stream error:", err)
		return err
	}
	fmt.Println("stream:", stream)
	go func() {

		reqs := []*firestorepb.ListenRequest{
			// TODO: Create requests.
			&firestorepb.ListenRequest{
				Database: `projects/<yourproject>/databases/(default)`,
				TargetChange: &firestorepb.ListenRequest_AddTarget{
					AddTarget: &firestorepb.Target{
						Once: false,
						ResumeType: &firestorepb.Target_ReadTime{
							ReadTime: &timestamp.Timestamp{
								Seconds: 2,
							},
						},

						TargetType: &firestorepb.Target_Documents{
							Documents: &firestorepb.Target_DocumentsTarget{
								Documents: []string{
									//`projects/<yourproject>/databases/(default)/documents/device`,
									`projects/<yourproject>/databases/(default)/documents/device/<device-id>`,
								},
							},
						},


					},
				},
			},
		}
		fmt.Println("Reqs:", reqs)
		for _, req := range reqs {
			if err := stream.Send(req); err != nil {
				// TODO: Handle error.
				fmt.Println("send err:", err)
			}
		}
		//stream.CloseSend()
		//fmt.Println("close send")
	}()
	for {
		resp, err := stream.Recv()
		if err == io.EOF {
			fmt.Println("io.EOF:", err)
			break
		}
		if err != nil {
			// TODO: handle error.
			fmt.Println("receive err:", err)
			return err
		}
		// TODO: Use resp.
		_ = resp
		fmt.Println("Resp:", resp)
		time.Sleep(1000)
	}
	fmt.Println("quit")

	stream.CloseSend()
	fmt.Println("close send")

	return nil
}

```

**Comment by jba** [comment]
We recommend the `cloud.google.com/go/firestore` package. That said, I don't think the result would be any different.

@schmidt-sebastian, do you have any ideas?

**Comment by schmidt-sebastian** [comment]
The Server SDKs for Firestore use Google's Cloud Identity and Access Management for authentication. They are meant to authenticate SDKs that run in trusted environments against the server and hence bypass any rules set up through Firestore Rules. With Google Cloud's Default Credentials (https://cloud.google.com/video-intelligence/docs/common/auth#authenticating_with_application_default_credentials), this authentication can be done in the background automatically. 

The Go Server SDK are part of the FirebaseAdmin SDk, which are not designed to run with end-user credentials. These SDKs should not be used in software that runs on end-user devices.  If you need end-user access, please take a look at the Firestore SDKs for iOS, Android or the Web.

**Comment by zkdzegede** [comment]
@schmidt-sebastian  

Thanks for the information, I was hoping this wasn't the case 😞 

I just also realized that I had set ```GOOGLE_APPLICATION_CREDENTIALS``` inside my .envrc file and forgotten. That must be why it worked without adding any extra authentication code.

Do you have a recommended way to put this on an end-user device that runs with golang?  Would it be best to start up a local node client and use the Node/Web sdk instead? (This is not an iOS or Android device but an embedded IoT device)

**Comment by schmidt-sebastian** [comment]
Please use the Firebase Node SDK for this use case: https://www.npmjs.com/package/firebase
