### ISSUE TITLE
pubsub: message ack not working

### ISSUE THREAD

**Issue by lopezator** [GoogleCloudPlatform/google-cloud-go#1030]
I am using "cloud.google.com/go/pubsub" to publish/subscribe/pull from a topic.

Tried in many different ways I cannot Ack a pubsub message. I have the following test with code grabbed from https://cloud.google.com/pubsub/docs/quickstart-client-libraries#pubsub-subscribe-go:

```
package gcp

import (
	"context"
	"fmt"
	"sync"
	"testing"

	"cloud.google.com/go/pubsub"
)

var (
	projectID    = flag.String("project_id", "xxxx", "GCP Project ID")
	topic        = flag.String("topic", "xxxx", "GCP Pubsub Topic")
	subscription = flag.String("subscription", "xxxx", "GCP Pubsub Subscription")
)

func TestGCP(t *testing.T) {
	ctx := context.Background()

	client, err := pubsub.NewClient(ctx, *projectID)
	if err != nil {
		t.Fatalf("creation of client: %v", err)
	}

	if err != nil {
		t.Fatalf("failed to create client: %v", err)
	}

	tpc := client.Topic(*topic)

	// Publish 10 messages on the topic.
	var results []*pubsub.PublishResult
	for i := 0; i < 10; i++ {
		res := tpc.Publish(ctx, &pubsub.Message{
			Data: []byte(fmt.Sprintf("hello world #%d", i)),
		})
		results = append(results, res)
	}

	// Check that all messages were published.
	for _, r := range results {
		_, err := r.Get(ctx)
		if err != nil {
			t.Fatalf("failed checking if the message was published: %v", err)
		}
	}

	// [START pubsub_subscriber_async_pull]
	// [START pubsub_quickstart_subscriber]
	// Consume 10 messages.
	var mu sync.Mutex
	received := 0
	sub := client.Subscription(*subscription)
	cctx, cancel := context.WithCancel(ctx)
	err = sub.Receive(cctx, func(ctx context.Context, msg *pubsub.Message) {
		msg.Ack()
		fmt.Printf("Got message: %q\n", string(msg.Data))
		mu.Lock()
		defer mu.Unlock()
		received++
		if received == 10 {
                        //Uncommenting the following line make msg.Ack to work
			//time.Sleep(2*time.Second)
			cancel()
		}
	})
	if err != nil {
		t.Fatalf("failed receiving message: %v", err)
	}
	// [END pubsub_subscriber_async_pull]
	// [END pubsub_quickstart_subscriber]
}

```

The messages are publishing and receiving ok, but if I execute in my shell:

`
gcloud pubsub subscriptions pull my-sub --auto-ack --limit=10
`

I can see the 10 sent messages. 

As I am using --auto-ack on gcloud CLI, the messages got ack-ed correctly and I cannot see them anymore.

I suppose that this means the msg.Ack wasn't working properly in first place.

**Comment by jba** [comment]
I can't duplicate that. When I run your program and then call `gcloud pubsub descriptions pull`, I see "Listed 0 items."

Although it shouldn't matter, could you add a `time.Sleep(2*time.Second)` before the call to `cancel()`?

**Comment by lopezator** [comment]
@jba Confirmed, **it works** with ```time.Sleep(2*time.Second)```. The issue persist without it. 

I updated the first post with the full code including imports, consts, and the code that was inside the NewClient function.

My host machine is MacOS high sierra if it does even matter. It fails for me both on test side (like the code I posted) and a "normal" implementation.

Let me know if you need more info to debug/reproduce.

**Comment by jba** [comment]
Can you add a log message before https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/iterator.go#L321, to verify that `Acknowledge` is being called after you cancel, and also at https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/iterator.go#L348 (displaying `err`) to see if the `Acknowledge` call succeeds?

**Comment by lopezator** [comment]
I was pinning my project to release v0.2.3, not master. It's working ok when using master. Thanks for the support.
