### ISSUE TITLE
GPU Support 

### ISSUE THREAD

**Issue by afritzler** [GoogleCloudPlatform/google-cloud-go#1034]
Hi,

is there currently a way to create a GPU machine on GCP via the go cloud sdk? (because I couldn't find anything)

Regards,
Andreas

**Comment by jba** [comment]
See the `AcceleratorTypes` service and the `Instance.GuestAccelerators` property. Also see 
https://cloud.google.com/compute/docs/gpus/add-gpus#create-new-gpu-instance.
