### ISSUE TITLE
bigtable: emulator cannot retrieve binary qualifier

### ISSUE THREAD

**Issue by dmccobra** [GoogleCloudPlatform/google-cloud-go#1037]
The bigtable emulator is having problems retrieve the value of a column when the column qualifier is an arbitrary byte array (as opposed to the bytes from a String).  The emulator spits out this error when I run the code below:

Cloud Bigtable emulator running on 127.0.0.1:8086
2018/06/20 13:51:53 Bad column_qualifier_regex_filter pattern "\\\x13\x97h\x96\x80\\\bA\xb7\x9bm\\\x05ڙZ\x83H": error parsing regexp: invalid UTF-8: `�h��A��m\ڙZ�H

	@Test
	public void badColumnTest() {
		try (Table table = conn.getTable(bigTableConfig.getZoneProductCountTableName())) {
			byte[] badCol = new byte[] {19, -105, 104, -106, -128, 8, 65, -73, -101, 109, 5, -38, -103, 90, -125, 72};
			Put put = new Put("myRow".getBytes())
					.addColumn("f".getBytes(), badCol,  "hi".getBytes());
			table.put(put);

			Get get = new Get("myRow".getBytes())
					.addColumn("f".getBytes(), badCol);
			Result result = table.get(get); //  <-- emulator spits out parse error from this call
			
			assertTrue(Arrays.equals(
			          "hi".getBytes(),
			          result.getValue("f".getBytes(), badCol)));
				
		} catch(Exception exception) {
			throw new RuntimeException(exception);
		}
	}

**Comment by dmccobra** [comment]
I'm not familiar with the emulator implementation - are you saying that the column qualifiers are being interpreted internally as regexs?

**Comment by sduskis** [comment]
This is what the java produces, formatted in json:

```
rows {
  row_keys: "myRow"
}
filter {
  chain {
    filters {
      chain {
        filters {
          family_name_regex_filter: "f"
        }
        filters {
          column_qualifier_regex_filter: "\\\023\227h\226\200\\\bA\267\233m\\\005\332\231Z\203H"
        }
      }
    }
    filters {
      cells_per_column_limit_filter: 1
    }
  }
}
```

**Comment by sduskis** [comment]
The qualifier filter regex is this in binary: 

```
[92, 19, -105, 104, -106, -128, 92, 8, 65, -73, -101, 109, 92, 5, -38, -103, 90, -125, 72}
```

The original is:
```
 {19, -105, 104, -106, -128, 8, 65, -73, -101, 109, 5, -38, -103, 90, -125, 72}
```

**Comment by bshafiee** [comment]
I've the same problem in Go ☹️

**Comment by sduskis** [comment]
@jba, is this something you can take?

**Comment by jba** [comment]
Done. I won't get to it before early September, though.

**Comment by jba** [comment]
@bshafiee you're right: the doc on the proto says that column filters "are evaluated as full matches."

**Comment by enocom** [comment]
Thanks for the comment, @jba. I'll make the changes you suggest.

For reference, I found the Java client is quoting regular expressions [here](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/c5d5c7ea31c823a64cb00ee70617677682472565/bigtable-client-core-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/read/ReaderExpressionHelper.java#L69).

**Comment by jba** [comment]
Assuming that it is actually wired up to the column filter (I don't have the tooling to easily discover that), the code you linked would turn my filter `a*`, intended to match a column with zero or more `a`s, into `a\*`, which would only match the column with the name `a*`. In other words, Java disables regexp matching for columns.

That's fine, I guess, if that's what its documentation says. And the emulator should behave properly when it receives `a\*` by matching only `a*`. See https://play.golang.org/p/NI_5AQPqyNm.

**Comment by enocom** [comment]
After further investigation, I realize my comment above is mistaken. The Java client does not quote meta characters when using the column filter. Instead, it escapes queries that request an exact match.
