### ISSUE TITLE
Feature request: labels for error reporting.

### ISSUE THREAD

**Issue by majelbstoat** [GoogleCloudPlatform/google-cloud-go#1039]
`errorreporting.Entry` currently only supports an `Error`, `Request`, and `Stack`. It would be great if it also supported `Labels`, like the logging client does. This would allow us to classify errors, and attach metadata without polluting the main error message and destroying cardinality.

**Comment by jba** [comment]
The [Error Reporting API](https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report) doesn't support labels, so this client can't provide them either.

**Comment by majelbstoat** [comment]
Thanks for the update. How best to make that request to the right people?

**Comment by jba** [comment]
The Stackdriver [User Voice community](https://googlecloudplatform.uservoice.com/forums/302820-stackdriver).
