### ISSUE TITLE
Google-cloud-go-sontaya_butdaphung

### ISSUE THREAD

**Issue by toongegi** [GoogleCloudPlatform/google-cloud-go#1044]
(delete this for feature requests)

## Client

e.g. PubSub

## Describe Your Environment

e.g. Alpine Docker on GKE

## Expected Behavior

e.g. Messages arrive really fast.

## Actual Behavior

e.g. Messages arrive really slowly.

**Comment by jba** [comment]
Assuming this is a mistake.
