### ISSUE TITLE
spanner: Application Default Credentials fail to work after a timeout

### ISSUE THREAD

**Issue by majelbstoat** [GoogleCloudPlatform/google-cloud-go#1045]
Opening per @jba in https://github.com/GoogleCloudPlatform/google-cloud-go/issues/945#issuecomment-400081366

## Client

Spanner

## Describe Your Environment

Local development running on Alpine Docker within K8s cluster provided by Docker for Mac

## Expected Behavior

I expect the spanner package to correctly pick up my local "Application Default Credentials", which have been set up using `gcloud auth application-default login`, and to keep using them for re-connections, even after timeouts.

## Actual Behavior

The application starts up correctly, with a connection using application default creds. However, after a timeout or some kind of session drop, Spanner fails to re-connect with the following error:

```
Failed to prepare session, error: spanner: code = "Unauthenticated", desc = "transport: context deadline exceeded"
```

I'm not explicitly setting a timeout, but in development i have services which use spanner clients that run for a long time. If I close the laptop for a while, the first request in the morning gives the above error. I can also trigger it by waiting a (long-ish?) period of time idling without a query.

I expected the client to automatically recover from severed connections (for whatever reason). It looks like it's trying to do that, but failing to re-read or refresh the credentials.

**Comment by majelbstoat** [comment]
Now that I've added a couple of go services that use Spanner, this is actually pretty unusable for me in dev. I have to restart a service every 20 minutes or so. For what it's worth, the nodejs client doesn't have the same problem, and i'm making the application default credentials available in exactly the same way.

Is there a workaround where I can force it to re-use the creds, even if i have to monkey patch something for now?

**Comment by jba** [comment]
Here's what I don't get about your description: the error text "Failed to prepare session" occurs twice in the spanner client ([here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/spanner/session.go#L908) and about 30 lines later), and in both cases it is effectively a warning&mdash;the message is logged, not returned, and the enclosing loop happens again. So when you say "spanner fails to re-connect with the following error," you don't mean that your program gets an error back from a spanner call. 

Does your program go into an infinite loop where this message is printed repeatedly?

That, plus your use of Alpine, suggests that your problem is the one described in #791. The fix is described in https://github.com/GoogleCloudPlatform/google-cloud-go/issues/791#issuecomment-350605132.

Unfortunately for my theory, you should never be able to use the client successfully if it were true. So maybe it's something else.

**Comment by majelbstoat** [comment]
Thanks for taking a look! Yes, it's an infinite loop where this is printed repeatedly. I already had ca-certificates included in the image for a different reason. And yes, it does work on initial load.

**Comment by jba** [comment]
I don't have any other ideas at this point. Could you try increasing the timeout [here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/spanner/session.go#L903) and [here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/spanner/session.go#L952) to a large value and see if that makes a difference?

Have you tried it with a service account instead ADC?

**Comment by majelbstoat** [comment]
So, just to report back that there's nothing obvious in the logs even with that info level:

```
WARN[10455] grpc: addrConn.createTransport failed to connect to {spanner.googleapis.com:443 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup spanner.googleapis.com on 10.96.0.10:53: no such host". Reconnecting... source=grpc
INFO[10455] pickfirstBalancer: HandleSubConnStateChange: 0xc420196d40, TRANSIENT_FAILURE source=grpc
INFO[10456] pickfirstBalancer: HandleSubConnStateChange: 0xc420196bb0, CONNECTING source=grpc
WARN[10456] grpc: addrConn.createTransport failed to connect to {spanner.googleapis.com:443 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp: lookup spanner.googleapis.com on 10.96.0.10:53: no such host". Reconnecting... source=grpc
INFO[10456] pickfirstBalancer: HandleSubConnStateChange: 0xc420196bb0, TRANSIENT_FAILURE source=grpc
INFO[10463] pickfirstBalancer: HandleSubConnStateChange: 0xc4201fc0a0, CONNECTING source=grpc
INFO[10464] pickfirstBalancer: HandleSubConnStateChange: 0xc420196d40, CONNECTING source=grpc
INFO[10464] pickfirstBalancer: HandleSubConnStateChange: 0xc4201fc0a0, READY source=grpc
INFO[10465] pickfirstBalancer: HandleSubConnStateChange: 0xc420196bb0, CONNECTING source=grpc
INFO[10465] pickfirstBalancer: HandleSubConnStateChange: 0xc420196d40, READY source=grpc
INFO[10465] pickfirstBalancer: HandleSubConnStateChange: 0xc420196bb0, READY source=grpc
INFO[10466] pickfirstBalancer: HandleSubConnStateChange: 0xc420196ad0, CONNECTING source=grpc
INFO[10466] pickfirstBalancer: HandleSubConnStateChange: 0xc420196ad0, READY source=grpc
WARN[10490] Error: User not found.    cause=Failed to retrieve record. code=Unauthenticated env=dev error=User not found. method=/service.Users/GetUser
2018/06/27 13:57:09 Failed to prepare session, error: spanner: code = "Unauthenticated", desc = "transport: context deadline exceeded"
2018/06/27 13:57:09 Failed to prepare session, error: spanner: code = "Unauthenticated", desc = "transport: context deadline exceeded"
2018/06/27 13:57:09 Failed to prepare session, error: spanner: code = "Unauthenticated", desc = "transport: context deadline exceeded"
2018/06/27 13:57:09 Failed to prepare session, error: spanner: code = "Unauthenticated", desc = "transport: context deadline exceeded"
...
```

The error happens the first time I make a request. My application error is the `WARN[]` line. This service is itself a GRPC server, and I don't know the internals well enough to know if some of those lines are from spanner, or from the grpc serving code. Howvever, the `INFO[]` prefix and `source=grpc` means that the code is making use of a logging adapter I have set for GRPC: `grpclog.SetLoggerV2(&logging.GRPCAdaptor{})`. It's interesting that the session/unauthenticated errors don't have that prefix.

I'll try and increase those timeouts, though with my setup it might take me a little while. (Containers are rebuilt from scratch when the service is started, and the code is refetched.) Testing with a service account will be easier first.

**Comment by jba** [comment]
> It's interesting that the session/unauthenticated errors don't have that prefix.

Those are from our spanner client, which uses the standard library log package.

**Comment by jba** [comment]
You may be getting bitten by the fundamental problem with Application Default Credentials. It is well-explained [here](https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/182#issuecomment-319803070).

Service accounts are the right way to authenticate, even for dev.

**Comment by jba** [comment]
See https:/cloud.google.com/doc/authentication for guidance on using service account credentials.

**Comment by broady** [comment]
/cc @hostirosti

I think this is related to the issue we were debugging this morning.

**Comment by jba** [comment]
Does the context that you pass into `spanner.NewClient` ever get cancelled or time out?

**Comment by hostirosti** [comment]
Hi Jamie,
the workaround is to use a service account file. This way a canceled context used to create the client doesn't invalidate creds for any connections:
`var opts []option.ClientOption
	if _, err := os.Stat("service-account.json"); err == nil {
		opts = append(opts, option.WithServiceAccountFile("service-account.json"))
		log.Print("Found service account file... using for auth")
	}
	c, err := spanner.NewClientWithConfig(context.Background(), dbPath, spanner.ClientConfig{NumChannels: 20}, opts...)
	if err != nil {
		return nil, err
	}
`

The other option is to use context.Background() without any timeout to obtain the client.

**Comment by majelbstoat** [comment]
@hostirosti, @jba: thanks, appreciate the help. will do that and report back.

**Comment by hostirosti** [comment]
@majelbstoat you can also use credentials set via the GOOGLE_APPLICATION_CREDENTIALS environment variable. This way a canceled context (which was used to obtain the client) doesn't interfere with subsequent calls either.

**Comment by hostirosti** [comment]
@majelbstoat you don't need to run gcloud in your container. [Here](https://github.com/hostirosti/til-about-cloudspanner/blob/master/02-choosing-right-primary-keys/version01/golang/Dockerfile) is how I build a docker container with a static linked app (with a 2-staged docker build).

You can build the container via `docker build -t sample-container .`

To run the container you mount the service account and pass the ENV in the following way:
```
docker run --rm -v `pwd`/service-account.json:/service-account.json -e GOOGLE_APPLICATION_CREDENTIALS=/service-account.json sample-container
```

**Comment by majelbstoat** [comment]
Yep, got this working with a Kubernetes secret mounted as a file. https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/ 

So far, seems good. Thanks for all the help.
