### ISSUE TITLE
Soft-warn about application default credentials using gcloud credentials

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-go#1047]
Due to user issues with quota and API enablement, the auth libraries should issue a soft warning (that can be silenced) when application default credentials uses user credentials from the Cloud SDK. They should not warn if the credentials for the cloud sdk are service account credentials.

```
Your application has authenticated using end user credentials from Google 
Cloud SDK. We recommend that most server applications use service accounts
 instead. If your application continues to use end user credentials from Cloud 
SDK, you might receive a "quota exceeded" or "API not enabled" error. For 
more information about service accounts, see 
https://cloud.google.com/docs/authentication/.
```

Additional context:
https://groups.google.com/a/google.com/forum/#!topic/client-auth-team/DKqrFw6lL1Q
https://buganizer.corp.google.com/issues/64388723
https://github.com/GoogleCloudPlatform/google-auth-library-python/pull/266

**Comment by JustinBeckwith** [comment]
Side note - it's unclear to me if this belongs here or in the Go OAuth2 client.  Feel free to move if needed :)

**Comment by broady** [comment]
Changing to P2, don't think this will be resolved within the next week, especially considering 4th July holiday.

**Comment by jadekler** [comment]
We decided offline not to implement this feature. Closing this for now, give a shout if you want to re-open to discuss again.
