### ISSUE TITLE
Raise error on *storage.ObjectHandle.If(Condition) fail

### ISSUE THREAD

**Issue by AnvilDev** [GoogleCloudPlatform/google-cloud-go#1055]
## Client

Is there any way to raise an error if a precondition isn't met on a file?

All I see is that the function onto the resulting `*storage.ObjectHandle` is ignored if the `*storage.ObjectHandle.If(storage.Condition)` fails, but I need to raise an error when this happens, not simply let it pass silently.

**Comment by jba** [comment]
Can you provide an example? With the code
```
 obj := c.Bucket(bucket).Object(objName).If(storage.Conditions{GenerationMatch: 17})
 a, err := obj.Attrs(ctx)
```
I get an error.

**Comment by AnvilDev** [comment]
I'm trying to use `.NewWriter`, which returns no error, even `Write` into the `*storage.NewWriter` doesn't return an error if the generations don't match.

**Comment by AnvilDev** [comment]
@jba Is there a workaround to this behavior?

**Comment by jba** [comment]
Let me look into it a bit more.

**Comment by jba** [comment]
Are you checking the error from `Writer.Close`? This code prints an error:
```
    ctx := context.Background()
    c, err := storage.NewClient(ctx)
    if err != nil {
        log.Fatal(err)
    }
    obj := c.Bucket(bucket).Object("issue1055")
    w := obj.NewWriter(ctx)
    fmt.Fprint(w, "something\n")
    if err := w.Close(); err != nil {
        log.Fatal(err)
    }
    attrs, err := obj.Attrs(ctx)
    if err != nil {
        log.Fatal(err)
    }
    fmt.Printf("wrote generation %d\n", attrs.Generation)
    gobj := obj.If(storage.Conditions{GenerationMatch: attrs.Generation + 1})
    w = gobj.NewWriter(ctx)
    fmt.Fprint(w, "second\n")
    fmt.Printf("error on close: %v\n", w.Close())
```

**Comment by AnvilDev** [comment]
@jba 

I never thought to check that error, thanks!

Maybe the documentation for using `.If()` could be a little clearer?

**Comment by jba** [comment]
It's actually more about using `Writer` correctly. Whenever you use an implementation of `io.Writer` in Go, you should always check the error from `Close`. We say it explicitly in the [doc for `Writer.Write`](https://godoc.org/cloud.google.com/go/storage#Writer.Write): "Always use the error returned from Writer.Close to determine if the upload was successful."

**Comment by AnvilDev** [comment]
Right, I understand. My main problem is that nowhere in the `.if()` documentation does it hint at the fact that an error might be raised if the precondition isn't met, which led me to believe I needed a workaround.

"Operations on the new handle will only occur if the preconditions are satisfied."

It would be nice if it said that the operations would raise an error.

**Comment by jba** [comment]
Good point. See https://code-review.googlesource.com/c/gocloud/+/30190.

**Comment by jadekler** [comment]
Closing this issue since https://code-review.googlesource.com/c/gocloud/+/30190 clarifies the documentation.
