### ISSUE TITLE
cbt deleterow always outputs usage error

### ISSUE THREAD

**Issue by ssh-spnz** [GoogleCloudPlatform/google-cloud-go#1058]
## Client

cbt version output:
```
0.5.1 8d90a3f 2018-06-04 20:04:09
```

gcloud version output:
```
Google Cloud SDK 207.0.0
alpha 2018.06.22
beta 2018.06.22
bq 2.0.34
cbt 
core 2018.06.22
gsutil 4.32

```

## Describe Your Environment

Debian 9

## Expected Behavior

--

## Actual Behavior

Command being run is: `cbt deleterow exampletable examplerowkey app-profile=default`
The result is simply `usage: cbt deleterow <table> <row> [app-profile=<app profile id>]` being logged. Leaving out the app-profile argument makes no difference.

**Comment by kavehmz** [comment]
This issue is fixed here by 1053c23baa9b4302ae28c46a3dc9f076f0821a6f

I think those who have issue depend on gcloud to deliver the latest version in master.

**Comment by jba** [comment]
@sduskis Any idea when gcloud will pick up this fix?

**Comment by sduskis** [comment]
@garye, what do we need to do to get out a new version of cbt for gcloud?

**Comment by garye** [comment]
I'm going to put together a new build of `cbt` today with hopes of getting it in next week's gcloud release.

**Comment by kavehmz** [comment]
If you are like me looking for the fix, either you need to wait, or compile cbt your self (it is Go and very easy) or if you are not familiar with Go but you can use docker use the following docker file:

```Dockerfile
FROM golang:1 AS build

RUN go get -v -u cloud.google.com/go/...

WORKDIR /go/src/cloud.google.com/go/
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOROOT_FINAL=/ go build -o /cbt bigtable/cmd/cbt/cbt.go

FROM debian
COPY --from=build /cbt /cbt
RUN apt-get update && apt-get install -y ca-certificates
ENTRYPOINT [ "/cbt" ]
```

Then you can build and run cbt  (save the content above in a file named Dockerfile):

```bash
#build
$ docker build -t cbt .
# Run cbt and attach your config (which includes .gcloud that has your crendentials)
$ docker run --rm --name cbt -v ~/.config:/root/.config  cbt -project my-project -instance my-instance ls
```
