### ISSUE TITLE
datastore: document metadata operations

### ISSUE THREAD

**Issue by karalabe** [GoogleCloudPlatform/google-cloud-go#106]
There are quite a lot of metadata operations doable (kind, stat, etc retrieval), which is possible currently too, but only if you know the internal data types and related entity kinds.

E.g.

``` go
type KindStat struct {
    KindName            string `datastore:"kind_name"`
    EntityBytes         int    `datastore:"entity_bytes"`
    BuiltinIndexBytes   int    `datastore:"builtin_index_bytes"`
    BuiltinIndexCount   int    `datastore:"builtin_index_count"`
    CompositeIndexBytes int    `datastore:"composite_index_bytes"`
    CompositeIndexCount int    `datastore:"composite_index_count"`

    Count     int       `datastore:"count"`
    Bytes     int       `datastore:"bytes"`
    Timestamp time.Time `datastore:"timestamp"`
}

stats := []KindStat{}
datastore.NewQuery("__Stat_Kind__").GetAll(ctx, &stats)
```

It would be nice to collect all these metadata types, queries, operations, and have them under a more pleasant API :)

**Comment by PerryBirch** [comment]
+1 Meta queries would be very helpful in the native libs.  (Thanks for the struct def btw, exactly what I needed)

**Comment by jba** [comment]
I think we can document these in the package somewhere (perhaps by including the above struct). I don't think more client surface is needed.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
