### ISSUE TITLE
Storage: SignedURL does not generate working URL's

### ISSUE THREAD

**Issue by sbsends** [GoogleCloudPlatform/google-cloud-go#1062]
(delete this for feature requests)

## Client

Storage

## Describe Your Environment

MacOS High Sierra, 10.13.6 (17G65)
## Expected Behavior

Generated signed URLs should work as expected

## Actual Behavior

Signed URLs consistently result in an error.

```golang
// Generation Code:

url, err := storage.SignedURL("redacted-bucket", "redacted-object", &storage.SignedURLOptions{
    GoogleAccessID: "<redacted>@<redacted>.iam.gserviceaccount.com",
    PrivateKey:     []byte("-----BEGIN PRIVATE KEY-----\nMIIEv..."),
    Method:         "GET",
    Expires:        time.Now().Add(48 * time.Hour),
})
```
```XML
// Using the same URL in:
// Browser (Chrome)
<Error>
<Code>MalformedSecurityHeader</Code>
<Message>Your request has a malformed header.</Message>
<ParameterName>signature</ParameterName>
<Details>Signature was not base64 encoded</Details>
</Error>

// CURL: 
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to redacted-bucket/redacted-object</Details>
</Error>

```

**Comment by sbsends** [comment]
Curl: Wrapping the URL in quotes solves the problem. 
Browser: manually changing the host to storage.cloud.google.com seemed to work. 

This is very inconsistent. Please consider upgrading to the newer format utilized by gsutil.

```
e.g. 
 x-goog-algorithm=
x-goog-credential=
x-goog-date=
x-goog-expires=
x-goog-signature=

```

**Comment by jba** [comment]
I know you closed this, but I was curious anyway.

I couldn't reproduce either problem. The URL I generated looks like https://storage.googleapis.com/my-bucket/my-object?Expires=1532098587&GoogleAccessId=642080918101-compute%40developer.gserviceaccount.com&Signature=LACE3ECUdfuiGAXpMVGaFyfMLg%2B9AosihkmsCOeYXsE49HNf%2BlEJ5JD%2Fu0gaTxv97WbRBYvEtUJFytezbF1UG5lLi5WeeRbRwvaiX8%2BDCXapO7e1%2BYhsbqKIWWlMh2cTHt8ua1MSUE4R6FsyBrnvd1dKBh0PjZypz1rhssrXg1BIo7Htz4H4wWzFaC3B8b7dn7Kpcn6Z2%2BL3OsNGjro%2FqMoKkGpYg%2BUbanTpV7uvgWPOMYYeFxRVim5JF%2BF8Xs7AVuxPRvLprl2Vp5CshIfJ%2FdQ8EJMqqyI9CvEZNOwirBDhOq9sbNXT0sqE2uxhtCGLSYPGglGjnM1yPFpCoWvSFg%3D%3D.

I used it with curl as is, without quotes, in a bash shell, and it worked fine.

I pasted it into my Chrome browser and it worked.

**Comment by mayurdhurpate** [comment]
Getting the same error as @sbsends. Both the suggested [workarounds](https://github.com/googleapis/google-cloud-go/issues/1062#issuecomment-405116209) work in  my case too.

The link I generated using the Cloud Storage nodejs  `upload` and `getSignedUrl` calls:
```ts
const response = await storage.bucket(bucketName).upload(filename, {
      gzip: true,
      destination: folderName+'/'+filename.split('/').pop(),
      metadata: {
        cacheControl: 'public, max-age=31536000',
      },
    });
    
    const urlData = await response[0].getSignedUrl({
      action: 'read',
      expires: '03-09-2491'
    })
 ```

Here is the link which was generated:

https://storage.googleapis.com/pruoo-test.appspot.com/tempMedia%2FPeVyRbIAYf4kUwSMRZAebrain_booster_calculator.png?GoogleAccessId=firebase-adminsdk-1rrh6%40pruoo-test.iam.gserviceaccount.com&Expires=16446997800&Signature=G7MM%2BU9Zl%2F4CHQnglifUq2qPSX0yR8tMabToHYekLk%2Bjc1zHKmWajwOWLw9sKiE9CCHU%2BbOppwb0zfJPOt9iMhzmtokkyl8op%2FpvSFpWaQdy6sIhNZm5CkSU6fkSmrV0%2BR7ts1MNHAuTg4cdpExsBBapbiBEpa%2B36vsjlQpESaIex6G6MESTW4hsbDLVv5bQEeRn4rAGODYUSteQq3qw0Vsx4tc6bY3Fid1bDsyCBHzQGiDjV3z3w4FiCnOdFdR2cf6SWnmEvK2FkBT%2B0jLcZU%2FvzRAuHG2kFPj7RjM6vsb4QJFykY8SwFGp9xBWMo7%2FGhovqMK%2FpGgvEY7RCOly1Q%3D%3D

**Comment by diogoaguiar** [comment]
Had the same problem. The [workarround](https://github.com/googleapis/google-cloud-go/issues/1062#issuecomment-405116209) works but why does this happen?

**Comment by tbpg** [comment]
Mind filing a new bug with the code used to generate the URL, the client version (e.g. `v0.51.0`), the URL you get, the URL that works, and any other information that's helpful?

**Comment by anasanzari** [comment]
still happening with node client

**Comment by volgin** [comment]
Same problem in Java runtime.

**Comment by stpe** [comment]
I'm experiencing this issue as well with the domain-replace-workaround working.

In a Cloud Function for Firebase, using firebase-admin v11.3.0 and firebase-functions v4.1.0, initializing Firebase using `initializeApp()` (i.e. no options) and `const bucket = getStorage().bucket('gs://<BUCKET_NAME>');` the following code works:

```
async function signUrl(filePath) {
    const urlOptions = {
        version: "v4",
        action: "read",
        expires: Date.now() + 1000 * 60 * 2, // 2 minutes
    };

    const [url] = await bucket
        .file(filePath)
        .getSignedUrl(urlOptions);

    return url.replace('storage.googleapis.com', 'storage.cloud.google.com');
}
```

Without the replace the URL responds with an HTTP 400 and body:
```
<Error>
<Code>MissingSecurityHeader</Code>
<Message>Your request was missing a required header.</Message>
<Details>x-goog-credential</Details>
</Error>
```

(Without the replace) the following URL is generated:
`https://storage.googleapis.com/<BUCKET_NAME>/xray-part-301134.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&amp;X-Goog-Credential=<PROJECT_ID>%40appspot.gserviceaccount.com%2F20221130%2Fauto%2Fstorage%2Fgoog4_request&amp;X-Goog-Date=20221130T192609Z&amp;X-Goog-Expires=121&amp;X-Goog-SignedHeaders=host&amp;X-Goog-Signature=3d62842561162a83fcce8879bb2fb9c024cb45291507172590b5fd7e7978b1e53ce9692b431ea12a9d17655bb0028f32c86b1a988b4aac6ac0a35146e833351fe59a959fa1b18d9bc59a6a64e853152ed4610141d2a2cf3ae439f4f94523b567d9e31a4e8cf7258a08efc48d7fdde0f1bf59dc22ac60cfa581c4b92ddb415f4703458d8f52a505cc59292231d2c4f95dc4c208dc32e93628e8e8d59f8a800a533dfb73b571955bbe77b16bd2992f6b03a587154d2c6906fd922a3fd5442e89536fc5e9c4fcc88900d8d681279c9cf5115d7f90e3ae06ac96cb1ad818fbd4ece604d9f582093117c27794b2ddfa1a0fde2f2ac36eb5e4c50eb73acfe005aeec0b`

With the replace to use storage.cloud.google.com it redirects to (which works):
`https://00f74ba44bdcb693c4a5dbafac6bb81ecb353dcff8-apidata.googleusercontent.com/download/storage/v1/b/<BUCKET_NAME>/o/xray-part-301134.jpg?jk=AFshE3XQ02l3jINPGAYtaTYUC06UQ7o-tYPFVzSu3qQ1AinjHmN7-l5rk-C0Cx6Qg6kCaPFJO2POsjNUO394ZbaelWmBP2mK-fEbYKheqgjjhKiUwi4Z7KpgZa4LVBzS1tZQl36WXSo5QPgs11lspLAOBuUlYbCTgIMbXXz2SvmvWPBPOYfKPEWD_vvuDT8tiEfbWBP_kiW7IUGArFUjl5wrxB9e5wVachaR1QV7F7pCSta_8ZI4EPDUYq9z8a-JAGGUnGh2IPsXyFtqNJHVX0zJBs6EFSTEwapff0LV_TBWwg0zMK6_aug_Q4Ny2slpZ9hYwkizPZbdeDFHNR3azjNgY9vaDjCywh8a4DJe77i9TyWR4ukdeCtSxNvoTTX2bdusFV6_1KTp_G7rJi2djhjt9v7jLQwGBdR8QQPJvvLJLe1LZXM_3MqE_jTEGk5C5nAfnNDaDwWS110VcxW25GAXx-U2G7TnqX9Q7w4ZWg5dxYhTF31_GucALsHJ0VpLyZ5-RDkZkQjHzgu-lHV0cVwL9JsSQwVSron9pyv1LveQYNuSeZE2nJ-6-vrethTR8YAXKPqL1uEwseLpRz0naNRvU45_SgYG09wYg2ZHRXQrZebudoMSYHjNESKEuHTRKunvt5YWRQwsissbfJsA9MwRblkAwzeZRCp4CpxJ6NnZUG_-jZFICb5WT8EuFhdJheLgVtpu-H4rwZmglP-woqdSCX8V9mxrZFulnks81OpcBmoto0g1Jl5HILMcIyWxXGaoUlwkeeyG8c7OKsTWQ30tc4U8OErFavAVUYGKMPbVAvYK8mruyEeXqhfwK72iyQyF7nlKc6n3J3yENTGWjGVcat21dgZoXFTjhJDMGJ_NbDEb91Tj8BRQvFjv0mXec4Ps91uhIOClhcyQSBvGBxp5qIXJBZ5o_i6a2v59HvfoSzEJQjMMMJuOgOgAkA2rVbQf7bmdG4N_sAsSQXcutipqQVzDcrvUI3IMqEd2HknFYF2TXvPJnYCqlSFCbTg9_aLu-KaZTQCKkeLHlGAFhgU-QmuFCBJgGFoy6jiGLDJ3s4Fv4mDFP9nYPGrYl8RtexVogoattRiMqVEsL4BKDQhOT8c7JlIM7TPwibt9mbLkX1xSIJLgbNUm4rAX4vGjMvfwT8VEbyVcz8P7wa_1L8t3sfmD6HHXtonhm_tP9Hi6pJsIySHPhY5Jn0sRO5oiN7mFQCPdsXQ5hKtohqKGyGQ&isca=1`
