### ISSUE TITLE
google.golang.org/api dependency revision not stated in this repo, causes breaking changes upgrading 0.18.0 to 0.24.0

### ISSUE THREAD

**Issue by henrahmagix** [GoogleCloudPlatform/google-cloud-go#1067]
## Client

PubSub

## Describe Your Environment

macOS + go1.10.3 darwin/amd64 + dep v0.4.1

## Expected Behavior

Upgrading from 0.18.0 to 0.24.0 should upgrade required dependencies.

## Actual Behavior

Dependencies of this package were not upgrade.

Received errors when building:
```
$ go build -v
github.com/myuser/myrepo/vendor/cloud.google.com/go/monitoring/apiv3
github.com/myuser/myrepo/vendor/cloud.google.com/go/pubsub
# github.com/myuser/myrepo/vendor/cloud.google.com/go/monitoring/apiv3
vendor/cloud.google.com/go/monitoring/apiv3/alert_policy_client.go:83:20: undefined: monitoring.AlertPolicyServiceClient
# github.com/myuser/myrepo/vendor/cloud.google.com/go/pubsub
vendor/cloud.google.com/go/pubsub/topic.go:351:12: t.bundler.HandlerLimit undefined (type *bundler.Bundler has no field or method HandlerLimit)
vendor/cloud.google.com/go/pubsub/topic.go:353:12: t.bundler.HandlerLimit undefined (type *bundler.Bundler has no field or method HandlerLimit)
```

### `t.bundler.HandlerLimit`

This is using `google.golang.org/api/support/bundler`, which came as [revision 65b0d8655182691ad23b4fac11e6f7b897d9b634](https://github.com/google/google-api-go-client/tree/65b0d8655182691ad23b4fac11e6f7b897d9b634) when this package was installed at v0.18.0 on 2018-01-23.

Today I upgraded this package to v0.24.0 but the dependency `google.golang.org/api` was not upgraded, and so produced the above errors.

Would it be possible to include dep's `Gopkg.toml` and `Gopkg.lock` files in this repo so dependencies can be tracked and breaking changes don't occur? Because I don't know what revision of `google.golang.org/api` I need to match this package's v0.24.0 release.

**Comment by jadekler** [comment]
Hello! Sorry you ran into pain there. Our plan for this kind of problem is to adopt Go modules. I've created https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1068 to formally track this work.

In the meantime, we expect upgrades to this repository to happen in tandem with upgrades to its (thankfully few) dependencies, e.g. `go get -u cloud.google.com/go/...`. Our CI is configured to [always test this repository and its dependencies at HEAD](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/.travis.yml#L10).

I'll close this issue for now, though you're welcome to re-open it if you have further questions or concerns.

**Comment by henrahmagix** [comment]
Thanks @jadekler, looking forward to go modules!
