### ISSUE TITLE
Bigquery client fails to build when included in vendor dir from dep staring versions >= 0.22.0 

### ISSUE THREAD

**Issue by AngerM** [GoogleCloudPlatform/google-cloud-go#1071]
## Client
Bigquery

## Describe Your Environment
OS X, golang 1.10.3 from brew

## Expected Behavior
Bigquery client builds when listed as a dependency in dep

## Actual Behavior
We used to use `0.21.0` previously without issue. We were updating some of our locked dependencies when I noticed the new version of the go libs. All versions `0.22.0` to `0.25.0` fail to build when I tried them. I went back to `0.21.0` and re-ran `dep ensure` and the builds once again succeed.
From GoPkg.toml
```
 [[constraint]]
   name = "cloud.google.com/go"
  version = "0.25.0"
```

Building the project:
```
 $ go build
# github.com/MAXAds/max-platform/vendor/cloud.google.com/go/bigquery
./job.go:786:21: s.ActiveUnits undefined (type *bigquery.QueryTimelineSample has no field or method ActiveUnits)
./job.go:787:21: s.CompletedUnits undefined (type *bigquery.QueryTimelineSample has no field or method CompletedUnits)
./job.go:789:21: s.PendingUnits undefined (type *bigquery.QueryTimelineSample has no field or method PendingUnits)
./query.go:173:22: cannot use &ptrue (type *bool) as type bool in assignment
./query.go:175:22: cannot use &pfalse (type *bool) as type bool in assignment
./query.go:205:48: cannot convert nil to type bool
./query.go:205:58: invalid indirect of qq.UseLegacySql (type bool)
```

**Comment by jba** [comment]
It looks like you need to update `google.golang.org/api/...` to HEAD.

**Comment by AngerM** [comment]
that worked
