### ISSUE TITLE
Build breaks on profiler/proftest

### ISSUE THREAD

**Issue by h8liu** [GoogleCloudPlatform/google-cloud-go#1072]
## Client

profiler

## Describe Your Environment

Alpine Docker

## Expected Behavior

Build pass.

## Actual Behavior

Build breaks

```
# cloud.google.com/go/profiler/proftest
src/cloud.google.com/go/profiler/proftest/proftest.go:549:55: cannot use "cloud.google.com/go/storage".RoleReader (type "cloud.google.com/go/storage".ACLRole) as type string in field value
src/cloud.google.com/go/profiler/proftest/proftest.go:549:55: too few values in struct initializer
```

**Comment by h8liu** [comment]
Example build log:

https://smallrepo.com/builds/20180723-224023-9aca3d5b

**Comment by jba** [comment]
I have a fix: https://code-review.googlesource.com/c/gocloud/+/30771.

**Comment by jba** [comment]
Submitted. Should be fixed at head.
