### ISSUE TITLE
firestore: unclear why CollectionIterator has no Stop method

### ISSUE THREAD

**Issue by mvdan** [GoogleCloudPlatform/google-cloud-go#1075]
```
// Stop stops the iterator, freeing its resources.
// Always call Stop when you are done with an iterator.
// It is not safe to call Stop concurrently with Next.
func (it *DocumentIterator) Stop() {
```

All the iterators in this package can be stopped, but not `CollectionIterator`. Is there a reason for this? If this is by design, I think it should be documented. Otherwise, I'm left thinking that I am not freeing its resources as per the godoc above.

**Comment by jba** [comment]
It is by design. I tried to clarify the docs in https://code-review.googlesource.com/c/gocloud/+/30830.
