### ISSUE TITLE
kms/apiv1: doc comment references cloud.google.com/go/kms which does not exist

### ISSUE THREAD

**Issue by zombiezen** [GoogleCloudPlatform/google-cloud-go#1077]
The KMS client (`cloud.google.com/go/kms/apiv1`) has documentation saying:

> Use the client at cloud.google.com/go/kms in preference to this.

But this package does not exist. I assume this is an auto-generated oversight.

**Comment by pongad** [comment]
Configuration changes made. It should take effect the next time we regenerate. I'll close this for now, but let us know if you need to regenerate faster.
