### ISSUE TITLE
How to use BigQuery JSON table schemas (as generated by https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema)?

### ISSUE THREAD

**Issue by chrusty** [GoogleCloudPlatform/google-cloud-go#1078]
## Client

BigQuery

## Describe Your Environment

Alpine Docker on GKE

## Expected Behavior

It would make sense to be able to Unmarshal JSON table schemas (as generated by https://github.com/GoogleCloudPlatform/protoc-gen-bq-schema) directly into a **bigquery.Schema**  (as it is with github.com/google/google-api-go-client/bigquery/v2/TableFieldSchema)

## Actual Behavior

The JSON generated by protoc-gen-bq-schema needs to be converted by the user (possible enough, but not a smooth experience).

Suggested solutions:
- Add a flag to protoc-gen-bq-schema to output JSON in the new format (pretty ugly solution)
- Add a public method on the Schema struct which loads a generated JSON schema: `func (s Schema) FromJSON() error`. While we're at it, perhaps a `ToJSON()` wouldn't be a bad idea either.

I'm happy to make a PR

**Comment by jba** [comment]
We'd welcome a function
```
func SchemaFromJSON(json []byte) (Schema, error)
```
Thanks for offering to contribute! Note that we use Gerrit, not github, for code review. Please read [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md).

**Comment by jba** [comment]
BTW, I don't see a use case for `Schema.ToJSON`, so unless you have one let's leave it out.

**Comment by chrusty** [comment]
OK, I've submitted the PR to code-review

**Comment by jba** [comment]
Fixed by 42663dc6b4a619136612d75116e7cbfbe049b84f.

**Comment by arbarlow** [comment]
sorry to add to this already closed issue, but I'm using the above new method and was wondering how to actually insert the records to bigquery, as my schema has been created with underscores i.e `first_name` but when uploading the object, it's null as looking at the code for a struct with Go field `FirstName` bigquery will try to insert that, even though the JSON tags are set, is there any way to simple load the Go object that I'm using whilst ago using the `protoc-gen-bq-schema` lib

**Comment by jadekler** [comment]
@arbarlow Could you open a new issue please?

**Comment by chrusty** [comment]
@arbarlow This PR just gave us the ability to create a schema definition (which can be used to programatically create the tables with the BigQuery API). Streaming data into these tables is then done the same way as any other table.
