### ISSUE TITLE
Cloud SQL calls in OpenCensus Tracing

### ISSUE THREAD

**Issue by Deleplace** [GoogleCloudPlatform/google-cloud-go#1085]
Feature request

We're using App Engine and Stackdriver Trace. Most API calls are already automatically traced, but not Cloud SQL queries.

Quoting [the docs](https://cloud.google.com/trace/docs/overview#how_does_stackdriver_trace_work) : _Stackdriver Trace works with all App Engine APIs, **with the exception of Cloud SQL**._

It would be very useful to have all Cloud SQL queries traced in OpenCensus Tracing (and we would then use the custom exporter to Stackdriver Trace).

In 2017 one of our reporting tools in prod was very slow due to hundreds of SQL queries executed serially for any backend request, but it wasn't obvious at first where exactly the problem was (where the time was spent).

**Comment by jadekler** [comment]
Thanks for this @Deleplace. I'm not super familiar with all the logging options, but on second look this may end up not being opencensus specific (despite me asking you to title it as such :) ). I'll follow up internally starting with the appengine folks about this.

**Comment by jba** [comment]
The right place for this FR is with the Cloud SQL team. See the options on their [support page](https://cloud.google.com/sql/docs/mysql/support), especially [User Voice](https://googlecloudplatform.uservoice.com/forums/302613-cloud-sql).

**Comment by jadekler** [comment]
I've created internal bug 112630309.

**Comment by abhi2705** [comment]
Any update here? I have the same req.

**Comment by jadekler** [comment]
No updates yet unfortunately.
