### ISSUE TITLE
broken link and incorrect branding in README

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/google-cloud-go#1096]
I spotted a few issues in the repo's `README.md` file, all in the Supported APIs section:

+ `DataProc` should be changed to `Dataproc`, per the [product's home page](https://cloud.google.com/dataproc/).
+ `DialogFlow` should be changed to `Dialogflow`, per the [product's home page](https://cloud.google.com/dialogflow-enterprise/).
+ `Cloud BigQuery` should be changed to `BigQuery` per the [product's home page](https://cloud.google.com/bigquery/). That home page also mentions `Google BigQuery`, but that needs to be fixed; please just use `BigQuery` in the `README`. (Added 2018-08-31)
+ The links for Dialogflow aren't working at the moment, presumably because the file doesn't define links named `cloud-dialogflow` or `cloud-dialogflow-ref`.

**Comment by jadekler** [comment]
I believe this has been resolved.

**Comment by hegemonic** [comment]
Can you please reopen this issue? The broken links were fixed, but the branding issues were not.

**Comment by jadekler** [comment]
Apologies - fixes are in https://code-review.googlesource.com/c/gocloud/+/32570
