### ISSUE TITLE
Stackdriver traces rarely has full request details, but frequently has just few details

### ISSUE THREAD

**Issue by mblasi** [GoogleCloudPlatform/google-cloud-go#1098]
Hello again!

Still fighting with stackdriver traces....
After upgrading the stackdriver client, as detailed in #978 , I don't see traces anymore...

## Client

google-cloud-go Stackdriver trace client

## Describe Your Environment

Google App Engine Flexible, serving golang gin-gonic rest api

## Expected Behavior

View app traces in traces view

## Actual Behavior

My traces spans are not shown.

I followed all steps specified here: https://cloud.google.com/trace/docs/setup/go

Then, 

I initialize stackdriver trace:

```
package main

import (
        "cloud.google.com/go/logging"
        "context"
        "contrib.go.opencensus.io/exporter/stackdriver"
        "fmt"
        "go.opencensus.io/trace"
)

func main() {
        exporter, err := stackdriver.NewExporter(stackdriver.Options{ProjectID: "my-project", OnError: func(err error) {
                panic(err)
        }})
        if err != nil {
            panic(err)
        }
        defer exporter.Flush()
        trace.RegisterExporter(exporter)

        handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
                _, span := trace.StartSpan(context.Background(), "dummy")
                defer span.End()
                fmt.Printf("Handling request")
        })     
               
        http.Handle("/", handler)

}

```
My sample handle requests, but I cant see any trace information in https://console.cloud.google.com/traces/traces

I have stackdriver trace api enabled, billing enabled... 

With the previous implementation, as specified in the issue #978 I saw the traces, but I had some lost information such as http method, and status code.. anyhow, that packages are deprecated:

"go.opencensus.io/trace"
"go.opencensus.io/exporter/stackdriver"

What am I missing?

Thank all of you for your work and help.

Best regards,
Matías.

**Comment by mblasi** [comment]
Dismiss this! The issue was fixed with this configuration:

`trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
`

Here is the doc:

> By default, traces will be sampled relatively rarely. To change the sampling frequency for your entire program, call ApplyConfig. Use a ProbabilitySampler to sample a subset of traces, or use AlwaysSample to collect a trace on every run:
`trace.ApplyConfig(trace.Config{DefaultSampler: trace.AlwaysSample()})
`
Thanks,
Matías.

**Comment by mblasi** [comment]
It's me again...

I was really happy when I saw a trace with all details! HTTP method, status code, and several others:

![image](https://user-images.githubusercontent.com/40089/43962905-4631b832-9c8f-11e8-8273-97d34ef79949.png)

But it was a "rarely sampled span" :(

When I configured it to use sampler "AlwaysSample" or "ProbabilitySampler", the sampled data is much less than the previous one:

![image](https://user-images.githubusercontent.com/40089/43963058-b1f8d2bc-9c8f-11e8-8d39-7c08a3c481f2.png)

Is there any way to control wich data is sampled??? Is it really related to the Config.Sampler used?

I see one detail when the trace is "rarely sampled", it has a root span not created by me:

![image](https://user-images.githubusercontent.com/40089/43963269-359387f2-9c90-11e8-9b76-51342eb7f958.png)


Best regards,
Matías.

**Comment by jba** [comment]
@rakyll @ramonza Any idea where the loss of info is happening? I don't think it's any code in this repo.

**Comment by ramonza** [comment]
In order to get HTTP request details, you need to use [ochttp.Handler](https://godoc.org/go.opencensus.io/plugin/ochttp#Handler) to wrap your handler. You will not get these details automatically on spans created directly through the trace.StartSpan function.

**Comment by mblasi** [comment]
That was the issue!! Thank you @ramonza !

Regards,
Matías
