### ISSUE TITLE
cbt count returns nothing

### ISSUE THREAD

**Issue by DariuszAniszewski** [GoogleCloudPlatform/google-cloud-go#1099]
Hey,

I noticed that `cbt count` doesn't give the count of objects in the table anymore. 
Printing the value was removed [in this commit](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/746fd9fb60d7a2db0242a4b7fd7a37ffc98522bb#diff-97417fedb6f5a2c6cc1451ea28cb1d08).

Is this on purpose? Shouldn't `cbt count` actually print the count, not just calculate it for no use?

I might be missing some broader context of this change, but I'd love to be able to read the count.

## Client

`cbt`

## Describe Your Environment

N/A

## Expected Behavior

`cbt count` should return the number of items in the table

## Actual Behavior

`cbt count` returns nothing.

**Comment by jba** [comment]
It is merged to master in this repo, but gcloud has its own separate release process. We'll update this issue when it's in gcloud. In the meantime, you can run
```
 go get -u cloud.google.com/go/bigtable/cmd/cbt
```
and use `$GOPATH/bin/cbt`.

**Comment by garye** [comment]
This is fixed in Cloud SDK 214.0.0.
https://cloud.google.com/sdk/docs/release-notes
