### ISSUE TITLE
storage: Writer support for server-side MD5 / CRC32C validation

### ISSUE THREAD

**Issue by jgraettinger** [GoogleCloudPlatform/google-cloud-go#110]
Currently a user can't specify hashes to be validated on upload. If I understand things properly, ObjectAttrs ought to have optional user-settable MD5 & CRC32C fields which are passed through in ObjectAttrs.toRawObject().

See also: relevant [storage API page](https://cloud.google.com/storage/docs/hashes-etags#_JSONAPI)

**Comment by bradfitz** [comment]
I just ran into this too. Seems like an easy enough addition.

**Comment by c0b** [comment]
+1 need this feature

**Comment by c0b** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/writer.go#L84 calls `attrs.toRawObject`
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/storage.go#L651-L665

Where this `attrs.toRawObject` didn't set `Md5Hash` or `Crc32c` is it the very simple add?

```go
// toRawObject copies the editable attributes from o to the raw library's Object type.
func (o *ObjectAttrs) toRawObject(bucket string) *raw.Object {
	acl := toRawObjectACL(o.ACL)
	return &raw.Object{
		Bucket:             bucket,
		Name:               o.Name,
		ContentType:        o.ContentType,
		ContentEncoding:    o.ContentEncoding,
		ContentLanguage:    o.ContentLanguage,
		CacheControl:       o.CacheControl,
		ContentDisposition: o.ContentDisposition,
		StorageClass:       o.StorageClass,
		Acl:                acl,
		Metadata:           o.Metadata,
	}
}
```

https://godoc.org/google.golang.org/api/storage/v1#Object
