### ISSUE TITLE
Stackdriver: status codes doesn't match between traces and UI filter

### ISSUE THREAD

**Issue by mblasi** [GoogleCloudPlatform/google-cloud-go#1102]
## Client

stackdriver-trace

## Describe Your Environment

Google app engine flexible environment (golang)

## Expected Behavior

I generate traces, they are instrumented with opencensus-go, the spans have the http request and response attributes.
I want to filter traces by status code.

## Actual Behavior

If I filter the traces with status_code 200, it doesn't work.

I can see the status code in the span as '0' instead of '200'. Looks related to https://github.com/census-instrumentation/opencensus-go/blob/10cec2c05ea2cfb8b0d856711daedc49d8a45c56/trace/status_codes.go

Please, let me know if it should be reported in opencencsus-go repo.

Regards,
Matías.

**Comment by jadekler** [comment]
I've closed this issue since @ramonza 's reply. If you still have questions, let us know.
