### ISSUE TITLE
Stackdriver: missing http method in filter options

### ISSUE THREAD

**Issue by mblasi** [GoogleCloudPlatform/google-cloud-go#1103]
## Client

Stackdriver-go

## Describe Your Environment

GAE Flexible golang

## Expected Behavior

I want to filter by HTTP PATCH method traces.

## Actual Behavior

HTTP PATCH is missing.

OPTIONS and HEAD are missing too.

Regards,
Matías.

**Comment by mblasi** [comment]
Sorry for few details.

I'm talking about the stackdriver traces UI (https://console.cloud.google.com/traces/traces). It has a filter by HTTP METHOD. It just contains GET/POST/PUT/DELETE.

Regards,
Matías.

**Comment by mblasi** [comment]
Sorry for few details.

I'm talking about the stackdriver traces UI (https://console.cloud.google.com/traces/traces). It has a filter by HTTP METHOD. It just contains GET/POST/PUT/DELETE.

Regards,
Matías.

**Comment by jba** [comment]
This issue tracker is for the Go cloud clients. Try contacting [Stackdriver Trace support](https://cloud.google.com/stackdriver/docs/support) or click on a "Send Feedback" link on one of the doc pages.
