### ISSUE TITLE
Storage: Support for streaming (and error handling)

### ISSUE THREAD

**Issue by snktagarwal** [GoogleCloudPlatform/google-cloud-go#1108]
Thanks guys for an amazing library.

We are using the golang library to write audio files to storage. I have a few questions regarding the right use of library for streaming purposes. We want the following qualities from the library.

* The library should be able to stream in a configurable amount (I see `ChunkSize` in the current API)
* The library should be able to save the partial content (worst case the service crashes and has no time to do recovery)

Is the Go library setup to do something like this? Can we instead flush in periodic amounts? I see the GCS supports a streaming API https://cloud.google.com/storage/docs/streaming. Is Golang actually implementing this?

**Comment by jadekler** [comment]
ChunkSize is the what you're looking for regarding your first question, yes.

I'm not exactly sure what you're asking for in the second question. Could you clarify by describing the scenario? Is it when you're uploading a large object and your service crashes, so you'd like to make sure it's flushing periodically (so some of the data is stored before the crash)?

**Comment by snktagarwal** [comment]
Yes. The use case is we are an Audio Streaming service (for the purposes of this discussion). What that means is that audio is streaming all the time (we don't really have a Flush() or Close() call on the Writer object). Hence, as the audio streams it should be available in the storage buckets.

Currently we see that even after reducing the ChunkSize to 256k (smallest) and let's say I am uploading a file of 100MiB large and I crash the service a few seconds into the upload -- I don't see anything persisted in the bucket.

The other way to ask this question is, does the go GCS library implement this API: https://cloud.google.com/storage/docs/streaming

**Comment by snktagarwal** [comment]
@blangner-suki

**Comment by jadekler** [comment]
Hi @snktagarwal. The `writer.Close()` performs a flush. If your program is quitting unexpectedly, you could trap the signal and call close. A quick codeup here:

```
        sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, os.Interrupt)
	go func(){
		<-sigChan
		if err := ow.Close(); err != nil {
			panic(err)
		}
		os.Exit(1)
	}()
```

I tested this briefly against a 1gb file and it seemed to do the trick just fine.

**Comment by jadekler** [comment]
Also, I don't know that we implement the streaming API you linked, but I'm fairly new to the client so I've sent a question out to a colleague of mine.
