### ISSUE TITLE
PubSub client Receive method never returns when context is cancelled

### ISSUE THREAD

**Issue by ajroetker** [GoogleCloudPlatform/google-cloud-go#1109]
Bug

## Client

PubSub
current

## Describe Your Environment

Docker on GKE

## Expected Behavior

When the context in the PubSub reader's Receive method is cancelled, the receive method will return and stop receiving messages.

## Actual Behavior

In the iterator when the `stop()` method is called, a `it.stopped` channel is closed https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/iterator.go#L118 and the comments in the `receive()` method would suggest that this channel should be checked before trying to retrieve messages for the iterator https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/iterator.go#L175 but as far as I can tell the stopped channel is never checked for `closed(...)` anywhere in the code.

As the code behaves today, if I cancel the context, I need to have a MaxOutstandingMessages or MaxOutstandingBytes set in order for the Acquire to eventually fail for the Receive method to actually return. This is undesirable because it requires that the MaxOutstandingMessages (or Bytes) is hit before the function return because the Acquire function in the flow controller also only checks the context when acquiring messages if the maximum is reached.

This also has the effect that if you choose to set MaxOutstanding settings to 0 and manage those things on the consumer side, the iterator and flow_controller will never return and you'll be stuck in a forever loop. Most people won't see these issues unless they are using high values of MaxOutstanding settings.

**Comment by ajroetker** [comment]
cc @epsniff

**Comment by jadekler** [comment]
I was unable to reproduce this ([gist here](https://gist.github.com/jadekler/fc96aa5d9ff31bc75ec89258058975b2)); when I cancel the ctx sent into Receive, my program halted (despite not setting MaxOutstandingMessages or MaxOutstandingBytes) as expected.

Could you provide a small reproduction? I'm happy to look into this.

**Comment by ajroetker** [comment]
@jadekler I've taken your gist and modified it to reproduce the issue [](https://gist.github.com/ajroetker/f77ea128c6a50cd1d69a9b7d99163dee) (careful running it, it left a routine running on my computer). The important changes are that we do not ack the messages right away in the receive and we set maxoutstanding settings to -1 (i.e. off). In our code we put messages from the receive function on a channel and handle them in another goroutine.

**Comment by ajroetker** [comment]
Also we set numgoroutines to 2 which is also important to reproducing the issues I believe. I think that what is happening is that the map which keeps the state of the inflight messages is never "drained" because one of the two goroutines always has something in flight when checkDrained is called.

**Comment by jadekler** [comment]
Roughly how long do you wait before acking messages? Are messages guaranteed to be eventually acked? I believe it's known behavior that until messages are acked, Receive will block. @jba is that correct?

**Comment by ajroetker** [comment]
We are guaranteed that when the context is cancelled that outstanding messages are acked within 10 minutes. I can reproduce the issue in the example gist even when I've checked that all outstanding messages are acked/nacked after the cancel is called.

**Comment by jadekler** [comment]
Ok, thank you. Finally: is your expectation that once you call cancel, Receive halts immediately? Or, that Receive waits for all acks and then halts? (I believe the behavior is the latter)

**Comment by ajroetker** [comment]
@jadekler The latter, that once all inflight messages are acked/nacked, that receive will return.

Currently I can still even reproduce the issue with something like this

```
        messages := []*pubsub.Message{}
	ctx2 := context.Background()
	ctx2, cancel2 := context.WithCancel(ctx2)
	go func() {
		time.Sleep(5 * time.Second)
		fmt.Println("canceling2")
		cancel2()
		time.Sleep(5 * time.Second)
		for _, m := range messages {
			m.Nack()
		}
		time.Sleep(5 * time.Second)
		fmt.Println("canceling")
		cancel()
		time.Sleep(5 * time.Minute)
		os.Exit(1)
	}()

	fmt.Println("Receiving", time.Now())
	sub.ReceiveSettings.MaxOutstandingMessages = -1
	sub.ReceiveSettings.MaxOutstandingBytes = -1
	sub.ReceiveSettings.NumGoroutines = 1
	err = sub.Receive(ctx, func(c context.Context, m *pubsub.Message) {
		//fmt.Println("Got message", string(m.Data), time.Now())
		//m.Ack()
		select {
		case <-ctx2.Done():
			m.Nack()
		default:
			messages = append(messages, m)
		}
	})
```

**Comment by jadekler** [comment]
Thanks. By adding those settings and a timer before the ack, I'm able to reproduce. I'll label this a bug and take a peek.

**Comment by ajroetker** [comment]
@jadekler Any updates here?

**Comment by jadekler** [comment]
@ajroetker Sorry, my colleague (and primary reviewer) is on leave. Given the subtle nature of this bug it's good to get a solid review before we push anything through. :) We should have an update soon - please feel free to add yourself as cc on the aforementioned code review!

**Comment by jadekler** [comment]
Just a quick note, I'm still tracking this and the review for that CL continues. Apologies for the delay.
