### ISSUE TITLE
Cannot use multiple label filters with monitoring API when listing time series

### ISSUE THREAD

**Issue by nhooyr** [GoogleCloudPlatform/google-cloud-go#1110]
(delete this for feature requests)

## Client

Monitoring

## Describe Your Environment

Just through a testing google cloud instance.

## Expected Behavior

This label filter should work

```
metric.type = "logging.googleapis.com/user/my_metric" AND (metric.labels.instance_name = "foo" OR metric.labels.instance_name = "bar")
```

## Actual Behavior

It fails with saying there was an internal error from the monitoring API.

Removing the OR clause of the above filter makes it begin to work.

**Comment by nhooyr** [comment]
I'm trying to grab metrics for all instances within a single instance group so I list all of the instances within the instance group and then try and grab all the metrics for them via that filter and it doesn't work. For now I'm just going to grab all the metric for all instances and then just filter myself in my own code.

**Comment by jadekler** [comment]
Actually, I've been directed to ask you to directly file this bug against the actual backend service. Would you mind doing so? It would remove the middleman (me) :)

I believe you can use the link to the monitoring issue tracker here: https://cloud.google.com/support/docs/issue-trackers
