### ISSUE TITLE
BigTable Mutation Count Limitations and .Set() Operations

### ISSUE THREAD

**Issue by tylerdmace** [GoogleCloudPlatform/google-cloud-go#1111]
## Client
BigTable

## Describe Your Environment
Running an App Engine Flex Go app locally.

## Expected Behavior

Mutation count limit to be 100k

## Actual Behavior
I have found that `mutation.Set()` operations actually count against the mutation limit while the number of actual mutations do not.

Example: If I create 100k mutations with 2 .Set()s each, BT complains that I am trying to pass 200k mutations. 3 .Set()s results in BT complaining that I'm passing 300k.

```Unable to bulk write records to BigTable: rpc error: code = InvalidArgument desc = Too many mutations: 200000 provided; limit 100000```

**Comment by garye** [comment]
What is the error message exactly? I didn't think the emulator validated this...

**Comment by tylerdmace** [comment]
@garye Actually, it's very likely that I had unset the env variable required for emulator. I'll verify here momentarily and update the issue accordingly.

**Comment by tylerdmace** [comment]
Updated to accurately depict environment (was not in fact using the emulator as previously stated) and included the error message I see when using two `.Set()` operations per `Mutation`.

**Comment by sduskis** [comment]
This is a service constraint.  One [`MutateRowsRequest`](https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/bigtable.proto#L252) can't have more than 100K cells (aka [`Mutation`](https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/data.proto#L444)s in protobuf parlance).

The GoLang library can do one of two things:

1. Fail fast, and give a more user friendly error that uses clearer GoLang library oriented language.  Java has an issue to do the same thing (see [here](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/1919)).
2. Break up the large request into multiple smaller requests that are less than 100K cells.  The library would still check to make sure than a single row's `Mutations`/`SetCells` don't exceed 100K.

**Comment by enocom** [comment]
@jba Do you have a preference for one of the suggestions mentioned above?

**Comment by jba** [comment]
The client should be smart and break up the request.

**Comment by sduskis** [comment]
When doing this, please make sure that you don't break up an individual entry.  Each `Entry` is a transaction, and if you break it up, you break some basic Cloud Bigtable guarantees.  It's perfectly acceptable to break up 10 Entries with 20K mutations into 2 `MutateRowsRequest`s.  You ought not break up a single Entry with 150K mutations, but rather, you should throw a meaningful exception.

**Comment by enocom** [comment]
@sduskis Thank you for the information.

Based on my reading of the proto files, it looks like the `mutations` field in a [`MutateRowRequest`](https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/bigtable.proto#L227) could be broken up into collections under 100,000 without breaking any Cloud Bigtable guarantees.

Each individual `Entry` of the `entries` field of [`MutateRowsRequest`](https://github.com/googleapis/googleapis/blob/master/google/bigtable/v2/bigtable.proto#L252) on the other hand would have to be treated atomically as you say, but a `MutateRowsRequest` could be split into multiple requests provided `entries` are left as is.

Does that sound correct?

**Comment by sduskis** [comment]
@enocom: that's correct.  You can break up a single `MutateRowRequest` request by `entries`, as long as you don't split an individual `Entry`.
