### ISSUE TITLE
Path Format Helpers

### ISSUE THREAD

**Issue by bdhess** [GoogleCloudPlatform/google-cloud-go#1113]
Helpers to build path strings are missing in Go clients, but are available in most other clients (e.g. Java, Python, Ruby).  Ideally, we would generate path format helpers for Go.

Python example:
```python
key_path = kms.KeyManagementServiceClient.crypto_key_path(
        project, location, key_ring, crypto_key)
```

Go example (current):
```go
keyPath := fmt.Sprintf(
    "projects/%s/locations/%s/keyRings/%s/cryptoKeys/%s", 
    project, location, keyRing, cryptoKey)
```

Go example (desired):
```go
keyPath := kms.CryptoKeyPath(project, location, keyRing, cryptoKey)
```

**Comment by jba** [comment]
We have no plans to add these to the Go clients. In our opinion, they offer a small amount of convenience and add clutter to the client surface. However, @pongad now owns the generated Go clients, and he may want to reconsider.

We should also move this issue to the repo that holds the Go generator, which @pongad can point us to I'm sure.

**Comment by bdhess** [comment]
I'd like to point out that each of the six other generated-client languages offers a facility like this, so I guess I'm curious why the outcome of the convenience vs clutter evaluation would be so different for Go.

**Comment by jba** [comment]
The Go design style tends towards minimalism. The other six languages tilt in the other direction. I think if you compare the velocity of new language features in any of the other six to Go, you'll see a pretty dramatic graph. We try to embody that design ethos in our libraries.

**Comment by pongad** [comment]
We just got approval to create a new repo for Go generator. I'll update this issue when it gets created.

We've had such helper methods in the past, and our experience is that they add more confusion than clarity. In addition to the clutter, the methods themselves aren't ideal: they are difficult to find, and their names are often unfortunately long. FWIW, I believe Python is also trying to move away from them.
