### ISSUE TITLE
Flattening in GAPIC-generated clients

### ISSUE THREAD

**Issue by bdhess** [GoogleCloudPlatform/google-cloud-go#1114]
Golang seems not to support the flattening settings in the GAPIC config.  Is this by design?

Current sample:
```go
resp, err := client.Encrypt(context.Background(), &kmspb.EncryptRequest{
	Name: keyPath,
	Plaintext: []byte(textRaw),
})
```

Desired sample:
```go
resp, err := client.Encrypt(context.Background(), keyPath, []byte(textRaw))
```

**Comment by jadekler** [comment]
Yes, that is by design. There are benefits to this design: for example, we can add fields to EncryptRequest without breaking users, whereas we could not do so in the latter example in a backwards-compatible way.

**Comment by bdhess** [comment]
Aha, makes perfect sense given the lack of overloading in golang.  Thanks Jean.

**Comment by jadekler** [comment]
No problem! :)
