### ISSUE TITLE
Cloud Build support

### ISSUE THREAD

**Issue by kyleconroy** [GoogleCloudPlatform/google-cloud-go#1115]
Is there any planned support for creating builds manually via the API? 

https://cloud.google.com/cloud-build/docs/running-builds/start-build-manually

**Comment by kyleconroy** [comment]
Never mind, it appears I should be using https://godoc.org/google.golang.org/api/cloudbuild/v1

**Comment by kyleconroy** [comment]
What's up?

**Comment by tbpg** [comment]
@kyleconroy robot run amok -- sorry for the noise.
