### ISSUE TITLE
Logging - Monitored Resource 

### ISSUE THREAD

**Issue by David-hod** [GoogleCloudPlatform/google-cloud-go#1116]
(delete this for feature requests)

## Client

e.g. PubSub

## Describe Your Environment

e.g. Alpine Docker on GKE

## Expected Behavior

e.g. Messages arrive really fast.

## Actual Behavior

e.g. Messages arrive really slowly.

**Comment by David-hod** [comment]
I tried to log an entry to stackdriver with a special properties on the monitored resource and it seems like the log is sent but the monitored resource field is not correct on stackdriver. I debugged it all the way to the auto generated grpc client and it looks fine. It seems like it's an issue on the grpc client.

```
	client, err := logging.NewClient(context.TODO(), "my-app")
	if err != nil {
		t.Fatal( fmt.Errorf("could not create stackdriver client. error:%s",err.Error()))
	}
	err = client.Ping(context.TODO())
	if err != nil {
		t.Fatal(fmt.Errorf("could not connect to stackdriver client. error:%s",err.Error()))
	}
	mr:= monitoredres.MonitoredResource{
		Type: "project",
		Labels:map[string]string{"label1":"my-app","service":"hook"},
	}
	logname:="request"
	//logger := client.Logger(logname)
	logger := client.Logger(logname,logging.CommonResource(&mr))
	logger.LogSync(context.TODO(),logging.Entry{Severity:logging.Debug,Payload:"something happened",Resource:&mr})
	client.Close()
```

**Comment by David-hod** [comment]
I used LogSync() since I debugged the issue. on production we are using Log(). 
when I open stackdriver UI this is the log that I see :

```
{
 insertId:  "ptdyzmf1476w9"  
 logName:  "projects/my-app/logs/request"  
 receiveTimestamp:  "2018-08-23T15:03:34.240539679Z"  
 resource: {
  labels: {
   project_id:  "my-app"    
  }
  type:  "project"   
 }
 severity:  "DEBUG"  
 textPayload:  "something happened"  
 timestamp:  "2018-08-23T15:01:52.954310841Z"  
} 
```

I expected it to be :
```
{
 insertId:  "ptdyzmf1476w9"  
 logName:  "projects/my-app/logs/request"  
 receiveTimestamp:  "2018-08-23T15:03:34.240539679Z"  
 resource: {
  labels: {
   label1:  "my-app", 
    service: "hook    
  }
  type:  "project"   
 }
 severity:  "DEBUG"  
 textPayload:  "something happened"  
 timestamp:  "2018-08-23T15:01:52.954310841Z"  
} 
```
I debugged it all the way and it seems it like google issue

**Comment by jadekler** [comment]
Ah ok, yeah, that is quite odd. AFAICT the client just does a simple passthrough of your resource to the backend. Therefore, I think it's likely to be a backend issue. Would you mind re-filing this against the backend issue tracker? You can find it here: https://cloud.google.com/support/docs/issue-trackers
