### ISSUE TITLE
cbt stops working with the emulator after 1h of being offline.

### ISSUE THREAD

**Issue by jcgregorio** [GoogleCloudPlatform/google-cloud-go#1118]
I discovered this while trying to do some development using the BigTable emulator while on a 3h plane flight with no wifi.

cbt worked for the first hour but after the first hour would freeze when I tried to do anything with it.

The problem is that even if BIGTABLE_EMULATOR_HOST is set, cbt still tries to call out to "gcloud config config-helper...", which will try to refresh the auth token if it has expired, which freezes when you are offline. Note that this only happens when -cred isn't set, if -cred is set, even to a non-existent file, then "gcloud config config-helper..." is never called and the freeze doesn't occur, which is a work-around for this issue.

## Client

cbt

## Describe Your Environment

Linux.

## Expected Behavior

cbt and the BigTable emulator should work all the time in an offline situation.

## Actual Behavior

cbt freezes after 1h of offline time.

**Comment by enocom** [comment]
Thanks for reporting this, @jcgregorio. 

What version of gcloud were you using when you saw this?

**Comment by jcgregorio** [comment]
$ cbt version
0.6.0 a55dfc0b 2018-07-18 20:10:55

**Comment by enocom** [comment]
@jcgregorio Thanks for the cbt version. That helps.

What version of gcloud was on your system when you say this problem?

I'm trying to reproduce the hang before making any changes, but haven't had any luck with gcloud v220.0.0.

**Comment by jcgregorio** [comment]
Google Cloud SDK 213.0.0

**Comment by enocom** [comment]
@jcgregorio Using Google Cloud SDK 213.0.0 and the associated cbt version (0.60.0), I'm still unable to reproduce this problem.

Would you mind providing steps to reproduce?

**Comment by jcgregorio** [comment]
Hmm, I just tried to reproduce on 220 and can't seem to, feel free to close this issue.

**Comment by enocom** [comment]
@jcgregorio Thanks for trying to reproduce it. If you see this pop up again, feel free to re-open this and we'll dig into it once more.
