### ISSUE TITLE
Bigtable emulator rejects valid timestamps

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-go#1120]
## Client

The Bigtable emulator.

## Describe Your Environment

Any.

## Expected Behavior

A mutation with a timestamp value of `0` should be accepted by the emulator, it is accepted by the server.

## Actual Behavior

The timestamp is rejected.

I think the problem is here:

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/b1954287c11b66ec6972819af95ccd7af1b3cdb1/bigtable/bttest/inmem.go#L1065

That `<=` should be `<`.

**Comment by jadekler** [comment]
Thanks for reporting this. https://code-review.googlesource.com/c/gocloud/+/32170
