### ISSUE TITLE
storage.Reader should implement io.ReadSeeker rather than loading everything immediatly

### ISSUE THREAD

**Issue by bLuka** [GoogleCloudPlatform/google-cloud-go#1124]
On the storage package, building a `*storage.Reader` means start loading the file in memory (`storage/reader.go:130`).

I was looking for binding a `*storage.Reader` to the `http.ServeContent` method to optimize seeking for file parts thanks to the If-Range requests.

This means `storage.Reader` should implement the `io.ReadSeeker` interface, and delegate the file loading to the `Read()` method. A `Seek()` method should also be implemented.

I know the If-Range requests can be handled as-is with the `storage.NewRangeReader()` function, but I think it would be prettier to have `io.ReadSeeker` implemented.

I'll try submitting a PR for this 🙂

**Comment by jadekler** [comment]
Hi @bLuka - if you intend on submitting a code change, please do so via gerrit. We unfortunately don't have github-gerrit two-way support yet :( A description of how to do so can be found at our [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md) - let me know if you have any questions about that though!

**Comment by bLuka** [comment]
Let's go then o/
https://code-review.googlesource.com/c/gocloud/+/32310

**Comment by jba** [comment]
I'm sorry, I'm just getting around to looking at the motivation for the CL. I'm not sure modifying the storage client is the right way to do this.

First, it involves significant changes to `storage.Reader`, as the CL shows. The current state of the CL is just the start. It would need unit and integration tests, and then there's the issue of delaying the request until the first read, which will further complicate the reader (and change its semantics a bit, since `NewRangeReader` will not return an error if there's a problem).

Second, I think providing `Seek` is misleading, since you're not really seeking through the stream, you're making a new request. 

Third, it won't be a great fit: `io.ReadSeeker` can't handle all the information in the ranged request. For example, if the request asks for 10 bytes at offset 17, `http.ServeContent` will seek to 17. Your implementation will then issue a ranged request for the _entire_ content at offset 17, which could result in unnecessary traffic (and expense). 

Fourth, I think you could easily implement `io.ReadSeeker` on top of the storage client. Here's a sketch:
 ```
type storageReadSeeker struct {
	ctx    context.Context
	obj    *storage.ObjectHandle
	r      *storage.Reader
	offset int64 // initial offset
	pos    int64 // current position (like 'seen' in storage.Reader)
}

func (s *storageReadSeeker) Read(buf []byte) (int, error) {
	if s.r == nil {
		// Note: the -1 for length is necessary because we don't have all the information
		// from the request that http.ServeContent received.
		s.r, err = s.obj.NewRangeReader(s.ctx, s.offset, -1)
		// check err
	}
	n, err := s.r.Read(buf)
	// set pos
	// check err
}

func (s *storageReadSeeker) Seek(offset int64, whence int) (int64, error) {
	var newOffset int64
	switch whence {
	//...
	}
	s.r.Close()
	s.r = nil
	s.offset = newOffset
	// Next call to Read will re-open at the right place.
	// ...
}
```

**Comment by bLuka** [comment]
Thanks for your answer!

I understand your highlights, and I need further knowledge on HTTP's range requests and Go architecture. I'd be glad if I could ask you some questions?

1. I had the same assumption at first (when I opened this issue), thinking all the file would be downloaded right after the HTTP request.
However that would need a large internal (at kernel level?) buffer if you don't consume it right now, and I remembered a `write` syscall may block on a socket until a `read` through it.

   So I'm wondering wether an HTTP body would be consumed if nobody is reading it or not?
   I did my whole CL's design after supposing that was not the case, that may had be a mistake 😄 

2. I'm often going into the code I'm using to make it include everything I need to use it as smoothly as I can. By doing so, I'm creating huge modules I'm using with the fewest lines of code.

   So, if I understand your advice correctly, a better way here would be to wrap the storage module in an `io.ReadSeeker` structure I define on the top of the module?
   What benefices it makes from doing so?
   Should I make it in another module I'll export later, or directly in the one where I need it?

**Comment by jba** [comment]
1. I didn't mean to say that the whole file would be downloaded. You're right that an HTTP Body won't be consumed if no one reads it. But we can assume that the data is buffered, so even if you only want the first ten bytes, perhaps 8K or 64K are delivered. That's still a lot more bandwidth and money than necessary.

2. The advantage to writing code that uses the client (or any package) rather than adding the code to the package is that the package stays small, with only the features that most people need. For the clients in this repo, we generally try to make them fairly light wrappers around the underlying API. We often add functionality to expose new parts of the API, but we don't generally add convenience functions, especially if they can be implemented on top of the client. 

I think the `io.ReadSeeker` wrapper could certainly be its own package, but if you only need it in one place, you can just put it in that package. You can always break it out to its own package later if you find another use for it.

**Comment by carbocation** [comment]
Just curious if anyone has defined an `io.ReadSeeker`-compatible wrapper? I have previously implemented an `io.ReaderAt` wrapper (discussed in #1125) but not a `ReadSeeker`.

**Comment by carbocation** [comment]
I gave this a shot, building on @jba 's reply above. Posting here in case it helps others:

```go
package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"strings"

	"cloud.google.com/go/storage"
	"github.com/carbocation/pfx"
)

// Decorates a Google Storage object handle with an io.ReadSeekCloser. Derived
// from
// https://github.com/googleapis/google-cloud-go/issues/1124#issuecomment-419070541
type GSReadSeekCloser struct {
	*storage.ObjectHandle
	Context context.Context
	Closer  *func() error

	r        *storage.Reader
	offset   int64 // initial offset
	pos      int64 // current position (like 'seen' in storage.Reader)
	filesize int64 // if this is known and set, it enables io.SeekEnd
}

func (s *GSReadSeekCloser) Read(buf []byte) (int, error) {
	var err error
	if s.r == nil {
		// Note: the -1 for length is necessary because we don't have all the information
		// from the request that http.ServeContent received.
		s.r, err = s.NewRangeReader(s.Context, s.offset, -1)
		if err != nil {
			return 0, err
		}
	}
	n, err := s.r.Read(buf)
	if err != nil {
		return 0, err
	}
	s.pos += int64(n)

	return n, nil
}

func (s *GSReadSeekCloser) Seek(offset int64, whence int) (int64, error) {

	// Seeking is not actually possible. As a proxy, we close the current
	// connection, reset the reader, and reset the offset.
	var newOffset int64

	// Set the offset for the next Read or Write to offset, interpreted
	// according to whence
	switch whence {
	case io.SeekStart:
		// Set our new offset relative to 0
		newOffset = offset
	case io.SeekCurrent:
		// Set our new offset relative to our current offset
		newOffset = s.offset + offset
	case io.SeekEnd:
		// Set our new offset relative to the end of the file. If the end of the
		// file is not known, fail.
		if s.filesize == 0 {
			return 0, fmt.Errorf("GSReadSeekCloser.Seek: io.Seeker 'whence' value %d is not implemented", whence)
		}

		newOffset = s.filesize - offset
	}

	// Close the current reader and remove it.
	s.r.Close()
	s.r = nil

	// Update our offset
	s.offset = newOffset

	// Not sure that this is the correct thing to do for pos. (Treating this as
	// how many bytes we have read from the current offset.)
	s.pos = 0

	// Return the new offset relative to the start of the file
	return s.offset, nil
}

// Satisfies io.Closer. If o.close is not set, this is a nop.
func (o *GSReadSeekCloser) Close() error {
	if o.Closer != nil {
		return (*o.Closer)()
	}

	return nil
}
```

**Comment by raceordie690** [comment]
@[carbocation](https://github.com/carbocation)  Thanks for posting, saved me some time.  To suit my needs, I made some changes.  I'm using Arrow/Parquet reader and reading multi-terabyte parquets spread across 20 or so GB shards.  So, I made some changes to better take advantage of Parquets parallel reading.  Of particular note, passing -1 to NewRangeReader causes Parquet Reader to read the entire file into memory, in my case, 20-22GB's.   At least in my use case, Parquet only issues ReadAt and never sequential.

`import (
	"context"
	"fmt"
	"io"
	"sync"
	"sync/atomic"

	"cloud.google.com/go/storage"
)

// Decorates a Google Storage object handle with an io.ReadSeekCloser. Derived
// from
// https://github.com/googleapis/google-cloud-go/issues/1124#issuecomment-419070541
type GSReadSeekCloser struct {
	*storage.ObjectHandle
	Context context.Context
	Closer  *func() error

	r          *storage.Reader
	pos        int64          // current position (like 'seen' in storage.Reader)
	filesize   int64          // if this is known and set, it enables io.SeekEnd
	TotalBytes int64          // REP: replaced offset with TotalBytes
	mux        sync.Mutex     // REP: Lock sequential reads -- recommend using either sequentially or randomly, not both
	wg         sync.WaitGroup // REP: Keep track of how many ReatAt readers
	closed     bool           // REP: no more reading allowed
}

//* create a new GSReadSeekCloser -- default starting position is 0
func NewGSReadSeekCloser(obj *storage.ObjectHandle, ctx context.Context, closer *func() error) (s GSReadSeekCloser, err error) {
	a, err := obj.Attrs(ctx)
	if err != nil {
		return
	}
	s = GSReadSeekCloser{ObjectHandle: obj, Context: ctx, Closer: closer, pos: 0, filesize: a.Size, closed: false}
	return
}

func (s *GSReadSeekCloser) Read(buf []byte) (int, error) {
	var err error
	if s.closed {
		return 0, io.EOF
	}
	s.mux.Lock()
	defer s.mux.Unlock()
	if s.r == nil {
		if s.pos == 0 {
			//* REP use NewReader for pos == 0
			//* ReadAt will use their own readers

			s.r, err = s.NewReader(s.Context)
			if err != nil {
				return 0, err
			}
		} else {
			//! REP if you open a RangeReader, you cannot continue reading from a point without
			//! opening a new RangeReader. Using -1 enables this, however, it reads remainder of file into buffer.
			n, err := s.ReadAt(buf, s.pos)
			s.pos += int64(n)
			return n, err
		}

	}
	n, err := read(s.r, buf)

	//* REP: always move the file position even if there is an error
	s.pos += int64(n)
	atomic.AddInt64(&s.TotalBytes, int64(n))
	return n, err
}

// ReadAt simply reads from a specific position in the file, always relative to 0 (beginning)
// REP as specified, ReadAt should not modify state of reader
// REP added to complete interface requirements
func (s *GSReadSeekCloser) ReadAt(buf []byte, offset int64) (n int, err error) {
	var atReader *storage.Reader
	if s.closed {
		return 0, io.EOF
	}
	s.wg.Add(1)
	defer s.wg.Done()
	atReader, err = s.NewRangeReader(s.Context, offset, int64(len(buf)))
	if err != nil {
		return
	}
	defer atReader.Close()
	n, err = read(atReader, buf)
	atomic.AddInt64(&s.TotalBytes, int64(n))
	return
}

func (s *GSReadSeekCloser) Seek(offset int64, whence int) (int64, error) {

	// Seeking is not actually possible. As a proxy, we close the current
	// connection, reset the reader, and reset the offset.
	var newPos int64
	if s.closed {
		return 0, io.EOF
	}
	s.mux.Lock()
	s.mux.Unlock()

	// Set the offset for the next Read or Write to offset, interpreted
	// according to whence
	switch whence {
	case io.SeekStart:
		// Set our new offset relative to 0
		newPos = offset
	case io.SeekCurrent:
		// Set our new offset relative to our current offset
		newPos = s.pos + offset
	case io.SeekEnd:
		// Set our new offset relative to the end of the file. If the end of the
		// file is not known, fail.
		if s.filesize == 0 {
			return 0, fmt.Errorf("GSReadSeekCloser.Seek: io.Seeker 'whence' value %d is not implemented", whence)
		}

		newPos = s.filesize - offset
	}

	// Close the current reader and remove it.
	if s.r != nil && s.pos != newPos {
		s.r.Close()
		s.r = nil
	}

	// Update our offset
	s.pos = newPos

	// Return the new offset relative to the start of the file
	return s.pos, nil
}

// Satisfies io.Closer. If s.close is not set, this is a nop.
// REP: o -> s for consistency
func (s *GSReadSeekCloser) Close() error {
	if s.closed {
		return io.EOF // Already closed
	}
	s.closed = true
	if s.Closer != nil {
		return (*s.Closer)()
	}
	// Wait for any ReadAt's to complete
	s.wg.Wait()
	return nil
}

// REP: general purpose read
func read(rdr *storage.Reader, buf []byte) (n int, err error) {
	var r int

	for n < len(buf) && err == nil {
		r, err = rdr.Read(buf[n:])
		n += r
	}
	return n, err
}
`

**Comment by raceordie690** [comment]
@[carbocation](https://github.com/carbocation) Thanks for posting, saved me some time. To suit my needs, I made some changes. I'm using Arrow/Parquet reader and reading multi-terabyte parquets spread across 20 or so GB shards. So, I made some changes to better take advantage of Parquets parallel reading. Of particular note, passing -1 to NewRangeReader causes Parquet Reader to read the entire file into memory, in my case, 20-22GB's. At least in my use case, Parquet only issues ReadAt and never sequential.  

Robert

```go
import (
	"context"
	"fmt"
	"io"
	"sync"
	"sync/atomic"

	"cloud.google.com/go/storage"
)

// Decorates a Google Storage object handle with an io.ReadSeekCloser. Derived
// from
// https://github.com/googleapis/google-cloud-go/issues/1124#issuecomment-419070541
type GSReadSeekCloser struct {
	*storage.ObjectHandle
	Context context.Context
	Closer  *func() error

	r          *storage.Reader
	pos        int64          // current position (like 'seen' in storage.Reader)
	filesize   int64          // if this is known and set, it enables io.SeekEnd
	TotalBytes int64          // REP: replaced offset with TotalBytes
	mux        sync.Mutex     // REP: Lock sequential reads -- recommend using either sequentially or randomly, not both
	wg         sync.WaitGroup // REP: Keep track of how many ReatAt readers
	closed     bool           // REP: no more reading allowed
}

//* create a new GSReadSeekCloser -- default starting position is 0
func NewGSReadSeekCloser(obj *storage.ObjectHandle, ctx context.Context, closer *func() error) (s GSReadSeekCloser, err error) {
	a, err := obj.Attrs(ctx)
	if err != nil {
		return
	}
	s = GSReadSeekCloser{ObjectHandle: obj, Context: ctx, Closer: closer, pos: 0, filesize: a.Size, closed: false}
	return
}

func (s *GSReadSeekCloser) Read(buf []byte) (int, error) {
	var err error
	if s.closed {
		return 0, io.EOF
	}
	s.mux.Lock()
	defer s.mux.Unlock()
	if s.r == nil {
		if s.pos == 0 {
			//* REP use NewReader for pos == 0
			//* ReadAt will use their own readers

			s.r, err = s.NewReader(s.Context)
			if err != nil {
				return 0, err
			}
		} else {
			//! REP if you open a RangeReader, you cannot continue reading from a point without
			//! opening a new RangeReader. Using -1 enables this, however, it reads remainder of file into buffer.
			n, err := s.ReadAt(buf, s.pos)
			s.pos += int64(n)
			return n, err
		}

	}
	n, err := read(s.r, buf)

	//* REP: always move the file position even if there is an error
	s.pos += int64(n)
	atomic.AddInt64(&s.TotalBytes, int64(n))
	return n, err
}

// ReadAt simply reads from a specific position in the file, always relative to 0 (beginning)
// REP as specified, ReadAt should not modify state of reader
// REP added to complete interface requirements
func (s *GSReadSeekCloser) ReadAt(buf []byte, offset int64) (n int, err error) {
	var atReader *storage.Reader
	if s.closed {
		return 0, io.EOF
	}
	s.wg.Add(1)
	defer s.wg.Done()
	atReader, err = s.NewRangeReader(s.Context, offset, int64(len(buf)))
	if err != nil {
		return
	}
	defer atReader.Close()
	n, err = read(atReader, buf)
	atomic.AddInt64(&s.TotalBytes, int64(n))
	return
}

func (s *GSReadSeekCloser) Seek(offset int64, whence int) (int64, error) {

	// Seeking is not actually possible. As a proxy, we close the current
	// connection, reset the reader, and reset the offset.
	var newPos int64
	if s.closed {
		return 0, io.EOF
	}
	s.mux.Lock()
	s.mux.Unlock()

	// Set the offset for the next Read or Write to offset, interpreted
	// according to whence
	switch whence {
	case io.SeekStart:
		// Set our new offset relative to 0
		newPos = offset
	case io.SeekCurrent:
		// Set our new offset relative to our current offset
		newPos = s.pos + offset
	case io.SeekEnd:
		// Set our new offset relative to the end of the file. If the end of the
		// file is not known, fail.
		if s.filesize == 0 {
			return 0, fmt.Errorf("GSReadSeekCloser.Seek: io.Seeker 'whence' value %d is not implemented", whence)
		}

		newPos = s.filesize - offset
	}

	// Close the current reader and remove it.
	if s.r != nil && s.pos != newPos {
		s.r.Close()
		s.r = nil
	}

	// Update our offset
	s.pos = newPos

	// Return the new offset relative to the start of the file
	return s.pos, nil
}

// Satisfies io.Closer. If s.close is not set, this is a nop.
// REP: o -> s for consistency
func (s *GSReadSeekCloser) Close() error {
	if s.closed {
		return io.EOF // Already closed
	}
	s.closed = true
	if s.Closer != nil {
		return (*s.Closer)()
	}
	// Wait for any ReadAt's to complete
	s.wg.Wait()
	return nil
}

// REP: general purpose read
func read(rdr *storage.Reader, buf []byte) (n int, err error) {
	var r int

	for n < len(buf) && err == nil {
		r, err = rdr.Read(buf[n:])
		n += r
	}
	return n, err
}
