### ISSUE TITLE
Storage: Possible to support io.ReaderAt interface?

### ISSUE THREAD

**Issue by carbocation** [GoogleCloudPlatform/google-cloud-go#1125]
I have a few terabytes of genetic data (split into files that are hundreds of gigabytes to terabytes in size). These are binary files and are indexed, such that on a filesystem I can drop into any part of the file and read a set of genotypes very quickly [using a custom library](https://github.com/carbocation/bgen). This is currently written expecting an `os.File`. However, I believe it would be feasible to rewrite this to only require an `io.ReaderAt`, but I don't believe this can be done with the current Google Storage API.

Is it possible for this API to support the `io.ReaderAt` interface?

**Comment by rogerhub** [comment]
For a quick solution, you should be able to implement your own ReaderAt with [NewRangeReader](https://godoc.org/cloud.google.com/go/storage#ObjectHandle.NewRangeReader) right? Although, this interface makes it more explicit that each random read adds an additional latency cost.

**Comment by carbocation** [comment]
@rogerhub your suggestion worked perfectly. I [created an interface](https://github.com/carbocation/genomisc/compare/8c9ef122d6ab47285dd12288bd9adbad1e735edd...4611e6df9ce70ee9967d19f580ce147ab96106c4) that modeled the aspects that I needed from `os.File`, and which I could make the storage API conform to with a bit of contortion. For my limited needs, this was actually quite painless.

**Comment by jadekler** [comment]
Closing this as it seems your needs have been met. Thanks @rogerhub :)
