### ISSUE TITLE
BigQuery: Page through query results using a pageToken while being able to store the results in a custom struct

### ISSUE THREAD

**Issue by DerekDuchesne** [GoogleCloudPlatform/google-cloud-go#1126]
Our use case is that we would like to paginate through query results using a `pageToken` so that we can process the results in multiple requests. We can do that via `iterator.NewPager()`, however if we use that, we have to store the results in type `*[][]bigquery.Value`. By using `RowIterator.NextPage()`, we can store the results in custom structs, but then we lose the ability to start reading at a specific `pageToken`. Is there a way that we can paginate using a `pageToken` while storing the results in custom structs?

Below is an example program which tries to paginate through the query results and store the values in a custom struct. The logged error is:
`Error paging through results: slicep should be of type *[][]bigquery.Value, got *[]main.myRow`

```go
package main

import (
	"context"
	"fmt"
	"log"

	"cloud.google.com/go/bigquery"
	"google.golang.org/api/iterator"
)

var (
	projectID = "INSERT_PROJECT_ID"
)

type myRow struct {
	Foo int `bigquery:"foo"`
}

func main() {
	// Create a BigQuery client.
	ctx := context.Background()
	bqClient, err := bigquery.NewClient(ctx, projectID)
	if err != nil {
		log.Fatalf("Error creating bigquery client: %v", err)
	}

	// Create a simple query that reads two rows from BigQuery.
	qry := bqClient.Query("SELECT foo FROM (SELECT 1 AS foo) UNION ALL (SELECT 2 AS foo)")

	// Run the query, get an iterator for the results.
	rowIter, err := qry.Read(ctx)
	if err != nil {
		log.Fatalf("Error reading query results: %v", err)
	}

	// Store the results.
	var results []myRow
	pager := iterator.NewPager(rowIter, 1, "")
	nextPageToken, err := pager.NextPage(&results)
	if err != nil {
		log.Fatalf("Error paging through results: %v", err)
	}

	// Print the results.
	fmt.Printf("Results: %#v\n", results)

	// Print the next page token.
	fmt.Printf("Next page token: %#v\n", nextPageToken)
}
```

**Comment by jba** [comment]
You should be able to paginate using `rowIter.PageInfo().Token`. See https://godoc.org/google.golang.org/api/iterator#PageInfo for usage.

**Comment by DerekDuchesne** [comment]
Thank you for the info about `RowIterator.PageInfo().Token`. I didn't realize you could set the token on the `RowIterator` right after it's created via `RowIterator.PageInfo().Token = "token"`. Same for `RowIterator.PageInfo().MaxSize`.

Thanks for the help! I'll close this issue now.

**Comment by fodcool** [comment]
hi bro, i got the same error:  ```Error paging through results: slicep should be of type *[][]bigquery.Value, got *[]main.myRow```
how to fix it?  thx

**Comment by dliroberts** [comment]
Hey @fodcool, I was asking myself the exact same question after reading this thread! The proposed solution here is to not use `iterator.NewPager()` at all, as if you do, you need to provide a `*[][]bigquery.Value`, which is hard to work with. Instead, you can do something like:

```
	qry := bqClient.Query("SELECT foo FROM (SELECT 1 AS foo) UNION ALL (SELECT 2 AS foo)")

	rowIter, err := qry.Read(ctx)
	if err != nil {
		log.Fatalf("Error reading query results: %v", err)
	}
	rowIter.PageInfo().Token = pageToken
	var foo myStruct{}
	rowIter.Next(&foo)
	nextToken := rowIter.PageInfo().Token
```

The key thing to note here is you can both...
* Read `rowIter.PageInfo().Token` _after_ a `Next()` call, in order to get a token value you can use later, and
* Set `rowIter.PageInfo().Token` _before_ a `Next()` call, in order to pick up where you left off
