### ISSUE TITLE
Dataproc: Unable to set a region different than global

### ISSUE THREAD

**Issue by hleonps** [GoogleCloudPlatform/google-cloud-go#1129]
## Client

Dataproc

## Describe Your Environment

macOS 10.13.6
go 1.10.3
google-cloud-go  v0.26.0

## Expected Behavior

Set any available region specified in https://cloud.google.com/compute/docs/regions-zones/#available. Also to be able to use [auto zone](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/auto-zone) with non-global region.

## Actual Behavior

If a region like `us-central1` is sent in the request, the response will be `rpc error: code = InvalidArgument desc = Region 'us-central1' invalid or not supported by this endpoint; permitted regions: '[global]'` which is unexpected, since the REST API accepts an equivalent request.

**Comment by jadekler** [comment]
@hleonps I believe this error is being returned by the backend service, rather than the client library. Could you re-file this issue on their issue tracker? See: https://cloud.google.com/support/docs/issue-trackers

**Comment by hleonps** [comment]
@jadekler you're right. Thank you.
