### ISSUE TITLE
firestore querying nil fails if attribute does not exist

### ISSUE THREAD

**Issue by asontha** [GoogleCloudPlatform/google-cloud-go#1133]
## Client

Firestore

## Describe Your Environment

local development

## Expected Behavior

when querying for documents where attribute does not exist, this should work:
.Where(<attribute we're looking for>, "==", nil)

## Actual Behavior

Requires that the attribute exists but is set to null

**Comment by jadekler** [comment]
Could you point to the documentation for that property? Or, are you seeing this behavior in other languages?

**Comment by jba** [comment]
@schmidt-sebastian, what is the right behavior here?

**Comment by schmidt-sebastian** [comment]
`Nil/Null` are special field values in Firestore that are distinct from "field is not set". You can only query for fields that are explicitly set to `nil`.

Note that there is a work-around that might help here. You can use `orderBy` to only return documents that have an explicit value for a given field, no matter what the value is. While this is the opposite of what you are asking for, it might solve your problem nonetheless.

**Comment by jadekler** [comment]
Closing since this seems to be working as intended.
