### ISSUE TITLE
datastore: RunInTransaction() does not pass previous transaction ID on retry

### ISSUE THREAD

**Issue by havardk** [GoogleCloudPlatform/google-cloud-go#1137]
The datastore client's RunInTransaction() contains this piece of code that seems to pass down the previous transaction id when retrying a transaction because it previously conflicted with another transaction:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/8c9fc24c2b85cbc71e8f1dbb6b7ac70a20bfe1c2/datastore/transaction.go#L176-L180

However, just before this code we call Transaction.Commit() and after Commit(), the transaction id is *always* nil.  I'm not sure what the backend does with this data, but this code should either be fixed or removed.

**Comment by jba** [comment]
https://code-review.googlesource.com/c/gocloud/+/32770
