### ISSUE TITLE
BigQuery: job data is fetched without compression and with prettyPrint?

### ISSUE THREAD

**Issue by jayp** [GoogleCloudPlatform/google-cloud-go#1140]
I am running a query and reading the results using [the code sample presented in the godoc](https://godoc.org/cloud.google.com/go/bigquery#example-Job-Read).

The library calls the following URL: https://www.googleapis.com/bigquery/v2/projects/.../datasets/_.../tables/anon.../data?alt=json&startIndex=0

This request results with an implicit `prettyPrint=true`. The difference between that and `prettyPrint=false` is huge (~10x) for my data. This is worse because client is not requesting compressed data.   

- Firstly, I want to double check that this is the default behavior? I am having a hard time believing it.
- Secondly, I can't grok from the documentation/code how callers can enable compression and/or disable prettyPrint.

**Comment by jba** [comment]
Astonishingly, you are right. https://code-review.googlesource.com/c/google-api-go-client/+/32710 fixes it in the underlying code generator. (We're just going to disable prettyPrint everywhere.) Then we have to actually regenerate the code, then a `go get -u` should fix it for you.

I don't know how to enable compression either.

**Comment by jba** [comment]
Reminder: you won't see this until https://code-review.googlesource.com/c/google-api-go-client/+/32750 is submitted and you `go get -u cloud.google.com/go/bigquery`. Will ping here.

**Comment by jba** [comment]
CL submitted. Please let us know if it's working for you.

**Comment by jayp** [comment]
Fix works for me. Thank you!
