### ISSUE TITLE
HTTP 400 Error when calling ex

### ISSUE THREAD

**Issue by JamieSinn** [GoogleCloudPlatform/google-cloud-go#1142]
## Client

AppEngine

## Describe Your Environment

Golang 1.10 on AppEngine Flex

## Expected Behavior

HTTP(S) Request is permitted when using urlfetch as the client.

## Actual Behavior

Error log:

```
internal.flushLog: Flush RPC: service bridge returned HTTP 400 ("App Engine APIs over the Service Bridge are disabled.\nIf they are required, enable them by setting the following to your app.yaml:\n\nbeta_settings:\n enable_app_engine_apis: true\n")
```
Code:
```
func makeTBARequest(c *gin.Context, path string) string {
	url := "https://www.thebluealliance.com/api/v3" + path
	ctx := appengine.NewContext(c.Request)
	client := urlfetch.Client(ctx)
	req, err := http.NewRequest("GET", url, nil)
	req.Header.Set("User-Agent", "OTR-Scouting")
	req.Header.Set("X-TBA-Auth-Key", "XXXX")
	resp, err := client.Do(req)
	if err != nil {
		log.Debugf(ctx, "HTTP request error for TBA %v", err)
		return ""
	}

	body, _ := ioutil.ReadAll(resp.Body)
	log.Debugf(ctx, "HTTP GET returned status %v", resp.Status)
	return string(body)
}
```

This is the only documentation I can find for making external requests - and it's for the standard env.

https://cloud.google.com/appengine/docs/standard/go/outbound-requests

**Comment by JamieSinn** [comment]
Related: https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/pull/92
Adding the mentioned code to the app.yaml throws an error mentioning the wrong documentation:

```
WARNING: Support for the compat runtimes and their base images (enable_app_engine_apis: true) has been deprecated.  Please migrate to a new base image, or use a Google managed runtime. To learn more, visit https://cloud.google.com/appengine/docs/flexible/python
/migrating.
Services to deploy:
...
```

**Comment by jadekler** [comment]
Hello! I believe your issue is about `google.golang.org/appengine/urlfetch`? If so, the place to file this issue would be https://github.com/golang/appengine. This repo is `cloud.google.com/go/...`.

I'll close this for now, but let me know if that's incorrect - I'm happy to re-open!

**Comment by JamieSinn** [comment]
Oops, I'll move it there. The issue is present when using the base http library as well if that matters.
