### ISSUE TITLE
cloudsql error while connecting with golang dial unix /cloudsql/xxx .s.PGSQL.5432: connect: no such file or directory

### ISSUE THREAD

**Issue by preetsc27** [GoogleCloudPlatform/google-cloud-go#1152]
## Client

Cloud SQL - postgres

## Describe Your Environment

App engine flex golang

## Expected Behavior

Connect to database

## Actual Behavior

dial unix /cloudsql/my_project_id:asia-south1:trapigodb/.s.PGSQL.5432: connect: no such file or directory

app.yaml
```yaml
service: dbtest
runtime: go1.9
env: flex

env_variables:
  POSTGRES_CONNECTION: "user=postgres password=xxxx dbname=tdb host=/cloudsql/my_project_id:asia-south1:trapigodb"
```

main.go
```go
package main

import (
	"github.com/gin-gonic/gin"
	"net/http"
  "database/sql"
	"fmt"
	_ "github.com/lib/pq"
	"os"
  "strings"
)

func dbFunc() (*sql.DB, error){
	var db *sql.DB
	var err error


datastoreName := os.Getenv("POSTGRES_CONNECTION")
db, err = sql.Open("postgres", datastoreName)
	if err != nil{
		fmt.Println("ERROR GRD JI:", err)
		return nil, err
	}

	fmt.Println("Connected to databse")
	return db, nil
}


func main() {
	router := gin.Default()

	router.GET("/", func(c *gin.Context) {
		c.String(http.StatusOK, "GRD")
	})

	// this is the main code
	router.GET("/dbCheck", func(c *gin.Context) {
		db, err := dbFunc()
		if err != nil {
      c.String(http.StatusOK, err.Error())
			return
		}
		defer db.Close()
		rows, err := db.Query("SELECT name from dj")
		if err != nil{
			c.String(http.StatusOK, err.Error())
			return
		}
		defer rows.Close()
		var usernames []string
		for rows.Next(){
			var username string
			err = rows.Scan(&username)
			if err != nil{
				c.String(http.StatusOK, err.Error())
				return
			}
			usernames = append(usernames, username)
		}
		out := strings.Join(usernames, ",")
		c.String(http.StatusOK, out)
	})

	router.Run(":8080")
}
```

## Note
* Cloud SQL API and SQL Admin API is on.
* I did not created a cloud proxy as it is to run locally I instead directly deployed the app just for testing.

**Comment by jadekler** [comment]
Hello! This issue tracker is unfortunately only used for `cloud.google.com/go/...` libraries. It appears your question is related to using the Cloud SQL API with the stdlib sql connector on AppEngine. For questions relating to that, please use either the recommended AppEngine support paths https://cloud.google.com/appengine/community.

**Comment by sharkyze** [comment]
Hey, @preetsc27. 
Have you asked this question elsewhere or were you ever able to get this to work ?

**Comment by preetsc27** [comment]
I was able to get it working.

**Comment by binajmen** [comment]
> I was able to get it working.

Would you mind share your experience? :)

**Comment by preetsc27** [comment]
It is working now.

**Comment by binajmen** [comment]
I get that, but what have you done to fix this issue? It could help me understand my issue :S

**Comment by GrigoriyMikhalkin** [comment]
@binajmen Hi, did you solved your issue)?

**Comment by binajmen** [comment]
Yes, it was linked to my ENV variables that were not set properly.
You definitely have to make sure the db URI you use is well built. For MySQL, using GORM, something like that:

```dbURI = fmt.Sprintf("%s:%s@unix(/cloudsql/%s)/%s?charset=utf8mb4&parseTime=True&loc=Local", dbUser, dbPwd, dbHost, dbName)```

where `dbHost` is your CLOUDSQL_CONNECTION_NAME

**Comment by GrigoriyMikhalkin** [comment]
@binajmen Thanks!
