### ISSUE TITLE
[Storage] Bucket Lock missing features

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-go#1153]
Synced with @jadekler on this in person.
## Client

Storage client library doesn't surface all new metadata associated to Bucket Lock as defined in the [GCS Discovery Document](https://www.googleapis.com/discovery/v1/apis/storage/v1/rest).

## Missing Metadata from Object and Bucket Attrs Structs

* Unable to check if a retention policy is locked by using metadata in Bucket resource ("isLocked" in RetentionPolicy)
* I'm unable to get/update Bucket metadata for DefaultEventBasedHold and get/update Object metadata for EventBasedHold.
* I'm unable to get/update Object metadata for TemporaryHold.
* I'm unable to get Object metadata for retentionExpirationTime.

**Comment by jadekler** [comment]
Note: RetentionExpirationTime appears to be read-only. Here are the docs:

```
        // RetentionExpirationTime: A server-determined value that specifies the
	// earliest time that the object's retention period expires. This value
	// is in RFC 3339 format. Note 1: This field is not provided for objects
	// with an active event-based hold, since retention expiration is
	// unknown until the hold is removed. Note 2: This value can be provided
	// even when temporary hold is set (so that the user can reason about
	// policy without having to first unset the temporary hold).
	RetentionExpirationTime string `json:"retentionExpirationTime,omitempty"
```

**Comment by frankyn** [comment]
That's expected that's why I called out get only in the issue. Sorry if I confused you.

**Comment by jadekler** [comment]
Shoot. Must be tired, I totally read it as get/update. Sorry!

**Comment by frankyn** [comment]
No worries! I understand. Thanks for your help!
