### ISSUE TITLE
pubsub: Receive sometimes deadlocks if the pubsub client is closed before Receive returns

### ISSUE THREAD

**Issue by nhooyr** [GoogleCloudPlatform/google-cloud-go#1156]
this loop becomes an infinite loop

https://github.com/googleapis/gax-go/blob/1ef592c90f479e3ab30c6c2312e20e13881b7ea6/invoke.go#L67

because the pubsub receive retrier considers rpc canceled errors to be retryable, see https://github.com/GoogleCloudPlatform/google-cloud-go/blob/52c81d2be13be4e238119034b12b7c075af5baf2/pubsub/apiv1/subscriber_client.go#L92

There is also https://github.com/GoogleCloudPlatform/google-cloud-go/blob/52c81d2be13be4e238119034b12b7c075af5baf2/pubsub/service.go#L71 which is used further up the call stack and would also cause an infinite loop.

**Comment by nhooyr** [comment]
Linked commit only fixes https://github.com/GoogleCloudPlatform/google-cloud-go/blob/52c81d2be13be4e238119034b12b7c075af5baf2/pubsub/service.go#L71

What about https://github.com/GoogleCloudPlatform/google-cloud-go/blob/52c81d2be13be4e238119034b12b7c075af5baf2/pubsub/apiv1/subscriber_client.go#L92 ?

**Comment by nhooyr** [comment]
Both are definitely causing deadlocks. I added printfs when I was debugging to confirm.

**Comment by jadekler** [comment]
Right on. @pongad do you happen to know where [this line](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/52c81d2be13be4e238119034b12b7c075af5baf2/pubsub/apiv1/subscriber_client.go#L95) is being generated from?

**Comment by erickertz** [comment]
@nhooyr Thanks for posting this, I am seemingly experiencing the same behavior and it had me scratching my head for a while. My client is using the Receive method and it periodically gets deadlocked. I am handiling the non-retry error return from Receive and have put tons of logging into my client app, but when it deadlocks no error returns and the Receive callback no longer functions. 

I have yet to go as far as you did with additional logging in the client, but what I am seeing seems spot on with what you reported. Were you able to work around this at all until a fix is released? Thanks!

**Comment by nhooyr** [comment]
Yes I was able to work around. Cancel the context passed to receive first and ensure receive exits before closing the pubsub client.

**Comment by erickertz** [comment]
@nhooyr I see. Did you do this by adding some type of listener on the Subscription? I guess I'm just not sure how to detect if the Subscription has been canceled in order to cancel the context. Thanks again, big help.

**Comment by guillaumeblaquiere** [comment]
Hello

I experience this issue with the lib version: cloud.google.com/go v0.39.0 
It occurs randomly on my Cloud Run and Cloud Function (alpha Go 1.12).

I just trying to force the grpc-go version to 1.13 to see if it's better. More news in few hours...

I release a version (of cloud function package) of my code (but it shouldn't be useful, the problem is exactly this one described)
https://github.com/guillaumeblaquiere/pubsubToBq

**Comment by jadekler** [comment]
@guillaumeblaquiere Please file a new issue.
