### ISSUE TITLE
PubSub

### ISSUE THREAD

**Issue by kakadiyahardik** [GoogleCloudPlatform/google-cloud-go#1157]
I am using PubSub with java,  

## My code for subscriber
ProjectSubscriptionName subName = ProjectSubscriptionName.of(CommonUtils.GCLOUD_PROJECT_ID,
					SUBSCRIPTION_ID);

			MessageReceiver receiver = new MessageReceiver() {
				@Override
				public void receiveMessage(PubsubMessage message, AckReplyConsumer consumer) {
					String messageString = message.getData().toStringUtf8();
					System.out.println("message received : " + message.getMessageId());
					consumer.ack();

				}
			};

			Subscriber subscriber = null;
			try {
				ExecutorProvider executorProvider = InstantiatingExecutorProvider.newBuilder().setExecutorThreadCount(1)
						.build();
				subscriber = Subscriber.newBuilder(subName, receiver)
						.setCredentialsProvider(FixedCredentialsProvider.create(credentials))
						.setExecutorProvider(executorProvider).build();

				subscriber.startAsync();
			} catch (Exception e) {
				errorLog.push(e);
			}

## Actual Behavior
It creates a lot of thread so after start application my server gonna closed within few times

**Comment by jadekler** [comment]
Unfortunately this issue tracker is for Go only. Could you please re-file this issue in the Java issue tracker? https://github.com/GoogleCloudPlatform/google-cloud-java/issues/
