### ISSUE TITLE
Add Vision helper method for Object Localization 

### ISSUE THREAD

**Issue by dizcology** [GoogleCloudPlatform/google-cloud-go#1160]
Please add helper method (partial) to Vision for Feature.Type OBJECT_LOCALIZATION, in this file: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/vision/apiv1/client.go

See related Ruby issue: https://github.com/googleapis/google-cloud-ruby/issues/2482
See related PHP issue: https://github.com/googleapis/google-cloud-php/issues/1303
And related C# change: https://github.com/googleapis/google-cloud-dotnet/commit/367420a1602950bdf3271294ffec873c2b76d114
And related comment on ruby-docs-samples for sample demonstrating ObjectLocalization: https://github.com/GoogleCloudPlatform/ruby-docs-samples/commit/963d75f833d46400dafd03c0b33a7839319cd0ac#r217499831

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/33471
