### ISSUE TITLE
storage: cancelling *Writer context leaks media buffer and io pipe

### ISSUE THREAD

**Issue by nytopop** [GoogleCloudPlatform/google-cloud-go#1161]
When calling [NewWriter](https://godoc.org/cloud.google.com/go/storage#ObjectHandle.NewWriter), it is implied that cancelling the provided context is sufficient to abort the upload:

> It is the caller's responsibility to call Close when writing is done. To stop writing without saving the data, cancel the context.

However, in many cases, if only the context is cancelled (without calling `Close` or `CloseWithError`) then the pipe created [here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/writer.go#L94) is never closed. As such, [`(*MediaBuffer).loadChunk`](https://github.com/googleapis/google-api-go-client/blob/master/gensupport/buffer.go#L49) blocks forever and the `*MediaBuffer` never gets garbage collected. This results in a memory/goroutine leak:

goroutine             |  heap
:-------------------------:|:-------------------------:
![2018-09-26-113122_152x1172_scrot](https://user-images.githubusercontent.com/7799664/46101048-cd0d2c00-c17f-11e8-8822-275d9fe61cb7.png)  |  ![2018-09-26-113344_340x1123_scrot](https://user-images.githubusercontent.com/7799664/46101158-13fb2180-c180-11e8-8e17-5a74284f1fc9.png)

## Expected Behavior
Cancelling the passed in context should eventually free all associated resources.

## Actual Behavior
It does not.

**Comment by nytopop** [comment]
Thanks @jadekler! :trophy:

**Comment by jadekler** [comment]
Sure thing! Let us know if you observe any more problems.
