### ISSUE TITLE
Bigquery: Why civil.Date map Date type field from 2018-09-09 to 0000-00-00?

### ISSUE THREAD

**Issue by richzw** [GoogleCloudPlatform/google-cloud-go#1164]
With the following codes

		var record []bigquery.Value
		err := it.Next(&record)
		if err == iterator.Done {
			break
		}

		if err != nil {
			fmt.Println("Failed to parse bigquery value")
		}

		fmt.Println(record)

The results are

       [74BkBzTiR 1 2018-09-09]
       [74BkBzTiR 2 2018-09-09]
       [74BkBzTiR 3 2018-09-09]

However, when I use the following struct to map those row data

		var record struct {
			Uid     string    
			Level   int     
			UtcDate civil.Date
		}

		err := it.Next(&record)
		if err == iterator.Done {
			break
		}

		if err != nil {
			fmt.Println("Failed to parse bigquery value")
		}

		fmt.Println(record)

Give results

      {74BkBzTiR 1 0000-00-00}
      {74BkBzTiR 2 0000-00-00}
      {74BkBzTiR 3 0000-00-00}

The date `2018-09-09` map to `0000-00-00`. 

Is there something wrong with my codes or anything I am missing?

**Comment by jadekler** [comment]
@jba Would this be covered in the work happening in https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1145?

**Comment by jba** [comment]
@jadekler I don't think it's related.

@richzw What are your column names? When you read a row into a record, the column names have to match up, or you can use a tag like
```
   UtcDate civil.Date `bigquery:"myDateField"`
```

See https://godoc.org/cloud.google.com/go/bigquery#example-InferSchema--Tags.

**Comment by richzw** [comment]
Wow, @jba , you are right, after adding tag `bigquery: udate`, the date could be fetched correctly.
Thank you very much.
