### ISSUE TITLE
Full list of BigQuery error reasons.

### ISSUE THREAD

**Issue by piotrkowalczuk** [GoogleCloudPlatform/google-cloud-go#1170]
It would be very useful if the package would expose constants that describe possible reasons error occurred (plus some description). As a result, it would be possible to unpack received error and react as necessary. 

As an example, let's use simple gRPC API that wraps BigQuery and allows to retrieve some data. If let's say it runs out of the budget, the application should return `codes.ResourceExhausted` after each call that failed due to that reason. 

If there is any other way to achieve it right now. Please let me know.

**Comment by jba** [comment]
The BigQuery API is HTTP/JSON based, not gRPC based. You can try casting the error to [`*googleapi.Error`](https://godoc.org/google.golang.org/api/googleapi#Error) and looking at the HTTP status code.

**Comment by piotrkowalczuk** [comment]
@jba Sorry for not being precise enough. The example I gave is use case when checking what was the `reason` would be useful.

The point is that I have no idea what are possible values of the `reason` field. So my application is not able to handle failure properly. 

I assumed that `reason` is a field that carries necessary context. Additional documentation on how error handling should be implemented would be useful.

**Comment by jba** [comment]
Agreed. But the Go client is just passing along whatever the service returns. So this is really an issue for the BigQuery service (https://cloud.google.com/bigquery).

**Comment by enocom** [comment]
@piotrkowalczuk Here's a nice table summarizing the values for `reason`: https://cloud.google.com/bigquery/troubleshooting-errors.
