### ISSUE TITLE
pubsub: Hang on Recieve

### ISSUE THREAD

**Issue by JackyChiu** [GoogleCloudPlatform/google-cloud-go#1173]
## Client

PubSub v0.29 && v0.24

## Describe Your Environment

Local macOS && GKE

## Expected Behavior

`Receive` should exit when the context is canceled. 

## Actual Behavior

Receive will hang and not exit. 

I did some digging and it's waiting for the `messageIterator.stop` method [here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/subscription.go#L516). It seems like this only happens when a large number of messages (of reasonable size) are backlogged. This happens in production as well when the service crashes due to error. It will restart with a large backlog. 

This can be reproduced locally with this [gist](https://gist.github.com/JackyChiu/f09d0f529e1c97ce1d5a0284e82581bf).  

So far the options I've found are to either `RecieveSettings.Synchronous` (which isn't ideal because we have a high throughput service), or increase the `RecieveSettings.NumGoroutines` which also isn't ideal because the number of goroutines to bypass this issue depends on the environment (whether in production or development).

**Comment by jadekler** [comment]
This is being investigated in https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1163, so let's continue the discussion there. In the meantime, if you're wanting to resolve this immediately, please try pinning to `google-cloud-go=v0.24.0` and `grpc-go=1.13.0`.

Thanks for providing some repro and debugging - that's much appreciated. I'll investigate these today.

**Comment by jadekler** [comment]
Just looked into this: my last comment is actually completely wrong: it's totally unrelated. Sorry. Re-opening and investigating.

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/34152

**Comment by JackyChiu** [comment]
Thanks for the quick follow up!

**Comment by jadekler** [comment]
Hi @JackyChiu. https://code-review.googlesource.com/c/gocloud/+/34191 fixes this problem in pstest, but does not fix the underlying problem. Instead, other commits to google-cloud-go, google-api-go-client, and grpc-go should by now have fixed that issue with the exception of some degraded performance some users might experience (being tracked in https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1177).

Could you try updating to google-cloud-go=HEAD, google-api-go-client=HEAD, grpc-go=v1.15.0?

If you find that you're still experiencing the issue, please let us know and we can re-open.

**Comment by JackyChiu** [comment]
Thanks! I just deployed changes to our service running `google-cloud-go=v0.24` and `grpc-go=v1.13.0` after the mention that this test issue was unrelated. I'll be following along in #1177
