### ISSUE TITLE
spanner: can not create database containing `-` in the database id

### ISSUE THREAD

**Issue by yfuruyama** [GoogleCloudPlatform/google-cloud-go#1178]
## Client

spanner

## Describe Your Environment

* Go: go1.11.1 darwin/amd64
* google-cloud-go: v0.25.0

This is a test code to reproduce the bug.

```go
package main

import (
	"context"
	"fmt"

	adminapi "cloud.google.com/go/spanner/admin/database/apiv1"
	adminpb "google.golang.org/genproto/googleapis/spanner/admin/database/v1"
)

func main() {
	ctx := context.Background()
	client, _ := adminapi.NewDatabaseAdminClient(ctx)

	projectId := "<PROJECT_ID>"
	instanceId := "<INSTANCE_ID>"
	_, err := client.CreateDatabase(ctx, &adminpb.CreateDatabaseRequest{
		Parent:          fmt.Sprintf("projects/%s/instances/%s", projectId, instanceId),
		CreateStatement: "CREATE DATABASE test-1",
	})
	if err != nil {
		fmt.Println(err)
	}
}
```

## Expected Behavior

The table is successfully created.
(Syntax reference: https://cloud.google.com/spanner/docs/data-definition-language#create_database)

## Actual Behavior

Following error happened.

```
rpc error: code = InvalidArgument desc = Error parsing Spanner DDL statement: CREATE DATABASE test-1 : Syntax error on line 1, column 21: Expecting 'EOF' but found '-1'
```

## Additional

From web console, I was able to create a database containing `-` in the database id.

**Comment by jba** [comment]
This is a Spanner issue, not a Go client issue. @snehashah16.

**Comment by snehashah16** [comment]
Hey Jonathan, afair this should be allowed .  I have created databases in the past with hyphens and underscores . I could be wrong and I can reproduce this. Could u give me the error response

**Comment by jadekler** [comment]
As Jonathan mentioned, this is the Spanner API returning an error, not the client library. So, I'm going to close this issue and I'll create an internal bug for the API authors. Thanks for mentioning this to us @snehashah16.
