### ISSUE TITLE
Document syntax of using both maxage + maxversions for cbt

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/google-cloud-go#1179]
https://github.com/GoogleCloudPlatform/google-cloud-go/issues/581#issuecomment-392903476 says:

> This was fixed with 75e7ef3b96310bc12657d209b5f9f7bb1d16af1b, which added the ability to write policies like `maxage=3d and maxversions=100`.

Could this be added to the comments of the appropriate method(s) so it shows up in the docs, e.g.,

* https://cloud.google.com/bigtable/docs/cbt-reference#create_a_table
* https://cloud.google.com/bigtable/docs/cbt-reference#set_the_gc_policy_for_a_column_family

so it's clear for users how to do this?

/cc: @garye, @ghaisa

**Comment by jadekler** [comment]
Hi @mbrukman - could you please file an internal bug, since maintainers of this repo are generally not in charge of cloud.google.com documentation?

**Comment by mbrukman** [comment]
Sorry for not clarifying. That page is not manually written, it's auto-generated from the `cbt` command-line tool which is tracked in this repo, specifically [`bigtable/cmd/cbt/cbtdoc.go`][cbtdoc], which is auto-generated from [`bigtable/cmd/cbt/cbt.go`][cbt] which are in this repo.

[cbtdoc]: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/24c3c3d77a0907226ed74ef8515f8a23544c7dfa/bigtable/cmd/cbt/cbtdoc.go
[cbt]: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/24c3c3d77a0907226ed74ef8515f8a23544c7dfa/bigtable/cmd/cbt/cbt.go

**Comment by jadekler** [comment]
Ah! That's news to me! Thank you for re-opening.

**Comment by enocom** [comment]
@mbrukman In particular, are you thinking of `maxversions=2 and maxage=1h` or `maxversions=2 or maxage=1h` showing up under [createtable](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/24c3c3d77a0907226ed74ef8515f8a23544c7dfa/bigtable/cmd/cbt/cbtdoc.go#L142-L145) and [setgcpolicy](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/24c3c3d77a0907226ed74ef8515f8a23544c7dfa/bigtable/cmd/cbt/cbtdoc.go#L307-L310)?

**Comment by mbrukman** [comment]
@enocom — yes, that's precisely what I was thinking of!

**Comment by enocom** [comment]
Thanks! I'll update the docs accordingly.
