### ISSUE TITLE
cbt count takes longer time than expected 

### ISSUE THREAD

**Issue by pranay29** [GoogleCloudPlatform/google-cloud-go#1180]
## Client

Bigtable

## Describe Your Environment

`cbt count` on Bigtable with millions of records

## Expected Behavior

`cbt count` should return and display the #records even if the records are more than 100Million.

## Actual Behavior

`cbt` count does not return records for more than 1 hour

`cbt` throws below error, while trying the count operation -> 

`Retryable error: rpc error: code = DeadlineExceeded desc `

Here is the command that I use from `cloud shell` ->

`cbt -project my-project -instance my-instance count my-table`

The table contains around 100-110 million records. But I need to verify it by running a `count` on Bigtable.

Bigtable instance configuration details -
Instance type - Development
Storage type - HDD

**Comment by sduskis** [comment]
CBT count does a read rows and counts on the client side.  We don't have an easier way to do that.  You can run a [Dataflow job](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/dataflow-connector-examples#sourcerowcount---reading-from-cloud-bigtable), but that's also a bit onerous.

**Comment by sduskis** [comment]
There are probably two TODOs:

1.  There's probably a bug in our GoLang retry logic which didn't resume after the deadline exceeded.

2.  There's also an opportunity for a more effective method of counting.  We can use `SampleRowKeys` to get partitions of the table, and then run multiple go routines to read multiple partitions concurrently. 

@enocom, we should address TODO 1 first, which would likely require some discussion.  @garye, any insights would be appreciated about TODO 1.

TODO 2 is speculative, and should be filed as a separate feature request.

**Comment by garye** [comment]
From the message it looks like it _was_ retried. The scan encountered the server-side deadline but should be retried after that. It probably just hadn't finished yet when @pranay29 gave up.

**Comment by enocom** [comment]
@pranay29 Does cbt exit when it reports `Retryable error` or is it logging that message without exiting?

**Comment by pranay29** [comment]
I will retry and give you the exact message but I think it retries.

**Comment by sduskis** [comment]
The error in the OP is `Retryable error: rpc error: code = DeadlineExceeded desc`.  As @garye [said](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1180#issuecomment-430049222), that's a warning only, and that a retry is in progress.

**Comment by enocom** [comment]
Yes, I see that in the code [here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/1d9633a229077f680bf8fe431a93d5f489835506/bigtable/internal/gax/invoke.go#L68). Other than splitting a large request into multiple parts (as you mentioned above), I'm not sure if there's anything actionable here. The retry code looks OK to me.

**Comment by pranay29** [comment]
These are the logs from the command that I used to `count` on the Bigtable table - 

```
2018/10/18 21:31:12 Retryable error: rpc error: code = DeadlineExceeded desc = Error while reading table 'projects/my-proj/instances/my-instance/tables/my-table', retrying in 93.774911ms
2018/10/18 21:58:40 Retryable error: rpc error: code = DeadlineExceeded desc = Error while reading table 'projects/my-project/instances/my-instance/tables/my-table', retrying in 111.569721ms
```

As we see from the timestamps, it is quite evident that `count` is not optimized, though `reads`  from `Bigtable` are.

**Comment by enocom** [comment]
Thanks for the update @pranay29. 

The `Retryable error` you're seeing is the client bumping up against a deadline on the backend.

I think [the suggestion](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1180#issuecomment-429992080) by @sduskis is the best approach.

**Comment by pranay29** [comment]
> CBT count does a read rows and counts on the client side. We don't have an easier way to do that. You can run a [Dataflow job](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/tree/master/java/dataflow-connector-examples#sourcerowcount---reading-from-cloud-bigtable), but that's also a bit onerous.

Yes @sduskis you are right. We even tried a Dataflow job but it returned with same `Retryable error`. 

It would be nice to have a fix around this so that `count` command returns results more effectively.
