### ISSUE TITLE
Add fmt/lint checks to CI

### ISSUE THREAD

**Issue by jadekler** [GoogleCloudPlatform/google-cloud-go#1190]
- [x] [gofmt](https://golang.org/cmd/gofmt/)
- [x] [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports)
- [x] [lint](https://github.com/golang/lint)
- [x] [staticcheck](https://github.com/dominikh/go-tools)

**Comment by dsymonds** [comment]
This really shouldn't have added linting as an enforced part of the CI. While the others are at least 100% reliable, golint is definitely not as it tries to automate some level of human sensitivity. Having it here makes for a lot of unnecessary busywork.

Would you mind if I remove the linting?
