### ISSUE TITLE
bigquery: stream older data into partitioned tables

### ISSUE THREAD

**Issue by FdeFabricio** [GoogleCloudPlatform/google-cloud-go#1192]
## Client

BigQuery

## Describe Your Environment

golang:1.9 docker image
```
# vendor
name = "cloud.google.com/go"
revision = "dfffe386c33fb24c34ee501e5723df5b97b98514"
version = "v0.30.0"
```
## Expected Behavior

Stream data older than 7 days into time partitioned tables using `(u *Uploader) Put`. The [documentation](https://cloud.google.com/bigquery/streaming-data-into-bigquery#streaming_into_partitioned_tables) says it is possible to stream data not older than 1 year in the past.

## Actual Behavior

I tried adding the $yyyymmdd suffix (#427) for a 35 days old entry but I got this error message:

> The destination table's partition download_2018$20180918 is outside the allowed bounds. You can only stream to partitions within 31 days in the past and 16 days in the future relative to the current date.`

Then I tried adding an entry not older than 31 days and I got this error message: 

> Value 1537706070000000 for field hit_time of the destination table palcomp3-hotbkp:hits.download_2018$20180923 is outside the allowed bounds. You can only stream to date range within 7 days in the past and 3 days in the future relative to the current date.

Table schema and partitioning config:
```golang
bigquery.TableMetadata{
	Schema: bigquery.Schema{
		{Name: "music_id", Required: true, Type: bigquery.IntegerFieldType},
		{Name: "user_id", Required: false, Type: bigquery.IntegerFieldType},
		{Name: "hit_time", Required: true, Type: bigquery.TimestampFieldType},
	},
	TimePartitioning: &bigquery.TimePartitioning{Field: "hit_time", RequirePartitionFilter: true},
	Clustering:       &bigquery.Clustering{Fields: []string{"music_id"}},
}
```

**Comment by jadekler** [comment]
Sorry for the not-great experience. :/ This seems to be an error with the underlying service, though, as opposed to the client libraries. Would you mind re-filing this bug there? This feedback would be very valuable for them. See the list of backend issue trackers here: https://cloud.google.com/support/docs/issue-trackers

**Comment by chemikadze** [comment]
@FdeFabricio As far as I understand, passing `Field` in `TimePartitioning` assumes partitioning column. At the same time, suffix in table name is used for ingestion-time partitioned tables. As far as I understand, suffix should not be used in case of column-based partitioning.

**Comment by FdeFabricio** [comment]
@chemikadze Yeah, you are right. There was a divergence with the API and its documentation, since this is a feature that has been rolled out very recently. But it is working ok now.

ref: https://issuetracker.google.com/issues/118122471
