### ISSUE TITLE
Setting ExpirationTime to Zero neither throws Error  or changes Table to never expire

### ISSUE THREAD

**Issue by cobookman** [GoogleCloudPlatform/google-cloud-go#1196]
Is it possible to change a table's expiration time to be never? Why does setting ExpirationTime to Zero not cause an error thrown or Expiration Time to change to `never`

## Client

BigQuery

## Describe Your Environment

gLinux

## Expected Behavior

If Expiration Time set to 0, either change Table Expiration to Never, or throwing Error.

## Actual Behavior

No change to expiration time, no error.

Sample Code:
```
package main

import (
        "fmt"
        "time"
        "log"
        "context"
        "cloud.google.com/go/bigquery"
        "encoding/json"
)

func main() {
        ctx := context.Background()
        c, err := bigquery.NewClient(ctx, "my-project")
        if err != nil {
                log.Fatal("failed to make client", err)
        }
        d := c.Dataset("testdataset")

        md, err := d.Metadata(ctx)
        if err != nil {
                log.Fatal("failed to get dataset metadata", err)
        }
        bmd, _ := json.MarshalIndent(md, "", "  ")
        log.Println("Datset Metadata", string(bmd))

        t := d.Table("testtable")
        mt, err := t.Metadata(ctx)
        if err != nil {
                log.Fatal("failed to get table metadata", err)
        }
        bmt, _ := json.MarshalIndent(mt, "", "  ")
        log.Println("Table Metadata", string(bmt))

        mt2, err := t.Update(ctx, bigquery.TableMetadataToUpdate{
                Description: fmt.Sprintf("My Table (timestamp - %d)", time.Now().Unix()),
                ExpirationTime: time.Time{},
        }, "")
        if err != nil {
                log.Fatal("Failed to change table metadata", err)
        }
        bmt2, _ := json.MarshalIndent(mt2, "", "  ")
        log.Println("Changed Table Metadata", string(bmt2))
}
```
Note that no error thrown when calling t.Update(...), and no change to Table Metadata's Expiration Time.

**Comment by cobookman** [comment]
Mirroring internal thread.

1) Sending null as the expiration time changes Expiration Time to `never`. Sending 0 as expiration time deletes the table all together.
2) It's Not possible to give NULL / NIL for Expiration Time:
https://godoc.org/google.golang.org/api/bigquery/v2#Table
```
    ExpirationTime int64 `json:"expirationTime,omitempty,string"`
```

api/bigquery/v2/Table && TableMetadataToUpdate should likely be modified to be pointers vs raw types. Allowing for nil value & for nil to be passed back up to BQ RPC

**Comment by cobookman** [comment]
An alternative is to copy the behavior of BQ CLI Command and have the following cause a table's expiration time to be changed to "never":
```
tm, err := t.Update(ctx, bigquery.TableMetadataToUpdate{
    ExpirationTime: time.Time{},
}, "")
```

This can be done by doing following Code Changes:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/table.go#L333-L335
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/table.go#L488-L491
```
if tm.ExpirationTime.IsZero() {
    t.ExpirationTime = nil
    forceSend("ExpirationTime")
} else {
    // note this is also a bug due to overflowing of int64 - see issue 1194
    expirationTime := int64(tm.ExpirationTime.UnixNano() / 1e6) 
    t.ExpirationTime = &expirationTime
    forceSend("ExpirationTime")
}
```


https://github.com/googleapis/google-api-go-client/blob/master/bigquery/v2/bigquery-gen.go#L3025
```
type Table struct {
    ...
    ExpirationTime *int64
}
```

**Comment by cobookman** [comment]
@jadekler How is this a question? BQ CLI command, BQ WebUI, and Rest API all allow for this.
Feel free to mark as dup of issue #1194

**Comment by jadekler** [comment]
I've held off re-labeling this until we see what's going on in https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1194. Will update once we know more.

**Comment by enocom** [comment]
Thanks for your report @cobookman. We'll work to get this fixed.
