### ISSUE TITLE
Invalid Deprecation Warning

### ISSUE THREAD

**Issue by cobookman** [GoogleCloudPlatform/google-cloud-go#1197]
On https://godoc.org/google.golang.org/api/bigquery/v2
it lists "This package is DEPRECATED. Use package cloud.google.com/go/bigquery instead."

However "https://godoc.org/cloud.google.com/go/bigquery" source code references "https://godoc.org/google.golang.org/api/bigquery/v2".

Can we give clearer warnings on the gRPC autogen package vs more dev friendly Cloud SDK version.

**Comment by jba** [comment]
I'm not sure what the issue here is. A certain package is deprecated for users because a better package is available. The better package uses the deprecated package as an implementation detail. What would the "clearer warning" look like?

**Comment by cobookman** [comment]
Deprecation == do not use package as in < 1 year it'll be removed and broken.
If the cloud.google.com/go/bigquery is relying on a deprecated package that's not good. and we should probably have a P0/P1 ticket open to track the migration off of google.golang.org/api/bigquery/v2
--
Now if the notice is to just let the user know there's a more developer friendly package available. We should probably change the text to read.

""This package is the raw gRPC library and is not formally supported by Google Cloud.
Please use cloud.google.com/go/bigquery for the formal BigQuery SDK."""

**Comment by broady** [comment]
It's not the raw gRPC library, it uses JSON/REST.

Deprecated certainly doesn't mean "it'll be removed/broken in <1 year". I think the wording is fine.
