### ISSUE TITLE
Spanner query GROUP BY not working when using prepared statement with variable binding

### ISSUE THREAD

**Issue by lc-jordanfelix** [GoogleCloudPlatform/google-cloud-go#1201]
## Client

Spanner

## Describe Your Environment

macOS Mojave (Version 10.14) Terminal with Go 1.11.1 using cloud.google.com/go v0.31.0

## Expected Behavior

Expect query in which the GROUP BY column-name is specified using parameter binding (using spanner.Statement) to either group the results by specified column or error due to the column value being a string literal.

We want to allow our API consumer to specify which columns by which to group the results.  However, we would like to prevent SQL injection which is why we tried using parameter binding.  If there is a better way to do this, please let us know.  Thanks!

## Actual Behavior

Example:
```go
spannerClient.Single().Query(context.Background(), spanner.Statement{
  SQL: "SELECT * FROM table GROUP BY @column",
  Params: map[string]interface{}{
    "column": column,
  }
})
```

The above query executes as if the 'GROUP BY @column' does not exist at all.  The docs state "Parameters may appear anywhere that a literal value is expected" and GROUP BY cannot use literal values in Spanner, however, this kind of statement executes without error but also does not group the results.

**Comment by jadekler** [comment]
This appears to be WAI. See https://groups.google.com/a/google.com/forum/?utm_medium=email&utm_source=footer#!msg/cloud-spanner-users/8-VlRHEvB40/tZqsL6pGCgAJ:

> Query parameters can be used in substitution of arbitrary expressions. They cannot, however, be used in substitution of identifiers, *column names*, table names, or other parts of the query itself.

**Comment by lc-jordanfelix** [comment]
Hi @jadekler, thanks for getting back to us about that. As it is working as intended, we still are curious as to why the statement execution has no error.  An error would have helped us track down our mistake easier.  We ended up coming to the same conclusion; the issue was more about the result from executing the above spanner.Statement.  When running the same statement in the Cloud Spanner console, it returns an error.

We cannot access the forum post linked, but your quote was helpful nonetheless.

**Comment by jadekler** [comment]
@lc-jordanfelix That's a great point. We've raised this with the backend team, but if you'd like, please feel free to also open an issue at https://cloud.google.com/support/docs/issue-trackers.

**Comment by adirastogi** [comment]
This looks like some sort of a bug in the client library implementation because as you've observed by running the query through the cloud console, this SQL statement shouldn't even compile.

Adding @crwilcox  to help get a repro.

**Comment by jadekler** [comment]
@adirastogi Client libraries do not perform parameter binding; they merely return the error given by spanner. Let's continue the discussion on internal bug 118686392.
