### ISSUE TITLE
Is there some way to provide all of the subscribers with all messages of subscription, rather than with subset of those messages?

### ISSUE THREAD

**Issue by IvanProdaiko94** [GoogleCloudPlatform/google-cloud-go#1205]
_Originally posted by @IvanProdaiko94 in https://github.com/GoogleCloudPlatform/google-cloud-go/issues/698#issuecomment-435045046_

**Comment by kamalaboulhosn** [comment]
If you need to have all subscribers receive all messages, then it is necessary to create a subscription for each of those subscribers. Delivery to multiple subscribers takes on two forms:

Fan out: Every subscriber receives the entire set of messages. This is done by using different subscriptions.
Load balancing: Subscribers receive a subset of the messages, allowing for more parallel processing of messages. This is done by using a single subscription with multiple subscribers.

**Comment by IvanProdaiko94** [comment]
@kamalaboulhosn, pubsub provides only 10k subscriptions in the project, so, for doing a lot of small tasks, fan out is ok, but it has too small subscriptions limit

**Comment by IvanProdaiko94** [comment]
@kamalaboulhosn is this done in

**Comment by kamalaboulhosn** [comment]
Yes, that is correct. Cloud Pub/Sub isn't really designed for cases of very high fanout (in terms of number of topics or in terms of number of subscriptions per topic) at this time.

**Comment by IvanProdaiko94** [comment]
@kamalaboulhosn could you please suggest any alternative having such an ability in GCP (AppEngine)?
