### ISSUE TITLE
functions/metadata: FromContext and NewContext use Metadata values thus perhaps unnecessary copying

### ISSUE THREAD

**Issue by odeke-em** [GoogleCloudPlatform/google-cloud-go#1208]
I promised @tbpg that I'd give feedback on Go on Google Cloud Functions.

While compiling some feedback for Tyler and Stewart, I was studying the metadata package and I noticed that the metadata helpers FromContext and NewContext use a Metadata value instead of a pointer.
This comes from the default code bootstrapped in the GCF UI in
<img width="628" alt="screen shot 2018-11-04 at 6 22 04 pm" src="https://user-images.githubusercontent.com/4898263/48031721-f9668180-e109-11e8-920c-8ec3dba4852e.png">

I didn't know whether to report this via email or here, as the email with Stewart copied was more of the product feedback than code+performance suggestions.

### Problem statement
By the definition of a value, whenever we pass one into a function all constituent fields that are by value are also copied in every invocation. Basically the value put into NewContext will be copied and the one from FromContext is just retrieved. The copy into NewContext is what am trying to avoid i.e.

Architecture|Sizeof(Metadata)|Sizeof(*Metadata)
---|---|---|
386 (32bit)|60|4
x86 (64bit)|104|8

### Suggestion
I think we should use pointer values and on retrieving the saved metadata we should be able to have the originally stored one lest we'd be making an unnecessary copy. If perhaps this is for a secure design then sure we can use values but otherwise I've made a comparison and the results show we can shave an allocation and a bunch of bytes as shown above but also reduce time in FromContext+NewContext by 70% and bytes allocated too by 70% Given that this code is in the hot path, I believe that we could make Go on GCF even faster.

### Diff
```diff
diff --git a/functions/metadata/metadata.go b/functions/metadata/metadata.go
index 8f401698..5e1c521d 100644
--- a/functions/metadata/metadata.go
+++ b/functions/metadata/metadata.go
@@ -33,7 +33,7 @@ type Metadata struct {
 	// EventType is the type of the event. For example: "google.pubsub.topic.publish".
 	EventType string `json:"eventType"`
 	// Resource is the resource that triggered the event.
-	Resource Resource `json:"resource"`
+	Resource *Resource `json:"resource"`
 }
 
 // Resource holds Google Cloud Functions resource metadata.
@@ -48,15 +48,15 @@ type Resource struct {
 }
 
 // NewContext returns a new Context carrying m.
-func NewContext(ctx context.Context, m Metadata) context.Context {
+func NewContext(ctx context.Context, m *Metadata) context.Context {
 	return context.WithValue(ctx, contextKey{}, m)
 }
 
 // FromContext extracts the Metadata from the Context, if present.
-func FromContext(ctx context.Context) (Metadata, bool) {
+func FromContext(ctx context.Context) (*Metadata, bool) {
 	if ctx == nil {
-		return Metadata{}, false
+		return nil, false
 	}
-	m, ok := ctx.Value(contextKey{}).(Metadata)
+	m, ok := ctx.Value(contextKey{}).(*Metadata)
 	return m, ok
 }
```

#### Benchmarks
```go
package metadata_test

import (
	"context"
	"testing"
	"time"

	"cloud.google.com/go/functions/metadata"
)

func BenchmarkNewContext(b *testing.B) {
	md := &metadata.MetadataPtr{
		EventID:   "70172329041928",
		Timestamp: time.Date(2018, 07, 06, 12, 11, 10, 979, time.UTC),
		EventType: "google.pubsub.topic.publish",
		Resource: &metadata.Resource{
			Service: "uploads",
			Name:    "gcf_testing",
			Type:    "create",
		},
	}
	ctx := context.Background()

	b.ResetTimer()
	b.ReportAllocs()

	for i := 0; i < b.N; i++ {
		if dtx := metadata.NewContextPtr(ctx, md); dtx == nil {
			b.Errorf("Iteration #%d: NewContext returned nil", i)
		} else if gmd, _ := metadata.FromContextPtr(dtx); gmd != md {
			b.Errorf("Iteration #%d: FromContext:\nGot: %v\nWant:%v\n", i, gmd, md)
		}
	}
}
```

#### Benchmarks
```shell
$ benchstat before.txt after.txt 
name                old time/op    new time/op    delta
NewContext_value-8     168ns ± 1%      50ns ± 1%  -70.02%  (p=0.000 n=9+8)

name                old alloc/op   new alloc/op   delta
NewContext_value-8      160B ± 0%       48B ± 0%  -70.00%  (p=0.000 n=10+10)

name                old allocs/op  new allocs/op  delta
NewContext_value-8      2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.000 n=10+10)
```

It will also help us gut out an unnecessary allocation on "no metadata" stored which I believe can be a targeted algorithmic slowdown by an attacker i.e. even on !ok we still allocate sizeof(Metadata) if using by value

Please let me know what you think and thank you for all the great work and for getting the project up!

**Comment by tbpg** [comment]
Thank you for the feedback! The original code was a value, switched to pointer in code review, then switched back to value (in the same code review) to avoid being able to change the value stored in the context.

We might need to make a breaking change to this package soon. So, I might hold off on this bug until that's decided (next week or two).

**Comment by odeke-em** [comment]
Thank you for the responses @enocom and @tbpg!

In regards to the labels, it is more of an API breaking change and performance consideration than a feature request.

**Comment by broady** [comment]
I think we're going to end up with a return value of `(*Metadata, error)`.

Thanks for the feedback, @odeke-em!

**Comment by odeke-em** [comment]
Cool, thanks for the update @broady!

**Comment by broady** [comment]
I misunderstood your original request. Yes, makes sense to have pointer types for the fields like Resource, too.

**Comment by tbpg** [comment]
https://code-review.googlesource.com/c/gocloud/+/35870 out for review - feel free to comment.
