### ISSUE TITLE
Pub/Sub missing lib version in README and GoDoc

### ISSUE THREAD

**Issue by anguillanneuf** [GoogleCloudPlatform/google-cloud-go#1212]
In [README.md](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/README.md) -> the Supported API table -> row Pub/Sub, the link should have been `godoc.org/cloud.google.com/go/pubsub/apiv1`. 

The API doc at [https://godoc.org/cloud.google.com/go/pubsub](https://godoc.org/cloud.google.com/go/pubsub) should also reflect the lib version `apiv1`.

**Comment by jadekler** [comment]
The link is intentionally godoc.org/cloud.google.com/go/pubsub. We prefer people not to use the generated apiv1 libraries. Similarly, we intentionally do not mention the pubsub/apiv1/ clients in pubsub/ - they serve different purposes.

Closing for now - let me know if you'd like to discuss this more. Also happy to chat offline.
