### ISSUE TITLE
Request: Vision API Helper Method for PRODUCT_SEARCH

### ISSUE THREAD

**Issue by beccasaurus** [GoogleCloudPlatform/google-cloud-go#1214]
Vision service client should have a helper method added for invoking just the `PRODUCT_SEARCH` [`Feature.Type`](https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1p3beta1#type_1)

See similar previous issues for `OBJECT_LOCALIZATION`:
 - PHP https://github.com/googleapis/google-cloud-php/issues/1303
 - Go https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1160
 - Ruby https://github.com/googleapis/google-cloud-ruby/issues/2482
 - C# (diff) https://github.com/googleapis/google-cloud-dotnet/commit/367420a1602950bdf3271294ffec873c2b76d114
 - Node.js _(these methods are added dynamically, no manual change)_
 - Python _(these methods are added dynamically, no manual change)_
 - Java _(no helper methods afaik)_

**Comment by beccasaurus** [comment]
Related issues for `PRODUCT_SEARCH`:
 - PHP https://github.com/googleapis/google-cloud-php/issues/1412
 - Go https://github.com/GoogleCloudPlatform/google-cloud-go/issues/1214
 - Ruby https://github.com/googleapis/google-cloud-ruby/issues/2593
 - C# https://github.com/googleapis/google-cloud-dotnet/issues/2677

**Comment by jadekler** [comment]
Is this an appropriate signature and method documentation?

```
// ProductSearch searches the image for products.
func (c *ImageAnnotatorClient) ProductSearch([...]) ([...])
```

**Comment by jadekler** [comment]
Added in https://github.com/GoogleCloudPlatform/google-cloud-go/commit/7e260a5462c4da5e7d57f8f745e958c60d68c576#diff-f42087059b37ae7f4d9f0d3a475801a8
