### ISSUE TITLE
Unavailable errors while using  spanner client

### ISSUE THREAD

**Issue by dneralla** [GoogleCloudPlatform/google-cloud-go#1216]
## Client

Spanner client

We get couple of forms of unavailable errors intermittently when using spanner go lang client.  

1) 502.Bad gateway with codes.Unavailable
2) lastErr is < rpc error: code = Unavailable desc = The server cannot handle this request right now. Please retry with backoff > (from the code it looks like last error is the last error functioned returned before the retry. Our context deadline is 1 sec and minBackoff of spanner client seems 1 sec  so that seems like the actual error before triggering the retry and it failed immediately in the retry loop as ctx Deadline is exceeded)

**Comment by jadekler** [comment]
@dneralla 502 get converted into grpc.Unavailable status code, which we retry. I suspect your context deadline needs to be higher: 1s is not giving the retry mechanisms time to sort out network hickups. Are you able to bump that to something like 30s?

**Comment by dneralla** [comment]
@jadekler By looking at code in spanner client I know maxBackoff is set at 32s  but I was just wondering why is that happening. And what can we do to mitigate that before just bumping up the Deadline. And also bumping up to 30s will effect our latencies (not just spanner but other things which depend on this commit being successful)

**Comment by jadekler** [comment]
@dneralla That's understandable. It sounds like what you need is custom retry behavior that suits your specific use case. Are you ok with me closing this question and leaving the custom retry feature request open? I think that's the core of the problem you're dealing with.

**Comment by dneralla** [comment]
@jadekler Sure but before doing that I was wondering when does spanner send those unavailable errors, is it a capacity issue .... or any thing we can control on the spanner nodes ? A little more information on those errors would be helpful

**Comment by dneralla** [comment]
@jadekler and also I built a image editing the spanner client code to set 200ms as minBackoff and  4 secs as maxBackoff and that only amplified those unavailable errors. So not sure if that would solve our problem entirely.

**Comment by jadekler** [comment]
A 502 is hard to debug because it can be any node along the network path to Spanner sending you the 502. For example, it may not be spanner at all! It could be a proxy on your end, or a proxy in GCP, etc. etc. Without knowing your entire setup it's hard to say. Suffice it to say, these hiccups happen and we deal with them with retry mechanisms. If you'd like to dig into this more, you could file an issue at the general GCP issue tracker https://cloud.google.com/support/docs/issue-trackers.
