### ISSUE TITLE
About data persistence on Bigtable emulator

### ISSUE THREAD

**Issue by TatsuyaKITABORI** [GoogleCloudPlatform/google-cloud-go#1217]
Hello, 

I use Bigtable emulator on my local docker environment, but I cannot save data on it somehow.

Do you have any ideas to fix this issue?

**Comment by sduskis** [comment]
@TatsuyaKITABORI, can you please elaborate on the nature of the problem?  How are you connecting to the emulator?  Do you have any stacktraces?

**Comment by jba** [comment]
I think OP thinks the emulator writes to persistent storage, but it doesn't.

**Comment by bo-ri** [comment]
@enocom @sduskis @jba 
Thank you for your quick response.

Yes, emulator works well.
But I want to perpetuate data on my local HDD or SSD.

Are there options something to fix this?

**Comment by enocom** [comment]
The emulator is in-memory only and for now we don't have any plans to change that. So it's probably best to explore alternative approaches for what you're trying to accomplish.
