### ISSUE TITLE
SourceLocation field not set in logadmin.fromLogEntry()

### ISSUE THREAD

**Issue by dhduvall** [GoogleCloudPlatform/google-cloud-go#1219]
When retrieving log entries, the `logging.Entry` struct you get back always has the `SourceLocation` member set to `nil`, even if the `logpb.LogEntry` struct has it populated. This is because the `fromLogEntry()` method, when it creates the `logging.Entry` return value, fails to set that member.

When the `Trace` member was added in https://code-review.googlesource.com/11435/, it was added on both sides, but when `SourceLocation`  was added in https://code-review.googlesource.com/30091, the `logadmin` part was missing.

**Comment by enocom** [comment]
@dhduvall Thanks for catching this. Would you like to submit a fix?

**Comment by dhduvall** [comment]
Only if it's likely to speed up the integration of the fix. I think the complexity of setting up a proper testing environment probably outweighs the simplicity of the fix, and I don't need the credit. I'm happy to submit a pull request (or the Gerrit equivalent) without having done anything but my own testing, assuming that CI testing will catch any issues.

**Comment by enocom** [comment]
OK. I'll pick it up in that case and try to get it into the next release. Thanks again.

**Comment by enocom** [comment]
This was released in [v0.33.1](https://github.com/GoogleCloudPlatform/google-cloud-go/releases/tag/v0.33.1).
