### ISSUE TITLE
GetMulti's no such entity error isn't comparable with datastore.ErrNoSuchEntity

### ISSUE THREAD

**Issue by facundomedica** [GoogleCloudPlatform/google-cloud-go#1220]
## Client

Datastore

## Describe Your Environment

Local with emulator

## Expected Behavior

If I do a `GetMulti` and get an `datastore: no such entity` I want to be able to check it with `datastore.ErrNoSuchEntity`.

## Actual Behavior

The error returned by `GetMulti` isn't comparable with `datastore.ErrNoSuchEntity`.

	us := make([]*models.User, len(kids))
	err := ds.GetMulti(context.Background(), kids, us)

	if err != nil {
		if err.Error() != datastore.ErrNoSuchEntity.Error() {
			log.Println("this doesn't get printed", err.Error())
		}

		if err != datastore.ErrNoSuchEntity {
			log.Println("this gets printed", err.Error())
		}

		return nil, err
	}

If I print `err` I get `datastore: no such entity`.

(I am aware of https://github.com/GoogleCloudPlatform/google-cloud-go/issues/258 but I don't see how it helps)

**Comment by enocom** [comment]
`GetMulti` returns a `datastore.MultiError`, which is just a slice of errors. Here's how to check if one of the returned errors was a `datastore.ErrNoSuchEntity`:
 
```
err = client.GetMulti(context.Background(), ks, ds)
if err != nil {
    if merr, ok := err.(datastore.MultiError); ok {
        for _, err := range merr {
            if err == datastore.ErrNoSuchEntity {
                log.Println("got a ErrNoSuchEntity")
            }
        }
    }
}
```

**Comment by facundomedica** [comment]
Thanks for your quick response! Shouldn't this be documented?  Also, why not return `datastore.MultiError` instead of `error`?

```go
// GetMulti is a batch version of Get.
//
// dst must be a []S, []*S, []I or []P, for some struct type S, some interface
// type I, or some non-interface non-pointer type P such that P or *P
// implements PropertyLoadSaver. If an []I, each element must be a valid dst
// for Get: it must be a struct pointer or implement PropertyLoadSaver.
//
// As a special case, PropertyList is an invalid type for dst, even though a
// PropertyList is a slice of structs. It is treated as invalid to avoid being
// mistakenly passed when []PropertyList was intended.
func (c *Client) GetMulti(ctx context.Context, keys []*Key, dst interface{}) (err error) {
	ctx = trace.StartSpan(ctx, "cloud.google.com/go/datastore.GetMulti")
	defer func() { trace.EndSpan(ctx, err) }()

	return c.get(ctx, keys, dst, nil)
}
```

**Comment by enocom** [comment]
Good idea. Here's a CL to add documentation and an example for this: https://code-review.googlesource.com/c/gocloud/+/35632.

As for the return value, we don't always return a `datastore.MultiError` is the simple answer. 

The longer answer is that it's considered good form to return an `error` type instead of custom types.
