### ISSUE TITLE
Unknown import path cloud.google.com/compute/metadata when using go modules

### ISSUE THREAD

**Issue by maxfofocker** [GoogleCloudPlatform/google-cloud-go#1227]
my error log is

```bash
../../../.gvm/pkgsets/go1.11.2/global/pkg/mod/golang.org/x/oauth2@v0.0.0-20181106182150-f42d05182288/google/default.go:17:2: unknown import path "cloud.google.com/go/compute/metadata": ambiguous import: found cloud.google.com/go/compute/metadata in multiple modules:
	cloud.google.com/go v0.33.1 (~/.gvm/pkgsets/go1.11.2/global/pkg/mod/cloud.google.com/go@v0.33.1/compute/metadata)
	cloud.google.com/go/compute/metadata v0.0.0-20181114215827-b51c7c77b284 (~/.gvm/pkgsets/go1.11.2/global/pkg/mod/cloud.google.com/go/compute/metadata@v0.0.0-20181114215827-b51c7c77b284)
```

I still can not to solve this error in my project.

my go version is : go version go1.11.2 darwin/amd64

**Comment by jadekler** [comment]
It seems as though you have some out-of-date code dependencies. Could you try updating everything, including oauth2, and blowing away any references to the defunct compute/metadata module (incl in your go module cache).

Context: we removed an erroneously-added module.

**Comment by jadekler** [comment]
Closing this due to lack of reply. Give a shout if you still have followup questions!
