### ISSUE TITLE
Repeat of issue #820

### ISSUE THREAD

**Issue by scottpettyjohn** [GoogleCloudPlatform/google-cloud-go#1228]
go get -v -u cloud.google.com/go
Fetching https://cloud.google.com/go?go-get=1
https fetch failed: Get https://cloud.google.com/go?go-get=1: x509: certificate signed by unknown authority
package cloud.google.com/go: unrecognized import path "cloud.google.com/go" (https fetch: Get https://cloud.google.com/go?go-get=1: x509: certificate signed by unknown authority)

If I use the -insecure flag, I get the missing meta-tag:

go get -v -u -insecure cloud.google.com/go/...
Fetching https://cloud.google.com/go?go-get=1
https fetch failed: Get https://cloud.google.com/go?go-get=1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Fetching http://cloud.google.com/go?go-get=1
Parsing meta tags from http://cloud.google.com/go?go-get=1 (status code 401)
package cloud.google.com/go/...: unrecognized import path "cloud.google.com/go/..." (parse http://cloud.google.com/go?go-get=1: no go-import meta tags ())

**Comment by jadekler** [comment]
@scottpettyjohn Is this resolved now? I just tried and was met with success.

cc @broady @dfawley @jba who were on https://github.com/GoogleCloudPlatform/google-cloud-go/issues/820

**Comment by scottpettyjohn** [comment]
Worked for me from a laptop not on corporate vpn. I am thinking it was a
proxy issue.

**Comment by jadekler** [comment]
That definitely sounds like a proxy issue. I'll defer to the folks I pinged.

**Comment by scottpettyjohn** [comment]
Thanks and sorry for the hassle!

**Comment by jadekler** [comment]
No problem. We've investigated - as far as we can tell everything seems to be working OK on our side. It is likely to be your side (the corporate VPN sounds like the likely culprit). Closing this for now - please report back if you find additional reason to believe it might be something on our side.

**Comment by broady** [comment]
Hopefully this kind of thing becomes less common once we* have Go module proxies in place :)

* the Go community
