### ISSUE TITLE
Speech: Service Unavailable Error for `func (x *speechStreamingRecognizeClient) Recv()`

### ISSUE THREAD

**Issue by jeffreyyong** [GoogleCloudPlatform/google-cloud-go#1231]
I'm currently using the streaming API from the Google Cloud Speech To Text Golang client library. When I'm trying to Send(*StreamingRecognizeRequest), it has got no issue. But when I tried to use the Recv() (*StreamingRecognizeResponse, error) method from type Speech_StreamingRecognizeClient interface, it returns the error "rpc error: code = Unavailable desc = The service is currently unavailable."

I'm using 1) cloud.google.com/go/speech/apiv1 and 2) google.golang.org/genproto/googleapis/cloud/speech/v1

First library to initialise the speech client NewClient() and the second library for RecognitionConfig{}, StreamingRecognizeRequest{} and other streaming related structs.

I have raised the issue [here](https://github.com/google/go-genproto/issues/114#issuecomment-440434439), but was redirected to this github repo.

**Comment by jadekler** [comment]
Copying from there (I didn't mind discussing there :) ):

When you receive Unavailable, I would recommend that you retry using exponential backoff. You could use https://godoc.org/github.com/googleapis/gax-go/v2#Backoff for this, if you'd like. However, ultimately the retry logic is up to you.

In other places in the client libraries, we generally expect network hiccups and put retry logic around RPCs. So, this is not uncommon.

Closing this for now, let me know if there's any more to this you'd like to discuss though!
