### ISSUE TITLE
ProductSearch return type

### ISSUE THREAD

**Issue by dizcology** [GoogleCloudPlatform/google-cloud-go#1235]
(delete this for feature requests)

## Client

Vision

## Describe Your Environment

Mac OSX

## Expected Behavior

ImageAnnotatorClient's ProductSearch method should return something that contains [ProductSearchResults](https://github.com/google/go-genproto/blob/master/googleapis/cloud/vision/v1/image_annotator.pb.go#L1781)

## Actual Behavior

It returns [LocalizedObjectAnnotations](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/vision/apiv1/client.go#L164)

When testing on an indexed product set, the golang library's ProdutSearch method always returns an empty list; while the python library correctly returns a list of products.

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/35890
