### ISSUE TITLE
Not able to set Custom Request Header for BackendService via the go-client-api

### ISSUE THREAD

**Issue by rajdhandus** [GoogleCloudPlatform/google-cloud-go#1236]
Hi Team,

I would like to create BackendService via Goland Client API. It looks like there is no way to set Custom Request Header via the Golang API. However, we are able to set it using the Console.

## Client

Compute

## Describe Your Environment

Mac OS

## Expected Behavior

Via the Console - there is a way to set Custom Request Headers for the Backend Service..

Per this - https://cloud.google.com/load-balancing/docs/backend-service?hl=en_GB&_ga=2.187041709.-446613136.1541030031#user-defined-request-headers

It looks like API should be exposing this functionality..

## Actual Behavior

Per the Doc https://cloud.google.com/compute/docs/reference/rest/v1/backendServices/get , there is no way to set Custom Request Header..

**Comment by jadekler** [comment]
Dupe https://github.com/googleapis/google-api-go-client/issues/315 - leaving the other open and closing this.
