### ISSUE TITLE
Feature request: subscribe to firestore changes via pubsub

### ISSUE THREAD

**Issue by mickeyreiss** [GoogleCloudPlatform/google-cloud-go#1237]
We are interested in subscribing to firestore changes via pubsub.

This is currently possible with cloud functions, but it would be simpler for us to subscribe in go via pubsub.

Is this possible or something the team would expect to release in the future?

**Comment by jadekler** [comment]
@kamalaboulhosn

**Comment by kamalaboulhosn** [comment]
This question would have to be directed to the Firestore team. I'm not sure what mechanism they use to trigger Cloud Functions. They would have to publish events into Pub/Sub. Once they are doing that, then you can subscribe to get the messages the same way as you would for any Pub/Sub topic.

**Comment by jadekler** [comment]
Thanks @kamalaboulhosn! @mickeyreiss, this seems likely to be a feature request for the backend service, as opposed to a client library feature request. The canonical place to request a larger backend features like this is on the GCP issue tracker: https://cloud.google.com/support/docs/issue-trackers. Closing this for now in favour of that - give a shout if I've missed something, though!

**Comment by mickeyreiss** [comment]
Thanks for the response! I'll my luck over at the GCP issue tracker. 

(For some reason, I can't find a section pertinent to firestore.)

![image](https://user-images.githubusercontent.com/47405/49307767-09644d80-f48b-11e8-953c-abb853613b1b.png)

**Comment by jadekler** [comment]
@mickeyreiss Thanks for mentioning. Just wanted to give a quick update that I'm looking into that and trying to find who owns that page.

**Comment by mickeyreiss** [comment]
@jadekler My issue number is 120329251, and it seems that after some shuffling, my submission ended up with the Cloud Datastore group. ¯\_(ツ)_/¯

**Comment by LeonorGG** [comment]
@mickeyreiss I'm looking for this in 2021, did you find a solution?

**Comment by mickeyreiss** [comment]
@LeonorGG we are still using a cloud function that receives firestore changes and republishes them as pubsub events. We also ended up building a REST API that allows the frontend to issue explicit writes rather than relying on firestore changes.

**Comment by alxlive** [comment]
You can subscribe to changes - not quite through a pubsub, but maybe this works for you. Here's the Firestore documentation:
https://firebase.google.com/docs/firestore/query-data/listen#go

However, there's no example for Go. I found the function newWatchStreamForDocument in the Go codebase:
https://github.com/googleapis/google-cloud-go/blob/257f322e68b75765bd316ccefed5461d4df538a0/firestore/watch.go#L101

But apparently this isn't exposed in the client API? But then there's DocumentSnapshotIterator, whose Next method blocks until changes occur:
https://github.com/googleapis/google-cloud-go/blob/66046da2a4be5971ce2655dc6a5e1fadb08c3d1f/firestore/docref.go#L792

The Collection object has a Snapshots method which returns the iterator. More info in this StackOverflow answer:
https://stackoverflow.com/a/54249594
