### ISSUE TITLE
dep fails to solve datastore dependencies

### ISSUE THREAD

**Issue by ermik** [GoogleCloudPlatform/google-cloud-go#1238]
## Client

Datastore

## Describe Your Environment

MacOS

## Expected Behavior

Can install via `dep ensure -add`

## Actual Behavior

Dep fails with `Solving failure: package go.opencensus.io/exemplar does not exist within project go.opencensus.io`

***
I feel like this is related to #908

cc @sdboyer dep version 0.5.0

**Comment by jadekler** [comment]
Closing this issue, since it seems out of our hands. Give a shout if you have followup questions!
