### ISSUE TITLE
pubsub: errors do not provide enough info

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/google-cloud-go#133]
Because this library simply wraps the generated Go clients, but doesn't document that/how it does that, it can be confusing to handle errors from some methods.

For instance, if I want to call `pubsub.CreateSub` and determine whether it returned an error because the server was unreachable or because the subscription already existed, I have to attempt to cast the error to an error type defined in a totally separate package:

``` go
sub, err := pubsub.CreateSub(...)
if err != nil {
  if gerr, ok := err.(*googleapi.Error); ok && gerr.Code == http.StatusConflict {
      // Already exists, ignore.
      return
  }
  log.Fatal(err)
}
```

This is unfortunate, since it requires users to know the implementation details of gcloud to be able to handle errors reasonably. It also ties gcloud to that implementation, or else break users' error handling unexpectedly.

It would be nice if certain common error cases could return errors defined in the gcloud package.

For instance, have `pubsub.CreateSub` return a `pubsub.ErrSubExists` error, so I can just write:

``` go
sub, err := pubsub.CreateSub(...)
if err != nil && err != pubsub.ErrSubExists {
  log.Fatal(err)
}
```

Determining which errors are "common" for each particular method might take some care, but I think it would be worth it.

**Comment by ImJasonH** [comment]
Maybe it's better to have an `IsConflict(err error) bool` method, that does the work of casting it to a `googleapi.Error` and checking the `Code`. That would also allow for future implementations not based on the generated client, without changing the API surface.

If such a method were to exist, it could be useful across all subpackages, e.g., `storage.CreateBucket` or future methods to create other conflictable resources. So maybe it belongs in the parent `google.golang.org/cloud` package.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
