### ISSUE TITLE
Cloud monitoring (custom metrics)

### ISSUE THREAD

**Issue by gpopovic** [GoogleCloudPlatform/google-cloud-go#134]
Any plans for cloud monitoring api?

**Comment by fredr** [comment]
+1
I might be able to help out with this, if help is wanted

**Comment by nightlyone** [comment]
@fredr Point-problem seems fixed, because all relevant fields are now pointers.

**Comment by fredr** [comment]
Sweet! thanks for the update @nightlyone!

I did build a small package for some basic usage of the cloud monitor api, until there is an official package: https://github.com/soundtrackyourbrand/cloudmon

**Comment by jba** [comment]
https://godoc.org/cloud.google.com/go/monitoring/apiv3 is the right package for this. We don't have plans for a handwritten client at the moment.
