### ISSUE TITLE
Support metadata change notification using channels.

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/google-cloud-go#136]
See https://cloud.google.com/compute/docs/metadata#waitforchange

TL;DR: The GCE metadata server supports hanging `GET` requests for metadata changes, either for a single key, or recursively for changes to any metadata in a directory.

It would be great to expose this to Go clients through a channel.

**Comment by adg** [comment]
Nice idea.

**Comment by jba** [comment]
We're not going to have a handwritten compute client. Sorry.
