### ISSUE TITLE
storage: compose objects API

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/google-cloud-go#146]
https://cloud.google.com/storage/docs/json_api/v1/objects/compose

This method lets you compose an object in GCS from other existing objects in GCS. The generated client can be called like so:

```
obj, err := svc.Objects.Compose("bucket", "destObj", &storage.ComposeRequest{
  SourceObjects: []*storage.ComposeRequestSourceObjects{
    {Name: "srcObj1"},
    {Name: "srcObj2"},
    {Name: "srcObj3"},
    //... and so on...
  },
}).Do()
// destObj's contents are now the source objects' contents, concatenated.
```

Source objects must be in the same bucket as each other, and the destination object. The API allows the caller to specify a particular generation of source objects, and to require that the destination's object is of a given generation. It also allows the caller to specify a pre-defined ACL for the destination object.

The destination object can be composed of itself and other objects, which allows for appending to an existing object.

An simple idiomatic Go API for this might look like:

```
func ComposeObject(ctx context.Context, bucket, destObject string, srcObjects... string) (*Object, error)
```

**Comment by derekperkins** [comment]
I'd really love to be able to use this with the storage package.

**Comment by okdave** [comment]
At first glance this looks straightforward. I want to be able to make sure that it can support the generation-matching precondition, or at least that the API will extend to that use case. So it might be worth working out a good solution to #188 first.
