### ISSUE TITLE
bigtable doesn't register with Cloud Trace

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/google-cloud-go#150]
It would be great to see bigtable calls listed as RPCs in Cloud Trace.

**Comment by raliste** [comment]
+1

Wouldn't be as simple as passing the `X-Cloud-Trace-Context` to internal requests if the ids are present within a context?

**Comment by dsymonds** [comment]
I suspect 90% of this will just be hooking gRPC and Cloud Trace together, but once that is done we can see whether it makes sense for the bigtable package to add its own specific annotations above that.

**Comment by garye** [comment]
Tracing can now be done using a technique described here:
https://cloudplatform.googleblog.com/2017/04/distributed-tracing-for-Go.html
