### ISSUE TITLE
storage.Writer should allow object to be cancelled

### ISSUE THREAD

**Issue by okdave** [GoogleCloudPlatform/google-cloud-go#175]
Per golang/go#12671, a developer should be able to cancel an object partway through writing it if something goes wrong.

Possible APIs include adding an `Abort` or `Cancel` method, or respecting the done channel on the provided `context.Context`.

@broady Do you want to look at this as part of your refactoring work? Or happy for me to look right away?

**Comment by broady** [comment]
context.Done sounds perfect for that.

you can certainly look right away, don't think the refactoring affects this very much.

I think an explicit Abort/Cancel method would be nice, too.

**Comment by okdave** [comment]
@bradfitz any suggestions on how to handle this for 1.4 (if at all)? It seems if I use `Transport.CancelRequest` there's a race which might trigger if the request isn't inflight yet. How does the net/http library handle the request's `Body` returning an error?

**Comment by bradfitz** [comment]
For 1.4, just use CancelRequest. You could delay the CancelRequest call for N milliseconds if you want. I wouldn't care much about making 1.4 perfect.

> How does the net/http library handle the request's Body returning an error?

Yeah, (if I interpret your question correctly), that's a good idea. Create an io.Reader that returns an error if the context is done, else delegates to the underlying reader. The http client when writing the request will then see the error and close the connection. Perfect-o.

**Comment by bradfitz** [comment]
For the log here, I added a CloseWithError because I urgently needed it for the Go builders:
https://code-review.googlesource.com/#/c/3480/

I'm pretty sure we want to keep it, but I'm open to changing it if anybody has better API ideas.

I still think we should also do the context thing, but I'm open to not doing it if people think CloseWithError is sufficient.

**Comment by okdave** [comment]
I'm pursuing the context thing more generally anyway for the generated APIs, so I think storage will get that for free regardless (I'll write an integration test once it's all wired up to be sure).

I like the `CloseWithError` but I wonder if something like `Cancelled` (which takes no error) might be cleaner. What does the error passed into that func achieve right now – can it provide a useful signal?

**Comment by okdave** [comment]
@bradfitz do you have a strong opinion on `Cancel` vs. `CloseWithError`?

**Comment by bradfitz** [comment]
If the question is `Cancel(error)` vs `CloseWithError(error)` then I'd prefer `CloseWithError` for consistency with the standard library.

If the question is `Cancel()` vs `CloseWithError(error)`, then I don't care too much either way.

**Comment by jba** [comment]
The context is now plumbed through to `ctxhttp.Do`, and the canceled error will be passed to `CloseWithError`, so I believe this is done.

**Comment by nhooyr** [comment]
@jba The cancelled error is not passed to `CloseWithError`, that function always returns a nil error.

The docs don't specify what `CloseWithError`'s error argument is used for so it's not clear whether its different from using a context. Shouldn't `CloseWithError` be deprecated or removed if using a context accomplishes the same thing?
