### ISSUE TITLE
storage: bad object names (and other values) return confusing errors

### ISSUE THREAD

**Issue by okdave** [GoogleCloudPlatform/google-cloud-go#196]
For example, an empty object name fails `Writer.Close` with `googleapi: Error 400: Required, required`.
An object name containing a new line fails with `googleapi: Error 400: Invalid Value, invalid`

These errors are really confusing and do not point to which part of the request was malformed.

Found while fixing #111

**Comment by jba** [comment]
Is this a problem with the underlying service or with our client? If the former, we should file a bug against GCS.

**Comment by okdave** [comment]
Our client: we're not doing a good job of converting the error from google.golang.org/api into something more digestible.

**Comment by jba** [comment]
As of this writing, a newline in an object name fails with `Error 400: Disallowed unicode characters present in object name`, which seems adequate.

A missing object name still fails with the original error, but GCS returns no additional information.

In both cases, we capture all the information we can, so this is not a client issue.
