### ISSUE TITLE
logging: Is there a way to capture HTTP request data?

### ISSUE THREAD

**Issue by fd** [GoogleCloudPlatform/google-cloud-go#203]
Is there a way to capture HTTP request data and have it show up like the appengine request log?

**Comment by bradfitz** [comment]
Read http.Request.Body from your Handler and log it?

**Comment by derekperkins** [comment]
@fd: There's no way to group the way that App Engine does. IMO, that's one of the most valuable features of GAE and the one I'd like to see duplicated with this package.

**Comment by jba** [comment]
Stackdriver Logging v2 allows you to associate an HTTP request with a log entry. We'll have a Go client for logging v2 soon.

**Comment by adams-sarah** [comment]
I think this is done (logging v2 client is in). @jba plz reopen if I'm wrong.
