### ISSUE TITLE
storage: writes fail without error

### ISSUE THREAD

**Issue by stephenplaza** [GoogleCloudPlatform/google-cloud-go#217]
In my application, I am writing thousands of disjoint objects about 32K in size to one bucket per second over several machines.  As one might expect, occasionally a request to the bucket fails requiring a restart.  However, I noticed that my bucket was missing the data for a handful of objects (maybe 1 per 100,000).  My code was not restarting the storage write request since the API was not always returning errors.  Here is a simplified code snippet:
                                                        

                obj := obj_handle.NewWriter(ctx)
                // write data to buffer -- err is alway nil, bytesbwriten == len(value)                                                            
                byteswriten, err := obj.Write(value)
                
                // close will flush buffer -- err is always nil                                                       
                err = obj.Close()

                // see if read value is same as written
                obj, _ := obj_handle.NewReader(db.ctx)
                value2, _ := ioutil.ReadAll(obj)

               // value2 != value (1/100,000 objects approximately) 

In my actual code, both reads and writes will retry on failure.  Also, the error was originally seen trying to fetch storage data several minutes after writing.

**Comment by okdave** [comment]
@stephenplaza if you look at those failed objects in the [developers console](https://console.developers.google.com) are they correct or also wrong? Is the value written completely missing, or truncated (or wrong in some other way)?

**Comment by stephenplaza** [comment]
I ran the test again.  The file exists but is empty.  I see this in my program debug and afterward when looking at the console.

(Right now, I am just doing the inefficient read after write to detect errors.  A re-write of the object (with exponential backup) produces the correct output.  With this conservative approach, I can still load over 10 million objects in under 2 hours and read >1 million objects per minute with this efficient library.)

Is there any issue with concurrency and this package that could cause strange behavior?  The objects written should be disjoint across machines and Go routines, but maybe an error here could cause a strange problem.  Another datapoint is that I am using Go1.5.  Go seems to make a lot of changes to garbage collection and my program often needs to force garbage collection.  Not sure if something strange is going on there.  I mention it because I notice that creating a lot of Writers (a few thousand within 1 minute) surprisingly really blows up memory usage (eventually the memory is reclaimed).

**Comment by okdave** [comment]
There shouldn't be any concurrency bugs in the library that affect correctness (we've designed it to be safe to upload multiple objects at once, and there are no known data races).

I'm really surprised that creating a lot of Writers blows up memory usage. Yes, each Writer will consume memory while it is open – they all have buffering built in for performance and automatic retries. However, as soon as a Writer is closed (ie. after Close returns) it should drop that memory. When you're creating the few thousand within a minute, how many are concurrently open?

**Comment by stephenplaza** [comment]
I limit my number of concurrent connections to 100.  Usually I hope for 1-2K requests per second per VM running the application.

**Comment by okdave** [comment]
I'd expect each Writer to be consuming roughly 32K: it will slurp the whole object into memory before sending it, up to 8MB (`DefaultChunkSize` in [the googleapi package][1]). That's in addition to any overhead from the HTTP package and below.

Do you have an example bucket/object ID you can share (off list is fine) so I can file a bug for the backend team to investigate?

[1]: https://godoc.org/google.golang.org/api/googleapi#pkg-constants

**Comment by stephenplaza** [comment]
I reran my experiment and loaded data in the bucket: "storagewritebug".  The following object is size 0 (but it shouldn't be 0):

AQAAAGQXAYAAAACAAACOgAAAdQAAAAEAAAAAAw==

With regards to the memory issue, I notice the memory blow-up when NewWriter is called followed by Close even without writing data.

**Comment by okdave** [comment]
Sorry for the delay in getting back to you. We did find an issue which was causing some small objects to fail to write correctly if there was an error (for example, a dropped network connection or server error) on the first attempt at uploading it. That has been patched, and we'll be adding extra tests to make sure it doesn't come back.

Can you let me know if you're still seeing the issue? It should be fixed from what we can see.

**Comment by stephenplaza** [comment]
I was away for a bit but will try to test this shortly.  To clarify, if there is a write failure, should an error message be returned to the caller or will the code retry the write?

**Comment by jba** [comment]
@stephenplaza We retry writes.

Are you still experiencing this issue?

**Comment by jba** [comment]
Closing because there have been no updates from the user.
