### ISSUE TITLE
bigtable: provide a README for the search example

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/google-cloud-go#252]
A Cloud Bigtable engineer suggested that the Bigtable search example could use a README. Ideally the README would cover all of the following information:
- Prerequisites (e.g., creating the table "shakespearetemplate")
- Command-line options
- What port the server is listening on

**Comment by jba** [comment]
What "search example" is this issue referring to? Is it in this repo?

**Comment by hegemonic** [comment]
Looks like the examples were [removed from this repo](https://code-review.googlesource.com/#/c/gocloud/+/11656/) a while back. I'll re-file this issue in the [new repo](https://github.com/GoogleCloudPlatform/golang-samples).
