### ISSUE TITLE
datastore: Fix multiple properties documentation

### ISSUE THREAD

**Issue by ernestoalejo** [GoogleCloudPlatform/google-cloud-go#253]
After [this commit](https://code.googlesource.com/gocloud/+/8e172451ca67fecbe20890ed512199f2a8b71af2) properties can contain multiple values in the same place. Change documentation to reflect it accordingly, because it still says:

> An entity can have multiple Properties with the same name, provided that p.Multiple is true on all of that entity's Properties with that name.

Also if `google.golang.org/appengine/datastore` won't be updated too, it would be highly appreciated to include a comment or code example to transform between the structures in these two packages. We are using both right now to implement data transfer tools.

**Comment by okdave** [comment]
Thanks @ernestoalejo I'll try to get to both those requests tomorrow

**Comment by ernestoalejo** [comment]
Thinking about the transform between the two libraries, it's something that doesn't fit the documentation, but probably someone wants to do it and now it needs reflect magic that wasn't needed before:

```go
package foo

import (
  "reflect"

  localds "google.golang.org/appengine/datastore"
  remoteds "google.golang.org/cloud/datastore"
)

func download() {
  remoteModels := XX
  remoteKeys := XX

  for i, remoteKey := range remoteKeys {
    localKey := convertKey(ctx, remoteKeys[i])

    localModel := []localds.Property{}
    for j, prop := range remoteModels[i] {
      if reflect.TypeOf(prop.Value).Kind() == reflect.Slice {
        v := reflect.ValueOf(prop.Value)
        for i := 0; i < v.Len(); i++ {
          localModel = append(localModel, localds.Property{
            Name:     prop.Name,
            Value:    v.Index(i).Interface(),
            NoIndex:  prop.NoIndex,
            Multiple: true,
          })
        }
      } else {
        localModel = append(localModel, localds.Property{
          Name:    prop.Name,
          Value:   prop.Value,
          NoIndex: prop.NoIndex,
        })
      }
    }

    ps := localds.PropertyList(localModel)
    if _, err := localds.Put(ctx, localKey, &ps); err != nil {
      return err
    }
  }
}
```

It seems it's an example rather than documentation. Or perhaps this issue is enough for those searching how to copy entities and does not need to be included in the repo.

**Comment by okdave** [comment]
I think the transformation between the two libraries is a pretty small corner case: most users won't need to worry about converting between the two types of `Property` since the normal struct representation is not changed.

FWIW, you don't need to use the reflect package to achieve that transformation above which simplifies it a lot:

```go
    var localModel localds.PropertyList
    for j, prop := range remoteModels[i] {
      if sl, ok := prop.Value.([]interface{}); ok {    
        for _, val := range sl {
          localModel = append(localModel, localds.Property{
            Name:     prop.Name,
            Value:    val,
            NoIndex:  prop.NoIndex,
            Multiple: true,
          })
        }
        continue
      }
      localModel = append(localModel, localds.Property{
        Name:    prop.Name,
        Value:   prop.Value,
        NoIndex: prop.NoIndex,
      })
    }
```

And actually, you need to be careful not to iterate over values of type `[]byte` when doing the conversion so checking that the kind is `reflect.Slice` is insufficient.

**Comment by ernestoalejo** [comment]
I knew there was something wrong in the code; thank you

**Comment by okdave** [comment]
I have 2 changes out now to improve the docs, but I'd still like to add an example too to do the translation like you have above (and in the other direction too).

**Comment by adams-sarah** [comment]
`p.Multiple` no longer exists. Closing issue.

**Comment by adams-sarah** [comment]
@JustinBeckwith please stop assigning things to me. I don't work at Google anymore. I don't work on this project anymore.

**Comment by JustinBeckwith** [comment]
Apologies, robot run amok 🤖

**Comment by adams-sarah** [comment]
Please kill the bot ☠️ . I'm still being assigned issues. It is driving me crazy.
