### ISSUE TITLE
datastore.GetMulti fails with internal error if there are duplicate keys

### ISSUE THREAD

**Issue by blixt** [GoogleCloudPlatform/google-cloud-go#254]
I have a case where I fetch a pair of users which in some cases may be the same user. Here's the code:

``` go
from, to := "bob", "bob"
keys := []*datastore.Key{
    datastore.NewKey(ctx, "Identity", from, 0, nil),
    datastore.NewKey(ctx, "Identity", to, 0, nil),
}
identities := make([]*Identity, 2)
err := store.GetMulti(ctx, keys, identities)
```

At this point, `err` will be:

```
datastore: internal error: server returned the wrong number of entities
```

I would expect this to put the same (or a copy of) `Identity` twice in the slice since there was a result. Currently I have to dedupe in my code instead.

**Comment by blixt** [comment]
This is the workaround I landed on, let me know if there's a better way please. :)

```go
func getIdentityPair(a, b string) (aa, bb *Identity, err error) {
	keys := []*datastore.Key{
		datastore.NewKey(ctx, "Identity", a, 0, nil),
		datastore.NewKey(ctx, "Identity", b, 0, nil),
	}
	identities := make([]*Identity, 2)
	if a == b {
		// This avoids an internal error in the datastore client.
		keys, identities = keys[:1], identities[:1]
	}
	err = store.GetMulti(ctx, keys, identities)
	if err != nil {
		return
	}
	aa = identities[0]
	if len(identities) == 2 {
		bb = identities[1]
	} else {
		bb = aa
	}
	return
}
```

**Comment by okdave** [comment]
Thanks for the report. I don't think the datastore code covers the case of repeated keys at all. We'll need to do extra work to make that case work. I think your workaround is the best way forward until we can fix it properly.

**Comment by nightlyone** [comment]
I did hit a similar bug on DeleteMulti with datastore returning duplicate keys on iteration and then being unable to handle them.

Is this related? Could that be fixed on the server side instead?
