### ISSUE TITLE
ErrNoSuchEntity is difficult to manage for GetMulti

### ISSUE THREAD

**Issue by blixt** [GoogleCloudPlatform/google-cloud-go#258]
When doing a `GetMulti` request, it's possible to get back a `MultiError` which doesn't compare with `ErrNoSuchEntity`. So now I have the choice of either ignoring all errors because I don't want to exit in case some of the entities exist – or I have to do a deep inspection of the error. Am I missing an easy way to not have to do either of those two?

It's unclear to me why it's an error in the first place – a `nil` value usually means something is missing, and a non-`nil` value means it was found. Is there a reason for that?

**Comment by okdave** [comment]
No, unfortunately you do have to loop to compare them (it's the only way you could tell, for example, which entities were missing and which failed to load for some other reason).

We have to use the error return to indicate a missing entity since `GetMulti` doesn't directly return the entity being retrieved.

**Comment by okdave** [comment]
@blixt Do you have a concrete suggestion for improving this? We've used this API in app engine for a while now and haven't found something more approachable yet.

**Comment by blixt** [comment]
My expectation was to get `nil` (or whatever empty value the input slice would have) in the result list and only other types of errors in the error result. Basically, a missing value is not an error – it's just an empty value. This is how I'm used to Go errors, that they are returned in cases where other languages would throw an exception (and `NoSuchEntity` would not be an exception, just normal operation). For example, the Python Datastore API only returns `None` rather than raising an exception if a key does not exist.

Obviously this would be an API change so it's probably not a realistic suggestion. The only non-breaking change I could suggest is that `MultiError` has a value `PartialResult` which indicates that the result list should be inspected because it contains a partial result (e.g., the error was not fatal / there were a few entities returned).

**Comment by jba** [comment]
I don't think we're going to make progress on this.
