### ISSUE TITLE
datastore: supporting multiple types of composite filters

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/google-cloud-go#26]
Right now Datastore doesn't natively support OR filters, however it is a feature we'd like to support. When switching from GAE Datastore to Cloud Datastore filters were explicitly changed from being represented as a list to a more hierarchical model to support this. There should be a plan in place for how to expose this, since now filters are assumed to be AND'ed together.

**Comment by jba** [comment]
Closing this, as we're now focusing our efforts on Firestore.

**Comment by cnbuff410** [comment]
Does it mean Firestore is preferred over Datastore in the future?

**Comment by jba** [comment]
I would say that if you're writing new code, you'll be better off using Firestore. I wouldn't migrate existing code.

**Comment by cnbuff410** [comment]
Ya I wasn't thinking about migration for now, I was thinking if the effort for datastore library development is decreasing gradually, it's a clear sign that we might need to consider the migration in the future.
