### ISSUE TITLE
storage: Object.NewReader uses the XML API

### ISSUE THREAD

**Issue by FiloSottile** [GoogleCloudPlatform/google-cloud-go#260]
It seems to be the only endpoint to do so, is that intentional?

Shouldn't it use https://cloud.google.com/storage/docs/json_api/v1/objects/get with `alt=media` (to save a roundtrip)?

Or maybe we can't specify a `Range` with `alt=media`?

**Comment by okdave** [comment]
I think it's just historical, but I don't think it makes any difference either way. Why do you say that using the `json_api` URL would save a roundtrip? `NewReader` only makes a single HTTP request.

**Comment by FiloSottile** [comment]
Sorry, didn't explain myself well, I was wondering if the JSON API was a no-go because it would have a round trip more for Range requests, not the other way around.

Only reason I noticed is that I added googleapi.Error support to NewReader (see open CL) and the JSON error is obviously not deserializing.

**Comment by adams-sarah** [comment]
Closing for now due to inactivity. Please reopen if necessary.
