### ISSUE TITLE
bigtable: Implement more row filters for the in memory testing implementation

### ISSUE THREAD

**Issue by rgruener** [GoogleCloudPlatform/google-cloud-go#261]
The in [memory implementation of Bigtable](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/bigtable/bttest/inmem.go) used for testing only implements the regex filters while performing reads.

The most notable filters missing in my opinion are the [ColumnRange](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-protos/src/main/proto/google/bigtable/v2/data.proto#L119) and the [TimestampRange](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-protos/src/main/proto/google/bigtable/v2/data.proto#L145).

**Comment by rgruener** [comment]
@garye

**Comment by garye** [comment]
These two filters are now implemented.

**Comment by ianrose14** [comment]
Is there a canonical list somewhere of the Filters that the devbt instance does and/or does not implement?

**Comment by garye** [comment]
The docs for the gcloud emulator has a list:
https://cloud.google.com/bigtable/docs/emulator

gcloud lags this repository by a week or a two, so doesn't include the recent row_key_regex and timestamp_filter additions. strip_value_transformer is up next.
