### ISSUE TITLE
Add a cloud.WithServiceAccountJSON option

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/google-cloud-go#262]
This would call google.JWTConfigFromJSON, apply the appropriate scopes to a TokenSource.

**Comment by broady** [comment]
Even better, take a file path

cc @rakyll

**Comment by rakyll** [comment]
The main argument behind []byte was not allow people not to depend on the actual file and let them pass these credentials in whatever way they would prefer. They may store them in a secure key-value store, etc.

The x/oauth2/google package is more of a generic one, hence needed to support such cases. In the scope of cloud, we have TokenSource option which is already pretty generic for every use case.

So, +1 to the filename rather than the []byte arg.

**Comment by rakyll** [comment]
I can get this done, if no one else is working on it.

**Comment by jba** [comment]
I just started, but you're better equipped.

**Comment by jba** [comment]
Questions: Is JSON the right name, or JWT? Is it necessarily a service account, or could it be some other kind of principal?

**Comment by rakyll** [comment]
JWT is the OAuth 2.0 protocol name, service account is the Google specific term. `WithServiceAccount(filename string)` sounds the best to me.

**Comment by broady** [comment]
yes yes yes yes

**Comment by rakyll** [comment]
Ok, this is uglier than what I was thinking.

JWTConfigFromJSON doesn't allow the setting of the scopes lazily. JWTConfigFromJSON.TokenSource requires a context.

And we need to keep the state of the last error. Yuck.

```
type withServiceAccount struct {
	ctx      context.Context
	filename string
}

func (w withServiceAccount) Apply(o *internal.DialSettings) {
	key, err := ioutil.ReadFile(w.filename)
	if err != nil {
		o.Err = err
		return
	}
	cfg, err := google.JWTConfigFromJSON(key) // scopes?
	if err != nil {
		o.Err = err
		return
	}
	o.TokenSource = cfg.TokenSource(w.ctx)
}
```

The option should look like `WithServiceAccount(ctx context.Context, filename string, scope ...string)`. Hence I am saying no to this feature :(

**Comment by jba** [comment]
No, just set a new field in Settings and let the dial function figure it all out.

**Comment by rakyll** [comment]
Oh, ok. I can use the filename lazily.

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/#/c/7371/.

**Comment by jba** [comment]
Fixed by https://code.googlesource.com/google-api-go-client/+/63cb68f1e3834e44683ca062ddf06cb9a889380a.
