### ISSUE TITLE
If multiple RowFilters are passed to ReadRow(s) in a variadic slice of bigtable.ReadOption, only one is applied.

### ISSUE THREAD

**Issue by rlmcpherson** [GoogleCloudPlatform/google-cloud-go#263]
If multiple filters are passed as ReadOptions to ReadRows, only one is applied since there is only one Filter on the request (`type ReadRowsRequest`) For instance:

```
tbl.ReadRow(ctx, row-key, bigtable.RowFilter(bigtable.LatestNFilter(1)), bigtable.RowFilter(bigtable.FamilyFilter("family")))
```

Instead, the correct approach is to use `ChainFilter` or `InterleaveFilter` This is not obvious behavior and I could not find any documentation in the api docs. This should be documented in the api and possibly be detected and return an error as well.

**Comment by dsymonds** [comment]
It is indeed incorrect usage, though I'd be nervous about special-casing particular options as not being accepted in duplicate. A documentation fix is probably the right move here.

**Comment by junghoahnsc** [comment]
I think the [document](https://cloud.google.com/bigtable/docs/go/reference#ReadOption) should mention this explicitly until this bug is fixed.
