### ISSUE TITLE
Clarify relationship with google-api-go-client is unclear.

### ISSUE THREAD

**Issue by timburks** [GoogleCloudPlatform/google-cloud-go#266]
Neither the README for this project nor the README for google-api-go-client explains the relationship between these two projects. As a result, newcomers experience them as two uncoordinated alternatives and because one is labeled "automatically generated" and the other contains prominent disclaimers about possible changes, neither appears to be a usable solution. 

The simplest way to address this would be to put more user-friendly information in the README. I suggest adding something like the following to the README of this project.

---

This repository contains handwritten Go packages for calling selected Google APIs. It builds on the [google-api-go-client](https://github.com/google/google-api-go-client) project, which contains lower-level, automatically-generated client libraries. Because it is automatically-generated, [google-api-go-client](https://github.com/google/google-api-go-client) supports a large set of Google APIs, so if the API that interests you isn't supported here, please look there for a possible solution.

**Comment by jba** [comment]
The story is about to get more complicated (and interesting). These handwritten packages are going to migrate to live on top of clients generated from the  [Google API Code Generator](http://github.com/googleapis/toolkit), which use gRPC. We're still figuring out where those generated clients will live. When the dust settles, I'll modify the README along the lines you suggest.

**Comment by bootstraponline** [comment]
> We're still figuring out where those generated clients will live.

Has there been any update on figuring out where the clients generated with [googleapis/toolkit](https://github.com/googleapis/toolkit) will live?

**Comment by jba** [comment]
I'm afraid not.

**Comment by jba** [comment]
We do have some text in the google-api-go-client README that points to this repo. I don't think we need to add a pointer in the other direction.
