### ISSUE TITLE
Instrumentation for bigtable client

### ISSUE THREAD

**Issue by rlmcpherson** [GoogleCloudPlatform/google-cloud-go#270]
I see there is already an issue for bigtable instrumentation for google cloud trace in https://github.com/GoogleCloudPlatform/gcloud-golang/issues/150 but it would also be great to have a general way to instrument the client for request metrics. Currently, I am doing this by adding instrumentation code around each call to the client but it's brittle and requires several lines of metrics-related code everywhere a bigtable request is sent. If there was a way to do this with grpc client options that could also work but I'm not aware of any way to do that currently. 

I know bigtable already publishes trace information to /debug/requests using the `net/trace` package but not everyone uses that and there are no tools available to consume and aggregate trace data.

**Comment by garye** [comment]
Now that gRPC has client-side interceptors, you can implement some basic metrics using something like this as an example:
https://github.com/grpc-ecosystem/go-grpc-prometheus

**Comment by garye** [comment]
Also see: https://cloudplatform.googleblog.com/2017/04/distributed-tracing-for-Go.html
