### ISSUE TITLE
Add support for the App Engine Admin API

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-go#274]
We have an Admin API (service management) for App Engine here:
https://cloud.google.com/appengine/docs/admin-api/reference/rest/

It's a pretty basic CRUD / REST style API, but it would be great to have wrappers that make it easier to use.

**Comment by dsymonds** [comment]
Like https://godoc.org/google.golang.org/api/appengine/v1beta5?

**Comment by broady** [comment]
We're focused on hand-crafting libraries for application development, not the service/ops layer (e.g. compute, container, appengine APIs).

@jgeewax should be able to elaborate.

**Comment by jba** [comment]
Closed due to lack of activity.
