### ISSUE TITLE
datastore: Cannot query from App Engine standard (regression)

### ISSUE THREAD

**Issue by ernestoalejo** [GoogleCloudPlatform/google-cloud-go#284]
After the commit 9975503b2391be7809757551d92e9124232eb41f the following code started to fail in App Engine standard. It is working correctly if I use the previous commit ef96b79660680a001725ce5dc5f5bcce24676409.

The code reaches "connected, querying", but it never returns from the query, even if I use a context with timeout.

``` go
package front

import (
  "net/http"

  "github.com/juju/errors"
  "golang.org/x/net/context"
  "golang.org/x/oauth2/google"
  "google.golang.org/appengine"
  "google.golang.org/appengine/log"
  "google.golang.org/cloud"
  "google.golang.org/cloud/datastore"
)

const (
  serviceAccountKey = `[edited]`
)

func init() {
  http.HandleFunc("/foo", fooHandler)
}

func fooHandler(w http.ResponseWriter, r *http.Request) {
  ctx := appengine.NewContext(r)
  if err := run(ctx, w, r); err != nil {
    log.Errorf(ctx, "FAILED: %s", err)
  }
}

func run(ctx context.Context, w http.ResponseWriter, r *http.Request) error {
  conf, err := google.JWTConfigFromJSON([]byte(serviceAccountKey), datastore.ScopeDatastore)
  if err != nil {
    return errors.Trace(err)
  }

  datastoreClient, err := datastore.NewClient(ctx, appengine.AppID(ctx), cloud.WithTokenSource(conf.TokenSource(ctx)))
  if err != nil {
    return errors.Trace(err)
  }

  log.Debugf(ctx, "connected, querying")
  q := datastore.NewQuery("MyEntityEdited").Filter("Project =", "ValueEdited")
  models := []datastore.PropertyList{}
  keys, err := datastoreClient.GetAll(ctx, q, &models)
  if err != nil {
    return errors.Trace(err)
  }

  log.Debugf(ctx, "keys: %d, models: %d", len(keys), len(models))

  return nil
}
```

**Comment by okdave** [comment]
@ernestoalejo sorry I haven't responded to this before, I hadn't seen it until now. Are you still seeing this issue?

The code as you have it shouldn't have worked at all on App Engine before the commit you listed: on GAE standard environment you can't use the `net.Dial` functions at all directly, and so the attempted connection via grpc should always fail.

Commit 9975503 correctly defaults to using the`socket` package to make the appropriate connection. Unfortunately, if you don't have billing enabled on your app then the connection fails in a way that makes grpc attempt to re-dial forever (related to grpc/grpc-go#668).

Note that  prior to August 2015 (commit 9bea863) this datastore package used a HTTP-based API which worked via a more traditional HTTP API, and so didn't have this requirement around the sockets API and billing.

Please re-open if you're still seeing the issue.

**Comment by ernestoalejo** [comment]
@okdave Sorry I should have been more explicit. It fails inside the AppEngine SDK, version 1.9.40 (latest at the moment). It is a dev tool and I didn't tried it at production.

This does work:
```go
  dial := grpc.WithDialer(func(addr string, timeout time.Duration) (net.Conn, error) {
   return net.DialTimeout("tcp", addr, timeout)
  })
  client, err := datastore.NewClient(ctx, appengine.AppID(ctx), option.WithTokenSource(conf.TokenSource(ctx)), option.WithGRPCDialOption(dial))
```

This does not work:
```go
  client, err := datastore.NewClient(ctx, appengine.AppID(ctx), option.WithTokenSource(conf.TokenSource(ctx)))
```

The console repeats this error multiple times well after the context timeout triggers:
```
2016/09/14 14:59:47 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Call error 11: Deadline exceeded (timeout)"; Reconnecting to {"datastore.googleapis.com:443" <nil>}
```

PD: I can't reopen the issue myself.

**Comment by okdave** [comment]
Thanks for the info. Does this code form part of an AE standard app? Are you starting it with `dev_appserver` or `goapp serve`?

@broady maybe the socket API wrapping isn't handling dev properly.

**Comment by ernestoalejo** [comment]
`dev_appserver`, I'm changing the `admin_host` and `datastore_path` flags to accommodate the Docker development container and `goapp` does not have them yet.

**Comment by adams-sarah** [comment]
I believe this has been fixed. Please reopen if I'm wrong.
