### ISSUE TITLE
bigtable: no way to view current GC policy

### ISSUE THREAD

**Issue by ianrose14** [GoogleCloudPlatform/google-cloud-go#290]
There is currently no way via the bigtable API to view what GC policy is currently set on a given column family.  Seems like this would be nice to add to the `TableInfo` struct.  I don't have a strong opinion what form this data should come in - for my current purposes just a string would be fine as I only envision using it for human consumption.

Also would be great to add this to the `cbt` tool.

**Comment by garye** [comment]
This is fixed by dac7754.

I'll close the issue when it has been released through gcloud.
