### ISSUE TITLE
trace: Simplify API

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/google-cloud-go#298]
I've been investigating the new trace package with @broady and the current API seems overly cumbersome. Given that the trace details are being stored in context, needing to keep track of spans in user-land + managing child inheritance seems unnecessary. Using syntax like this seems much easier and less likely to be mismanaged.

```
package main

func handler(w http.ResponseWriter, r *http.Request) {
    ctx := trace.Start(context.Background())
    trace.SetLabel(ctx, "foo", "bar")
    defer trace.Finish(ctx)


    ctx2 := trace.Start(ctx)
    _, err := otherpackage.RPC(ctx2)
    // ...
    trace.Finish(ctx2)

    ctx3 := trace.StartWithRequest(ctx, req)
    resp, err := otherpackage.RPC(ctx3)
    // ...
    trace.FinishWithResponse(ctx3, resp)
}
```

**Comment by derekperkins** [comment]
It also seems that similar to logging, trace should not respect cancelation deadlines, since those are likely the scenarios where you need trace the most. The package could/should add another label to the effect of `go:context/timeout` or `go:context/canceled`

**Comment by jba** [comment]
@jcd2 @okdave @mcgreevy  Should we do this?

**Comment by okdave** [comment]
This does seem much cleaner. @jcd2 wrote the original library, so I'll chat to him when he's back.

**Comment by tmc** [comment]
One thing to be considered in event of an api change is the use case of reconstructing traces across rpc boundaries (such as via grpc metadata). AFAICT the closest you can currently get is constructing a fake *http.Request with the tracing header populated but there's no way to access the span id.

**Comment by rakyll** [comment]
I would say that this fits under https://github.com/GoogleCloudPlatform/google-cloud-go/issues/412. We have a more comprehensive plan (forked from the initial discussion at https://groups.google.com/forum/#!topic/go-kit/AHgWcvCBat0) and this package is likely to follow the output of that work.

**Comment by jba** [comment]
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).
