### ISSUE TITLE
trace: integration with google.golang.org/appengine

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/google-cloud-go#299]
@jcd2 - @adamtanner mentioned that he would be willing to integrate this with google.golang.org/appengine. Hooking it into my app, I had a couple questions and will likely encounter more:
1. Will `appengine.WithContext` already include the base trace/span?
2. Do all requests have `X-Cloud-Trace-Context` set or only requests that are already being sampled? If not, how do we set a new context and tie it back to the request ID so it is usable in the interface?

**Comment by broady** [comment]
It looks like the traces are already being passed via the `google.golang.org/appengine` packages:
https://github.com/golang/appengine/blob/267c27e7492265b84fc6719503b14a1e17975d79/internal/api.go#L388-L392

**Comment by derekperkins** [comment]
> Applications should be able to decide which requests to trace.

Agreed. My high-volume routes might only need < 1% sampling, but there are other low-volume routes that I would always like to have full traces for.

**Comment by jba** [comment]
@rakyll Is there anything to do here?

**Comment by rakyll** [comment]
We probably first need to consider how we expose trace IDs from a context at the appengine package. Then, cloud.google.com/go/trace.FromContext can also return a Span if the current context has a trace context.

**Comment by jba** [comment]
OK, I was just asking whether this can be closed. Sounds like it should not be.

**Comment by jba** [comment]
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).
