### ISSUE TITLE
bigtable: expose a lookup-by-column convenience method

### ISSUE THREAD

**Issue by rameshdharan** [GoogleCloudPlatform/google-cloud-go#301]
Currently the bigtable ReadRow and ReadRows methods give me a Row object which I can index by column family yielding an array of ReadItem objects. 

It would be nice if there was a convenience method somewhere that allowed me to look up an individual ReadItem by column name. The most obvious way of course would have been for the Row object to be defined as a nested/multidimensional map but I imagine even if folks agreed with that and there weren't obvious performance issues it still wouldn't be worth breaking compatibility. 

At any rate a convenience method that takes a Row and Column and returns the matching ReadItem seems like a reasonably simple addition.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
