### ISSUE TITLE
bigquery: provide for access to Datasets on other projects

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#314]
Currently the bigquery client allows you to access tables in a project other than the client's. But it doesn't allow access to datasets. Should we provide that?

**Comment by jba** [comment]
Specifically, I propose to remove Client.OpenTable and replace it with client.Dataset, and Dataset.Table.

**Comment by jba** [comment]
@mcgreevy @okdave

**Comment by okdave** [comment]
That seems reasonable. Two related questions:

Do we want a simple way to get the datasets belonging to the client's project? That seems like the most common use case.
and/or
Does the client need the project ID at all in `NewClient` if we make this change?

**Comment by jba** [comment]
> Do we want a simple way to get the datasets belonging to the client's project? That seems like the most common use case.

Yes. We should have a Client.Datasets method returning an iterator.

> Does the client need the project ID at all...

I'm not sure. client.projectID shows up a lot, but it's not clear if it's always used. For example, it's passed to the customize methods from Client.cp, but none of them use it. Michael would have a better sense of that.

**Comment by okdave** [comment]
@mcgreevy do you have an opinion on this?

**Comment by mcgreevy** [comment]
The main remaining use for projectID in the client is to specify which project should be billed for an operation.

Many of the customize methods don't need it; I think some did in the past (@okdave I'll send you a cleanup change to remove the unnecessary instances) . The only customeize method that still needs it is customizeJob, which is implemented by the JobID option (https://godoc.org/cloud.google.com/go/bigquery#JobID) and which enables users to nominate the job reference that should be used for the operation.  A job reference is effectively a (projectid,jobid), and we fill in the projectID based on the client's project ID.  I'm not sure whether it's possible to specify a job reference with a project id that differs from the billing project ID (I suspect not).

**Comment by mcgreevy** [comment]
As for whether we should provide access to another project's datasets from a client, I'll have a think about it.

**Comment by nightlyone** [comment]
Another way would be to implement a NewClientProjects or something else to hang per project clients off. Multiple projects per client seems rare. Internally I even limit my client abstraction to a dataset in order to strictly isolate the code paths.

What is the use case for using multiple projects with single client that is much harder or more cumbersome with multiple clients?

**Comment by jba** [comment]
@nightlyone multiple clients over gRPC would imply multiple TCP connections.

I don't think we have a specific use case in mind. Multiple projects seems unlikely, but what about someone who owns project P1, but wants to work with a colleague's data in project P2? This seems plausible, given how bigquery is used: someone provides some data, and someone (else?) queries it.

**Comment by jba** [comment]
I propose:

Leave the projectID in the client, for auth and billing.

Client.Dataset(datasetID) returns a Dataset in the client's project.
Client.DatasetFromProject(projectID, datasetID) returns a Dataset in another project.

Client.Datasets() returns an iterator over the Datasets in the client's project. (We don't have this, but we should.)

Client.DatasetsFromProject(projectID) returns an iterator over the Datasets in projectID.

That covers tables, because from a Dataset you can list or get tables.

Client.JobFromID should probably be renamed Client.Job, for consistency. Then if necessary we could have Client.JobFromProject.

s/From/In/ if you prefer.

**Comment by okdave** [comment]
Generally SGTM – I like that `Dataset` and `Datasets` continue to work with the default project since that seems like the most common use case by far.

I'm not a fine of the those long names, but I can't think of much better.

- `Client.Project("proj").Dataset("ds")` (unnecesary level?)
- `Client.ProjectDataset("proj", "ds")` (slightly shorter, will group the "Project" ones together?)

**Comment by jba** [comment]
"ProjectDataset" doesn't sound right to me, and anyway I think we want to group the "Dataset" functions together, not the things you can get from another project.

If I use "In" instead of "From" we'll save two characters...

**Comment by mcgreevy** [comment]
> what about someone who owns project P1, but wants to work with a colleague's data in project P2? This seems plausible, given how bigquery is used: someone provides some data, and someone (else?) queries it.

Sure, we want to support querying from other projects, but this is already support by either qualifying tables in the query string with the relevant project:dataset , or specifying Default{Project,Dataset}ID in the Query struct.

The need to actually manipulate tables or dataset in another project, rather than simply querying them, seems much rarer.

**Comment by jba** [comment]
@mcgreevy OK, but this all started because I noticed Client.OpenTable, which takes a project ID. If that's unnecessary, let's remove it. If it is necessary, then logically it would seem to drag the rest of this along with it. Is there a use case for referring to a table in another project, but not a Dataset?

**Comment by derekperkins** [comment]
We add tables to other projects on a daily basis. We have an export option where we will write client data into their project. Anytime that they create a new view of their data, we create a corresponding table.

**Comment by mcgreevy** [comment]
I don't feel too strongly either way.  I'd be fine with jba's proposal.

**Comment by jba** [comment]
Client.DatasetInProject in progress. The iterators will have to wait until the current iterator dust settles.
