### ISSUE TITLE
pubsub: subscription lost connectivity

### ISSUE THREAD

**Issue by raliste** [GoogleCloudPlatform/google-cloud-go#321]
I'm hoping to leave an iterator running indefinitely, but I after a day of running the binary connectivity was lost.

Not sure about the code details regarding connectivity or timeouts, but, is an `it.Next()` suppose to last indefinitely? Otherwise I'd consider to use the pubsub push option instead.

**Comment by mcgreevy** [comment]
The iterator should not time out unless the Context which is passed to Subscription.Pull is canceled or times out.

When you say "the binary connectivity was lost", what error are you seeing exactly?

How are you obtaining the Context that you pass to Subscription.Pull?

**Comment by mcgreevy** [comment]
@raliste can you provide futher details? Otherwise I'll close this issue.

**Comment by davars** [comment]
I'm seeing something similar.  My program is a daemon so context is context.Background().  If the network loses connectivity for an extended period, the iterators hang on Next(), presumably inside apiService.fetchMessages.  

The previous version of my program used the deprecated PullWait in a loop, scoping the finite-time operation to a single fetch call, while letting the rest of the program assume an infinite iterator over the subscription.  I've worked around the issue in the new API by creating finite-time iterators in an infinite loop:

```
for {
    finiteCtx, _ := context.WithTimeout(backgroundCtx, iteratorLifetime)
    it, err := subscription.Pull(finiteCtx)
    // use it, calling it.Stop() when we finally get the inevitable context.DeadlineExceeded, abandon messages in flight from this iterator, etc.
}
```

But this doesn't really express what I want, which is an infinite iterator implemented using finite-time requests.  Can you move my loop inside the Pull function?  Or is there a better way to accomplish this?

**Comment by jba** [comment]
We're planning on moving the pubsub client on top of gRPC (#378). Before doing anything else, I'd like to see if that change affects this problem.

**Comment by schmohlio** [comment]
I use the iterator as a subscriber as well. I receive a lot the following in my logs running on k8 `transport: http2Client.notifyError got notified that the client transport was broken EOF.` 

Any way to confirm if this is benign? seems to always recover. any way to suppress?

**Comment by jba** [comment]
This is benign. See #293.
