### ISSUE TITLE
bigtable: add distinguishable "no such table" error

### ISSUE THREAD

**Issue by jmhodges** [GoogleCloudPlatform/google-cloud-go#323]
bigtable returns an opaque `grpc.rpcError` with error code `2` and only a string desc with the table's full name at the end for the user to match against for both creation of a duplicate table and deletion of non-existent table (at least, from the emulator). In the duplicate table case, you can figure it out by matching the prefix of the desc string (to ignore the server-generated full table name) and in the non-existent table case, you figure it out by matching the suffix of the desc string

This makes it harder to ignore non-problems in tests like deleting a table at the start of a unit test that doesn't already exist.

It would be nice to be able to tell what kind of error was returned without doing string matching or at least not string prefix and suffix matching. I'm not sure if the bigtable API supports that from first look, so maybe that's a feature request I would make elsewhere?'

Here's a test that shows off the errors (it expects the emulator to be running and `$BIGTABLE_EMULATOR_HOST` to be set).

```
func TestCreateDeleteTable(t *testing.T) {
    ctx := context.Background()
    admin, err := bigtable.NewAdminClient(ctx, "", "")
    if err != nil {
        t.Fatal(err)
    }

    err = admin.DeleteTable(ctx, "foobar_i_dont_exist")
    if err != nil {
        t.Errorf("what to do with %#v", err)
    }

    err = admin.CreateTable(ctx, "i_will_exist")
    if err != nil {
        t.Fatal(err)
    }
    err = admin.CreateTable(ctx, "i_will_exist")
    if err != nil {
        t.Errorf("second create i_will_exist: %s", err)
    }
    err = admin.DeleteTable(ctx, "i_will_exist")
    if err != nil {
        t.Fatalf("delete i_will_exist: %s", err)
    }
}
```

**Comment by garye** [comment]
I believe I37389d46d4d74576067cc15e84f386f02bf46af1 is a fix for this issue, at least partially. The emulator now returns `codes.NotFound` in the same places that the bigtable service does, and with `grpc.Code(err) == codes.NotFound` you can check to see if your table deletion error should be ignored or not.

I'll leave this open until we write a test to verify that this behavior is consistent between the emulator and actual service.
