### ISSUE TITLE
bigquery: Add support for useLegacySQL parameters

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/google-cloud-go#326]
https://cloud.google.com/bigquery/sql-reference/enabling-standard-sql

These parameters are needed in order to use standard SQL syntax.

**Comment by tswast** [comment]
I think we will need to add a `QueryOptions` with this, as well as adding it to the job configuration options (I'm not actually sure where the job insert call is in the library).

**Comment by broady** [comment]
https://godoc.org/google.golang.org/api/bigquery/v2#QueryRequest

`UseLegacySql`

**Comment by tswast** [comment]
"Experimental" means beta in this case, so I would propose adding it asap.
