### ISSUE TITLE
datastore: make examples more useful in godoc/testing

### ISSUE THREAD

**Issue by okdave** [GoogleCloudPlatform/google-cloud-go#332]
Currently the examples for datastore have a weird format since they designed to be retargeted to the [datastore developer reference](https://cloud.google.com/datastore/docs/concepts/entities). They contain weird machine comments `[START named_key]` and half-backed things like:

```
_ = taskKey // Use the task key for datastore operations.
```

This looks fine when extracted to the developer docs, but strange when seen inline in the godoc.

How can we fix this? Ideal properties:
- the examples read correctly in godoc and the external documentation
- where possible, the examples are self-contained (maybe we need to combine some of the smaller examples into larger examples with multiple sections)
- the examples are consistent with the other libraries here
- the examples are compiled to ensure correctness
- **stretch** the examples are run to ensure correctness (this would have prevented #330 for example).

We might need the examples to live in two places: one which contains the `[START etc]` tags, and the other for display in the godoc.

/cc @broady @jba

**Comment by adams-sarah** [comment]
godoc examples LGTM now.
@jba please reopen if I'm wrong.
