### ISSUE TITLE
pubsub: no way to access to the short topic name

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#342]
Topic.Name is returning the full name of a topic, e.g. `projects/bamboo-shift-504/topics/topic-1415926018` but all operations on Topic (such as Client.Topic(string)) requires the short name.

I cannot programmatically run operations like Topic.Delete without trimming the full name to be `topic-1415926018`.

Make it easier for users to access to this name rather than the full name.

(Hope I am not missing something obvious.)

/cc @jba @mcgreevy @broady

**Comment by jba** [comment]
The terminology is:
Name: projects/P/topics/T
ID: T

go/resource-names

Maybe Topic should have an ID field as well. And if the Name is never used
in our client, remove it?

**Comment by rakyll** [comment]
ID sounds good. Name is only useful for printing. We can implement String on Topic and Subscription that returns what Name currently returns.

**Comment by mcgreevy** [comment]
If you have a Topic on which to call Name, what prevents you from calling Delete directly on that Topic?

**Comment by rakyll** [comment]
It is tedious when you don't have a instance of Topic already which is the common case for hardcoded IDs.

It is somewhat also less visible that it could be achieved by constructing a Topic. I fear that users may depend on HasSuffix or similar unideal solutions. Given the full name is less useful than the ID, I would enjoy that we are also returning the ID.

**Comment by mcgreevy** [comment]
I'm still missing something. Can you give me an example where it's a problem?

**Comment by rakyll** [comment]
I don't want to do this:

```
	topic := c.Topic(topicName)
	for _, t := range topics {
		if t.Name() == topic.Name() {
		    // ....
		}
	}
```
when this is easier:

```
	for _, t := range topics {
		if t.ID() == topicName {
		    // ....
		}
	}
```

And users most likely doesn't need Name() other than printfing reasons.

**Comment by rakyll** [comment]
It is also impossible to migrate subscriptions and topics from one account to another.

```
for {
		s, err := it.Next()
		if err == pubsub.Done {
			break
		}
		if err != nil {
			return nil, err
		}
		// create a subscription with s.Name() under another project.
		// impossible to do without working on the full name.
	}
```

**Comment by mcgreevy** [comment]
Those examples seem a bit obscure, but I concede that ID is at least marginally more useful than Name.  Feel free to send me a change which renames Name to String, and adds ID methods.

**Comment by rakyll** [comment]
The API doesn't return the IDs, do we want to process the name field to calculate the IDs?

**Comment by mcgreevy** [comment]
Yes, I believe that's our only option.

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/#/c/7478/.
