### ISSUE TITLE
logging: remove OrderBy option, replace with ReverseChronology

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#344]
This is for what is currently preview/logging

Logging team says that sorting by time forward and backward are the only likely orderings, so default to ascending and provide a nullary option for reverse order.

@bradfitz @cbro @okdave Ideas for a better name?

**Comment by bradfitz** [comment]
Anything but ReverseChronology sounds good to me. :-)

`logging.NewestFirst()`?

If the default is ascending (oldest first, right?), then where do I specify the starting time? In some totally opaque `Filter(f string) EntriesOption`?

**Comment by jba** [comment]
What could be less opaque than `timestamp >= "2014-10-02T15:01:23.045Z"`? :)

NewestFirst SGTM.

**Comment by bradfitz** [comment]
That's kinda gross. Can we have a constructor for that, using Go types?

`logging.EntriesFrom(time.Time)` or something?

**Comment by jba** [comment]
We really don't want to go there. We're going to get caught in a maze of twisty passages. https://cloud.google.com/logging/docs/view/advanced_filters

People will want to filter on more than timestamp, like log name. We will end up either building an AST for the filter language or having a mix of filter strings and options.

**Comment by bradfitz** [comment]
Then at least add some documentation to the filter, and an `Example` of how to construct that "advanced" filter (`timestamp >= "2014-10-02T15:01:23.045Z"`) from a `time.Time`.
