### ISSUE TITLE
bigquery: reconsider Client.Copy

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#351]
The Copy method in the bigquery library elegantly provides lots of functionality in a single place:

* Loading data from GCS into a table
* Querying a table
* Copying from one or more tables into a table
* Extracting data from a table to GCS

But it has several costs:

1. It's not clear what Copy can be used for. Its Source and Destination arguments are exported interface types, but their methods are unexported, so there is no way from the godoc to determine which types implement them.  Issue #327, a request for a new feature, sat open for two weeks before it was finally noticed that the library already provides the feature—via Copy.

2. The Go client's use of "copy" and the API's use of "copy" do not align. Client.Copy returns a Job, which maps to the Job type of the BigQuery API. But the API's Job has [four types](https://cloud.google.com/bigquery/docs/reference/v2/jobs), only one of which happens to be copy. This causes confusion. (I'm not arguing that we should split the Job type into four subtypes, but rather that we should expose the four operations more clearly.)

3. Copy is a nested switch on its Source and Destination argument types, which is not an idiomatic Go design. It is more typical to see types with individual methods on them: a Table type with Copy and Extract methods, for example. The relevant types already exist in the client.

4. Copy returns runtime errors that could easily be caught at compile-time. For example, attempting to copy a table to a query returns an error. But in Solution 2 below, it is impossible to express that operation.

Solutions:

1. Keep Copy, but improve its documentation considerably.

2. Replace Copy with individual methods on the relevant types. All these methods return (*Job, error), as Client.Copy does:

   * Table.CopyTo(Table)
   * Tables.CopyTo(Table)
   *  Query.Run(Table)
   *  Table.LoadFrom(GCSReference)
   *  Table.ExtractTo(GCSReference)

I prefer Solution 2 (surprise). Adding documentation will help, but no matter how much English you write, it can't make up for seeing the possible operations directly in the godoc, in large type.

/cc @mcgreevy @okdave @broady @bradfitz @rakyll 

@dsymonds, IIRC you were implicated as one of the co-architects of Copy, so I would like to hear your arguments for it.

**Comment by nightlyone** [comment]
I would totally support solution 2. It took me a few days to discover that all this is done by Copy and involved reading the whole component. Other colleagues even completely ditched using the package and use the auto generated API package instead. So I am more than positive about providing a more discoverable api as the one suggested in solution 2.

**Comment by derekperkins** [comment]
Definitely the latter. `Copy` is definitely overloaded.

**Comment by jba** [comment]
@nightlyone @derekperkins We're close on this. We're going with a variation of Solution 2: the method will return a struct with fields you can set, and then you call Run on the struct to do the operation. For example,
```go
err := table1.LoadFrom(gcsRef).Run(ctx)
```
or
```go
ld := table1.LoadFrom(gcsRef)
ld.AllowJaggedRows = true
ld.AllowQuotedNewlines = true
err := ld.Run(ctx)
```
This will let us get rid of all the options, and it will be clear from the doc which options go with which operations.

The main thing we're hung up on is the name of these methods. Should we use names like `LoadFrom`, or `LoaderFrom`?

If we use a verb like `LoadFrom`, people may think that the method itself performs the operation:
```go
table.LoadFrom(gcsRef)
```
looks like it does what it says, but it's actually a no-op.

On the other hand, names like `LoaderFrom`, which would return a `Loader`, invite confusion with the  `NewUploader` method and `Uploader` type. Those behave differently: `NewUploader` takes options, and to use an `Uploader` you repeatedly call `Put` instead of calling `Run` once.

What do you think?

**Comment by derekperkins** [comment]
I like the api. I wrote our internal BQ package and it has long function signatures. This is a good solution for that.

Not that I have an answer, but my first thought was that this is very similar to the http package - `NewRequest().Do()` (I know that's not the function signature, I'm just referencing the concept). Maybe similar semantics could be used. `NewLoaderFrom().Do()`. I don't know that that is any better, just another idea.

**Comment by jba** [comment]
@nightlyone @derekperkins The new API is in.

**Comment by davinkevin** [comment]
I didn't find in the new API a way to copy the result of a request to a table. Is it normal or did I miss something ?

**Comment by jba** [comment]
Do you want to run a query and populate a table with the results?

If so, you should use `Query` to build the query, then set the `Dst` field of the Query to the table you want (it's documented under `QueryConfig`). Then run the query.

**Comment by davinkevin** [comment]
Yes, it's exactly what I want to do.

I use `client.Query` to build a query but I don't have `Dst` field in the Query...

![image](https://cloud.githubusercontent.com/assets/1970922/21611793/a634180c-d1ce-11e6-9324-90bf70957a4e.png)


Did I miss something ? (Of course, I've checked the `type Query struct`, no element `Dst`)

**Comment by jba** [comment]
A `Query` embeds a `QueryConfig`, which has a `Dst` field.

Based on what your IDE is saying, I think you need to update to the latest version with `go get -u`.

**Comment by davinkevin** [comment]
I though I had updated, but seems I've done something wrong...

It's good for me now, I will play with this new API 😄
