### ISSUE TITLE
logging: replace old logging client with new one

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#363]
Move the preview/logging package to logging.

**Comment by derekperkins** [comment]
Does this do request grouping like on GAE?

**Comment by jba** [comment]
I don't know what that is. Can you point me to doc or code?

**Comment by derekperkins** [comment]
App Engine groups all logs related to a single request together, making it easy to scan your logs, vs having hundreds of simultaneous requests all logging to a single stream.

It also surfaces the max severity, method, path and response code. IMO, it's the killer feature that GAE logging has over the competition. I've tried out Splunk, Loggly, LogEntries and a few others, but this is what makes migrating away from GAE a really hard decision. 

The infrastructure to support it is already there, the API just needs a way to register the appropriate metadata.

### App Engine Logging
![image](https://cloud.githubusercontent.com/assets/3588778/18445598/97dee53a-78db-11e6-9f9d-7be41cea7988.png)

### Compute Engine Logging
![image](https://cloud.githubusercontent.com/assets/3588778/18445631/bf1194f4-78db-11e6-911d-5fa4b31d42d2.png)

**Comment by jba** [comment]
Thanks for the excellent explanation.

We're going to have a higher-level package that does this, and also seamlessly handles tracing and reporting of panics. I'm not sure about its ETA.

This package is designed to be a lower-level wrapper of the underlying service.

**Comment by jba** [comment]
Fixed by 10cb077f8e3474ef9bbd05bfa32b932781d6f996.
