### ISSUE TITLE
trace: Document relation to golang.org/x/net/trace

### ISSUE THREAD

**Issue by nightlyone** [GoogleCloudPlatform/google-cloud-go#365]
Since [golang.org/x/net/trace](https://godoc.org/golang.org/x/net/trace) is an existing mechanism which users from other cloud platforms might already know and use, it seems useful to establish or at least document any intended or existing relationship.

The following questions should be answered:
- How do I send my traces from golang.org/x/net/trace to cloud.google.com/go/trace?
- If the above isn't possible: Given I did use  golang.org/x/net/trace in my application, how do I convert my code? (example needed)
- Can I use both mechanisms in the same program? Do they interfere somehow?

**Comment by rakyll** [comment]
I think we also need to answer a more fundamental question: Why don't the trace package export an x/net/trace.Trace implementation given that x/net/trace is widely used?

**Comment by jba** [comment]
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).
