### ISSUE TITLE
all: iterator's Next should require a context

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#367]
Currently, we are requiring user to pass a context to the iterator constructor, such as:

```
it := client.Buckets(ctx, proj)
```

It should be required at Next() instead where the RPC actually happens.

```
it := client.Buckets(proj)
it.Next(ctx)
```

/cc @jba @okdave @broady

**Comment by jba** [comment]
We picked this way to make it more convenient for the user.

**Comment by broady** [comment]
I think it's OK as-is. Iterators should not be long-lived.

**Comment by rakyll** [comment]
The other point is that there is some sort of integrity within iterator calls, e.g. you are not forking Next calls concurrently nor want to cancel them individually. If you are not interested in iterating anymore, the entire iterator should be cancelled.

Closing this non-issue issue.
