### ISSUE TITLE
example/storage: reduce scope of app engine demo

### ISSUE THREAD

**Issue by okdave** [GoogleCloudPlatform/google-cloud-go#368]
The current example is much broader in scope than the [equivalent python demo](https://github.com/GoogleCloudPlatform/appengine-gcs-client/blob/master/python/demo/main.py), and uses a much broader API surface than the dev_appserver will ever be able to emulate.

Consider paring back this demo so that if/when we have dev_appserver support, the app will be able to work in both production and development environments.

@rakyll @broady

**Comment by rakyll** [comment]
I am thinking about removing example/storage and revisiting it once we finalize the dev_appserver support. The migration of the examples has started with re-authoring the references at https://github.com/GoogleCloudPlatform/golang-samples/pull/112.

**Comment by jba** [comment]
The examples have been removed, so closing. @rakyll, if this still applies to the example in golang-samples, please open an issue there.

**Comment by broady** [comment]
It's OK now, I think. It's a separate thing, and I think useful enough to keep around.
