### ISSUE TITLE
Set up repo sync

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/google-cloud-go#369]
At the moment it's running on @okdave's workstation under his desk.

Find a more solid solution (that maybe uses gopherbot's credentials?)

/cc @adams-sarah @okdave @jba @rakyll @zombiezen

**Comment by adams-sarah** [comment]
Not sure if this is the same or separate, but the webhook (or whatever) that looks for phrases like "Fixes #000" in a commit message and closes the corresponding github issue should also use gopherbot's credentials, not Dave's.

**Comment by bradfitz** [comment]
We could make the main Go repo's syncer do it, as the "gopherbot" user.

That code lives in x/build/cmd/coordinator/watcher_process.go.

**Comment by adams-sarah** [comment]
What do other GCP repos do? (other languages)

**Comment by bradfitz** [comment]
> What do other GCP repos do? (other languages)

Use Github directly instead of Gerrit?

**Comment by broady** [comment]
@bradfitz that'd be great. I'll add gopherbot as a pusher to this repo.

We either need to run two coordinators or support multiple github orgs/gerrit origins. What do you think?

**Comment by adams-sarah** [comment]
Ah. Then I'm all for mimicking the main Go repo's config. The fewer unique configs, the merrier.

**Comment by broady** [comment]
> Only organization owners can Send invitations

I'll get a GCP org owner to add gopherbot to GCP.

**Comment by okdave** [comment]
Thanks all, this SGTM.

**Comment by adams-sarah** [comment]
@broady implemented this, I believe.
Closing for now. Feel free to reopen if I'm wrong.

**Comment by broady** [comment]
Yup.

https://github.com/broady/reposync, and it runs in this GCP project:
https://console.cloud.google.com/project/go-cloud-reposync
