### ISSUE TITLE
datastore: clean up tests to use fake where possible

### ISSUE THREAD

**Issue by okdave** [GoogleCloudPlatform/google-cloud-go#371]
Introducing a simple fake, rather than always relying on the production datastore service would:
- improve unit-test-level coverage by testing the API using a fake where possible
- allow us to test more of the code without resorting to internal implementation details/funcs (many parts of the tests today use unexported methods)

@adams-sarah

**Comment by broady** [comment]
Do you mean emulator? If so, +1.

**Comment by okdave** [comment]
Actually, all the tests currently pass against the emulator (I don't know if we make that easy to enable – I've definitely done it in the past).

This was mostly about better unit testing for the package. The coverage today without the integration tests is sub-optimal.

A more fully-fleshed in emulator in Go (like we have for bigtable) would be fantastic, but it's a non-trivial undertaking.

**Comment by adams-sarah** [comment]
Awesome. Thanks for writing this up @okdave

**Comment by jba** [comment]
https://code-review.googlesource.com/c/gocloud/+/14613 will solve this with gRPC replay.
