### ISSUE TITLE
storage: X-Goog-Stored-Content-Length header missing

### ISSUE THREAD

**Issue by dominikschulz** [GoogleCloudPlatform/google-cloud-go#372]
For unknown reasons we encounter a lot of objects with unparseable content length headers.

The problem is that there seems to be a memory leak due to a missing `res.Body.Close()` in the cloud/storage package.

Please see https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/storage.go#L548. IMHO there should be also a `res.Body.Close()` as with the previous error returns in the same method.

**Comment by bradfitz** [comment]
> For unknown reasons we encounter a lot of objects with unparseable content length headers.

What's the error message you get? Is it an empty string in there (`""`) or some non-decimal value?

>  IMHO there should be also a res.Body.Close() as with the previous error returns in the same method.

Looks like it. But I'm more concerned about the error in the first place.

/cc @jba

**Comment by dominikschulz** [comment]
The error returned by [NewReader](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/storage.go#L489) is `storage: can't parse content length "": strconv.ParseInt: parsing "": invalid syntax`.

I just realized that we *may* be requesting non-existing objects, but in that case I'd expect an `storage.ErrObjectNotExist` and not a `strconv.ParseInt` failure. I'll try to verify if we indeed request invalid objects and comment if I find something interesting.

**Comment by bradfitz** [comment]
If it's a 404, we already returned `storage.ErrObjectNotExist` up above that line. That error message is only returned on a 2xx response. I'm not sure which 2xx response would not have a `X-Goog-Stored-Content-Length` response header. I suppose we need to talk to the GCS folk and figure that out.

**Comment by okdave** [comment]
I've sent out a fix to the unclosed-body, but I agree with @bradfitz that we should only encounter an error like that in exceptional circumstances. I'm chasing up with the GCS team.

**Comment by bradfitz** [comment]
For finding the full size, I think we should be using the response Content-Range header instead.

**Comment by bradfitz** [comment]
https://code-review.googlesource.com/7850

**Comment by bradfitz** [comment]
@dominikschulz, do you have any details of which objects get that error? For a given object, do you see it sometimes work and sometimes not, or is it only for certain objects?

What's your caller code look like? Are you using `ObjectHandle.NewRangeReader`? Or only `ObjectHandle.NewReader`?

**Comment by dominikschulz** [comment]
The caller code is using `ObjectHandle.NewReader` as we're only interested in complete objects.

So far I haven't been able to get any details on the failing objects, and I can't give an ETA due to personal circumstances, but if I find something I'll report back to this issue.
