### ISSUE TITLE
storage: NewWriter returns 404

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#374]
Consider the following snippet:

```
    f, err := os.Open("notes.txt")
    if err != nil {
        return err
    }
    wc := client.Bucket(bucket).Object(object).NewWriter(ctx)
    if _, err = io.Copy(wc, f); err != nil {
        return err
    }
    if err := f.Close(); err != nil {
        return err
    }
    if err := wc.Close(); err != nil {
        return err
    }
```

It returns a 404 rather than creating a file with the contents I copy to thet wc. Returned error:

```
2016/09/16 15:12:18 failed to write to the object (golang-example-objects-1474063937): googleapi: Error 404: Not Found, notFound
```

/cc @jba @okdave

**Comment by rakyll** [comment]
I have just realized this is happening because the bucket doesn't exist not the object.

Is there a way we can return an error reflecting that?

**Comment by shantuo** [comment]
I experienced the exact same thing when I fixed some of the storage tests. I don't think there is any method that can immediately reflect if the bucket exists or not. We may either provide a method to check this, or modify client.Bucket (currently doesn't do any network operation) to check if the bucket exist?

**Comment by bradfitz** [comment]
We should *not* change `Client.Bucket` to do a network operation.

If we're going to make something slower, make an existing error path slower to stat the bucket and return a more descriptive error on an object PUT 404.

**Comment by rakyll** [comment]
I filed an issue against the API, keeping this open to track it.

**Comment by jba** [comment]
@rakyll How does keeping this open help us to track the API issue? Is there an internal bug number?

Tempted to close this, as it's not a problem with the client library.

**Comment by jba** [comment]
Closing. @rakyll, point to the API issue if you can.
