### ISSUE TITLE
pubsub: move on top of gRPC

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#378]
Change the pubsub client from using HTTP to gRPC.

**Comment by schmohlio** [comment]
Hi @jba sorry for follow up, but would it be possible to confirm if the `transport: http2Client.notifyError got notified that the client transport was broken EOF.` errors are benign for long running iterators (`Next()`), and if so, if there is a way to disable logging? 

They are filling up my k8 logs and obfuscating other errors. 

Any way to confirm if this is benign? seems to always recover. any way to suppress?

**Comment by jba** [comment]
So you're still seeing them at head? We just moved pubsub to gRPC. Can you replicate the problem?

**Comment by schmohlio** [comment]
@jba thanks for that reminder. It seems that the errors are actually coming from the `go/errors` and `datastore` libraries. Basically my datastore clients that are left open log this error every 4 minutes running on Container Engine. 

Should they be manually closed more often? Is there a list of which libraries are on gRPC, and also which clients are safe for concurrent use with multiple goroutines?

**Comment by schmohlio** [comment]
nevermind it looks like I'm running into something others have seen. https://github.com/GoogleCloudPlatform/google-cloud-go/issues/293

**Comment by rtjoseph11** [comment]
I'm seeing exactly the same issue as @schmohlio with getting this error every 4 minutes. I have a pubsub client and a bigquery client in my application.

**Comment by schmohlio** [comment]
@rtjoseph11 For now I just included the following in one of my libs and import it:

```
import "google.golang.org/grpc/grpclog"

func init() {
	grpclog.SetLogger(log.New(ioutil.Discard, "", 0))
}
```
