### ISSUE TITLE
pubsub: publish time needed in PubSub message

### ISSUE THREAD

**Issue by ptone** [GoogleCloudPlatform/google-cloud-go#381]
PubSub messages support a PublishTime field

https://github.com/google/google-api-go-client/blob/master/pubsub/v1/pubsub-gen.go#L457

But exposing this in this library has been a todo for some time
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/message.go#L40

with no tracking issue that I could find here in GH

cc: @mcgreevy

**Comment by jba** [comment]
https://code-review.googlesource.com/#/c/7815
