### ISSUE TITLE
[pubsub] make the keepalive robuster

### ISSUE THREAD

**Issue by tmatsuo** [GoogleCloudPlatform/google-cloud-go#382]
I have just migrated from the legacy client code to the newer pubsub client. In that project, I'm using pubsub for task queuing. Tasks can take from 30 seconds, or up to 8 hours.

I used to extend the ackDeadline within my code, with 15 seconds grace period and 3 times retries.

Now we're seeing significantly more failures on extending the ackDeadline.

I briefly looked at the source code of the current library and found the code below:

```
keepAlivePeriod := po.ackDeadline - 5*time.Second
ackTicker := time.NewTicker(keepAlivePeriod / 2) // Stopped in it.Stop
```

And keepalive retries just one time when modifyAckDeadline fails.

If I'm not mistaken, if the first attempt for modifying the ackDeadline fails with somewhat long latency (for example, somehow the request hangs for 5 seconds and fails), then it fails to modify the ackDeadline, thus we get the same message again.

Here are my suggestions for making it robuster:
- Retry few more times (or configurable retryCount)
- Configurable keepAlivePeriod (or automatic calculate more appropriate value)

**Comment by tmatsuo** [comment]
Ping, no news?

**Comment by jba** [comment]
Sorry, we are working on a greatly improved pull implementation, so we haven't looked carefully at this yet.

**Comment by tmatsuo** [comment]
@jba Alright, then maybe you can close this issue as long as you consider this problem when designing and implementing the new one.
