### ISSUE TITLE
storage component missing support for bucket versioning.

### ISSUE THREAD

**Issue by BrandonY** [GoogleCloudPlatform/google-cloud-go#383]
The "versioning.enabled" bucket metadata property does not appear to be exposed.

**Comment by jba** [comment]
https://code-review.googlesource.com/#/c/7818

**Comment by BrandonY** [comment]
Is there a way to enable bucket versioning, or create buckets with versioning enabled?

**Comment by jba** [comment]
Not yet, but we're working on that. It's a little bit subtle.

**Comment by jba** [comment]
Added in 45720db4a4f6f8e754ff7819db31a0603e134946.
