### ISSUE TITLE
compute/metadata uses internal package of a different package

### ISSUE THREAD

**Issue by TamalSaha** [GoogleCloudPlatform/google-cloud-go#384]
I am using the compute/metadata package with Go 1.7.1. It is failing to compile due to

```go
	imports google.golang.org/cloud/compute/metadata
	imports cloud.google.com/go/internal: use of internal package not allowed
```

https://github.com/GoogleCloudPlatform/google-cloud-go/commit/a395c2f47b3bc641b5c5e6716a1865e1737d9ff2#diff-4ff99412e0bc1122c84694ea4f62b8b1 seems to be the root of this issue.

**Comment by jba** [comment]
The google.golang.org/cloud import paths have been shut down. You should
use cloud.google.com/go/compute/metadata. See
https://groups.google.com/d/topic/google-api-go-announce/nXY-DYZGqz8/discussion
(and
please subscribe for future updates).

**Comment by TamalSaha** [comment]
I understand. Thanks @jba .
