### ISSUE TITLE
SampleRowKeys is not implemented in the emulator

### ISSUE THREAD

**Issue by lindsayismith** [GoogleCloudPlatform/google-cloud-go#385]
If I run the emulator and try to use it, my test code causes a panic:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47e2ac]

goroutine 36 [running]:
panic(0x7ea980, 0xc42000c140)
	/usr/lib/google-golang/src/runtime/panic.go:502 +0x1b3
cloud.google.com/go/bigtable/bttest.(*server).SampleRowKeys(0xc420131640, 0xc4201374f0, 0xa74040, 0xc420137580, 0x0, 0xc42022a4c8)
	<autogenerated>:3 +0x3c
google.golang.org/genproto/googleapis/bigtable/v2._Bigtable_SampleRowKeys_Handler(0x84e320, 0xc420131640, 0xa73020, 0xc4201d6120, 0xc420173c80, 0x0)
	/usr/local/google/home/lindsaysmith/work/cloud/go/src/google.golang.org/genproto/googleapis/bigtable/v2/bigtable.pb.go:817 +0x117
google.golang.org/grpc.(*Server).processStreamingRPC(0xc4201ac6e0, 0xa746a0, 0xc4202007e0, 0xc420224000, 0xc420173920, 0xa910a0, 0xc420173c50, 0x0, 0x0)
	/usr/local/google/home/lindsaysmith/work/cloud/go/src/google.golang.org/grpc/server.go:689 +0x702
google.golang.org/grpc.(*Server).handleStream(0xc4201ac6e0, 0xa746a0, 0xc4202007e0, 0xc420224000, 0xc420173c50)
	/usr/local/google/home/lindsaysmith/work/cloud/go/src/google.golang.org/grpc/server.go:773 +0xc36
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420140e90, 0xc4201ac6e0, 0xa746a0, 0xc4202007e0, 0xc420224000)
	/usr/local/google/home/lindsaysmith/work/cloud/go/src/google.golang.org/grpc/server.go:422 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/usr/local/google/home/lindsaysmith/work/cloud/go/src/google.golang.org/grpc/server.go:423 +0xa3

**Comment by garye** [comment]
Fixed by 66958b9. It will take a while for this to be released in the gcloud emulator package, but in the meantime you can grab the latest go library (cloud.google.com/go) and run bigtable/cmd/emulator/cbtemulator.go which is the exact same thing.
