### ISSUE TITLE
bigtable appengine standard

### ISSUE THREAD

**Issue by albertog** [GoogleCloudPlatform/google-cloud-go#388]
I have not seen examples of use bigtable from appengine **standard** can it be used?

**Comment by garye** [comment]
@lesv Do you know the status of this?

**Comment by lesv** [comment]
I haven't tried Go, it seems like it should work.  (Unlike Java or Python).

The issue should be making sure the AppEngine context is passed to gRPC.  I've heard that it does.
@broady Care to confirm?

@albertog Do you need an example to move forward?

**Comment by broady** [comment]
It will be usable, but it's likely quite slow.
