### ISSUE TITLE
option: please add option to pass json credentials via environment variables

### ISSUE THREAD

**Issue by arekkas** [GoogleCloudPlatform/google-cloud-go#392]
The options package currently supports `WithServiceAccountFile` and `WithTokenSource`. I got it working with the service account file, but not using pure OAuth2. For operation on e.g. heroku, it is neccessary to provide this data using environment variables, so it would be good to have `WithServiceAccount(data []byte)`.

**Comment by jba** [comment]
If you set the environment variable to the contents of the JSON file, you can use os.Getenv to get it, then do what we do after we read the file ([actual code here](https://github.com/google/google-api-go-client/blob/master/transport/dial.go#L114)):

```go
cfg, err := google.JWTConfigFromJSON([]byte(envVarValue), scope...)
if err != nil {...}
ts := cfg.TokenSource(ctx)
```
Then use `option.WithTokenSource(ts)`.

Here, `google` is the package `golang.org/x/oauth2/google` and `ctx` is a `context.Context`.

**Comment by arekkas** [comment]
Awesome, thanks!
