### ISSUE TITLE
bigtable: read retry sends different request for retries?

### ISSUE THREAD

**Issue by gamorris** [GoogleCloudPlatform/google-cloud-go#393]
I think the missing unit test is: when issuing a ReadRows request and a retryable error (e.g. unavailable) is received before any (partial) read data, the request for the retry should be the same as the original request.

I'm not completely sure I'm reading the code correctly but it looks like when an error occurs before any data is received it calls `retainRowsAfter()` with an uninitialized string. I think that will turn a `RowRange("a", "z")` request into a `RowRange("\x00", "z")` request for the retry?

Additionally, I don't think it should happen if everything is working properly, but if `retainRowsAfter()` ever turns a previously non-empty `RowList` into an empty list, or a previously non-empty `RowRange` into an empty range (e.g. `RowRange("a", "a\0")` into `RowRange("a\0", "a\0")`), that modified request should not be sent.

**Comment by garye** [comment]
Fixed by daafb8782bb0c3cc73c413c1a11a140989243b31
