### ISSUE TITLE
logging: remove `t.Skip`s on timeout

### ISSUE THREAD

**Issue by adams-sarah** [GoogleCloudPlatform/google-cloud-go#394]
We are currently calling `t.Skip` on a test if it times out (currently, if the network op takes longer than 2 minutes).

We do this instead of failing so frequently, which could hide other test failures in the sea of red.

Once the Stackdriver logging client goes GA or fixes their timeouts on read, we should remove these `t.Skip`s.

@zombiezen @jba

**Comment by pongad** [comment]
Searching for `Skip` in logging only shows `logging/apiv2/WriteLogEntries_smoke_test.go` which skips integration test in short mode.
I assume the work is already completed, so I'll close this. Please reopen if I misunderstood.
