### ISSUE TITLE
bigquery: support media upload

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#397]
The bigquery API supports the ability to [load data into a table directly via a POST request](https://cloud.google.com/bigquery/loading-data-post-request). This is a variant of jobs.insert. It is *not* the same feature as [streaming upload into a table](https://cloud.google.com/bigquery/docs/reference/v2/tabledata/insertAll), which is supported by `bigquery.Uploader`.

Currently this package does not support media upload. It only supports loading from GCS, via `Table.LoaderFrom(*GCSReference)`.

Options:

  1. Change `LoaderFrom` to take an interface type `LoadSource`, implemented by both `GCSReference` and something that wraps `io.Reader`. Loading from a `GCSReference` would look the same. Loading from an opened file `f` would look like

  ```go
  loader := table.LoaderFrom(bigquery.ReaderLoadSource(f))
  ```
  2. Add a `LoaderFromReader` method. Loading from an opened file would be 

  ```go
  loader := table.LoaderFromReader(f)
  ```

I prefer (2), but (1) might be better if more load sources were to appear. The BigQuery team states 

> We don't have any specific plans to support storage systems other than GCS ... the chances of a change are relatively small.... On the other hand, the API deliberately requires only a URI (nothing GCS-specific) to be flexible.

Supporters of (1) or some other backwards-incompatible approach should speak now, since we want to stabilize the package surface ASAP.

/cc @mcgreevy @zombiezen @adams-sarah @bradfitz

**Comment by nightlyone** [comment]
I prefer solution 2, since passing along URLs (e.g. a GCSReference) is fundamentally different in terms of CPU and memory required than feeding a local io.Copy loop. APIs should reflect this complexity, especially in Go.

**Comment by mcgreevy** [comment]
I also prefer 2.

**Comment by jba** [comment]
PTAL at the solution. I went with a variant of (1), because when you consider options, it makes everything more consistent. See [ReaderSource](https://godoc.org/cloud.google.com/go/bigquery#ReaderSource) and related types.
