### ISSUE TITLE
bigquery: support a ValueLoader for maps or structs

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#399]
ValueLoader takes a slice of values, whereas ValueSaver produces a map[string]Value.  This difference reflects what the underlying API produces/consumes. 

For users that just want to deal with a slice of values and not worry about maps, we have ValuesSaver which can convert a slice of values to a map[string]Value, with the aid of a Schema.

It might be nice to similarly provide another adapter that implements ValueLoader, but stores the data in a map, so something like:

``` go
type MapLoader map[string]Value

func (ml MapLoader) Load(v []Value, s Schema) error {
  // TODO
}
```

**Comment by jba** [comment]
Perhaps we could even do more and populate a struct via reflection.

@mcgreevy thoughts?

**Comment by adams-sarah** [comment]
My first question is, can you describe the use case? I'd love to hear more about when this would be useful for users. Also, have we already had any requests for this from users? If so, please link!

**Comment by mcgreevy** [comment]
The struct part has long been planned, in fact there is a TODO in uploader.go to provide a default ValueSaver implementation for structs which uses reflection.

This would be analogous to datastore, and be very convenient for some users for both uploading and storing query results.  However, there are some users which will not know at compile time the form of the queries that they will issue. These users need the flexibility of a slice of Values or a map.

**Comment by adams-sarah** [comment]
Got it! Thanks for the explanation @mcgreevy

**Comment by jba** [comment]
What if we changed the argument to RowIterator.Next to interface{} and accepted:
- a ValueLoader
- a map[string]Value or map[string]interface{}
- a pointer to a struct

**Comment by mcgreevy** [comment]
FYI the old Iterator.Get accepted an interface{} for this reason, but I didn't pick up on the change to ValueLoader when the switch to RowIterator happened.

**Comment by jba** [comment]
If the user passes a pointer to a struct to RowIterator.Next, we match the struct fields to the schema of the returned rows. This is my proposed design for how field matching should work. For the implementation, see https://code-review.googlesource.com/#/c/9175.

Only exported fields of a struct are considered. You cannot set unexported fields with reflect.

Because [BigQuery column names are case-insensitive](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#case_sensitivity), field names are matched case-insensitively. So schema fields `name` and `Name` both match to struct field `Name`. 

Fields in the schema that don't match exported fields in the struct are ignored. This lets you read a subset of columns from a table into a struct, which seems useful.

Exported fields in the struct that are not in the schema are ignored. This could be useful if you are not sure of the exact set of columns, or you want to use the same struct type for different tables. These use cases aren't that compelling, so I'd be happy return an error on unmatched struct fields if that is what folks want.

If no fields of the struct match, the implementation returns an error, because this case almost certainly indicates that the user was mistaken about the table schema. At a minimum, it will waste resources by iterating over a table or query and discarding the results.

The last three properties are shared with [gob](https://godoc.org/encoding/gob#hdr-Types_and_Values).

Struct field types and schema types must match exactly. The schema types BOOLEAN, STRING, FLOAT and TIMESTAMP match to bool, string, float64 and time.Time respectively. Repeated columns match to slices of the corresponding type.

The schema type INTEGER maps to int, because the BigQuery client uses strconv.Atoi to convert it. Since INTEGER is a 64-bit value, this is arguably a bug that will result in an error reading large values on 32-bit systems. We should consider parsing to an int64 instead, in which case the mapping would also change to int64.

Nested schemas (fields of type RECORD) are mapped to nested structs, recursively. The corresponding struct field type may be a struct or a pointer to struct; if the latter, the implementation creates a new struct before populating it.

Enforcing strict correspondence of types means that a struct used to infer a schema may not be usable with this feature. For example, calling InferSchema on 
```go
struct {
    Short int16
}
```
returns a schema with an INTEGER column, but the same struct cannot be used as an argument to RowIterator.Next in this design. However, if the user makes the struct implement ValueLoader by writing the appropriate Load method, then it can be passed RowIterator.Next.

The ability to pass a struct to RowIterator.Next is a convenience, and will always be slower than a custom Load method. So I don't think we need to make it round-trip with InferSchema by being  less strict when matching field types. Doing so would complicate the design and could result in run-time errors when column values were too large for their matching field types.

I haven't mentioned anything about struct tags. We could interpret struct tags to give the user more control over the matching process, but I would prefer not to, in order to keep the feature simple.

@pongad @nightlyone @zombiezen @jmuk @broady @rakyll

**Comment by pongad** [comment]
I'm good with the behavior on unmatched fields in struct and schema. Since this behavior matches gob and json's, it sounds like a good idea to keep them consistent.

I also think enforcing strict types and using int64 is OK. Would it be a breaking change if we later want to support sizes though?

Another thing we might want to consider is how to tie-break field name matches. If we have a schema field named (case-insensitive) "name" and two Go fields "Name" and "NAME". Which one do we match? The json package doesn't seem to define this, but it looks like it prefers whichever field gets declared first.

This might enter the realm of I-don't-want-to-think-about-this-anymore: What about anonymous fields? Json package treats them as if the members of embedded structs belong to the outer struct. I can see us just treating it as nested though; the implementation is probably easier as well.

**Comment by mcgreevy** [comment]
Re: embedded fields: please review the discussion on the schema inference cl:  
https://code-review.googlesource.com/#/c/4220/

Embedded field support was dropped from that change due to
(a) some divergence in corner cases between the behaviour of the schema inference code and encoding/json
(b) a desire not to support embedded fields in schema inference if they weren't going to be supported in marhsalling/unmarshalling (i.e. ValueSaver/Loader support for structs).

I think that it's important to be consistent if at all possible in the treatment of embedded fields between ValueLoader/Saver and encoding/json.

**Comment by schmohlio** [comment]
To your point, why not make the inference as simple as possible, and limit it to `encoding/json` types. It's been working really well for our clients, as they send us arbitrary json, and **often not-so-complex domain logic translates to complex types**. Imagine an `order` event with `{"items":[{"sku":123, "price": 22.22}, ...]}`. You need to deal with nested structs. 

Below is a hint (less judicious unit testing) at our implementation of inferring the schema. The ValueSaver implementation becomes very simple, afterwards. Would love to contribute if you guys think this would be useful. We've moved a lot of clients off of redshift and onto BigQuery by using the Streaming API and this sort of JSON schema inference to represent the domain elements in BigQuery Schemas.

```
// authors: Matthew Schmohl <fullstackanalytics.io>
import (
	"cloud.google.com/go/bigquery"
	"errors"
)

var (
	// generic error for any issue inferring schema
	BadInfer      = errors.New("problem inferring schema")
	BadMerge      = errors.New("unable to merge schemas")
	InvalidSchema = errors.New("invalid schema")
)

type SchemaInferError struct {
	msg    []error
	reason string
}

func (e *SchemaInferError) Error() string { return e.reason }

type SchemaInferer interface {
	Infer() (bigquery.Schema, error)

package schemautil

import "cloud.google.com/go/bigquery"
import "strings"

type JsonElem interface{}
type JsonObj map[string]interface{}
type JsonArr []interface{}

// implements SchemaInferer for Json Encodings.
func (o JsonObj) Infer() (s bigquery.Schema, err error) {
	s, err = traverse(o)
	if err != nil {
		return
	}
	// the top-level of a schema must contain at-least one field
	if len(s) == 0 {
		err = BadInfer
	}
	return
}

// builds a forwards compatible bigquery schema.
func traverse(jobj JsonObj) (fields bigquery.Schema, err error) {
	for k, v := range jobj {
		switch v.(type) {
		case nil:
			// do nothing if null.
		default:
			f, ferr := createField(k, v)
			if ferr != nil {
				err = ferr
				return
			}
			if f != nil {
				fields = append(fields, f)
			}
		}
	}
	return
}

// walks through potential inferrable fields within array. the first non-null field is used to merge with subsequent fields.
// if a nested array is found, we short circuit with error. if no non-null fields are found, a nil is returned.
// NOTE: on Go slices: only the underlying array is passed by reference. metadata about the slice is passed by value. :)
func walk(name string, jarr JsonArr) (s *bigquery.FieldSchema, err error) {

	var accum *bigquery.FieldSchema
	var j int
	for _, v := range jarr {

		j++

		if _, ok := v.([]interface{}); ok {
			err = BadInfer
			return
		}

		accum, err = createField(name, v)
		if err != nil {
			return
		}

		if accum != nil {
			break
		}
	}

	if accum == nil {
		s = nil
		return
	}

	for _, v := range jarr[j:] {
		if _, ok := v.([]interface{}); ok {
			err = BadInfer
			return
		}
		next, e := createField(name, v)
		if e != nil {
			err = e
			return
		}
		accum, err = mergeField(accum, next)
		if err != nil {
			return
		}
	}

	s = accum
	s.Repeated = true
	return
}

func createField(nm string, v JsonElem) (fs *bigquery.FieldSchema, err error) {
	if nm == "" {
		err = BadInfer
		return
	}
	name := CleanseName(nm)
	//name := nm
	switch vv := v.(type) {
	case bool:
		fs = &bigquery.FieldSchema{Name: name, Required: false, Type: bigquery.BooleanFieldType}
	case float64:
		fs = &bigquery.FieldSchema{Name: name, Required: false, Type: bigquery.FloatFieldType}
	case string:
		fs = &bigquery.FieldSchema{Name: name, Required: false, Type: bigquery.StringFieldType}
	case []interface{}:
		jarr := JsonArr(vv)
		inner, aerr := walk(name, jarr)
		if aerr != nil {
			err = aerr
			return
		}
		if inner == nil {
			fs = nil
			return
		}
		fs = inner
	case map[string]interface{}:
		jobj := JsonObj(vv)
		inner, jerr := traverse(jobj)
		if jerr != nil {
			err = jerr
			return
		}
		if len(inner) == 0 {
			fs = nil
			return
		}
		fs = &bigquery.FieldSchema{Name: name, Required: false, Type: bigquery.RecordFieldType, Schema: inner}
	case nil:
		fs = nil
	default:
		err = BadInfer
	}
	return
}


// coalesces bigquery schemas, checking for full compatibility.
func merge(this bigquery.Schema, that bigquery.Schema) (bigquery.Schema, error) {

	// convert existing schema to map, keyed by Name, all lower-case.
	m := make(map[string]*bigquery.FieldSchema)
	keys := make([]string, 0, len(this))
	for _, v := range this {
		keys = append(keys, strings.ToLower(v.Name))
		m[v.Name] = v
	}

	// weave new schema through existing, adding new fields where necessary.
	var newFields bigquery.Schema
	newFields = make([]*bigquery.FieldSchema, 0, len(that))
	for _, new := range that {
		old, ok := m[strings.ToLower(new.Name)]
		if ok {
			f, err := mergeField(old, new)
			if err != nil {
				return this, err
			}
			m[new.Name] = f
		} else {
			newFields = append(newFields, new)
		}
	}

	var merged bigquery.Schema
	for _, key := range keys {
		merged = append(merged, m[key])
	}
	merged = append(merged, newFields...)

	return merged, nil
}

func mergeField(this *bigquery.FieldSchema, that *bigquery.FieldSchema) (merged *bigquery.FieldSchema, err error) {

	switch {
	case this == nil && that != nil:
		merged = that
		return
	case that == nil && this != nil:
		merged = this
		return
	case this == nil && that == nil:
		merged = nil
		return
	}

	// only fields with same name can be merged.
	if this.Name != that.Name {
		err = BadMerge
		return
	}

	// can't go from not required to required..
	if this.Required == false && that.Required == true {
		err = BadMerge
		return
	}

	// must both repeat or not repeat.
	if this.Repeated != that.Repeated {
		err = BadMerge
		return
	}

	// must be compatible types
	//if (this.Type != that.Type) && !(this.Type == bigquery.IntegerFieldType && that.Type == bigquery.FloatFieldType) {
	if this.Type != that.Type {
		err = BadMerge
		return
	}

	var nestedSchema bigquery.Schema
	if this.Type == bigquery.RecordFieldType {
		s, e := merge(this.Schema, that.Schema)
		if e != nil {
			err = e
			return
		}
		nestedSchema = s
	}

	merged = &bigquery.FieldSchema{
		Name:        this.Name,
		Description: that.Description,
		Repeated:    that.Repeated,
		Required:    that.Required,
		Type:        that.Type,
		Schema:      nestedSchema}
	return
}
```

**Comment by jba** [comment]
Returning to this after laying some important groundwork.

The current design aims to be as consistent as possible with encoding/json, and with schema inference.

* Which struct field is matched to a schema field? We first look for an exact name match among the exported struct fields (including exported fields of embedded structs). If that fails, we perform a case-insensitive match of the names, taking the lexically first field that matches. (Exactly like encoding/json.)

* What about fields that don't match? It's fine if either the struct or the schema has additional unmatched fields. They are simply ignored. That is true even if there is no overlap between struct and schema fields. (Exactly like encoding/json.)

* What Go types correspond to a schema type? Exactly what schema inference allows. Namely:
   * STRING: `string` 
   * BYTES: `[]byte`
   * BOOL: `bool`
   * FLOAT64: `float32` or `float64`
   * INT64: any integer type except `uint`, `uint64` and `uintptr`
   * TIMESTAMP: `time.Time`
   * TIME: `civil.Time`
   * DATE: `civil.Date`
   * DATETIME: `civil.DateTime`
   * Repeated: a slice or array of a corresponding element type.

  This means that loading can fail for `float32` and the smaller integral types because the value in   the row overflows the field type. We return an error in this case.

* What happens when repeated fields are loaded? Slices are truncated to zero length and then appended to; arrays that are too short get a prefix of the data; arrays that are too long are padded with zero values. (Exactly like encoding/json.)

* How are pointers to arrays, slices and structs handled? Inference should work the same on them as it would if there were no pointer; loading should use existing values if present (following the rules for repeated fields above) and allocate new ones if not.  (Exactly like encoding/json.) This round of work will support loading into struct pointers. A subsequent round will support inference of all three (#442) and loading into slice and array pointers (#443).

https://code-review.googlesource.com/#/c/9175 implements this design.

**Comment by bernardolm** [comment]
> 

@schmohlio hi man, what the function `CleanseName` in your code do? It's not in code.
