### ISSUE TITLE
datastore emulator not creating local_db.bin file

### ISSUE THREAD

**Issue by cyxg** [GoogleCloudPlatform/google-cloud-go#405]
Hello, I'm trying to get the datastore emulator up and running on Ubuntu 16.04, I installed it with no problem, and it seems to be able to start (`gcloud beta emulators datastore start`) with no problem:

```
WARNING: Reusing existing data in [/home/cyxg/.config/gcloud/emulators/datastore].
Executing: /home/cyxg/Code/go/google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host=localhost --port=8309 --store_on_disk=True --consistency=0.9 --allow_remote_shutdown /home/cyxg/.config/gcloud/emulators/datastore
[datastore] Oct 21, 2016 5:10:38 PM com.google.cloud.datastore.emulator.CloudDatastore$FakeDatastoreAction$7 apply
[datastore] INFO: Provided --allow_remote_shutdown to start command which is no longer necessary.
[datastore] Oct 21, 2016 5:10:38 PM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub <init>
[datastore] INFO: Local Datastore initialized:
[datastore] 	Type: High Replication
[datastore] 	Storage: /home/cyxg/.config/gcloud/emulators/datastore/WEB-INF/appengine-generated/local_db.bin
[datastore] Oct 21, 2016 5:10:39 PM io.grpc.internal.ManagedChannelImpl <init>
[datastore] INFO: [ManagedChannelImpl@23fe1d71] Created with target localhost:8309
[datastore] Oct 21, 2016 5:10:40 PM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub load
[datastore] INFO: The backing store, /home/cyxg/.config/gcloud/emulators/datastore/WEB-INF/appengine-generated/local_db.bin, does not exist. It will be created.
[datastore] Oct 21, 2016 5:10:40 PM io.gapi.emulators.netty.NettyUtil applyJava7LongHostnameWorkaround
[datastore] INFO: Applied Java 7 long hostname workaround.
[datastore] API endpoint: http://localhost:8309
[datastore] If you are using a library that supports the DATASTORE_EMULATOR_HOST environment variable, run:
[datastore] 
[datastore]   export DATASTORE_EMULATOR_HOST=localhost:8309
[datastore] 
[datastore] Dev App Server is now running.
[datastore] 
```
But the `.config/gcloud/emulators/datastore/WEB-INF/appengine-generated/` folder does not contain a `local_db.bin`, and when I try to search for it (`find -name "local_db.bin"`) then no result. 
Any ideas what might be wrong?

**Comment by adams-sarah** [comment]
I don't work on the emulator, but it seems to me that the emulator creates the local_db.bin file once you invoke the first write call, and not before. So when you first start up the emulator for the first time, I think it is normal for the local_db.bin file not to exist yet.
Have you tried hitting the emulator with your application? Is it not working as you expected?

**Comment by cyxg** [comment]
Oh thanks! I thought my code was fine (still getting used to golang) so I figured the problem was that the local_db.bin file didn't exist..

After some debuggnig then I can see that the environment variables are not recognized, e.g.
```
addr := os.Getenv("DATASTORE_EMULATOR_HOST")
if addr == "" {
	log.Fatal("DATASTORE_EMULATOR_HOST not set")
}
```

Which is kinda weird because when I run `$ printenv` in the same terminal tab then I can see that `DATASTORE_EMULATOR_HOST=localhost:8128`.. so I guess the problem is that these 5 environment variables are not being recognized:

```
export DATASTORE_DATASET=mydb
export DATASTORE_EMULATOR_HOST_PATH=localhost:8128/datastore
export DATASTORE_HOST=http://localhost:8128
export DATASTORE_EMULATOR_HOST=localhost:8128
export DATASTORE_PROJECT_ID=mydb
```

I'll try to fix this and pray it works, I hope you can wait with closing this issue while I try to fix this :)

**Comment by RadientBrain** [comment]
> Oh thanks! I thought my code was fine (still getting used to golang) so I figured the problem was that the local_db.bin file didn't exist..
> 
> After some debuggnig then I can see that the environment variables are not recognized, e.g.
> 
> ```
> addr := os.Getenv("DATASTORE_EMULATOR_HOST")
> if addr == "" {
>     log.Fatal("DATASTORE_EMULATOR_HOST not set")
> }
> ```
> 
> Which is kinda weird because when I run `$ printenv` in the same terminal tab then I can see that `DATASTORE_EMULATOR_HOST=localhost:8128`.. so I guess the problem is that these 5 environment variables are not being recognized:
> 
> ```
> export DATASTORE_DATASET=mydb
> export DATASTORE_EMULATOR_HOST_PATH=localhost:8128/datastore
> export DATASTORE_HOST=http://localhost:8128
> export DATASTORE_EMULATOR_HOST=localhost:8128
> export DATASTORE_PROJECT_ID=mydb
> ```
> 
> I'll try to fix this and pray it works, I hope you can wait with closing this issue while I try to fix this :)
> 
> Edit: Okay it seems to work now, although I decided to go with the "dirty" route and just set the env variables with `os.Setenv`, thanks again @adams-sarah :)

Yes Setting the env variables using `os.Setenv` resolves the issue for creating `local_db.bin` file
