### ISSUE TITLE
Failed to dial datastore.googleapis.com:443: grpc: the connection is closing; please retry.

### ISSUE THREAD

**Issue by dlsniper** [GoogleCloudPlatform/google-cloud-go#413]
Hello,

I have this little project: https://github.com/gopheracademy/gopher which I've just recently started using Cloud Datastore with.
The problem is that I'll get a bunch of:

```
Failed to dial datastore.googleapis.com:443: grpc: the connection is closing; please retry.
```

from time to time and I have no clue how to mitigate this.

The project is running in GKE.

Please advise, thank you.

**Comment by jba** [comment]
I'm not sure of the exact cause, but I'd recommend creating a single client for the life of your program, instead of creating a new one on each call to processCLList.

**Comment by dlsniper** [comment]
Hi @jba, 

I've tried that as well but with the same problem. 
I'll revert back to that if that's the recommended way to use it. 
Will it at least retry to connect automatically? Do I need to specify any parameters? 

Thank you.

**Comment by jba** [comment]
@dlsniper, you say that when you create a single client for the life of the program (which is recommended, BTW), you get "the same problem". Does that mean you see "failed to dial" messages "from time to time"? That would be surprising, since you're only dialing once.

@broady @bradfitz @zombiezen Do you have any thoughts on what might be causing this?

**Comment by dlsniper** [comment]
@jba yes, that's correct, when using a single client, I would still see the messages from above occasionally. Maybe it's something with the GKE to Cloud Datastore connectivity? I admit I haven't had time to properly investigate this, sorry.

**Comment by zombiezen** [comment]
cc @iamqizhao from gRPC

The recommended way is definitely to have a client connection for the process's lifetime.. my understanding is that gRPC generally handles the retry/reconnect logic.  Once you've done that, more failure logs would certainly help us debug.

**Comment by jba** [comment]
One thing I'd like to understand (I'm fairly ignorant of GKE) is whether the messages you're describing are from one process, or aggregated from all processes running as a pod/service/whatever.

**Comment by dlsniper** [comment]
Hi all,


Thank you so much for helping out on this.
I've updated the application to use a single connection for the lifetime of the application.
I'm getting a different kind of error now, see attached: 
![snapshot181](https://cloud.githubusercontent.com/assets/607868/19872435/8f28794a-9fb1-11e6-888e-b90698ac2eca.png)
The messages are from a pod which contains a single container that has a single binary in it.

Should I try and use a custom http.Client or a custom grpc.Connection / connection options?
Thank you.

**Comment by zombiezen** [comment]
I think you can actually safely ignore these, unless you are seeing application-level failures.  Individual HTTP/2 connections will be dropped over the course of your application, but gRPC will automatically redial AFAIK.

**Comment by dlsniper** [comment]
I'm sorry, it's the first time I'm using Cloud Datastore and I'm not used with messages like that popping up in my logs.
What do you think about adding two extra options for the logging. One to inject a default logger and one to inject a debug logger. The logger should have the signature of the current ` log/fmt - Printf() ` function (I suspect that's what is used now). That way the users have a way to control the logs that appear.
Also, it would be welcomed to document this behavior in the package documentation.

I'd be happy to work on these are they are easy patches but I won't have time until the end of the week at least.

**Comment by zombiezen** [comment]
The message you're seeing is coming from gRPC, not the Cloud libraries.  You can change the logger that gRPC uses with [`grpclog.SetLogger`](https://godoc.org/google.golang.org/grpc/grpclog#SetLogger).

However, for a high-traffic application, it can be useful to know when these events occur, since they may correlate with higher error rates.  Is there a way we can make the error message more useful for you, perhaps?

**Comment by jba** [comment]
Same issue as #293.
