### ISSUE TITLE
Is there a simple way to check to see if a particular bigquery.dataset exists (for a given datasetID)?

### ISSUE THREAD

**Issue by gvelesandro** [GoogleCloudPlatform/google-cloud-go#414]
The current API doesn't offer a simple way see if a dataset with a particular name already exists in a project.  Here is why:

1) `client.Dataset("<datasetID>")` returns a dataset handle regardless of whether the dataset exists or not
2) `bigquery.Dataset` struct doesn't expose the datasetID property, so it's impossible to know what datasetID the reference is referring to. 
3) It's also impossible to iterate over bigquery.Datasets, and check the existence of a particular DatasetID, because the ID of a dataset is not exposed. 

Am I missing something?

**Comment by jba** [comment]
You're not missing anything. Those are both oversights. 

We will expose the Dataset ID and we'll implement a get operation for datasets.

**Comment by gvelesandro** [comment]
Same is true for Tables. There isn't an easy way to check whether a table with a particular name exists within a dataset, or it's merely a reference.

**Comment by jba** [comment]
Call Table.Metadata for that.

**Comment by gvelesandro** [comment]
If the table doesn't exist, calling `Table.Metadata` throws an exception. Are you suggesting to parse  the exception and use it to guide the application logic?

**Comment by jba** [comment]
Yes. Sorry that wasn't clear the first time. Something like this:
```go
if e, ok := err.(*googleapi.Error); ok && e.Code == http.StatusNotFound
```
I'm not sure if it is in fact a 404---unfortunately I have to leave for the day (NYC). But print the error.

http is "net/http" and googleapi is "google.golang.org/api/googleapi".

**Comment by jba** [comment]
We exposed the Dataset fields in bd2cfb7bff891c991d689904e0a33cf1e567485b. Working on Dataset metadata operations.

**Comment by jba** [comment]
Dataset.Metadata added in e4d16e4a0d626800b40739a532ed577104da235b.
