### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by yipjustin** [GoogleCloudPlatform/google-cloud-go#419]
Hello,

I am getting this error since around 4pm PST, Nov 3, 2016.

```
$ go get cloud.google.com/go/datastore
# google.golang.org/genproto/googleapis/datastore/v1
src/google.golang.org/genproto/googleapis/datastore/v1/datastore.pb.go:1013: undefined: grpc.SupportPackageIsVersion3
```

It is blocking all my travis submit since it needs to install dependencies. Is there any workaround for that?

Thanks!

Justin

**Comment by montanaflynn** [comment]
I had the same issue and it was fixed with using `-u`:

```
go get -u cloud.google.com/go/vision
```
