### ISSUE TITLE
bigquery: RowIterator Schema

### ISSUE THREAD

**Issue by josean1966** [GoogleCloudPlatform/google-cloud-go#420]
In earlier version I was using the following code to get the Iterator Schema:

var sch bigquery.Schema
for it.Next(context.Background()) {
	if sch == nil {
		sch, err = it.Schema()
		if err != nil {
			//log.Errorf(ctx, "err calling Schema: %v\n", err)
			return err
		}
		for _, element := range sch {
			fmt.Printf("name: %s  fieldtype: %s \n", element.name, element.type)
		}
	}
}

In the new version, with RowIterator, how can I do this?

I've been looking for info but I didn't find it.

I tried with:
job, err := bqQuery.Run(context.Background())
for {
	var vl bigquery.ValueList
	err := it.Next(&vl)
	fmt.Printf("vals v : %v\n", &vl)
	fmt.Printf("vals s : %s\n", &vl)
	if err == iterator.Done {
		break
	}
	if err != nil {
		fmt.Printf("error : %v", err)
		return
	}
}

I only got values but nothing about Schema.
Any help would be very aperciated.
Thanks in advance.

**Comment by jba** [comment]
You'll need to write your own ValueLoader. Its Load method takes the schema as a second parameter. (It will be passed the same schema for every row.) Your Load method can just call the Load method on a ValueList, so you won't ahve to duplicate that code.

**Comment by josean1966** [comment]
Do you have any small example?
Thanks.

**Comment by albertog** [comment]
will be very useful for me also..

**Comment by juceberipe** [comment]
Also for me.

Thanks.

**Comment by adams-sarah** [comment]
See ValueMap's implementation of Load https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/value.go#L48-L56

**Comment by josean1966** [comment]
Got it!!!!
Thank you very much @adams-sarah @jba .

**Comment by nightlyone** [comment]
Maybe turning this into an example would help.

**Comment by josean1966** [comment]
I did it in this way. 
Any suggestion from contributors/members would be appreciated:

	type valueListWithSchema struct {
		vals   bigquery.ValueList
		schema bigquery.Schema
	}

	func (v *valueListWithSchema) Load(vs []bigquery.Value, s bigquery.Schema) error {
		v.vals.Load(vs, s)
		v.schema = s
		return nil
	}

	func main() {

		...

		// Job result Iterator
		it, err := job.Read(ctx)
		fmt.Printf("error : %v %v\n", err, it)

		for {

			var vls valueListWithSchema

			err := it.Next(&vls)
			if err == iterator.Done {
				return
			}
			if err != nil {
				fmt.Printf("error : %v", err)
				return
			}

			for ord := range vls.schema {
				fmt.Printf("sch name - type: %v - %v\n", vls.schema[ord].Name, vls.schema[ord].Type)
			}


			for ord, val := range vls.vals {
				fmt.Printf("order - value - datatype: %v - %v - %v\n", ord, val, vls.schema[ord].Type)
			}

		}
	}

**Comment by jba** [comment]
That looks fine. (Except you shouldn't enter the loop if job.Read returns an error.)
