### ISSUE TITLE
storage: data-race in cloud storage appengine example

### ISSUE THREAD

**Issue by gregjones** [GoogleCloudPlatform/google-cloud-go#422]
#70 appears to have introduced a data-race on the `bucket` variable. Simultaneous requests to this demo app are unlikely, but as the justification for this (#69) was to avoid promoting bad practices to new developers, it seems a shame to leave it as it is.

**Comment by rakyll** [comment]
The canonical references are at https://github.com/GoogleCloudPlatform/golang-samples/tree/master/docs/managed_vms/storage.

@broady, should we delete these legacy samples under examples/storage?

**Comment by broady** [comment]
Yes, we should. Check that they are not referenced on cloud.google.com anymore. Last I checked, they were.

**Comment by gregjones** [comment]
It's linked to from [here](https://cloud.google.com/appengine/docs/go/googlecloudstorageclient/app-engine-cloud-storage-sample#specifying_the_cloud_storage_bucket)

**Comment by rakyll** [comment]
Ok, just fixing the race then for now.
