### ISSUE TITLE
bigquery: address date partition in Uploader

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/google-cloud-go#427]
While streaming data into a date partitioned table in BigQuery, I need to be able to choose which date for it to go into. `[tableID]$YYYYMMDD` It seems like it would need to be a separate method on Uploader:

`func (u *Uploader) PutIntoDate(ctx context.Context, src interface{}, Date time.Time) error`

**Comment by CaptainCodeman** [comment]
I used the `$yyyymmdd` suffix for the table name and it _seems_ to have worked OK.

**Comment by jba** [comment]
@derekperkins, did using the `$` notation work for you?

**Comment by derekperkins** [comment]
Yes, it did work. It'd be nice to add that to the docs.
