### ISSUE TITLE
bigquery: schema inference of []byte should produce BYTES

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#433]
Currently, a field of type []byte will be inferred as bigquery type STRING. Even in legacy SQL, there is a BYTES type, which seems more appropriate.

This was in the first patch set of https://code-review.googlesource.com/#/c/4220 and doesn't seem to have been questioned. 

@nightlyone @mcgreevy was this a motivated choice, or a mistake (or something else)?

**Comment by nightlyone** [comment]
@jba I believe BYTES wasn't available as a documented field type at the time this has been written. 

Note: There are also 4 different time related field times documented now, which weren't at the time schema inference has been written. So I would handle all this with a struct tag.

**Comment by jba** [comment]
@nightlyone I'm going to fix this before we go beta. []byte will infer as BYTES.

I'll also make time.Time => TIMESTAMP. We're working on the three other time types (see https://code-review.googlesource.com/#/c/9566).

I'm open to tags but not just yet.

**Comment by nightlyone** [comment]
The semantic difference between QL STRING vs. BYTES is a different one than Go string vs. []byte types. So I would suggest adding tags for this case.

**Comment by jba** [comment]
I don't understand -- what is the difference? It seems that STRING is exactly a Go string -- UTF-8 characters -- and BYTES is exactly []byte.

**Comment by nightlyone** [comment]
@jba all APIs that exist for UTF-8 exist for string and []byte so in real programs the difference for a Go programmer is usually just the answer to the question: "Is this range of bytes immutable after creation?" 
if yes -> string, no -> []byte

The assumption that a string always holds Unicode runes encoded as UTF-8 and no zero bytes is simply not true in Go. See https://blog.golang.org/strings for a deeper explanation.

**Comment by jba** [comment]
> all APIs that exist for UTF-8 exist for string and []byte

That's not exactly true&mdash;for-range behaves differently for strings&mdash;but I see your point.

> so in real programs the difference for a Go programmer is usually just the answer to the question: "Is this range of bytes immutable after creation?"

That's one consideration, but "is this text or binary?" also matters a lot.

In any case, your argument would suggest that both string and []byte map to BYTES, not STRING, which I think would be quite unexpected.
