### ISSUE TITLE
Upgrade strategy?

### ISSUE THREAD

**Issue by blixt** [GoogleCloudPlatform/google-cloud-go#434]
Go doesn't come with a package manager and so (unfortunately) by default it puts the responsibility on the library manager to ensure clean builds of a codebase don't break even if the codebase was not touched.

In the case of `cloud.google.com/go/datastore`, I've had it break a few times due to changes that would normally be considered major version updates (most recently `datastore.NewKey` -> `datastore.{ID,Name}Key`).

Have you guys considered an upgrade strategy for dependents? For example, having an import path that exposes a frozen API (e.g., `import "cloud.google.com/go/datastore.v1"`), so that the dependent may upgrade to the new API version on their own accord.

As it stands today, we have to fork your repo to freeze the API for our builds.

**Comment by jba** [comment]
This is a well-known problem. We've tried to mitigate it in a couple of ways:

* We set up the [google-api-go-announce](https://groups.google.com/forum/#!forum/google-api-go-announce) mailing list, designed specifically to inform users of these libraries of breaking changes. (Please subscribe!)
* We point to the announcements on the [google-cloud slack channel](https://gophers.slack.com/messages/google-cloud).
* When possible, we keep both old and new versions of the package surface for a while, to make it easy to convert.
* We tag the repo just _before_ each breaking change, to make vendoring easier.

In your case, the datastore change was [announced](https://groups.google.com/forum/#!topic/google-api-go-announce/hqXtM_4Ix-0) on Nov 1, with a detailed list of changes, a link to vendoring tools, and the name of the tag to vendor at. The actual breaking commit happened a week later.

We talked at one point about adding version numbers to the import paths, but rejected it. That's not the way the Go ecosystem is going. But the good news is that a working group is designing a package management tool with the support of the Go team. Hopefully that will resolve these sorts of problems.

More good news: five of these clients (datastore, logging, bigquery, pubsub and storage) are going beta soon, which means we're pretty confident about their APIs. They're not going to change much after that.
