### ISSUE TITLE
bigquery: should Load truncate or append?

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#437]
When reading rows into a []Value, the current behavior appends to the slice:

```
vals := []Value{1}
... it.Next(&vals) ... // assume one column with value 2
fmt.Println(vals) // output: [1 2]
```
Reading into a map has the same property: new keys will be added or overwritten, but existing keys will remain.

I'd argue that we should be consistent with [encoding/json.Unmarshal](https://godoc.org/encoding/json#Unmarshal):
> To unmarshal a JSON array into a slice, Unmarshal resets the slice length to zero and then appends each element to the slice.

That would be a change to our current behavior.

> To unmarshal a JSON object into a map, Unmarshal first establishes a map to use. If the map is nil, Unmarshal allocates a new map. Otherwise Unmarshal reuses the existing map, keeping existing entries.

That is our current behavior.

So I'd vote for changing client's behavior on slices. Are there compelling reasons for the append semantics?

/cc @mcgreevy @nightlyone @zombiezen @broady @pongad

**Comment by nightlyone** [comment]
@jba I agree with your reasoning here and would support the changes regarding slices. The current behaviour leads to errors while iterating.

**Comment by pongad** [comment]
I support this change. +1 for making it consistent with json!
