### ISSUE TITLE
Pubsub client Pull keeping track of subscriptions

### ISSUE THREAD

**Issue by andyhaskell** [GoogleCloudPlatform/google-cloud-go#438]
I noticed that for pubsub pull subscriptions, `getSubscriptionConfig`, which is called by `Subscription.Pull`, calls `SubscriberClient.GetSubscription`.

As far as I know, this results in a `Get` operation on pubsub, which is one of the administrative operations. Since the [max quota](https://cloud.google.com/pubsub/quotas) for administrative operations is relatively low compared to the other quotas, this seems inefficient to do a `Get` operation on every call to `Pull`, especially if these pull calls are to the same pubsub subscription. I think what could be more efficient is if a pubsub `Client` stores the configurations of subscriptions it has recently `Pull`ed from so that it can limit the number of `Get` operations it calls.

**Comment by jba** [comment]
Calls to Pull should be relatively infrequent. The typical subscriber will start pulling early in its lifetime and will iterate over the pulled messages indefinitely. 

If we cache the config, we may miss updates to AckDeadline.

I think we should leave this as it is until we actually encounter a problem.

**Comment by jba** [comment]
We're addressing this in the Go client by removing the dependence on the subscription's ack deadline.

**Comment by jba** [comment]
The streaming pull implementation we now use should make this a non-issue. Reopen if it's still a problem.

**Comment by pongad** [comment]
@jba I think we're still doing it right? https://github.com/GoogleCloudPlatform/google-cloud-go/blob/5f94087a825c463c8ee36fde5f05aadbc23234d4/pubsub/subscription.go#L295

I created distribution pkg for deadline adjustment but we actually need to use it.

**Comment by jba** [comment]
Oh, I was confused. This issue is about quota. Since both Pull and Receive calls are rare, it shouldn't matter. 

I'm not sure why I reopened this on Oct. 23. Maybe because it's the closest to what you're trying to do with distribution. But since is not an outstanding problem right now, let's leave it closed.
