### ISSUE TITLE
go get version inaccurate

### ISSUE THREAD

**Issue by Spikey123** [GoogleCloudPlatform/google-cloud-go#440]
Hello. I ran into a problem and just wanted to share it for a fix or enlighten myself in case I'm doing something wrong.
http://stackoverflow.com/questions/40915315/google-cloud-bigquery-undefined-valuelist/40917067#40917067

Using go1.6.3 (not sure this makes a difference) when I run "go get cloud.google.com/go/bigquery" I get a version of the code that has an un-exported valueList type. My understanding is that running the go get command fetches the latest version from the repo but the latest version in here appears to have ValueList exported, as expected. Anyone know if this is a valid issue and can reproduce?

Thanks.

**Comment by jba** [comment]
You're doing everything right. This one's on us.

We develop, and serve "go get", from https://code.googlesource.com/gocloud. That's the source of truth for the code. We mirror to this repo, but we don't have that process as automated as it should be. (It's in the works.)

I just did a mirror, so you'll find that now the repos agree. 

By the way, are you subscribed to [the announcement mailing list](https://groups.google.com/forum/#!forum/google-api-go-announce)? We'll announce breaking changes there when or before they happen.

**Comment by Spikey123** [comment]
I just subscribed to the mailing list.

Thank you for the explanation!
