### ISSUE TITLE
datastore: proper handling of unexported anonymous struct fields

### ISSUE THREAD

**Issue by adams-sarah** [GoogleCloudPlatform/google-cloud-go#441]
Given that bigquery will soon be encoding/decoding data into user structs (https://github.com/GoogleCloudPlatform/google-cloud-go/issues/238) with proper handling of unexported anonymous struct fields, eg:

```go
type A struct {
	b
}

type b struct {
	C string
}

myA := A{b: b{C: "hello"}}
```

will (and should) be marshaled like:

```
{"C":"hello"}
```

then we should now fix the datastore package, which currently marshals the above as:

```
{}
```

even though this will change the behavior for users. We should be consistent with bigquery, and we should fix this broken behavior before it's too late.

@zombiezen @jba thoughts?

**Comment by zombiezen** [comment]
+0.5, especially if we can leverage the new fields package.

**Comment by jba** [comment]
I think it would be great if you fixed this. Very soon. Should be easy with the fields package.
