### ISSUE TITLE
bigquery: support struct field loading into pointers to slices and arrays 

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#443]
This will match encoding/json.

See #399 and  #442.

**Comment by adams-sarah** [comment]
We should do this for datastore too then.

**Comment by jba** [comment]
encoding/json will actually do much more than fill in pointers to slices and arrays; it will handle pointers to anything. It will happily unmarshal into the following struct, allocating as necessary:
```
type S struct {
    X **int
    Y *[]int
    Z *[3]int
    W *SomeStruct
}
```
With the exception of pointers to structs, I don't think any of these adds significant value. But they do add significant complexity to the implementation.

So I suggest not implementing this (that is, pointers to slices and arrays), at least until there is a clear need.

@adams-sarah @zombiezen @pongad @mcgreevy

**Comment by adams-sarah** [comment]
I agree, I don't see a use case for *[]int, and I think the use case for *[3]int is very uncommon. So I think we should hold off on those two.

I do think we should allow pointers to structs as struct fields.
One big use case for this is with the omitempty feature. Even if omitempty is never implemented in bigquery, allowing pointers to structs eliminates the need for something like:
```go
type B struct {}
type A struct {
    X  B `json:"-"`
    Y *B `datastore:"-" bigquery:"-" json:"X,omitempty"`
}
```

And I think we should mirror this behavior in datastore (https://github.com/GoogleCloudPlatform/google-cloud-go/issues/446)

Finally, if we allow pointers to structs, I think it would be odd for us not to allow pointers to basic types (is this already implemented in bigquery?).

**Comment by jba** [comment]
> I do think we should allow pointers to structs as struct fields.

Agreed. They are very common.


> Finally, if we allow pointers to structs, I think it would be odd for us not to allow pointers to basic types (is this already implemented in bigquery?).

Bigquery does support pointers to structs. I don't see why that implies pointers to basic types, any more than pointers to arrays and slices. The only common case is struct pointers.
