### ISSUE TITLE
transport: with option.WithHTTPClient, hitting "unsupported HTTP client specified" error

### ISSUE THREAD

**Issue by mpl** [GoogleCloudPlatform/google-cloud-go#445]
Hi,

To setup a logging client with the V1 API, we used to do:

	serviceAccountFile := "/home/joe/foo.json"
	jsonSlurp, err := ioutil.ReadFile(serviceAccountFile)
	if err != nil {
		return fmt.Errorf("error reading service account file: %v", err)
	}
	jwtConf, err := google.JWTConfigFromJSON(jsonSlurp, logging.Scope)
	if err != nil {
		return err
	}
	logc, err := logging.NewClient(context.Background(), "someProjectId", "someLogName", option.WithHTTPClient(jwtConf.Client(context.Background())))
	if err != nil {
		return fmt.Errorf("error creating logging client: %v", err)
	}

which, migrated to the V2 logging API, becomes:

	serviceAccountFile := "/home/joe/foo.json"
	jsonSlurp, err := ioutil.ReadFile(serviceAccountFile)
	if err != nil {
		return fmt.Errorf("error reading service account file: %v", err)
	}
	jwtConf, err := google.JWTConfigFromJSON(jsonSlurp, logging.WriteScope)
	if err != nil {
		return err
	}
	logc, err := logging.NewClient(context.Background(), "someProjectId", option.WithHTTPClient(jwtConf.Client(context.Background())))
	if err != nil {
		return fmt.Errorf("error creating logging client: %v", err)
	}

and that now errors as:
	
	error creating logging client: unsupported HTTP client specified

which I tracked down to google.golang.org/api/transport/dial.go, in DialGRPC. So that hinted to me that I could now do instead:

	logc, err := logging.NewClient(context.Background(), "someProjectId", option.WithServiceAccountFile(serviceAccountFile))

And that seems to be working out for my use case.

But it seems that the version where I provide the http client should still work, shouldn't it? Or if not, what's the point in being able to provide the http client to logging.NewClient?

Regards,
Mathieu

**Comment by mpl** [comment]
Cc: @bradfitz

**Comment by jba** [comment]
As you found out, the new logging client is on gRPC, and you can't pass an HTTPClient. True, gRPC runs over HTTP(2), but that's at level below where we (as gRPC users) can operate. gRPC wants us to use its own kind of connections.

The fact that that's a runtime error and not a compile-time one is a tradeoff in how complex we want to make client options. Now there is one type for all of them (option.ClientOption). And almost all of them can be used for both HTTP and gRPC clients. Instead of duplicating options or doing something complicated with interfaces, we just kept it to the one type.

**Comment by mpl** [comment]
Right, thanks.
I've only understood that a few minutes ago when rereading the doc, which clearly states, "This option may only be used with services that support HTTP as their communication transport.", and connected the dots that gRPC might be what logging uses.

The client options tradeoff is fair enough, but I'm not sure the connection between the error message and the fact that logging does not use net/http at all is obvious enough. It wasn't to me at least.

(But the issue is fixed as far as I'm concerned since I now understand what's going on).
