### ISSUE TITLE
Speech API Example

### ISSUE THREAD

**Issue by chanwit** [GoogleCloudPlatform/google-cloud-go#447]
Hello

I'm looking for a working example of the Speech API (Streaming via gRPC).
Where could I find one?

Thank you

**Comment by broady** [comment]
A few here:
https://github.com/GoogleCloudPlatform/golang-samples/tree/master/speech

They're linked from the docs, but not embedded (yet), like for most other APIs in this library.

**Comment by chanwit** [comment]
Thank you for super quick reply, @broady !!
May I ask a bit more on how could I authen this service with `credential.json`?

In a Java example, I can do so via `GOOGLE_APPLICATION_CREDENTIALS`.

**Comment by broady** [comment]
Same thing. Use application default credentials:
https://developers.google.com/identity/protocols/application-default-credentials

You can also use the `WithServiceAccountFile` option if you don't want to set environment variables.
https://godoc.org/google.golang.org/api/option#WithServiceAccountFile

**Comment by chanwit** [comment]
Thank you, @broady.
This is awesome!!

**Comment by broady** [comment]
Let me know how you go. Any feedback on documentation and your experience getting started would be much appreciated!

**Comment by ssenthil416** [comment]
@broady 

I tried to build only livecaption.go alone
but I got this error

go run livecaption.go
# google.golang.org/genproto/googleapis/api/annotations
../../google.golang.org/genproto/googleapis/api/annotations/annotations.pb.go:41: unknown proto.ExtensionDesc field 'Filename' in struct literal

**Comment by broady** [comment]
@ssenthil416 run this:

`go get -u google.golang.org/genproto/googleapis/api/annotations`

**Comment by ssenthil416** [comment]
Yes after update it got fixed

**Comment by chanwit** [comment]
@broady I'm going to try this on a pre-production environment.
Any recommendation to specific commits known to be stable?

**Comment by broady** [comment]
@chanwit HEAD is fine, you can also use the v0.6.0 tag from this repo, but the dependent packages are more likely to cause discernible changes in behavior (mostly gRPC).

**Comment by darkzbaron** [comment]
hey, there. I know it is an old thread but im using this code : [https://github.com/GoogleCloudPlatform/golang-samples/blob/master/speech/livecaption/livecaption.go](url)
 but this does not seem to produce anything, it returns 
```
Could not recognize: code:11 message:"Exceeded maximum allowed stream duration of 65 seconds."
```

It looks like im not getting any input from the mic. Any help would be very much appreciated.

Thanks,Jonathan
