### ISSUE TITLE
storage: ability to set request Accept-Encoding header to disable transcoding

### ISSUE THREAD

**Issue by krolaw** [GoogleCloudPlatform/google-cloud-go#449]
As per: https://cloud.google.com/storage/docs/transcoding

I would like to set the read request header:
Accept-Encoding: gzip
To prevent transcoding for reads from the appengine, but leave transcoding for other clients intact.

The former being more important, I'll be setting the writer's metadata field cache-control: no-transform, which prevents transcoding from all requests.

**Comment by ernsheong** [comment]
Submitted CL to https://code-review.googlesource.com/18430
