### ISSUE TITLE
Update ReadMe to reflect quality levels of client libraries

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-go#450]
We will soon have client libraries at different quality levels. Let's make sure we reflect this information in our top-level ReadMe file the moment we cut the new release.

The update for [PHP's ReadMe](https://github.com/omaray/google-cloud-php/blob/readme-update-beta/README.md) has already be done (as a [Pull Request](https://github.com/GoogleCloudPlatform/google-cloud-php/pull/274) for now) and can be used as a good example we can follow.

Go seems to have its own thing going on in the ReadMe. I would suggest looking at the PHP example to see what could be ported over. I would list at least the following:

- [x] Update the Supported APIs to show what is truly Beta and what is not

- [x] Is Experimental the same as Alpha? Should we change the wording? If Experimental is expected in Go then that's fine too.

- [x] Perhaps we can move the "News" section elsewhere? Seems like it should go in the "releases" part of the repo. But maybe with Go that's not possible? Or at least reduce the size of the section perhaps?

**Comment by jba** [comment]
First checkbox is done in https://code-review.googlesource.com/9750.

Experimental has no special meaning in Go; we can use Alpha if you prefer. Just let me know.

I shortened the news section (https://code-review.googlesource.com/#/c/9751). But I will be putting an announcement about beta at the top of news, so everyone will see it first.

**Comment by omaray** [comment]
Thanks Jonathan. Yes, if Experimental has no special meaning then let's call it Alpha. This way it will be consistent with the other language libraries.

**Comment by omaray** [comment]
Also, can we add somewhere a description for what Beta and Alpha means? In the PHP example you'll see that we have a Versioning section that explains Beta/Alpha towards the end: https://github.com/omaray/google-cloud-php/blob/readme-update-beta/README.md

Can we do something similar in Go? I guess people might wonder what alpha/beta means.
