### ISSUE TITLE
pubsub: the maxPayload size used in splitAckIDs is larger than allowed by gRPC. 

### ISSUE THREAD

**Issue by epsniff** [GoogleCloudPlatform/google-cloud-go#452]
After upgrading our pubsub client from the http based client to the gRPC client we noticed a huge drop in our ack rate for high volume subscriptions.   But at the same time our pull rate and processing rates remained the same. 

By adding error logging to [acker.go](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/acker.go#L147), I discovered these consumers were dropping all of the acks with this error.
```
2016/12/07 22:14:41.421964 acker.go:162: ack dropping 6151 msgs: error:rpc error: code = 3 desc = Request payload size exceeds the limit: 524288 bytes.
```

After lowering the [maxPayload](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/service.go#L223) const to be 512k, the errors stopped and my ack rate returned to normal.
```
maxPayload       = 1 * 1024 * 1024
```
Should be:
```
maxPayload       = 512 * 1024
```

**Comment by jba** [comment]
Thanks for the report, CL practically wrote itself.

https://code-review.googlesource.com/#/c/9758

**Comment by epsniff** [comment]
thanks for fixing it so fast.
