### ISSUE TITLE
pubsub: Message ack ID currently inaccessible

### ISSUE THREAD

**Issue by AndyHaskell** [GoogleCloudPlatform/google-cloud-go#454]
Currently through the pubsub client, `Message.ackID` is a [lowercase field](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/message.go#L38-L39) on a pubsub message. As a result, this leaves methods in the underlying [apiv1 API](cloud.google.com/go/pubsub) that require a message's `AckID`, such as `ModifyAckDeadline`, inaccessible. `ModifyAckDeadline` is especially important for being able to quickly retry processing pubsub messages, which is currently referenced in [this TODO](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/iterator.go#L157-L159).

I would like to make a feature request for AckID to be accessible through an exported field or method, which would make this pubsub API `ModifyAckDeadline` functionality accessible.

**Comment by jba** [comment]
We'd rather expose the functionality you want in cloud.google.com/go/pubsub, so you don't have to use the underlying client at all. Is it just the NACK behavior referenced in that TODO, or are there other things you'd like to do with ModifyAckDeadline?

**Comment by AndyHaskell** [comment]
@jba right now the behavior I'm interested in is just the NACK behavior.

**Comment by jba** [comment]
@AndyHaskell FYI the fix will nack quickly on Message.Done(false), but not instantaneously. The delay is hardcoded. Let me know if the performance doesn't meet your requirements.

**Comment by lc-chrisbarton** [comment]
We would like to log the ackID so we can use it with the gcloud commandline tools to directly ack/nack messages that appear in our error logs
