### ISSUE TITLE
Docs: "Go" doesn't appear in the dropdown for Python/PHP/.NET

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-go#455]
STEPS

- Open the client lib reference landing page for [Python](https://googlecloudplatform.github.io/google-cloud-python/)
- Select the drop-down as shown below

EXPECTED RESULT
- "Go" should show up as one of the languages

ACTUAL RESULT
- "Go" doesn't appear
- Same issue when are on the landing page of PHP and .NET

/cc @jskeet @dhermes @jdpedrie

![image](https://cloud.githubusercontent.com/assets/6609430/21040622/f8efa7c0-bd9a-11e6-9655-2af65baa863e.png)

**Comment by jskeet** [comment]
Filed https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/636 to cover .NET. Will address this today.

**Comment by jba** [comment]
I think those sites just need to be regenerated.

**Comment by rakyll** [comment]
Closing this. Go appears everywhere now.
