### ISSUE TITLE
Wrong status in resumable upload

### ISSUE THREAD

**Issue by nnvn** [GoogleCloudPlatform/google-cloud-go#457]
while doing resumable uploads, I'm getting **308 Permanent Redirect**. 308 is **Resume incomplete** as per [the docs](https://cloud.google.com/storage/docs/xml-api/reference-status)

*Don't know where to post this(noob)*

**Comment by bradfitz** [comment]
Not enough info.

308 has two independent meanings. GCS used it to mean "Resume incomplete" before it was formalized as "308 Permanent Redirect" elsewhere.

What is your code and what are you doing?

The Go libraries should be correctly handling it.

Closing for now, until there's something actionable to do. Feel free to reopen with more details.
