### ISSUE TITLE
Doc link on PushConfig gives 404

### ISSUE THREAD

**Issue by dogben** [GoogleCloudPlatform/google-cloud-go#458]
In the documentation for PushConfig.Attributes:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/c54037b480cdda2c7f7600acdd5e506001f04eec/pubsub/subscription.go#L92

the link https://cloud.google.com/pubsub/reference/rest/v1/projects.subscriptions#PushConfig.FIELDS.attributes results in 404 Not Found.

Probably should be updated to https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions#pushconfig

**Comment by rakyll** [comment]
@ajessup, want to open a CL to fix this? Otherwise, I am going to do it.

**Comment by ajessup** [comment]
Hey Jaana - would you mind doing it? I don't have easy access right now.

**Comment by rakyll** [comment]
Sure, mailed https://code-review.googlesource.com/#/c/10052/.
