### ISSUE TITLE
pubsub: not acknowledged well

### ISSUE THREAD

**Issue by junghoahnsc** [GoogleCloudPlatform/google-cloud-go#459]
Hello,

I'm trying to pull messages in one goroutine and distribute the pulled messages to number of workers through a channel. Each worker receives messages from a channel, processes, and then acknowledges it in for loop. Although each worker acknowledges a message within 50ms, messages do not seem to be acknowledged well. The stackdriver shows the number of undelivered messages are increasing although the job is pulling much faster than incoming messages.

I searched the source codes and found that 
```
// newPuller constructs a new puller.
// batchSize is the maximum number of messages to fetch at once.
// No more than batchSize messages will be outstanding at any time.
func newPuller(...)
```

The default batch size looks like 100 (max prefetch size), but the number of workers in my job is 512. Is this the reason why messages are not acknowledged well?

I tried to set the prefetch size same as the number of workers, but it didn't fix the issue.
But when I use one worker which means pulled messages are acknowledge sequently, it works.
Should I acknowledge each pulled message before calling MessageIterator.Next()?
But `acker` doesn't seem to require that, but I'm not sure.

Thanks

**Comment by junghoahnsc** [comment]
I'm not sure whether this is related to https://github.com/GoogleCloudPlatform/google-cloud-go/issues/452.
After I used this fix, it looks like working even when I used more workers than max prefetch size.

**Comment by rakyll** [comment]
Looks like they might be related. Should we close this issue and you reopen it again if you ever come across to it?

**Comment by jba** [comment]
@junghoahnsc let me be clear: when you use the version of pubsub at head (go get -u), your problem goes away?

**Comment by junghoahnsc** [comment]
Yes, I'm using commit 9d965e63e8cceb1b5d7977a202f0fcb8866d6525 and this issue seems to be fixed.
