### ISSUE TITLE
datastore: connection often fails and does not recover

### ISSUE THREAD

**Issue by Bogdanp** [GoogleCloudPlatform/google-cloud-go#462]
Our internal Datastore backup process relies on this library to query a large number of Datastore entities and save them to disk. The issue is oftentimes the underlying Datastore connection fails which our code tries to accommodate by retrying with exponential backoff, but it seems as though the connection never recovers whenever this happens. Here's a snippet from our logs during one of these issues:

```
07:53:58 time="2016-12-13T13:53:58Z" level=warning msg="error querying namespaces: rpc error: code = 14 desc = grpc: the connection is unavailable. Retrying with backoff in %!f(time.Duration=125)..." 
07:53:58 2016/12/13 13:53:58 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: EOF"; Reconnecting to {datastore.googleapis.com:443 <nil>}
07:53:58 time="2016-12-13T13:53:58Z" level=warning msg="error querying namespaces: rpc error: code = 14 desc = grpc: the connection is unavailable. Retrying with backoff in %!f(time.Duration=250)..." 
07:53:59 time="2016-12-13T13:53:59Z" level=warning msg="error querying namespaces: rpc error: code = 14 desc = grpc: the connection is unavailable. Retrying with backoff in %!f(time.Duration=500)..." 
07:53:59 time="2016-12-13T13:53:59Z" level=warning msg="error querying namespaces: rpc error: code = 14 desc = grpc: the connection is unavailable. Retrying with backoff in %!f(time.Duration=1000)..." 
07:54:00 time="2016-12-13T13:54:00Z" level=warning msg="error querying namespaces: rpc error: code = 14 desc = grpc: the connection is unavailable. Retrying with backoff in %!f(time.Duration=2000)..." 
07:54:02 time="2016-12-13T13:54:02Z" level=warning msg="error querying namespaces: rpc error: code = 14 desc = grpc: the connection is unavailable. Retrying with backoff in %!f(time.Duration=2000)..." 
07:54:04 time="2016-12-13T13:54:04Z" level=warning msg="error querying namespaces: rpc error: code = 14 desc = grpc: the connection is unavailable. Retrying with backoff in %!f(time.Duration=2000)..." 
```

Here is a snippet from the code that runs this query:

```go
	ctx := context.Background()
	ds, err := datastore.NewClient(ctx, opts.Project)
	assertWithMessage(err, "cannot construct new datastore client")
	defer ds.Close()

	jobs := make(chan backupJob, opts.Concurrency*opts.BacklogFactor)
	results := make(chan string, opts.Concurrency*opts.BacklogFactor*100)
	for i := 0; i < opts.Concurrency; i++ {
		go backupWorker(ctx, ds, opts, jobs, results)
	}

	jobCount := 0
	retries := 0
	q := datastore.NewQuery("__namespace__").KeysOnly()
	for it := ds.Run(ctx, q); ; {
		k, err := it.Next(nil)
		if err == iterator.Done {
			break
		} else if err != nil && retries < maxRetries {
			retries = backoff(retries, "error querying namespaces: %s", err.Error())
			continue
		} else if err != nil {
			assertWithMessage(err, "error querying namespaces")
		} else {
			retries = 0
		}
```

This issue pops up frequently so I would appreciate some advice on how to deal with it.

This only started happening when we switched from `google.golang.org/cloud/datastore` at `426f71cccabdf34d0fd67fc49e25038c8f49a0bb` to recent versions of this library (currently `v0.6.0-7-g310a9a2`).

**Comment by jba** [comment]
A couple of things I noticed:

Your backoff durations are in the nanoseconds. I think your backoff function assumes they are in milliseconds. To work with durations, multiply by a unit, like 125 * time.Millisecond. You should also use %s to print a time.Duration.

The import path you provided is obsolete. You should be using cloud.google.go/go/datastore. Please go get the most recent version.

Let's see if those changes help.

**Comment by Bogdanp** [comment]
The durations are in milliseconds and the backoff function is working correctly (except, as you point out, the duration logging is wrong) as you can tell by the log timestamps.

The backoff function:

```go
func backoff(attempts int, message string, fmts ...interface{}) int {
	period := time.Duration(math.Min(125 * math.Pow(2, float64(attempts)), 2000))
	fmts = append(fmts, period)
	logrus.Warningf(message + ". Retrying with backoff in %0.2f...", fmts...)
	time.Sleep(period * time.Millisecond)
	return attempts + 1
}
```

> The import path you provided is obsolete.

We are using the latest version of `cloud.google.go/go/datastore`.

**Comment by adams-sarah** [comment]
I suspect this may actually be an issue with google.golang.org/grcp; a lot has changed around how/when we call resetTransport (the func which is producing your second log line, "grpc: addrConn.resetTransport failed to create client transport...") since the date of the commit sha you provided for the cloud datastore package (426f71cccabdf34d0fd67fc49e25038c8f49a0bb), early May.
I assume you updated the two packages together?

@jba @zombiezen do you know anyone working on the grpc package who we could ping?

In the meantime, @Bogdanp can you give an order of how many entries you are querying for, how many you get before the connection fails, and how much time passes between first entry received and connection failing?

**Comment by mnadel** [comment]
Thanks, @adams-sarah. I'm working w/ @Bogdanp on this issue.

We're using v1.0.5 (https://github.com/grpc/grpc-go/commit/708a7f9f3283aa2d4f6132d287d78683babe55c8), which appears to be the most recent release tag.

We're iterating over ~ 150k entries when this error occurs. We'll add some metrics in order to capture data so that we can answer your other questions.

**Comment by zombiezen** [comment]
@iamqizhao, any ideas about this behavior?  As best as I can tell, this is just making RPCs over an unreliable connection.

@Bogdanp You shouldn't implement retry/backoff in your application; gRPC handles this for you.  By the time that gRPC gives you back an error, it has already done this for you, and could be causing rate-limiting issues.

**Comment by mnadel** [comment]
Thanks @zombiezen, but it's essentially unusable w/o our client-side retries. Also -- it's running on a CGE instance :)

**Comment by zombiezen** [comment]
Acknowledged. It does seem like there may be a client library or gRPC issue here.  I still can't rule out network, but it does seem less likely. :)

Once the underlying issue has been fixed, your client-side retry mechanism will be layering on top of gRPC's client-side retry mechanism, which can cause production failures along with making your code more complex.  If a bunch of your jobs drop connection to Datastore simultaneously (network failure or machine migration), then your higher-level retry will cause spikes in traffic to Datastore, which might cause Datastore to rate-limit your incoming connections.  This results in your service falling over or a high increase in latency.

**Comment by mnadel** [comment]
Roger that, thanks. Makes sense; we'll be sure to revert client-side retry once the underlying issue is resolved.

**Comment by iamqizhao** [comment]
grpc will automatically reconnect when seeing a network error so that the application should not do reconnecting by itself. You (or datastore client lib) do need to set the rpc to non-fail-fast via grpc.FailFast(false) call option to your rpcs so that grpc will retry these rpcs when it sees a network error.

**Comment by Bogdanp** [comment]
Thanks @iamqizhao! It does not look like we can pass our own `CallOption`s through to the RPCs via the client library and grepping for `FailFast` in this repo does not yield any results. I'd prefer it if the client library passed the parameter down itself but would be happy even if it just exposed a way for users to do it.

**Comment by zombiezen** [comment]
@iamqizhao Would it make sense to introduce a DefaultCallOption dial option to gRPC?  If that is added, we could ensure that gets added in this repository.

**Comment by jba** [comment]
@zombiezen That may be too coarse-grained. A client might not want all its RPCs to retry.

@iamqizhao The [relevant doc](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md) explains the semantics but doesn't talk about the tradeoffs or best practices. Why wouldn't everyone want to retry on transient errors? Why is the default value true?

**Comment by iamqizhao** [comment]
I am probably not the right person to defense this decision. To be honest, I ever tried to argue that the default value should be non-failfast but it did not get through (and you can see what value I used when I worked on it :-).

**Comment by mnadel** [comment]
Thanks everyone. (Agreed, @iamqizhao; failing fast as the default behavior for this is not intuitive.) With everyone's input here we've made this change, and it's yet to fail:

 ```
 -	ds, err := datastore.NewClient(ctx, opts.Project)
 +	ds, err := datastore.NewClient(
 +		ctx,
 +		opts.Project,
 +		option.WithGRPCDialOption(grpc.WithBackoffMaxDelay(5*time.Second)),
 +		option.WithGRPCDialOption(grpc.WithBlock()),
 +		option.WithGRPCDialOption(grpc.WithTimeout(30*time.Second)),
 +	)
```

**Comment by adams-sarah** [comment]
Closing for now. Feel free to reopen if issue persists.
