### ISSUE TITLE
logging: Do not set HttpRequest.Latency if Entry.HTTPRequest.Latency is 0

### ISSUE THREAD

**Issue by justinruggles** [GoogleCloudPlatform/google-cloud-go#463]
A latency of 0 ns doesn't make any sense, but the current logging package adds the field unconditionally if the HTTPRequest is present. Other fields where a 0 value doesn't make sense are omitted from the stackdriver log.

**Comment by rakyll** [comment]
Closed via https://github.com/GoogleCloudPlatform/google-cloud-go/commit/1a6ade992dec11be6d95ecb707336154711c4723.

**Comment by justinruggles** [comment]
Why was this ticket closed? It has nothing to do with the referenced commit.

**Comment by jba** [comment]
Closed via 78759a61330946eb0d8f57eb6f88a7c7d6574912.

**Comment by justinruggles** [comment]
Thanks!

**Comment by rakyll** [comment]
(Edited the wrong hash.)
