### ISSUE TITLE
Branding updates required for Translate API client libraries

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-go#464]
On November 15, 2016, Google launch a rebranding of Google Translate API to Google Cloud Translation API. This does not impact the method names but the URLbase as well as readmes, samples and comments.

URLbase has been already updated to translation.googleapis.com

We need to have update the Client library, the readme, client library docs, samples and code comments to use "Google Cloud Translation API" instead of Google Translate API. The short version of the new name is "Cloud Translation API" or "Translation API"

Note: the product Google Translate still exists. It is the API Google Translate API that has been re-branded.

**Comment by jba** [comment]
I think we should also update the import path, to cloud.google.com/go/translation.

Agreed, @zombiezen @broady?

**Comment by rakyll** [comment]
I think we should keep the import path compatible with the auto-generated clients. Auto-generated clients still uses "translate" name: https://godoc.org/google.golang.org/api/translate/v2

**Comment by broady** [comment]
sounds like it'll move to `.../api/translation/v2`, so let's change this one too.

good spot, @rakyll

**Comment by zombiezen** [comment]
Sigh, if only we had type aliases to soft-move packages.

**Comment by jba** [comment]
@pongad are we going to move the generated client to `translation`? I think we should.

**Comment by pongad** [comment]
Are we waiting for @omaray to OK this? I'm good with the change though. I assume we're also changing the package decl to `package translation`?

**Comment by omaray** [comment]
So in other languages (and for now), we kept the package name as "google-cloud-translate", as per the request from the Translation team. For instance:

https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-translate
https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-translate
https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/translate
https://github.com/GoogleCloudPlatform/google-cloud-python/tree/master/translate

**Comment by broady** [comment]
So, we should tend toward doing nothing? Maybe changing the proto package?

If we change the proto package, we should change google.golang.org/api/translate/... to translation

**Comment by pongad** [comment]
@omaray For context, the last element of the import path in Go is idiomatically the same as the package name. So `cloud.google.com/go/translate` should in general be called `translate` as well.

**Comment by pongad** [comment]
For record: we kept the package name "translate" but renamed the name of the API in README to "Translation". I'll close this for now; please reopen if it's still an issue.
