### ISSUE TITLE
Add "Translation" to the list of Supported APIs in the ReadMe

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-go#466]
SCENARIO
Navigate to the [Supported APIs](https://github.com/GoogleCloudPlatform/google-cloud-go#supported-apis) section of the ReadMe and look at the table of supported APIs.

EXPECTED
Translation should show up.

ACTUAL
Translation doesn't show.

NOTE
We are now rebranding from Translate to Translation. See [Issue 464](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/464).

**Comment by pongad** [comment]
Translation is already in README
