### ISSUE TITLE
errors: error reporting should have an option to not append go stacks

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/google-cloud-go#468]
I'm sending payloads from other languages environments to a go service -- I'd like to ship to stackdriver error reporting as well but there is not currently a way to omit the go stacks from logInternal here: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/errors/errors.go#L321

**Comment by zombiezen** [comment]
Should just add another field to the `Entry` struct like `OmitStack` or some such.

**Comment by derekperkins** [comment]
Can you just pass in your stack from the submitter? Another workaround today would be to send a single space into the entry.

**Comment by tmc** [comment]
This looks fixed as of https://github.com/GoogleCloudPlatform/google-cloud-go/commit/1c4a3ef0e89741b941ce0954012eb61f0478f2cc This was not an option a year ago when I opened this issue.
