### ISSUE TITLE
support gRPC Wait For Ready

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#469]
#### Background

By default,  gRPC will immediately return an error from an attempted RPC if the endpoint is temporarily unreachable. An RPC can instead be instructed to wait for the endpoint to become ready. This feature is called [Wait For Ready](https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md).

Clients that use the gRPC default will likely observe transient errors, which they will probably deal with by retrying the RPC. The default setting gives clients some transparency into the operation of the RPC layer, at the cost of additional complexity in retry logic.

Clients that use Wait For Ready will observe RPCs that appear to hang, perhaps indefinitely (since gRPC can not really be sure if an unreachable endpoint will ever recover). Such clients should set deadlines on contexts used for RPCs.

Neither setting of Wait For Ready will result in an RPC being retried. Retries are always under the control of the user's client.

#### Support

Currently, the Go Cloud Client Libraries backed by gRPC use the default, and provide no way to change it.  We would like to allow users to set Wait For Ready, so they can or eliminate their programs' retry logic. What is the best way to support that?

In gRPC, Wait For Ready is implemented by a CallOption. Every gRPC method that invokes an RPC has a variadic CallOption argument. So when using gRPC directly, one can obtain Wait For Ready on an RPC by passing the appropriate option. 

The clients generated by the [Google API Code Generator](https://github.com/googleapis/toolkit) provide the ability to set call options at the package level. Each RPC can have its own set of call options (e.g. `CreateBook` might have one set, used for all calls to `CreateBook`, while `GetBook` has a different set). There is no reason to change this to support Wait For Ready, but a `gax.CallOption` does need to be defined: https://github.com/googleapis/gax-go/issues/42.

This approach doesn't make sense for handwritten clients, because the surface of a handwritten client does not in general map directly to the RPCs of the underlying service. Adding a variadic CallOptions argument to each call will also not work, because in many cases the variadic argument position is reserved for other options.

A client could define a function `WaitForReady(bool, func())` which enables or disables Wait For Ready during the call of the function. 

I instead propose a slightly simpler design: two package-level functions,
```
SetWaitForReady(bool)  // Enable/disable Wait For Ready for all subsequent RPCs
WaitForReady() bool    // Return the current Wait For Ready value
```
that set the call option on all RPCs.

Most likely, users won't change the existing behavior, so these functions won't be called.

Another group of users will want to enable Wait For Ready at the beginning of the program, and leave it in that state throughout. They will make one call to `SetWaitForReady`.

If more fine-grained control is wanted, one can always write
```
f() {
   defer SetWaitForReady(WaitForReady())
   SetWaitForReady(true)
   ...
}
```

/cc @zombiezen @adams-sarah @shantuo @rakyll @broady @pongad

**Comment by bradfitz** [comment]
Package-level functions affecting package-level state seems wrong.

How would two concurrent calls with different desired options work with that? I don't think it would.

**Comment by jba** [comment]
Right. I'm proposing a crude solution that won't work for some cases.

I think the only way to get fine-grained control, as with two concurrent calls with different values, would be by putting this in the context. I'm hesitant to add more things to the context, though.

**Comment by bradfitz** [comment]
I'd put it in context before doing racy globals, if those are the two options.

**Comment by pongad** [comment]
From the code generator side, the option is more like per-client-per-method. Setting options for `CreateBook` just affects all calls to `CreateBook` from that client.

Changing the generated code slightly, we can also provide a way to "thread through" the option from the hand-written surface, if required.

**Comment by jba** [comment]
I guess using the context makes the most sense. In which case, we should probably enable this for the generator too, and perhaps phase out the current mechanism.

Are there other suggestions?

**Comment by pongad** [comment]
I don't think I have other suggestions, context makes the most sense for handwritten layer so far. At that point, the generated client might as well use the same mechanism so that we don't need to pack/unpack at the boundary.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
