### ISSUE TITLE
Bigtable should support multi-range readrows

### ISSUE THREAD

**Issue by ptone** [GoogleCloudPlatform/google-cloud-go#472]
The RPC API supports an array of rowranges for a rowset

https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#rowset

But in the golang library there is only a single "RowRange" that returns a proto with len==1 array

`func (r RowRange) proto()`

It should be possible to support a RangeList to complement RowList

**Comment by Iulian7** [comment]
Is there any plan for when this will be available?

**Comment by garye** [comment]
@Iulian7, I'll try to get to this within a week. Ping again if you don't see an update.

**Comment by garye** [comment]
Fixed by daf945bb8684eb8df711af0c3e3a07930a2a01b0
