### ISSUE TITLE
Where are release versions defined?

### ISSUE THREAD

**Issue by dghubble** [GoogleCloudPlatform/google-cloud-go#476]
Glide thinks the latest version of `cloud.google.com/go` is `v0.6.0` which seems to work. I don't find any Github releases stating this. I don't find any tagged commits with versions. I don't find it in source or `internal/versions`. On Gerrit I can't find a notion of sematic releases either. Maybe I'm not looking hard enough.

Are there semantic version releases or perhaps glide is confused? If so, where could I map a release to its commit hash.

Thanks much.

**Comment by adams-sarah** [comment]
Releases are marked as git tags. 
These releases may be found within the github UI from our main repo page (https://github.com/GoogleCloudPlatform/google-cloud-go) by clicking "releases" at the top.

Direct link here: https://github.com/GoogleCloudPlatform/google-cloud-go/releases

**Comment by dghubble** [comment]
Thanks for pushing those! :+1:
