### ISSUE TITLE
datastore: log RPCs

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#477]
Support logging of all outgoing RPCs to the console.

Requested by P. Costello.

See GoogleCloudPlatform/gcloud-common#214.

**Comment by zombiezen** [comment]
I have a little bit of bandwidth here to help, if you like @jba.

**Comment by jba** [comment]
@zombiezen Yes please!

**Comment by zombiezen** [comment]
Before I go off writing a CL, some questions:

1. Is using the standard "log" package acceptable?
1. Do we just want requests, or responses as well?
1. Seems like the easiest control to add would be an environment variable, but that makes the logging somewhat opaque to user of the client.  Is this okay?

**Comment by jba** [comment]
Looking around grpc to see if they offered something, I found https://github.com/grpc/grpc-go/blob/master/trace.go. I wonder if that could help.

**Comment by zombiezen** [comment]
Unassigning.  I don't have anything meaningful in-flight right now.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
