### ISSUE TITLE
goapp: errors that suggest gcloud commands should point user to gcloud SDK

### ISSUE THREAD

**Issue by Sajmani** [GoogleCloudPlatform/google-cloud-go#478]
In experimenting with the Go App Engine SDK, the goapp command returned an error that helpfully suggested a gcloud command to resolve it.  Unfortunately, I did not have the gcloud command installed.  The goapp error would be somewhat more helpful if it also suggested where to get the gcloud command (download the Google Cloud SDK).

sameer-macbookpro2% goapp deploy -application ELIDED-154714 -version 1
09:57 AM Application: ELIDED-154714 (was: None); version: 1 (was: None)
09:57 AM Host: appengine.google.com
09:57 AM Starting update of app: ELIDED-154714, version: 1
09:57 AM Getting current resource limits.
09:57 AM Scanning files on local disk.
Error 404: --- begin server output ---
This application does not exist (project_id=ELIDED-154714'). To create an App Engine application in this project, run "gcloud beta app create" in your console.
--- end server output ---
error while running appcfg.py: exit status 1
sameer-macbookpro2% gcloud beta app create
zsh: command not found: gcloud

At this point, the user has to find their way to this page for instructions on how to proceed:
  https://cloud.google.com/sdk/gcloud/#gcloud_and_the_sdk

**Comment by broady** [comment]
This issue will be obsolete soon: goapp/appcfg.py will be (next month or so) be replaced with `gcloud app deploy`.

**Comment by jba** [comment]
Closing assuming it's obsolete.
