### ISSUE TITLE
transport: set User-Agent for non-gRPC 

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/google-cloud-go#481]
https://github.com/google/google-api-go-client/blob/master/transport/dial.go#L49

Currently we drop the UserAgent option for plain HTTP clients (e.g., storage).

/cc @zombiezen

**Comment by ccemeraldeyes** [comment]
In the previous version of this library, we can pass in a [custom http.Client](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/blob/e84f61b28ec0a98cff7f1628f7d930f598f939fc/src/bosh-google-cpi/google/client/google_client.go#L94). Can we do the same thing in the new library?

**Comment by zombiezen** [comment]
At what scope do we need to set User-Agent here?  Is it that the Apiary clients are not sending the header, or that Veneers specifically need an override.

**Comment by broady** [comment]
Veneers need an override.

https://code-review.googlesource.com/#/c/10273/
