### ISSUE TITLE
Translate : a new Client cannot use an API KEY anymore ?

### ISSUE THREAD

**Issue by gedw99** [GoogleCloudPlatform/google-cloud-go#482]
client, err := translate.NewClient(ctx, option.WithAPIKey(apiKey))

I think this used to work.

I want to be able to give out API Keys to my users and restrict IP address.
If there is another way to be able to give out acces and restrict usng some other variable let me know.

**Comment by adams-sarah** [comment]
```
client, err := translate.NewClient(ctx, option.WithAPIKey(apiKey))
```
should still work. What issues are you running into?

**Comment by jba** [comment]
Feel free to re-open if this is still a problem for you.
