### ISSUE TITLE
google.golang.org/cloud/pubsub broken/deprecated?

### ISSUE THREAD

**Issue by JaegerBane** [GoogleCloudPlatform/google-cloud-go#483]
I'm currently trying to run `go generate` on a package that imports `google.golang.org/cloud/pubsub`, and I'm getting an error: 

`could not import google.golang.org/cloud/pubsub (can't find import: google.golang.org/cloud/pubsub)`

I thought I already had this package, so re-running a go get results in a _really_ weird error:

`can't load package: package google.golang.org/cloud/pubsub: code in directory /work/src/google.golang.org/cloud/pubsub expects import "cloud.google.com/go/pubsub"`

A bit of background research implies that this is down to `go get` running an install attempt. Getting that `cloud.google.com/go/pubsub` package has no effect, I'm guessing that `google.golang.org/cloud/pubsub` has been entirely deprecated? I can't see any indication that it has.

Everything builds and runs fine, I only see this issue when generating code.

**Comment by JaegerBane** [comment]
It turns out that the later `cloud.google.com/go/pubsub` package completely replaces the `google.golang.org/cloud/pubsub` package. Installing that and importing that package instead lets me generate code now.

_However_... actually getting that new package to build is crazy, there appears be a serious dependency issue. It uses a range of new packages but turns out that the recursive dependency fetch only actually pulls outdated packages (`github.com/golang/protobuf/proto` and `google.golang.org/grpc`). It's easy to fix but it isn't noted down anywhere in Google's docs from what I can see - I had to work it out by studying the source code of the various offending packages.

**Comment by adams-sarah** [comment]
Apologies for the inconvenience. This import path change was made last August, and announced here: https://groups.google.com/forum/#!topic/google-api-go-announce/82-qWvuZzrI

All google.golang.org/cloud packages were moved to cloud.google.com/go

Closing the issue for now. Please reopen if you have more unresolved issues around this.
