### ISSUE TITLE
cloud.google.com/go/pubsub has outdated dependencies?

### ISSUE THREAD

**Issue by JaegerBane** [GoogleCloudPlatform/google-cloud-go#484]
In relation to [#483](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/483), It looks like `cloud.google.com/go/pubsub` pulls in outdated dependencies which don't actually build.

In this case, all that needs to be done is manually updating `github.com/golang/protobuf/proto` and `google.golang.org/grpc`, but there's no indication in any documentation I've come across that this needs to be done - I had to puzzle it out from the source code consts that are thrown out when the build errors occur after importing the pubsub package.

Given that many that will be using this package won't necessarily be using any of it's dependancy packages directly, it would make sense to have this noted down somewhere?

**Comment by adams-sarah** [comment]
How did you update your dependencies?
After changing your google.golang.org/cloud/{PKG} imports to cloud.google.com/go/{PKG}, you should have been able to run:
```
go get -u ./...
```
from within your go project.

As noted on #483 , this change was made last August, and was announced on the google-api-go-announce google group as well as in the gophers slack (https://gophers.slack.com/archives/google-cloud/p1470694566000044).

But I'm sorry that this message did not reach you :(.

@jba thoughts about putting a line on the README.md, eg:
`(previously "google.golang.org/cloud")`?

**Comment by JaegerBane** [comment]
I was using `gb vendor` to pull the dependencies. Perhaps it's an issue with vendor? I've never seen it run into this kind of issue before, however.

I don't necessarily mind the change of naming convention in the pubsub package, it's more that there has to be a better way of fixing this then having someone go through the source code of a bunch of recursive-required packages they're not even using just to get google's official pubsub package to build. Seems a bit janky.

As for Gophers... that's fine at the time, but running google searches on the errors typically doesn't go into the depths of the Slack channel ;)

**Comment by adams-sarah** [comment]
Hm. The import paths within all the google cloud code (including the pubsub package) were updated months ago. The only explanation for this behavior is that you had old versions of your proto and grpc packages locally. 

This problem has not been reported by anyone else in the months since this change has taken place. I must conclude that this was a fluke, possibly with gb. Perhaps gb was fetching dependencies in the wrong order? It's hard to say.
