### ISSUE TITLE
bigquery: add Uploader.Put example using ValuesSaver

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#488]
We never show how to upload rows that are just []Value.

**Comment by sayden** [comment]
I'm sure I can handle this one. I have used almost all possibilities of the old and new versions already :)

Are we talking about a simple implementation of the `value.ValueSaver` interface? Or use `value.ValuesSaver` as stated in the title that already implements this interface so that we just show how to pass the schema and it's inserted into a BQ table?

With this info I'm pretty sure I can open a PR so that you can check it and ask me to adjust it. Also, I'll need to know how to add an integration test. Means, if we must set it so that a project ID, dataset and table is passed as an env variable or it is hardcoded in the code like "put-your-project-id-here".

**Comment by jba** [comment]
Thanks for offering to help! You should first read [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md).

This issue is about adding an example of Value**s**Saver, not ValueSaver, to [examples_test.go](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/examples_test.go). We have an [integration test](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/integration_test.go#L507) that uses it already, so no need to write another one. Just write a simple example, like the other ones for `Uploader.Put`.

**Comment by sayden** [comment]
Hi again It's the first time that I use Gerrit and I'm not sure if I understood well the committing process. I have set the aliases, did the `git change`, a new branch was created (tracking origin/master?), did the commit, fix the things that the server was asking and did the `git mail`. Everything look fine.

A tag has been created in my local but I haven't been able to push anywhere

It was mailed as `https://code-review.googlesource.com/#/c/gocloud/+/20650`

Sorry for bothering :( I just want to do it well. In fact I use all the code in this repo so much that I could help in many other areas so it's good that I understand the workflow well before bothering too much :)

**Comment by jba** [comment]
Mailing is pushing.

I got an email with your CL and commented on it. Next time, include me as a reviewer when you mail it, and it will show up on my gerrit dashboard as well.

**Comment by sayden** [comment]
Sorry, I mess it up and because I couldn't manage to push a second commit. I could only managed to push a new commit by amending the previous one. I thought it was "the way" but it has created a new change:

**Comment by bradfitz** [comment]
Yes, you do need to amend the commit back into 1 total commit, but you need to preserve the magic Change-Id line from the original commit. The Change-Id is the primary key.

**Comment by sayden** [comment]
Ok. I think I managed to update the proper Gerrit ID. I guess it will appear in jba dashboard. Maybe we can update also the file for contributing with a small example?

**Comment by jba** [comment]
Step 6 under Contributing in CONTRIBUTING.md says "Keep amending to the change with git codereview change and mail as your receive feedback. Each new mailed amendment will create a new patch set for your change in Gerrit." Did you do that and it failed to preserve the Gerrit ID?

**Comment by sayden** [comment]
I'm not sure what I did but I solved it by copy-pasting the Gerrit ID from the UI. 

Now I've just submitted the new patch by simply doing a `git add bigquery/examples_test.go`, then a `git commit --amend` and `git mail`. The ID was fine.

Now I just have to know how to add comments so I don't have to keep writing here once I'm working in a change :wink:

**Comment by jba** [comment]
Fixed by f66389d56fdc547c6c76f1dd0377065e7a319aa3.
