### ISSUE TITLE
Bigtable Emulator: Cannot delete a row and then add a row with the same key.

### ISSUE THREAD

**Issue by MitchRudominer** [GoogleCloudPlatform/google-cloud-go#489]
I am using the GRPC api in C++.

I have a simple unit test that works fine when I run it against the real Cloud Bigtable but it fails against Bigtable Emulator.

(1) Add 100 rows with row keys "row000", "row001", ... "row099". 
One column family, one column qualifier in that family, one short piece of data in each cell.
No timestamps are specified so they default to zero.

(2) Delete all 100 rows by sending the DropRowRange RPC with delete_all_data_from_table=true.

(3) Add 100 rows with the same exact meta-data and data as in (1). (Same keys, column family, column qualifier, timestamp [unspecified], and data.)

(4) Check by reading and see that there are no rows in the table.

(5) Add 200 rows with row keys  "row000", "row001", ... "row199". 

(6) Check by reading and see that the second group of 100 rows are now in the table. That is only the
rows with keys  "row100", "row101", ... "row199". 

So it seems that Bigtable Emulator has logged the fact that the rows with keys  "row000", "row001", ... "row099" have been deleted and after that it is not possible to add rows with those keys any more. But
rows with different keys may be added. I thought it might be a race condition but I tried putting in plenty of sleeps and it made no difference. It is impossible to add rows with those keys at any time later.

As I mentioned above this is not the behavior exhibited by the real Cloud Bigtable.

**Comment by garye** [comment]
This fix will take ~2 weeks to propagate to the gcloud emulator. If you need something faster than that and aren't comfortable building from source (bigtable/cmd/emulator/cbtemulator.go) let me know and I can put a binary up somewhere.

**Comment by MitchRudominer** [comment]
Gary, Thanks so much for your quick fix. That is awesome. I really
appreciate it. I think we'll be fine waiting for the release.

**Comment by garye** [comment]
Ok sounds good! Thanks for the report.
