### ISSUE TITLE
bigtable: How to check the result of DeleteRow?

### ISSUE THREAD

**Issue by junghoahnsc** [GoogleCloudPlatform/google-cloud-go#490]
Hello,

Applying DeleteRow mutation returns no error when the row doesn't exist.
What is the best way to check whether the row was actually deleted or not?

Thanks,

**Comment by garye** [comment]
I believe this is working as designed - while you cannot know if the row was deleted after a `DeleteRow` you can know that it is definitely not in the table, assuming no other error.

**Comment by junghoahnsc** [comment]
I think it depends on use cases. It looks like I have to read before deleting to know this.

**Comment by garye** [comment]
I agree that it can be helpful to know if a delete actually deleted something, but since the Bigtable model doesn't support this you're stuck with doing the read yourself.
