### ISSUE TITLE
trace: needs to support setting service name and version

### ISSUE THREAD

**Issue by ConorNevin** [GoogleCloudPlatform/google-cloud-go#494]
Is there any roadmap for improving the Trace API? 

Being unable to set service name and version through the client makes it impossible to use effectively when you have multiple apps sending traces

**Comment by zombiezen** [comment]
Yes, we are definitely working to improving the trace API.  It is in alpha now and we would like to work toward getting it to beta.

I'm going to rename this issue to the specific problem you identified.  Feel free to file more issues as you see other problems.

**Comment by rakyll** [comment]
These filters are for filters coming from the Google App Engine apps and there is something we can do until Stackdriver makes the field available for generic use.

**Comment by flaviamissi** [comment]
Not sure if this is useful, but related: https://stackoverflow.com/questions/41059291/adding-service-and-version-to-custom-stackdriver-trace-api

**Comment by mykolasmith** [comment]
Any update on this?

**Comment by rakyll** [comment]
@mykolasmith Not updates so far.

**Comment by jba** [comment]
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).
