### ISSUE TITLE
datastore: SaveStruct exits on first error when saving fields

### ISSUE THREAD

**Issue by rwl** [GoogleCloudPlatform/google-cloud-go#496]
I have a struct with a `map[string]string` field that I am trying to handle using the `PropertyLoadSaver` interface. The `LoadStruct` function returns an error as expected, but finishes trying the remaining fields first:

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/cd0da878c66091060d2e7403abd62192b3e387e0/datastore/load.go#L363-L365

Unfortunately, the `SaveStruct` function exits immediately when there is a error saving a field:

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/cd0da878c66091060d2e7403abd62192b3e387e0/datastore/save.go#L212

It would be great if both of the functions were consistent in this regard.

**Comment by rwl** [comment]
One way to fix this might be to simply do:

```diff
diff --git a/datastore/save.go b/datastore/save.go
index 75fa638..ea00815 100644
--- a/datastore/save.go
+++ b/datastore/save.go
@@ -186,12 +186,13 @@ func saveSliceProperty(props *[]Property, name string, opts saveOpts, v reflect.
 func (s structPLS) Save() ([]Property, error) {
        var props []Property
        if err := s.save(&props, saveOpts{}, ""); err != nil {
-               return nil, err
+               return props, err
        }
        return props, nil
 }
 
 func (s structPLS) save(props *[]Property, opts saveOpts, prefix string) error {
+       var lastError error
        for _, f := range s.codec {
                name := prefix + f.Name
                v := getField(s.v, f.Index)
@@ -209,10 +210,10 @@ func (s structPLS) save(props *[]Property, opts saveOpts, prefix string) error {
                opts1.flatten = opts.flatten || tagOpts.flatten
                opts1.omitEmpty = tagOpts.omitEmpty // don't propagate
                if err := saveStructProperty(props, name, opts1, v); err != nil {
-                       return err
+                       lastError = err
                }
        }
-       return nil
+       return lastError
 }

```

**Comment by jba** [comment]
I'd like to understand this better. Will the database actually get updated if we make this change? What's the advantage to reporting the last error instead of the first?

**Comment by rwl** [comment]
> Will the database actually get updated if we make this change?

It should do. As you say, we are just returning the last error instead of the first, which is in alignment with LoadStruct. However, we could test for this to make sure.

> What's the advantage to reporting the last error instead of the first?

A common use case for implementing PropertyLoadSaver would be if a struct has several compatible fields, but one or two fields that are incompatible with Datastore. In that case, it would be convenient if one could use `LoadStruct` and `SaveStruct` to handle the compatible fields, ignore the error associated with the incompatible fields and handle their persistence manually.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
