### ISSUE TITLE
datastore: Nested struct's implementation of PropertyLoadSaver ignored

### ISSUE THREAD

**Issue by rwl** [GoogleCloudPlatform/google-cloud-go#497]
When saving a struct that has a field with a struct type, if the nested struct implements the `PropertyLoadSaver` interface the `Save` method is not utilised:

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/cd0da878c66091060d2e7403abd62192b3e387e0/datastore/save.go#L92

It should be possible to perform the same check that is done for the top-level struct here:

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/cd0da878c66091060d2e7403abd62192b3e387e0/datastore/save.go#L38

Similarly, implementation of `PropertyLoadSaver` could be checked when loading a nested struct here:

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/cd0da878c66091060d2e7403abd62192b3e387e0/datastore/load.go#L277

**Comment by jencarlile** [comment]
I am running into this same issue in the appengine datastore package.  It does not appear to have the same fix applied

**Comment by jba** [comment]
Please open an issue at https://github.com/golang/appengine/issues.
