### ISSUE TITLE
bigquery: Add Job query metadata fields

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/google-cloud-go#498]
Queries return a lot more metadata than is exposed through the Job object. For example, I would love to store metrics on the following fields.

```
      "totalBytesProcessed": long,
      "totalBytesBilled": long,
      "billingTier": integer,
      "cacheHit": boolean,
```

**Comment by BlueMonday** [comment]
@derekperkins: I think this was added fairly recently: https://github.com/GoogleCloudPlatform/google-cloud-go/commit/4ce58eb695dea5bbb06f9ab6e8321318fd715632
