### ISSUE TITLE
pubsub: iterator.Next() needs to take its own context? 

### ISSUE THREAD

**Issue by epsniff** [GoogleCloudPlatform/google-cloud-go#499]
Because the iterator.Next() request doesn't take a context and uses the client's context it's a bit awkward to manage timeouts in Next().   For example when we get the following RPC error, it puts the Next() request into a deadlock since Invoke will retry forever:
```
err:rpc error: code = 14 desc = A pull requests for subscription '/subscriptions/TUNC' went to a server that is temporarily overloaded. Please try the request again.
```
But we can't add a timeout to the client's context since it's expected to run for days.

Our current workaround it to cancel the context provided to the client and then completely recreate the client.  But it would make for cleaner code if we could just do:
```go
      for { 
 		ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
		psMsg, err := iter.Next(ctx) //giving Next it's own context.
		if err != nil {
			switch err {
                        case context.ErrDeadlineExceeded:
 				continue
			case iterator.Done:
				break
			default:
				return err
			}
              }
              cancel()
              //process message
      }
```

**Comment by jba** [comment]
I understand why this is useful in the abstract, but I don't understand your specific example. Do you actually encounter an UNAVAILABLE error like that which never goes away? Are you experiencing that against the production service?

**Comment by epsniff** [comment]
@jba sorry it's taken me a bit to get back too you, have been busy putting out fires pubsub... :p 

In the last week all our touch points with the pubsub package have started hanging.  We first noticed it with topic publish.  The fix for all of them except message iterating were easy, and involved adding a context with a timeout.  

The stack dumps in most cases show that pubsub package was stuck in the pubsub's invoker, which seems to retry forever until the give context is canceled/time-outed.   The following is an example were it got stuck in the message iterator call. 
```
goroutine 678 [select]:
github.com/lytics/all/vendor/google.golang.org/grpc/transport.(*Stream).Header(0xc421cebf00, 0x561f4c1efb10, 0xc42067f880, 0x561f4c6ecf20)
	/home/sniffe/go/src/github.com/lytics/all/vendor/google.golang.org/grpc/transport/transport.go:244 +0x299
github.com/lytics/all/vendor/google.golang.org/grpc.recvResponse(0x7f70ddca8720, 0xc4219fc090, 0x0, 0x0, 0x561f4c6e9a40, 0x561f4c723db0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/sniffe/go/src/github.com/lytics/all/vendor/google.golang.org/grpc/call.go:63 +0xaa
github.com/lytics/all/vendor/google.golang.org/grpc.invoke(0x7f70ddca8720, 0xc4219fc090, 0x561f4c1875b4, 0x21, 0x561f4c0d9b20, 0xc421bdbc20, 0x561f4c0ec960, 0xc421bdbc60, 0xc4201dc240, 0x0, ...)
	/home/sniffe/go/src/github.com/lytics/all/vendor/google.golang.org/grpc/call.go:252 +0x92d
github.com/lytics/all/vendor/google.golang.org/grpc.Invoke(0x7f70ddca8720, 0xc4219fc090, 0x561f4c1875b4, 0x21, 0x561f4c0d9b20, 0xc421bdbc20, 0x561f4c0ec960, 0xc421bdbc60, 0xc4201dc240, 0x0, ...)
	/home/sniffe/go/src/github.com/lytics/all/vendor/google.golang.org/grpc/call.go:143 +0x19c
github.com/lytics/all/vendor/google.golang.org/genproto/googleapis/pubsub/v1.(*subscriberClient).Pull(0xc420142248, 0x7f70ddca8720, 0xc4219fc090, 0xc421bdbc20, 0x0, 0x0, 0x0, 0x8, 0xc420130118, 0x0)
	/home/sniffe/go/src/github.com/lytics/all/vendor/google.golang.org/genproto/googleapis/pubsub/v1/pubsub.pb.go:658 +0xd2
github.com/lytics/all/vendor/cloud.google.com/go/pubsub/apiv1.(*SubscriberClient).Pull.func1(0x7f70ddca8720, 0xc4219fc090, 0x561f4bb71da9, 0xc42067fb88)
	/home/sniffe/go/src/github.com/lytics/all/vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:326 +0x7b
github.com/lytics/all/vendor/github.com/googleapis/gax-go.invoke(0x7f70ddca8720, 0xc4219fc090, 0xc421bdbc40, 0x0, 0x561f4c1ef3d8, 0x561f4ba6e0d8, 0x20)
	/home/sniffe/go/src/github.com/lytics/all/vendor/github.com/googleapis/gax-go/invoke.go:70 +0x4d
github.com/lytics/all/vendor/github.com/googleapis/gax-go.Invoke(0x7f70ddca8720, 0xc4219fc090, 0xc421bdbc40, 0x0, 0x0, 0x0, 0xc42067fc58, 0x561f4ba6e0d8)
	/home/sniffe/go/src/github.com/lytics/all/vendor/github.com/googleapis/gax-go/invoke.go:48 +0xc5
github.com/lytics/all/vendor/cloud.google.com/go/pubsub/apiv1.(*SubscriberClient).Pull(0xc4203f6420, 0x7f70ddca8720, 0xc4219fc090, 0xc421bdbc20, 0x0, 0x0, 0x0)
	/home/sniffe/go/src/github.com/lytics/all/vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:328 +0x1a3
github.com/lytics/all/vendor/cloud.google.com/go/pubsub.(*apiService).fetchMessages(0xc420284290, 0x7f70ddc1eec8, 0xc420914980, 0xc420d28230, 0x4b, 0x561f000003e8, 0x561f4c723db0, 0x0, 0x0, 0x0, ...)
	/home/sniffe/go/src/github.com/lytics/all/vendor/cloud.google.com/go/pubsub/service.go:252 +0xc9
github.com/lytics/all/vendor/cloud.google.com/go/pubsub.newPuller.func1(0x561f4c723db0, 0x0, 0x0, 0x0, 0x0)
	/home/sniffe/go/src/github.com/lytics/all/vendor/cloud.google.com/go/pubsub/puller.go:55 +0x5e
github.com/lytics/all/vendor/cloud.google.com/go/pubsub.(*puller).Next(0xc420d5a9b0, 0x0, 0x0, 0x0)
	/home/sniffe/go/src/github.com/lytics/all/vendor/cloud.google.com/go/pubsub/puller.go:82 +0x124
github.com/lytics/all/vendor/cloud.google.com/go/pubsub.(*MessageIterator).Next(0xc420914a40, 0x0, 0xc420685260, 0x0)
	/home/sniffe/go/src/github.com/lytics/all/vendor/cloud.google.com/go/pubsub/iterator.go:93 +0x33
github.com/lytics/lio/src/eventstore/pubsubstore.(*pubsubIterator).runFetcher(0xc420d3cd70, 0x1, 0xc420d5c450)
{RM'ing MY CODE}
```

After fixing all the calls to the pubsub package the last remaining one was the calls to `MessageIterator.Next()`, which resulted in a pretty hacky workaround :(.  Basically I created a monitoring go routine that detects if a MessageIterator's rate drops to zero.  If it does, then it cancel's the iterator's context and recreates the MessageIterator.   It works but has some downsides, like not being able to ack any in-fight messages after the original iterator is killed.

I'm not sure what the exact error was that caused the invoker to retry forever as canceling the context just returns DeadlineExceeded error.  But I have seen the following two errors over the last couple of days in our logs.
```
2017/01/30 19:04:24 Failed to decode ("google.rpc.debuginfo-bin", "Q2xkamIyMHVaMjl2WjJ4bEx...TRUNCED...a3hNVFEzTmpnME1BPT0"): illegal base64 data at input byte 2056
```
```
rpc error: code = 14 desc = A pull requests for subscription '/subscriptions/foobar/events-aid-123' went to a server that is temporarily overloaded
```
When it locks up, it seems to only hit a subset of the topics/subscriptions but it effects that subscription across the board.  For those that do lock up, it happens to all message iterators from multiple machines within a few mins.

We consume between 20,000 and 80,000 messages per second, at about 20/80MB sec.  We consume the subscriptions from about 30 machines.  We have a few hundred topic/subscriptions.  We are currently vendor'ed at revision: 9150c396a4e2301b019900c8241a303518dfae11

**Comment by epsniff** [comment]
BTW I opened this the same day we started seeing these hangs: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/491 
 
And we're seeing hangs in GCS readers/writers but so far only a handful.

**Comment by epsniff** [comment]
Im guessing these issues are related to this: https://groups.google.com/forum/#!topic/cloud-pubsub-discuss/dGOXiL118Sw

**Comment by jba** [comment]
Looks like the underlying pubsub problems will be fixed in a couple of days.

Couldn't you build a simpler workaround by wrapping the call to Next in a select with a timeout, then canceling the context and restarting the Pull? In either case, I do understand that you'll still have the problem of dropped acks.

I'm hesitant to introduce a context arg into Next because (a) this is (in the scheme of things) a transient issue, and (b) we'll be rolling out a new implementation that uses streaming, so is more performant, and may not have this failure mode. In fact, in the streaming case I'm pretty sure canceling a single Next's context won't be any different from canceling the entire iterator's context.

Sorry this is biting you.

**Comment by epsniff** [comment]
@jba thank you!  At this point I'm only concerned with long-term solutions, so I can wait for the streaming implementation you mentioned.  

*possible workarounds (just in case anyone reading this needs some ideas):*

They both have the issue of dropping buffered ack'ed messages and for subscriptions with low volume restarting when no messages arrives within the timeout.  But I can live with them for now, especially with the fixed back-end rolling out today.
```go
	ctx, cancelIter := context.WithCancel(context.Background())
	t := time.AfterFunc(cancelIter(), time.Minute)
	iter, err := subscription.Pull(ctx)
	t.Stop()
	if iter == nil || err == context.Canceled {
		return ErrPullerCreationTimeout
	}
	defer cancelIter()
	// ...
	for {
		t := time.AfterFunc(cancelIter(), time.Minute)
		msg, err := iter.Next()
		t.Stop() // Next returned in a timely manner
		if err != nil {
			switch err {
			case context.Canceled:
				return ErrPullerNextTimeout
			case iterator.Done:
				break
			default:
				return err
			}
		}
		results <- msg
	}
```

```go
	ctx, cancelIter := context.WithCancel(context.Background())
	t := time.AfterFunc(cancelIter(), time.Minute)
	iter, err := subscription.Pull(ctx)
	t.Stop()
	if iter == nil || err == context.Canceled {
		return ErrPullerCreationTimeout
	}
	defer cancelIter()
	msgs := make(chan *pubsub.Msg)
	errs := make(chan error)
	go func() {
		for {
			if msg, err := iter.Next(); err != nil {
				errs <- err
				return
			} else {
				msgs <- msg
			}
			select {
			case <-ctx.Done():
				return
			default:
			}
		}
	}()
	for {
		select {
		case <-ctx.Done():
			return nil
		case msg <- msgs:
			results <- msg
		case err <- errs:
			return err
		case <-time.After(time.Minute):
			return ErrNextTimeout
		}
	}
```

**Comment by epsniff** [comment]
Im closing this issue since the latest version of the pub-sub client uses a different access pattern.
