### ISSUE TITLE
storage: troubles reading from App Engine

### ISSUE THREAD

**Issue by aubm** [GoogleCloudPlatform/google-cloud-go#502]
Hello there,

I am facing an issue with storage, when I try to read a file from App Engine.
Here is a sample project with a pretty typical approach: https://github.com/aubm/GAE-Read-From-Storage.

And here is the error I get: `Failed to get reader for file: Get https://storage.googleapis.com/<APP_ID>.appspot.com/sample.txt: http.DefaultTransport and http.DefaultClient are not available in App Engine. See https://cloud.google.com/appengine/docs/go/urlfetch/`

What intrigues me is that this code has worked so far, and it seems that a dependencies update broke it.

Maybe someone is having the same issue? Is that a bug or a breaking change to the library that now require a different approach. If so, the docs don't seem to be up to date: https://cloud.google.com/appengine/docs/go/googlecloudstorageclient/read-write-to-cloud-storage.

**Comment by aubm** [comment]
After a few more digging, it seems to have something to do with this commit https://code.googlesource.com/google-api-go-client/+/c55f685368bb1cdfed2c20283e2878a83b929730%5E%21/#F0

Any idea of how it can be addressed?

**Comment by broady** [comment]
https://code-review.googlesource.com/10710

**Comment by broady** [comment]
@aubm for now - you can roll back to before that commit, or patch in the change linked above if you'd like to test it out.

**Comment by aubm** [comment]
That was quick, thank you :)
