### ISSUE TITLE
storage: Support lifecycle configuration for buckets

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/google-cloud-go#503]
Off the top of my head, something like:

```go
err := storage.Bucket("new-bucket").Create(ctx, "project-id", &storage.BucketAttrs{
  LifecycleRules: []storage.LifecycleRule{{
    Action: storage.ActionDelete,
    Conditions: []storage.Condition{
      // NB: All conditions must be met before the action is taken.
      storage.AgeInDays(30),
      storage.CreatedBefore(someTime),
      storage.IsLive(false),
      storage.MatchesStorageClass(storage.StorageClassNearline),
      storage.NumNewerVersions(10),
    },
  }},
})
```

This request would configure a 30-day TTL for objects in the bucket, only if they were created before `someTime`, were not live (i.e., weren't the latest version), used the nearline storage class, _and_ if there were 10 newer versions.

* Docs: https://cloud.google.com/storage/docs/lifecycle
* JSON API: https://cloud.google.com/storage/docs/json_api/v1/buckets#lifecycle

**Comment by jba** [comment]
The design LGTM. Thanks for offering to do the work! Comments:

- I'd like the conditions to be fields of the `LifecyleRule` struct. I think the zero values can be interpreted as "ignore" for everything but IsLive (and maybe NumNewerVersions—not sure if 0 is meaningful there). For IsLive we could have a three-valued type.
- s/ActionDelete/DeleteAction/
- I assume the other action will look like `Action: storage.SetStorageClassAction(string)`?
- s/StorageClassNearline/Nearline/. I think we can do that for all except Standard, which we could call StandardClass. Or maybe we should append "Class" to all. Not sure. But they should be string constants, not a new type, because we already use a string for storage class and we'd like to avoid a breaking change.

/cc @broady @rakyll @adams-sarah

**Comment by jba** [comment]
Or instead of a three-valued type for IsLive, we could use interface{}. We could also use [optional.Bool](https://code.googlesource.com/gocloud/+/master/internal/optional/optional.go#27), but that package is internal and this struct could be inspected by the caller of Bucket.Attrs.

**Comment by broady** [comment]
+1 for a preference towards struct fields. Is `IsLive` the only one that requires some attention? A `*bool` type might be fine.

A builder pattern might help?

Extremely rough:
```
storage.LifecycleCondition().AgeInDays(30).IsLive(false).NewerVersions(10)
```

**Comment by ImJasonH** [comment]
The low-level generated client doesn't seem to differentiate between true/false/unset:

```go
type BucketLifecycleRuleCondition struct {
    ...
    // IsLive: Relevant only for versioned objects. If the value is true,
    // this condition matches live objects; if the value is false, it
    // matches archived objects.
    IsLive bool `json:"isLive,omitempty"`
    ...
}
```

(https://godoc.org/google.golang.org/api/storage/v1#BucketLifecycleRuleCondition)

**Comment by ImJasonH** [comment]
One reason I like `Action: storage.ActionDelete` is that the alternative could be something like `storage.SetStorageClass(newStorageClass)` -- the low-level API has a `Type` (delete or set storage class), and a `StorageClass` field that's only meaningful if `Type == "SetStorageClass"`.

That seems like the kind of thing the nicer API surface could account for, but I don't know if that's consistent with the way things are done in this library.

On second look, trying to do the same thing for Conditions is a bad idea, and a Condition struct would indeed be better.

**Comment by jba** [comment]
I agree with you about storage.ActionDelete (or DeleteAction).

**Comment by jba** [comment]
Regarding the treatment of IsLive, the ForceSendFields field of that struct lets us override the omitempty. And we must do that, since I'm sure the server treats false and omitted differently.

**Comment by jba** [comment]
We can continue discussion on the [CL](https://code-review.googlesource.com/#/c/10852).

**Comment by bg451** [comment]
@ImJasonH Is there any plan to add this in soon?

**Comment by ImJasonH** [comment]
My team's motivation for the feature has disappeared, so I don't have a strong need anymore.

If you want to pick up the CL and push it through that could be useful. IIRC there were some fairly subtle questions about what the defaults/options should be and how they should be expressed.

**Comment by jba** [comment]
@bg451 I'd be happy to help you with the CL.

**Comment by bg451** [comment]
Awesome, I'll read through the comments in the CL and see what changes still need to be made.

**Comment by bg451** [comment]
@ImJasonH @jba Kind of a dumb question, but how do I take over the CL? Do I need to create a new CL or do I use the existing one? I signed the CLA and followed the other steps in `contributing.md`.

**Comment by jba** [comment]
You should create a new one. At the top right of the main CL screen you'll see either a "Download" dropdown (old UI) or a "More" button/dropdown with a "Download patch" option (new UI).

But we should determine the design first. See the comments above.

**Comment by bg451** [comment]
Considering that the storage client library doesn't use the options pattern, I'm +1 for using struct fields to keep the API consistent. Also +1 for a three type solution to IsLive. It looks like zero values for the other BucketLifecycleRuleCondition fields are not ambiguous and can be treated as omitted, although I might be wrong about that. 

I went ahead and rebased the change against head, here's the [CL](https://code-review.googlesource.com/#/c/14330/). I'll add in some of the requests made in the last CL if the above is in the right direction @jba

**Comment by harshavardhana** [comment]
Is there an ETA when this will be available under master branch?

**Comment by bg451** [comment]
@harshavardhana We're getting pretty close to finishing the CL, hopefully it should be merged in the next couple of days.

**Comment by harshavardhana** [comment]
> @harshavardhana We're getting pretty close to finishing the CL, hopefully it should be merged in the next couple of days.

Thanks @bg451

**Comment by frankyn** [comment]
Hi all! What's the current status of adding object lifecycle management?

**Comment by jba** [comment]
Still working on the CL. I was at GopherCon, so we slipped a week.

**Comment by frankyn** [comment]
Thank you!
