### ISSUE TITLE
update documentation with new bigtable instance admin functionality

### ISSUE THREAD

**Issue by ccemeraldeyes** [GoogleCloudPlatform/google-cloud-go#506]
https://godoc.org/cloud.google.com/go/bigtable does not reflect updated functionality in https://github.com/GoogleCloudPlatform/google-cloud-go/bigtable, namely CreateInstance, DeleteInstance, and Instances

**Comment by adams-sarah** [comment]
Hm. Perhaps the package doc cache had not been updated recently when you checked?
At the bottom of godoc.org pages, there is some text ala "Updated 45 minutes ago. <a>Refresh now.</a>".

Regardless, CreateInstance, DeleteInstance, Instances are all on https://godoc.org/cloud.google.com/go/bigtable now.

Closing this issue. Feel free to reopen if you still don't see the changes.
