### ISSUE TITLE
[pubsub] How should I match with google.golang.org/api version

### ISSUE THREAD

**Issue by junghoahnsc** [GoogleCloudPlatform/google-cloud-go#510]
Hello,

I tried to sync `cloud.google.com/go` package to the latest. For this, I also needed to sync `google.golang.org/api` and `google.golang.org/genproto` to the latest ones.
But after that, my job didn't work.
For example, a nacked message is delivered to multiple workers over and over again even though the ack deadline is 300 sec and the job couldn't get any new messages.

When I used `cloud.google.com/go (9d965e63e8cceb1b5d7977a202f0fcb8866d6525)`,
`google.golang.org/api(6ae94d3fbc17a6600999dc24c28bd01735a87b76)`, and
`google.golang.org/genproto(08f135d1a31b6ba454287638a3ce23a55adace6f)`, and it worked.

How can I find the working versions of these packages?

Thanks,

**Comment by jba** [comment]
I don't know if you're still experiencing this. Can you try `go get -u` and see if this is still happening?

**Comment by junghoahnsc** [comment]
We're using bazel to build our system. Currently we're using 

```
    # Google go cloud.
    new_go_repository(
        name="com_google_cloud_go",
        importpath="cloud.google.com/go",
        tag="v0.7.0", )

    # Google API.
    new_go_repository(
        name="org_golang_google_api",
        importpath="google.golang.org/api",
        commit="d9d64fe74969b80fb4a435ae9280c9ff061a6097", )

    # Google genproto.
    new_go_repository(
        name="org_golang_google_genproto",
        importpath="google.golang.org/genproto",
        commit="d80a6e20e776b0b17a324d0ba1ab50a39c8e8944", )
```
, which seems to work.

**Comment by junghoahnsc** [comment]
I have another similar issue with pubsub.

```
cloud.google.com/go/external/com_google_cloud_go/pubsub/apiv1/publisher_client.go:186: cannot use func literal (type func("golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
```

I tried to use the last commit 'b4e9a381a01e953e880e6d2cf7fd02d412977cae' for cloud.google.com/go. But it failed with
```
cloud.google.com/go/external/com_google_cloud_go/longrunning/autogen/doc.go:30: undefined: metadata.FromOutgoingContext
cloud.google.com/go/external/com_google_cloud_go/longrunning/autogen/doc.go:33: undefined: metadata.NewOutgoingContext
```

I tried to use the last commit for api and genproto, but it didn't help.
What's the best way to find the correct commit numbers?

**Comment by jba** [comment]
I believe your current problem is that gRPC is not up to date.

> What's the best way to find the correct commit numbers?

I don't know if this is the best way, since I've never had to do this before. But this should work.

1. Set up an ordinary, empty Go workspace, by creating a directory and setting GOPATH to it.
2. Run `go get cloud.google.com/go/pubsub`.
3. `for g in $(find $GOPATH/src -name .git); do echo "$(dirname $g) $(git -C $(dirname $g) show-ref --hash HEAD)"; done`
