### ISSUE TITLE
trace: no way to create a root span without an already-traced HTTP request

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#515]
The trace package only allows to create spans for an http.Request or a header by:

```
func (c *Client) SpanFromHeader(name string, header string) *Span
func (c *Client) SpanFromRequest(r *http.Request) *Span
```

These constructors are meeting the requirements of the users who always have an already-traced incoming HTTP request but fails the users who doesn't have a traced request to begin with.

We should relax the API by adding:

```
func (c *Client) NewSpan(name string) *Span
```

Then, users can create root spans without having to have a traced HTTP request to begin with.

/cc @jcd2 @jba @broady

**Comment by broady** [comment]
Prototype:
https://github.com/GoogleCloudPlatform/golang-samples/pull/74

**Comment by rakyll** [comment]
I also drafted https://code-review.googlesource.com/c/11071/, please take a look.
