### ISSUE TITLE
logadmin.Client: iterator.Next() returns 'rpc error'

### ISSUE THREAD

**Issue by gottwald** [GoogleCloudPlatform/google-cloud-go#517]
I use the `logadmin.Client` to analyze some log data.

Occasionally I get this error:
```
rpc error: code = 13 desc = Internal error encountered.
```
The bigger the time window of the query gets, the more frequently I hit this error.

The code I'm using basically boils down to this:
```go
timeLimit := time.Now().Add(-12*time.Hour)
ctx := context.Background()
it := logclient.Entries(
	ctx,
	logadmin.Filter(fmt.Sprintf(`timestamp >= "%s" AND "Task in" AND "killed as a result of limit of"`, timeLimit.Format(time.RFC3339))),
)
for {
	entry, err := it.Next()
	if err == iterator.Done {
		break
	}
	if err != nil {
		return err
	}
	doSomeStuffWithPayload(entry.Payload)
}
```
It is fairly stable with a 12 hour time window, and nearly fails all the time with >48h.
Doing retries on the `it.Next()` call doesn't seem to help.

Our monthly log usage in stackdriver is about 2.7 TB, but the result set is fairly small. On a 48 hour time window I don't expect more than 20 log lines out of this query.

Am I doing something wrong or is this a bug?

**Comment by jba** [comment]
We should retry that error for you. Unfortunately, retrying Next won't help; iterators remember any error they see.

The logging team pointed out to me that non-indexed text searches are inherently slow. It would be better to use indexed fields or a narrower timestamp range.

**Comment by nish5887** [comment]
Running into the same issue when I using paging `pageToken, err := p.NextPage(&allentries)` gives me the error 

> rpc error: code = Internal desc = Internal error encountered.
