### ISSUE TITLE
pubsub: no acknowledge request transparency

### ISSUE THREAD

**Issue by rtjoseph11** [GoogleCloudPlatform/google-cloud-go#518]
I've had issues with pubsub acknowledge pulls and acks hanging occasionally in my application recently. I've added a timeout on the pull where it recreates the iterator if the pull takes longer than 60 seconds (which seems to have fixed part of this), but I've had to edit the google-cloud-go code to add error logging and a 5 second timeout on the acknowledge call since it is made internally in its own go routine. Is there a way this can be exposed so that the library exposes the acknowledge call so library users can add a timeout and check if errors occur? I'm on commit a5e721bf760c8055ea3ae8b732da1dc6a10fc3f9

**Comment by jba** [comment]
We're working on a higher-performance Pull implementation using streaming. When that's in we'll re-evaluate if this is still necessary.

**Comment by jba** [comment]
I'm closing this, because we've completely reimplemented the pull logic. Please reopen if you still experience problems.
