### ISSUE TITLE
storage: bucket attr enhancement WRITER and quota

### ISSUE THREAD

**Issue by sabrinatseng** [GoogleCloudPlatform/google-cloud-go#521]
Please add WRITER attribute to defaultObjectAccessControls and bucket quota configuration

Just trying give my user per bucket for my application.

**Comment by jba** [comment]
Sorry for the long delay on this bug. Can you explain in a little more detail what you want?

**Comment by jba** [comment]
Google Cloud Storage doesn't support WRITER in DefaultObjectAccessControls. See https://cloud.google.com/storage/docs/json_api/v1/defaultObjectAccessControls.
