### ISSUE TITLE
bigtable: cbt command should support table split

### ISSUE THREAD

**Issue by liujiongxin** [GoogleCloudPlatform/google-cloud-go#524]
When creating a table, it's desirable that cbt command supports table split, achieving similar effect as that in hbase shell. 

One hbase shell example:
_create "testtable", {NAME => "cf" },
       {SPLITS => (1..200).map {|i| "user#{1000+i*(9999-1000)/200}"}};_

**Comment by garye** [comment]
Fixed by 1acdf4a
