### ISSUE TITLE
pubsub: undelivered messages never pulled

### ISSUE THREAD

**Issue by habibrosyad** [GoogleCloudPlatform/google-cloud-go#525]
This is happen several times in my case, when I ran several pulls concurrently each with different topics. The undelivered messages just stay in there although i've tried to restart the subscription or making a new one. The strange thing is when there are new messages sent to the topic, the iterator start pulling again.  But those remaining messages just still there and never get pulled. Also, the undelivered messages count has peculiarity, it is always even, for example 500, 1000, 2000. Bellow attached a screenshot from StackDriver of this problem. I'm using commit [`6521623`](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/65216237311a9cfc641e2ec8188df94c0e05ddf4)

![pubsub](https://cloud.githubusercontent.com/assets/4804060/23186551/ab44c074-f8db-11e6-8588-cf62e292d6a3.jpeg)
(undelivered messages metrics)

**Comment by pongad** [comment]
This looks a lot like #684. I believe the part relevant to this issue is already resolved.
