### ISSUE TITLE
civil: rename to civiltime

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#526]
"civil" is a broad name to represent specifically civil time related types and utilities. "civiltime" will be more representative of what it actually provides. I am glad to make the change if everyone agrees.

/cc @jba @zombiezen

**Comment by jba** [comment]
Can we wait for (a) aliases and/or (b) a possible replacement for golang.org/x?

**Comment by zombiezen** [comment]
The end effect of this on calling code seems minimal: change the import path and optionally locally bind it as civil.  Isn't it just Spanner (alpha) that depends on this, or am I misremembering?

**Comment by jba** [comment]
Also bigquery.

I like `civil` because it works well in the name: `civil.Date`, `civil.Time`. If it lived in a `time` directory, then the path would be `something/time/civil`, which gets the time in there. I imagine/hope it will eventually end up in such a place.

Prior art where the package name needs the full import path to make sense:
* encoding/binary
* database/sql/driver
* go/parser

For now, I'd be willing to push it down into a time subdirectory (although it would be otherwise empty).

**Comment by rakyll** [comment]
At the worst case, we can use the "Deprecated" notice for a while and preserve a copy at civiltime, see https://rakyll.org/deprecated/.

I don't think putting it under a time sub package makes the clear case. We don't name packages util even they are under "io", see "io/ioutil".

We have a chance to fix it now or we won't ever be able to fix it in 6 months. The compatibility promise is the main reason why standard library APIs, naming and organization is not as optimal as we would desire to have at this stage. Let's not make the same mistakes because they are historically made and are not fixable.

**Comment by jba** [comment]
One of the design principles of packages is to avoid stutter. If we called the package civiltime, we'd have civiltime.Time and civiltime.DateTime. 

> I don't think putting it under a time sub package makes the clear case. We don't name packages util even they are under "io", see "io/ioutil".

I gave some examples of packages whose names are too general on their own, but make sense in their path. "server" is another common one. I think civil fits in that category.

**Comment by jba** [comment]
Most likely, this package will end up on a different import path entirely, making this issue moot. So closing.
