### ISSUE TITLE
pubsub: /google.pubsub.v1.Publisher/CreateTopic stalls on AppEngine locally

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#527]
Consider the following AppEngine app:

```
package hello

import (
	"log"
	"net/http"

	"cloud.google.com/go/pubsub"
	"google.golang.org/appengine"
)

func init() {
	http.HandleFunc("/", handler)
}

func handler(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)

	client, err := pubsub.NewClient(ctx, "bamboo-xxx")
	if err != nil {
		log.Fatalf("pubsub Client initialize failed %v", err)
	}

	topic, err := client.CreateTopic(ctx, "events")
	if err != nil {
		log.Fatal(err)
	}

	_ = topic
}
```

The calls to CreateTopic is stalling for a long period of time when run locally and never return back.

**Comment by rakyll** [comment]
Needs investigation, please report any findings if you have more insights about the problem.

**Comment by broady** [comment]
Not surprising. I think gRPC has issues running over App Engine's Socket API. I've reproduced something similar with Datastore.

**Comment by lucas-natraj** [comment]
i seem to have hit this issue today when using the `cloud.google.com/go/datastore` Client on AppEngine standard. 
consistently get `error: rpc error: code = Unavailable desc = grpc: the connection is unavailable`

**Comment by jba** [comment]
Are you folks still seeing this issue? If not, I'll assume it's been fixed.

**Comment by lucas-natraj** [comment]
unfortunately, i haven't had a chance to try it, and it may be a week or so till I can. 
but if you aren't able to repro it anymore, I'm fine with closing the issue.
i'll ping if i hit the problem again.
