### ISSUE TITLE
storage: MD5 representations inconsistent

### ISSUE THREAD

**Issue by drtriumph** [GoogleCloudPlatform/google-cloud-go#531]
The use of `MD5 []byte` in both `SignedURLOptions` and `ObjectAttrs` to both mean "an encoded base64 string of the hash, in []byte form", and "the hash itself", respectively, is confusing - and lead me to have to read the src to ensure I could trust the comment.

Perhaps either the name, the type, or both should be changed in `SignedURLOptions` to make it very clear that this is a base64 string (inside the package it's only used for a `fmt.Fprintf(buf, "%s\n", opts.MD5)`), perhaps something like:

```go
    // MD5Hash is the base64 encoded MD5 checksum of the file.
    // If provided, the client should provide the exact value on the request
    // header in order to use the signed URL.
    // Optional.
    MD5Hash string
```

Given that this is a breaking API change, I'm hesitant to make a PR, what do the authors of this repo think?

**Comment by broady** [comment]
The ideal is definitely to use `[]byte` consistently.

We could change `SignedURLOptions.MD5` to a string, which is consistent with the other "Base64 encoded hash" (like `CustomerKeySHA256`).

At this point, I think the only feasible option is to change the field in SignedURLOptions to a `string`. We shouldn't retain the `[]byte` type and change its meaning. I don't think we'd need to rename the field.

/cc @jba (currently on vacation)
/cc @zombiezen

**Comment by zombiezen** [comment]
I am in favor of making `[]byte` usage consistent.  At the very least, are we currently erroring if the author passes something that isn't a valid (base64 | hex | raw) hash?

**Comment by drtriumph** [comment]
I think simply making it a `string` fixes the confusion.

As for validation @zombiezen - there is none whatsoever, it would definitely be good to have some in there to prevent the library from creating upload URLs that can never be valid

**Comment by drtriumph** [comment]
See https://code-review.googlesource.com/#/c/11173/
