### ISSUE TITLE
trace: Expose Span.tracing

### ISSUE THREAD

**Issue by luna-duclos** [GoogleCloudPlatform/google-cloud-go#533]
Span.tracing returns whether or not things are currently being traced.
It should be exposed so that callers can determine whether to store the TraceID, alternatively, the TraceID should be "" when this function returns false.

**Comment by rakyll** [comment]
We should probably consistently return empty string for spans that are not traced.

I think we also need to revise which spans we are auto-generating a trace ID/span ID for. In the following example, span has a trace ID even though the request was not traced:

```
req, _ := http.NewRequest("GET", "https://users.service/users", nil)
span := traceClient.SpanFromRequest(req)
```

**Comment by rakyll** [comment]
Blocked, because we haven't reached to consensus for the behavioral change at https://code-review.googlesource.com/c/11311/.

**Comment by rakyll** [comment]
I am thinking about exporting Header from the trace package, see https://code-review.googlesource.com/c/11414/.

```
func (s *Span) Header() string {
	return spanHeader(s.trace.traceID, s.span.ParentSpanId, s.trace.globalOptions)
}
```

Header might rather be the following instead. So we don't have to increase the API surface to add a `Traced() bool` method.

```
func (s *Span Header() (header string, traced bool)

**Comment by luna-duclos** [comment]
Perhaps changing the signature of the TraceID function in the same fashion
would be useful too ?

**Comment by rakyll** [comment]
Yes, we can apply the same to the TraceID method.

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/c/11417/. We won't return an empty string, but will set ok to false.
