### ISSUE TITLE
all: extraneous files after running tests

### ISSUE THREAD

**Issue by adams-sarah** [GoogleCloudPlatform/google-cloud-go#534]
Running all tests locally (with `go test ./...`) leaves files like:
```
	127.0.0.1:49577:
	127.0.0.1:49588:
	127.0.0.1:49592:
	127.0.0.1:49832:
	127.0.0.1:49835:
	127.0.0.1:49838:
	127.0.0.1:49844:
	127.0.0.1:49847:
	127.0.0.1:49851:
	aborted
	finished
	queueingRetryable
	queueingRetryable-
	queueingUnretryable
	queueingUnretryable-
	unConnected
```

in project root.

Thoughts on adding a `.gitignore` to ignore these files?

**Comment by adams-sarah** [comment]
cc @rakyll

**Comment by jba** [comment]
We should probably track those down and eliminate them, or put them somewhere else.

**Comment by broady** [comment]
Where are they coming from? Let's get rid of them.

**Comment by adams-sarah** [comment]
I have no idea where they're coming from. I think they're new-ish; I don't remember seeing these last time I built all (over a month ago).
I'll track them down.

**Comment by rakyll** [comment]
Looks like they are coming from the Spanner tests.

**Comment by jba** [comment]
This is a mystery.

They must be coming from the spanner tests, and I sort of see how, but not really. Those tests contain strings like `"unConnected->queueingRetryable->queueingRetryable"`. If that were executed by the shell, it would create files `queueingRetryable-` and `queueingRetryable` before complaining that `unConnected-` was not a command. But those strings are only printed as part of test error messages, using `%v`. I don't see how the shell could be running them.

I don't see these files when I run `go test ./...` from cloud.google.com/go. Does anyone else other than Sarah?

**Comment by adams-sarah** [comment]
I can't repro again :(.
Maybe it was something else that generated the files? I'll keep digging.

**Comment by adams-sarah** [comment]
omg I see what happened.
I had the last build output in my clipboard and mistakenly pasted into shell before pasting what I meant to - the go test cmd.

That explains it. 
Sorry for confusion.
