### ISSUE TITLE
Datastore docs should be explicit about what Load/Get do to fields not present in the []Property

### ISSUE THREAD

**Issue by alercah** [GoogleCloudPlatform/google-cloud-go#535]
If you do a `Get` (or at a lower level, a `Load`) into a struct that wasn't freshly initialized, what happens? Are all the unknown fields zeroed out, or are they left as-is?

**Comment by adams-sarah** [comment]
Fields not in the []Property are left as-is. I'll update docs.

**Comment by adams-sarah** [comment]
Ah, looks like it's already in the docs: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/datastore/datastore.go#L341-L343

**Comment by alercah** [comment]
Ahhh! Not the best place for it, but it works :)

**Comment by adams-sarah** [comment]
This appears in the godoc comment for client.Get method, which is entry point for user for Load.
Where would you suggest instead?

**Comment by alercah** [comment]
I was looking at Load because I was trying to implement the
PropertyLoaderSaver (sp?) interface and wanted to make sure that I found
load some properties myself, then hand the rest to Datastore to finish. It
might make sense to have it in both places.

I later realized that I could tag the fields as datastore:"-" and have
Datastore do its load first. But it would be good to reference it in Load I
think.

**Comment by adams-sarah** [comment]
Okk. I will add it on load too. Thanks for the feedback.
