### ISSUE TITLE
trace: introduce a http.Client wrapper that traces all outgoing requests

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#540]
It would be great to export a custom http.Client that automatically creates spans for each outgoing requests and finishes them during RoundTrip.

Assume that the trace package returns a custom client that automatically follows the outgoing the requests:

```
func (c *Client) HTTPClient() *http.Client


// With a parent span.
req := http.NewRequest("GET", "https://google.com/", nil)
req = req.WithContext(context.WithValue(trace.ParentSpan, s))
client := traceClient.HTTPClient()
_, err := client.Do(req)

// Without a parent span.
req := http.NewRequest("GET", "https://google.com/", nil)
client := traceClient.HTTPClient()
_, err := client.Do(req)
```

Maybe we can experiment with this idea under trace/traceutil and see how it works. Such a utility would help our users start tracing outgoing requests without learning much about this package. Feedback is welcomed.

/cc @jcd2 @zombiezen @jba @broady

**Comment by rakyll** [comment]
`trace.ParentSpan` seems unnecessary. We can also expect to see the parent span in req's context.

Then, we can basically use `FromContext` to retrieve it.

**Comment by nightlyone** [comment]
Could you design it to be stackable?
So 

client := traceClient.HTTPClient()

becomes

oldClient:=new(http.Client)
client := traceClient.HTTPClient(oldClient)

That will compose better with other libraries doing the same.

**Comment by rakyll** [comment]
@nightlyone, yes! The API should take a base client somewhere. I don't know why I avoided this in the original proposal.

```
func (c *Client) HTTPClient(orig *http.Client) *http.Client
```

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/c/11312/.
