### ISSUE TITLE
trace: export cloudPlatformScope as Scope

### ISSUE THREAD

**Issue by dhowden** [GoogleCloudPlatform/google-cloud-go#543]
Currently it's not easy to reference the scope when setting up credentials for the trace client.

Can trace be updated to export the required scope? Other libraries in this repo do similar: bigquery.Scope, datastore.ScopeDatastore, etc (albeit slightly inconsistently 😜).

Also: from a few tests it would seem that `https://www.googleapis.com/auth/trace.append` is sufficient at the moment (not to mention somewhat more aptly named!).

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/c/11351/.
