### ISSUE TITLE
speech: encountering `rpc error: code = 13 desc = transport is closing` error

### ISSUE THREAD

**Issue by slash7** [GoogleCloudPlatform/google-cloud-go#544]
Hi, 

While using the speech API I sometimes encounter an gRPC error : 
```
receiveing rpc error: code = 13 desc = transport is closing
```

```golang
resp, err := client.SyncRecognize(ctx, &speechpb.SyncRecognizeRequest{
		Config: &speechpb.RecognitionConfig{
			Encoding:        speechpb.RecognitionConfig_LINEAR16,
			SampleRate:      16000,
			LanguageCode:    "en-US",
			MaxAlternatives: 1,
		},
		Audio: &speechpb.RecognitionAudio{
			AudioSource: &speechpb.RecognitionAudio_Uri{Uri: "gs:/REDACTED_FILE_NAME"},
		},
	})
```
The error does not appear every time. 
I've tested with audio files that are less than 30 seconds.  Some very small files, 5 sec or less are working more often.

**Comment by jba** [comment]
It should work for files less than one minute, so this is a bug, but it may not be a bug in our client. Code 13 is INTERNAL, and we don't retry automatically on INTERNAL. It's not clear we can fix this in our client; you may have to implement the retry yourself.

Have you tried AsyncRecognize as a workaround?

**Comment by slash7** [comment]
@jba thanks for taking a look at this.
I tracked down the issue to the request timeout period.
I'm using GAE, if I manually modify the context timeout to 60 seconds and send audio files that are less than one minute long it works.

**Comment by jba** [comment]
OK, good to know it's a GAE thing. We'll consider this closed, but reopen if you need to.
