### ISSUE TITLE
bigquery: Suggestion: allow access to the temporary created table by bigquery.go

### ISSUE THREAD

**Issue by Zanndorin** [GoogleCloudPlatform/google-cloud-go#547]
In both [QueryConfig](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/query.go) and [JobQueryConfig](https://godoc.org/google.golang.org/api/bigquery/v2#JobConfigurationQuery) it is stated that if the Destination table is empty a Temporary table will be created. Why not let users access this table for further operations instead of forcing them to create their own temporary table to do these operations on? In my case I wanted to start an export job on the query results (why is there not a query&extract job anyway?). For me the most intuitave way after reading the documentation was to use the temporary table created by the query / job.

**Comment by jba** [comment]
To get the temporary table:
```
q := client.Query(...)
job, err := q.Run(ctx)
// handle err
config, err := job.Config()
// handle err
tempTable := config.(*QueryConfig).Dst
```
