### ISSUE TITLE
trace: export a gRPC interceptor for incoming calls

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#548]
We currently only intercept outgoing calls, not providing a `grpc.UnaryServerInterceptor` to trace the outgoing ones; this is limiting the users to have an end-to-end tracing experience without handling the incoming calls themselves.

Even though the client interceptor is experimental, I will extend the package with a server interceptor to provide symmetrical support.

**Comment by harlow** [comment]
@rakyll let me know if there is anything I can do to help here. I have a little [toy project](https://github.com/harlow/go-micro-services) that does cross-service traces; happy to help test end-to-end functionality.

Are you thinking of passing the trace header in the context metadata? If so, one thing that might need some consideration is the `SPAN_ID` and whether it should be incremented each time the trace header is parsed by a downstream service.

```
TRACE_ID/SPAN_ID;o=TRACE_TRUE
```

**Comment by rakyll** [comment]
@harlow, it would be great to have feedback once the server interceptor is also in.

We are passing the trace header in the request header. This is the defacto propagation method Stackdriver supports. It enables cases with more than one language. For example, if you make a gRPC call from a Go client to a Java Server, our Java client library will be able to extract the span from the header.

**Comment by rakyll** [comment]
In the meantime, I asked the gRPC team if they have agreed on a standard for passing the trace info. Given, the clients don't allow to access the underlying request object, the defacto place to look at shouldn't be in the header. I will update once I know the answer.

**Comment by rakyll** [comment]
Mailed https://code-review.googlesource.com/c/11414/, the key is TBD.

**Comment by harlow** [comment]
Tried leaving a comment on the Gerrit system but unclear if it worked (doesn't seem to be showing anymore).

Thoughts namespacing the caller span similar to `grpc-go`:

```go
c.traceInfo.tr = trace.New("grpc.Sent."+methodFamily(method), method)
defer c.traceInfo.tr.Finish()
```

https://github.com/grpc/grpc-go/blob/d50cf2db166eaff3f2429425758d12205085eb5b/call.go#L170-L171

I'm curious to see what it looks like in the UI if there isn't a distinction between the Client and Server spans.

**Comment by dhowden** [comment]
@rakyll Awesome addition!  We have our own version of this running in production now, and our implementation is very similar (putting the trace header into metadata).  I've added a few comments to the current diff in Gerrit, hopefully it worked properly!

**Comment by dhowden** [comment]
Further to @halow's point: we are using `grpc.Sent` in client interceptors, but only using the method path in server interceptors (i.e. not `grpc.Recv` as in the `grpc-go` built-in hooks for `x/net/trace`).

It does mess up the URL-naming scheme that the Stackdriver UI uses, so we get things like `/grpc.Sent/endpoint.full.path...` in our traces, but it's very useful to quickly see the time lost in-between the invocation of the client method and the start of the server handler.

Not sure how you plan to handle this for the general library though.  The whole Stackdriver Tracing UI seems to assume that all traces are for HTTP requests (there are filters for request methods GET/POST/etc, and returned status codes).  Hopefully there are plans to update this to include more generic filtering criteria, or just things more friendly to gRPC (i.e. filtering by services, gRPC codes etc...).

**Comment by ahmetb** [comment]
Great to see this merged. Any ideas how can I use 

    func GRPCServerInterceptor(*trace.Client) grpc.UnaryServerInterceptor

in the `grpc.NewServer()`?
