### ISSUE TITLE
trace: explain that spans have two halves if resurrected at the server

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#549]
If a trace.Span is created from an incoming request, SpanFromRequest will return a second half for the original span created remotely. Second halves can create children and are finishable. They might traced or not traced and that attribute should be passed down to the children.

Document how SpanFromRequest work and the relationship with the two halves.

**Comment by Bo0mer** [comment]
Hi,

I want to ask and this issue and https://github.com/GoogleCloudPlatform/google-cloud-go/issues/538 seem to be related to my question.

I have a `http.Handler` that handles requests that are both traced and not traced by remote clients.
The problem I'm facing is that there is no way to tell if the `span` returned by `SpanFromRequest` will be uploaded to the server or not other than checking if the `X-Cloud-Trace-Context` header is set.

Is this the right way to do it, and can I expect that this behavior will be stable enough?

```go
func traceHandler(w http.ResponseWriter, req *http.Request) {
	span := traceClient.SpanFromRequest(req)
	if xtrace := req.Header.Get("X-Cloud-Trace-Context"); xtrace == "" {
		span = traceClient.NewSpan("trace")
	}
	defer span.Finish()

	// Do some work by calling some downstream dependencies.
}
```

Thanks and regards,
Ivan

**Comment by rakyll** [comment]
SpanFromRequest will always return a non-nil span and will upload depending on the client sampling policy. You should be able to achieve the behavior simply by:

```
func traceHandler(w http.ResponseWriter, req *http.Request) {
	span := traceClient.SpanFromRequest(req)
	defer span.Finish()

	// Do some work by calling some downstream dependencies.
}
```

**Comment by Bo0mer** [comment]
The problem is that I want to upload the traces regardless of the client. The doc for `SpanFromRequest` says:

```
...
If the request is not being traced, then a *Span is returned anyway, but it will not be uploaded to the server -- it is only useful for propagating trace context to child requests and for getting the TraceID. ...
```

This is why I add the check for the `X-Cloud-Trace-Context` - this is the mechanism I'm using to determine whether the request is being traced by the client which sent it. If it is traced - it will be uploaded based on its sampling policy. But if the header is missing, I'm creating a new span - to make sure that it will get uploaded too.

Thanks,
Ivan

**Comment by jba** [comment]
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).
