### ISSUE TITLE
bigquery: allow creation of date-partitioned tables

### ISSUE THREAD

**Issue by fortytw2** [GoogleCloudPlatform/google-cloud-go#550]
As far as I can tell, it's not possible to create a date-partitioned table via https://godoc.org/cloud.google.com/go/bigquery#Table.Create currently. This would be wonderful to be able to do (not sure how inserting into them works right now, either)

**Comment by BlueMonday** [comment]
@fortytw2 I think this lets you create date partitioned tables: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/table.go#L183

For example: 

```go
	ctx := context.Background()
	client, err := bigquery.NewClient(ctx, "project-id")
	if err != nil {
               return err
	}

	table := client.Dataset("my_dataset").Table("new-table")
	if err := table.Create(ctx, bigquery.TimePartitioning{}); err != nil {
               return err
        }
```

**Comment by fortytw2** [comment]
Weird! I definitely missed that, huge thanks @BlueMonday !
