### ISSUE TITLE
datastore: embedded struct value, PLS not respected

### ISSUE THREAD

**Issue by adams-sarah** [GoogleCloudPlatform/google-cloud-go#551]
When a ptr-to-struct type implements a PLS, but the struct *value* is embedded in a parent struct (not pointer), the PLS implementation is not respected.

Eg.
```go
type A struct {
	I int
}

func (a *A) Load([]Property) error {
	// ...
}

func (a *A) Save() ([]Property, error) {
	// ...
}

type Parent struct {
	A A
}
```

Original report: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/546#issuecomment-285506960

**Comment by dragonsinth** [comment]
Thanks!

**Comment by ianrose14** [comment]
👍
