### ISSUE TITLE
datastore: embedded PLS values not respecting `flatten` option

### ISSUE THREAD

**Issue by adams-sarah** [GoogleCloudPlatform/google-cloud-go#552]
If a child struct field implements PLS, the returned PLS properties are always stored as an Entity, even if the parent field had the `flatten` option enabled.

eg. 

```go
type A struct {
    Parent Parent `datastore:",flatten"`
}

type Parent struct {
    Child Child
}

type Child struct {
    I int
}

func (c *Child) Load(props []Property) error { /* ... */ }
func (c *Child) Save() ([]Property, error) { /* ... */ }
```

returned properties from A.Save would be:

```
[]Property{
    {Name: "Parent.Child", Value: Entity{Properties: []Property{{Name: "I", Value: 0}}}}
}
```

when it should be:

```
[]Property{
    {Name: "Parent.Child.I", Value: 0}
}
```

See https://github.com/GoogleCloudPlatform/google-cloud-go/issues/546#issuecomment-285746646 for original report

**Comment by adams-sarah** [comment]
@dragonsinth

**Comment by dragonsinth** [comment]
thanks!  I'll patch this in and give it a whirl

**Comment by adams-sarah** [comment]
Awesome. Thanks for the report.
