### ISSUE TITLE
Test top 4 APIs on GAE Flex, GKE, and GCE

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-go#557]
Test BigQuery, Storage, Datastore, and Logging client libraries on all the GCP platforms (don't include GAE Standard).

Close this issue once we confirm it all works.

**Comment by broady** [comment]
Manually? I confirm they work on Flex, have used on GKE and GCE, too.

Can check again, if it's an immediate concern.

We have end-to-end tests for storage and datastore via sample code for Flex, but not yet for GKE and GCE.

**Comment by omaray** [comment]
Manually for now works yes. To make sure our customers won't hit any issues. We can definitely talk about automation too (and regular automation with every release or nightly for instance).

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
