### ISSUE TITLE
pubsub: Potential goroutine leak with the new async topic.Publish()

### ISSUE THREAD

**Issue by oyvindsk** [GoogleCloudPlatform/google-cloud-go#558]
I have a long-running service that leaks goroutines after the latest changes to pubsub. Not sure if this is a bug or if I'm just doing something wrong or .

**From /debug/pproff:**

    goroutine profile: total 153646
    147725 @ 0x42e27a 0x42e35e 0x406991 0x406605 0x821190 0x45a861
    #	0x82118f	cloud.google.com/go/pubsub.(*Topic).initBundler.func1+0x5f	/root/src/cloud.google.com    /go/pubsub/topic.go:253
    
    5909 @ 0x42e27a 0x43d3e4 0x43c04c 0x73c021 0x45a861
    #	0x73c020	google.golang.org/api/support/bundler.(*Bundler).background+0x480	/root/src/google.golang.org/api/support/bundler/bundler.go:270

**Example goroutine:**

     goroutine 307 [chan receive, 140 minutes]:
     cloud.google.com/go/pubsub.(*Topic).initBundler.func1(0xc420181140, 0xc420181080, 0x7fc2f6dec070, 0xc420010458)
     	/root/src/cloud.google.com/go/pubsub/topic.go:253 +0x60
     created by cloud.google.com/go/pubsub.(*Topic).initBundler
     	/root/src/cloud.google.com/go/pubsub/topic.go:256 +0xe3

**The code that calls Publish() looks like this:**

	topic := psCli.Topic(psTopic)

	// Publish ping to pubsub
	// "Publish returns a PublishResult, which behaves like a future: its Get method blocks until the message has been sent to the service."
	pr := topic.Publish(ctx, psMsg)
	sid, err := pr.Get(ctx) // block until it's sent. This could be cancelled with ctx.Done()
	if err != nil {
		return err
	}

	log.Printf("Sendt Service Ping! (server id: %v)", sid)

	return nil

HEAD is a262d3f

Does the comment on line 250 indicate that is a known problem? 
https://github.com/GoogleCloudPlatform/google-cloud-go/blame/master/pubsub/topic.go#L250

**Comment by jba** [comment]
A missing Topic.Stop would be a problem if you re-created the topic. Does your program call psCli.Topic more than once?

**Comment by oyvindsk** [comment]
Ah, yes it does. Thanks @jba . I mistakenly though psCli.Topic() did almost nothing, and happily called it all the time. 

I guess that even with Topic.Stop() this would have been pretty ineffective? 

OK for me to close this, but it could also be renamed to a "topics are never stopped" kind of issue if you think that would be better.

**Comment by tiagopog** [comment]
I think this is really worth mentioning in the Go's Pub/Sub documentation. I went through the same problem – some pods in my Kubernetes cluster simply didn't stop allocating more and more memory – and it took me a lot of hours to discover that the problem was related to the re-call of `pubsub.Client.Topic()`, which is not clear/shown in the docs or examples available out there.

**Comment by jba** [comment]
Let me know if https://code-review.googlesource.com/11652 helps.

**Comment by tiagopog** [comment]
SLTM 👍

**Comment by backnotprop** [comment]
Something that isnt clear still, is if `pubsub.Client.Topic()` should be called outside of API handlers, e.g. an api endpoint that handles high-throughput requests and publishes to a topic in that handler. 

Dealing with `Kubernetes cluster simply didn't stop allocating more and more memory ` currently around this example:

```
// echo labstack example
func (a *app) apiHandler(c echo.Context) error {
	logger := c.Get("logger").(*logger.Logger)

	dataBytes, err := ioutil.ReadAll(c.Request().Body)
	if err != nil {
		logger.Error("error reading request body", err, nil)
		return c.JSON(500, nil)
	}

        // HERE -- should this be a singleton instead?
	topic := a.pubsubclient.Topic(a.Topic)

	defer topic.Stop()

	ctx := context.Background()
	res := topic.Publish(ctx, &pubsub.Message{
		Data: dataBytes,
	})
	// The publish happens asynchronously.
	// Later, you can get the result from res:
	msgID, err := res.Get(ctx)
	if err != nil {
		logger.Error("error sending to topic", err, nil)
		return c.JSON(500, nil)
	}

```
