### ISSUE TITLE
Metadata broken for Operation returned by CreateInstance in spanner client

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-go#559]
Following code fails with the error:
``
mismatched message type: got \"google.spanner.admin.instance.v1.CreateInstanceMetadata\" want \"google.spanner.admin.instance.v1.UpdateInstanceMetadata\""
``

op, err := client.CreateInstance(context.Background(), &instancepb.CreateInstanceRequest{
 Parent:     "projects/" + s.ProjectId,
  InstanceId: params["name"],
  Instance: &instancepb.Instance{
              Name:        "projects/" + s.ProjectId + "/instances/" + params["name"],
              DisplayName: displayName,
              NodeCount:   int32(numNodes),
              Config:      loc,
       },
})
_, err = op.Poll(context.Background())
metadata, err := op.Metadata()

It seems the issue is that the autogenerated code has generated the same LRO type for both UpdateInstance and CreateInstance operations.
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/spanner/admin/instance/apiv1/instance_admin_client.go#L583

**Comment by pongad** [comment]
Please see https://github.com/googleapis/toolkit/pull/1115 for potential solution.
