### ISSUE TITLE
errors: implement (*Client).Close()

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/google-cloud-go#562]
Currently there's no way to clean up an errors client. I want a service that reports errors on behalf of others (to do things like source mapping, etc). Not having a way to clean up means resources leak.

**Comment by rakyll** [comment]
This is now a bigger requirement. We can stop all working Topics and make them flush before we Close.

**Comment by zombiezen** [comment]
@adams-sarah Could you take this one, too?

**Comment by adams-sarah** [comment]
Yes, definitely.

**Comment by rakyll** [comment]
(I should have commented on the wrong issue, ignore my comment above.)
