### ISSUE TITLE
spanner: Start creating sessions in the session pool eagerly

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-go#565]
Currently spanner client creates sessions as needed. This can mean that the first request that comes in also has to pay the cost of creating a session. We should optionally start creating sessions in a goroutine as soon as client is created so that we can pay some of this cost in the background.

**Comment by broady** [comment]
Is this just something that could be documented?

That is, encourage users to send a "SELECT 1" query to warm up the client?

**Comment by vkedia** [comment]
We can document it but I am not sure if most people would read that. Also its an additional burden on the user which we can alleviate to some extent by doing what I suggested.

**Comment by broady** [comment]
Yeah, definitely puts the burden on the user. It's not something I'd want to add a knob for. That would just pollute an already complicated API surface.

If it's commonly needed, then let's turn it on by default. I don't see much of a downside.
If it's not commonly needed, then providing an example of a warmup request like above should suffice.

**Comment by vkedia** [comment]
I agree that doing this just by default (and not having an option for this) is better.

**Comment by larryxiao** [comment]
I think this can be closed with [spanner: add session pool maintainer to maintain the session pool size](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/5d569738354f4228407cb88f24f06c3738414042)?

**Comment by vkedia** [comment]
Yes you are right.

**Comment by yoheimuta** [comment]
@vkedia I could not find a way for users to set healthCheckMaintainerEnabled to true. Is it intentional that healthCheckMaintainerEnabled is always false? If this can be changed to true, I think that this issue will be resolved.

- https://github.com/GoogleCloudPlatform/google-cloud-go/blob/8dff92c85f4225d90bdd100ea741d9903acc259e/spanner/session.go#L368-L369

**Comment by larryxiao** [comment]
@yoheimuta it should be enabled by default now :) https://github.com/GoogleCloudPlatform/google-cloud-go/commit/01a416d37f408c6ab5b3d278338637813ba8af9a

**Comment by yoheimuta** [comment]
Thanks!
