### ISSUE TITLE
trace: underlying error is not displayed for uploading traces

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#568]
When I added some trace code for the first time, I got this error:

    2017/03/19 12:47:04 failed to upload 3 traces to the Cloud Trace server

I had no way of figuring out what is going on other than going into the source code for trace package and adding the underlying error myself.

IMO the actual underlying error should be displayed to help debugging when uploading traces fail.

**Comment by rakyll** [comment]
Sent out https://code-review.googlesource.com/c/11591/.
