### ISSUE TITLE
pubsub: panic when calling Topic.Stop() without publishing

### ISSUE THREAD

**Issue by bradleyfalzon** [GoogleCloudPlatform/google-cloud-go#570]
Hi,

There appears to be a panic when stopping a topic before publishing any messages.

This appears to be because the bundler is lazy loaded using `sync.Once` (https://github.com/GoogleCloudPlatform/google-cloud-go/blob/966116da4589c8b3b8e3f721bce15de99572f188/pubsub/topic.go#L212), but a call to `topic.Stop()` panics (https://github.com/GoogleCloudPlatform/google-cloud-go/blob/966116da4589c8b3b8e3f721bce15de99572f188/pubsub/topic.go#L241) with a nil pointer dereference.

Minimal example, although is occurs during a full setup with subscription too.

```go
package main

import (
        "log"

        "cloud.google.com/go/pubsub"
        "golang.org/x/net/context"
        "google.golang.org/grpc"
        "google.golang.org/grpc/codes"
)

func main() {
        ctx := context.TODO()
        client, err := pubsub.NewClient(ctx, "gopherci-dev")
        if err != nil {
                log.Fatal(err)
        }

        log.Print("creating topic")
        topic, err := client.CreateTopic(ctx, "test-topic")
        if code := grpc.Code(err); code != codes.OK && code != codes.AlreadyExists {
                log.Fatal(err)
        }

        log.Printf("stopping topic")
        topic.Stop()
        log.Printf("topic stopped")
}
```

**Comment by jba** [comment]
Fixed by https://code-review.googlesource.com/11523.
