### ISSUE TITLE
Best practice for receiving

### ISSUE THREAD

**Issue by matthewvalimaki** [GoogleCloudPlatform/google-cloud-go#571]
I am trying to understand what would be the best practice for receiving. Right now the documentation states the following `The callback is invoked concurrently by multiple goroutines, maximizing throughput. To terminate a call to Receive, cancel its context.` and I am unclear of the context usage.

In my specific use case I have one program which uses multiple pre-created subscriptions. This program only receives and I want stop receiving when program is asked to exit.

So in the documentation it states `cancel its context` and then in example it calls `context.Background()` once for client and once for the receive. Given my use-case should I use one context or one for each?

**Comment by broady** [comment]
Something like this:

```
	ctx, cancel := context.WithCancel(context.Background())

	sigc := make(chan os.Signal, 1)
	signal.Notify(sigc, os.Kill, os.Interrupt)

	go func() {
		sig := <-sigc
		log.Printf("Got signal %v", sig)
		cancel()
	}()

	// Use ctx here.
	_ = ctx
```

**Comment by matthewvalimaki** [comment]
@broady thank you for the quick reply. You did not comment on my question if I should use one context or multiple ones. Your example code suggests to use one. I need to definitely learn context more to be able to answer my own question, but I would appreciate your comment on this matter.

**Comment by broady** [comment]
If you're just cancelling them all together, then a single context is fine.

Using multiple contexts is fine, too, but unnecessary unless you need to handle cancelation in a more granular manner.

**Comment by matthewvalimaki** [comment]
Understood. Thank you for the clarification.
