### ISSUE TITLE
Documentation example for receive contains a typo

### ISSUE THREAD

**Issue by matthewvalimaki** [GoogleCloudPlatform/google-cloud-go#572]
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/1f6cb61c9e1ca4af0385fd194041afee7ba7af95/pubsub/doc.go#L62

This should be `m` not `msg`.

**Comment by rakyll** [comment]
Sent out https://code-review.googlesource.com/c/11592/.

**Comment by matthewvalimaki** [comment]
@rakyll thanks for the quick reaction. The next line, 63, also references to `msg`.

The other thing I just noticed is that `m *Message` should be `m *pubsub.Message`.

**Comment by rakyll** [comment]
@matthewvalimaki, you can leave comments on the Gerrit issues once you are signed it.

Thankfully, @jba noted it too. It is fixed now :)
