### ISSUE TITLE
[Proposal] traceutil: set labels for response metrics

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#573]
It looks like the ability to provide response metrics such as the `http/status_code` label exists in the `trace` package. However, when I am using `traceutil.HTTPHandler` I do not get those metrics in my traces.

I am trying to see if traceutil can use `WithResponse(resp)` method, but it doesn't seem that it is possible.

(Real-world example: in some error cases, such as timeouts, my spans take waay longer to finish and I return an error to the user. However I can't tell that it was an error response because http/status_code was not recorded.)

I think if we create a proxy  `http.ResponseWriter` instance in the `traceutil.HTTPHandler` , we can track the status code that is set on the object. Not to mention, we can add new metrics like `http/content_length`.

Any thoughts?

**Comment by ahmetb** [comment]
It appears like there is nothing stopping a user from creating their own `func(http.HandlerFunc)http.Handler` and intercepting calls to the `http.ResponseWriter` to capture things like status_code and content_length.

Possibly one can use such a `responseTracer` func to record response metrics:

    responseTracer(traceutil.HTTPHandler(aHandlerFunc))

So the main question becomes: Should we be automatically providing fields like `trace.cloud.google.com/http/status_code` out of the box in `traceutil.HTTPHandler`?

I feel like adding at least the status_code field would be an addition that a lot of users can make use of, which otherwise requires writing some code to wire up their own proxy ResponseWriter.

**Comment by rakyll** [comment]
These labels are to be set by the client-side, not the server. A server may return 404, but the client may receive 502 due to a disfunction at the load balancer. We need to record 502, not 404.

**Comment by rakyll** [comment]
You are more than welcomed to set custom labels on the server-side span to record what the server has responded though. Stackdriver Trace doesn't have a reserved label for the response attributes, hence we are not supporting it out-of-the-box from the trace package.

**Comment by ahmetb** [comment]
I still found it to be useful to record the responded_status_code, especially for instrumenting the user-facing HTTP endpoints (which do not have a parent span and the request comes from outside, so you don't know what the user actually observes).

I've got some example code here: https://play.golang.org/p/k-JjTlbNg5
