### ISSUE TITLE
all: autogenerated clients are broken

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#578]
All autogenerated packages are broken. For example:

```
$ go build cloud.google.com/go/trace/apiv1
# cloud.google.com/go/trace/apiv1
apiv1/trace_client.go:138: cannot use func literal (type func("golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
apiv1/trace_client.go:150: cannot use func literal (type func("golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
apiv1/trace_client.go:173: cannot use func literal (type func("golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
```

/cc @pongad @jba

**Comment by pongad** [comment]
@rakyll An update to autogenerated clients requires a corresponding change to [gax](https://github.com/googleapis/gax-go), could you try `go get -u`?

**Comment by rakyll** [comment]
It works on my local machine after a get -u, but kokoro tests are still failing: https://pantheon.corp.google.com/logs/viewer?project=go-cloud-kokoro&minLogLevel=0&expandAll=false&advancedFilter=resource.type%3D%22project%22%0Aresource.labels.project_id%3D%22go-cloud-kokoro%22%0AlogName%3D%22projects%2Fgo-cloud-kokoro%2Flogs%2Fkokoro-gocloud-gcp_ubuntu-presubmit-209-20170321-204149%22&timestamp=2017-03-22T03:42:48.775258267Z.

/cc @adams-sarah, we are `go get -u`'ing our dependencies, right?

**Comment by pongad** [comment]
Looking at this more closely, I don't think the `-u` thing is the problem. The function signature used to take 1 param, then it was updated to take 2. The error is complaining that autogenerated clients' function have 1 param. From this, I conclude that kokoro has the latest version of gax, it's actually go-cloud that is out of date in the build.

Does kokoro just checks out the commit then build it? Or does it rebase on top of master first? From the previous paragraph, I suspect that it is the former. Could you try rebasing your dev branch and push to Gerrit?

**Comment by rakyll** [comment]
Oh, kokoro doesn't rebase on the top of the master. The open CL was 33 CLs behind. Just rebased it and it works. Sorry for the noise.
