### ISSUE TITLE
trace: add more-standardised labels for grpc codes and errors

### ISSUE THREAD

**Issue by dhowden** [GoogleCloudPlatform/google-cloud-go#582]
Currently HTTP requests have standard label names for recording status codes, methods, etc.  At the moment gRPC has one label set by trace which is used when an RPC returns non-nil error:

```golang
// TODO: standardize gRPC label names?
span.SetLabel("error", err.Error())
```

Can we expand this to also seperate out the gRPC Code returned:

```golang
span.SetLabel("grpc/code", grpc.Code(err)) // see https://godoc.org/google.golang.org/grpc#Code
span.SetLabel("grpc/error", grpc.ErrorDesc(err)) // see https://godoc.org/google.golang.org/grpc#ErrorDesc
```

Note: `grpc/error` could be better named, `grpc/error_message`?. Also the code parameter can be set on every request.  Open for suggestions and tweaks!

Happy to make a CL for this if there's enough support for it.

**Comment by rakyll** [comment]
It would be a great to have some consensus with the API team before we reserve any more labels. I will suggest error code and description.

**Comment by dhowden** [comment]
Just wanted to check-in and see if there had been any progress on this?  If there is a public place where this is being discussed, would be great to have a link to it.

**Comment by jba** [comment]
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).
