### ISSUE TITLE
all: handle collisions in concurrent tests

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#583]
Some services provide no isolation for resources in the same project. For example, all metrics that you create with Stackdriver Logging as part of a project will be "global" to that project. So if you try to list metrics, you will get all of your project's metrics.

An integration test that tries to test the ListMetrics function by creating a bunch of metrics, listing them, and comparing the results will work fine when run in isolation (provided it cleans up after itself). But it will fail if run concurrently with another instance of itself, because it will see the other instance's metrics as well as its own.

Concurrent execution can and does happen (e.g. a CI system launches tests for each CL, and the CLs arrive faster than the tests finish). So these tests are flaky.

One solution (proposed by @pongad) is to impose a partition on the resources by creating each with an ID that identifies the test instance uniquely (like a nanosecond timestamp). We could make this work with our general [iterator testing package](https://godoc.org/google.golang.org/api/iterator/testing) by handing the tester a function that separates out the resources with the right timestamp.

**Comment by nightlyone** [comment]
If the nanosecond time is rounded to 1ms precision or even less precise, then collisions will still happen.

Just to provide an alternative to choose from: For CI systems alone passing a build id prefixed by the CI system id (e.g. travis-1234) works pretty well and supports multiple build systems at once.

**Comment by pongad** [comment]
Hmm you're right, I guess we can read `TRAVIS_BUILD_ID` env var?

**Comment by pongad** [comment]
@jba are we still seeing this? I believe we have resolved most of the issue?

**Comment by jba** [comment]
I haven't done a survey of all our tests to make sure they're isolated, so leaving open for now.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Long-Term-Plans.
