### ISSUE TITLE
nil pointer dereference in batch handling

### ISSUE THREAD

**Issue by devnev** [GoogleCloudPlatform/google-cloud-go#585]
We've seen multiple panics in production starting with following stack trace:

```
 runtime error: invalid memory address or nil pointer dereference
 stack trace 65536 bytes
 goroutine 1630159 [running]:
panic(0xcda0e0, 0xc420016030)
	/usr/local/go/src/runtime/panic.go:458 +0x243
cloud.google.com/go/datastore.(*Iterator).nextBatch(0xc420499dd0, 0xe05a7f, 0xb)
	src/cloud.google.com/go/datastore/query.go:668 +0x132
cloud.google.com/go/datastore.(*Iterator).next(0xc420499dd0, 0xc420dba0e0, 0x197, 0xc66720, 0xc421251040)
	src/cloud.google.com/go/datastore/query.go:621 +0x45
cloud.google.com/go/datastore.(*Client).GetAll(0xc4203def40, 0x7faf99486140, 0xc4210d7a40, 0xc420e6c270, 0xc3d8c0, 0xc420dba0e0, 0xc41ff922f8, 0xc4221d0cb8, 0x41288e, 0x40f07f, ...)
	src/cloud.google.com/go/datastore/query.go:498 +0x102
```

As of yet the reproduction case is not clear. The GetAll was on ~3500 entities.

**Comment by adams-sarah** [comment]
Can you paste the commit SHA for your cloud.google.com/go pkg which generated this panic?
Will be hard to debug otherwise. The line numbers in your stack trace don't match master.

**Comment by devnev** [comment]
We have glcoud.google.com/go vendored at commit 30b36ef. The line creating the panic is https://github.com/GoogleCloudPlatform/google-cloud-go/blob/30b36efdf5c81a1d3f9fac38e1496c29e8adc420/datastore/query.go#L668

**Comment by adams-sarah** [comment]
Thanks.
Seems probable that the returned `resp` can have a nil `Batch` and we're not accounting for it.
@jba can you take a look?

**Comment by jba** [comment]
That seems to be the only explanation, but the [docs](https://cloud.google.com/datastore/docs/reference/rest/v1/projects/runQuery) say that it can't happen.

If you can reproduce, that would be great.

**Comment by jba** [comment]
I just consulted with the Google Datastore team, and they don't see how `Batch` can be nil. This may be a bug in our client, but I can't see how. Without more information or a repro I don't think we'll make progress. You can try adding some log statements to your vendored client. Printing `t.req` and `resp` with `%#v` may tell us something.

**Comment by devnev** [comment]
It looks like this may be a bug in a gRPC client interceptor we use for retrying GDS RPCs. I am upstreaming a fix for the gRPC middleware in question. I'll close this issue for now, thank you for your patience.
