### ISSUE TITLE
No Debian/Ubuntu package?

### ISSUE THREAD

**Issue by quangv** [GoogleCloudPlatform/google-cloud-go#586]
There is no debian/ubuntu packages. So I couldn't do:

`sudo apt-get install google-cloud-sdk-app-engine-go`

I had to uninstall google-cloud-sdk with `apt-get remove` and reinstall again with the [linux instructions](https://cloud.google.com/sdk/docs/quickstart-linux).

I was able to run `gcloud components install app-engine-go`, however when I went to run the [hello world example](https://cloud.google.com/appengine/docs/standard/go/quickstart) with `dev_appserver.py app.yaml`, it seemed like it almost worked, but then got a really long error msg.

```
dev_appserver.py app.yaml
INFO     2017-03-28 00:26:52,892 devappserver2.py:764] Skipping SDK update check.
INFO     2017-03-28 00:26:52,930 api_server.py:268] Starting API server at: http://localhost:37745
INFO     2017-03-28 00:26:53,136 dispatcher.py:199] Starting module "default" running at: http://localhost:8080
INFO     2017-03-28 00:26:53,136 admin_server.py:116] Starting admin server at: http://localhost:8000
ERROR    2017-03-28 00:26:54,394 go_runtime.py:181] Failed to build Go application: (Executed command: /home/quang/dev/gcp/quick-start/google-cloud-sdk/platform/google_appengine/goroot/bin/go-app-builder -app_base /home/quang/dev/gcp/quick-start/go-helloworld -arch 6 -dynamic -goroot /home/quang/dev/gcp/quick-start/google-cloud-sdk/platform/google_appengine/goroot -gopath /home/quang/dev/gcp/quick-start/google-cloud-sdk/platform/google_appengine/gopath -nobuild_files ^^$ -incremental_rebuild -unsafe -print_extras_hash go_appengine/goroot/src/go/types/builtins.go go_appengine/goroot/src/os/exec_plan9.go.........................etc.

2017/03/27 20:26:54 go-app-builder: Failed parsing input: failed parsing dir go_appengine/goroot/src/go/build/testdata/multi: found packages main (file.go) and test_package (file_appengine.go) in go_appengine/goroot/src/go/build/testdata/multi

^CINFO     2017-03-28 00:26:55,665 shutdown.py:45] Shutting down.
INFO     2017-03-28 00:26:55,665 api_server.py:700] Applying all pending transactions and saving the datastore
INFO     2017-03-28 00:26:55,665 api_server.py:703] Saving search indexes
```

**Comment by pongad** [comment]
I believe you can `apt-get install google-cloud-sdk` then `gcloud components install app-engine-go`, right? I believe the `gcloud` command itself is available via debian/ubuntu packages, but you cannot install components of that command with `apt-get`.

With regard to the error message, did you add files `file.go` and `file_appengine.go` yourself? The helloworld example seems to only contain `hello.go`.

**Comment by quangv** [comment]
Hey pongad, thanks for response.

> I believe you can apt-get install google-cloud-sdk then gcloud components install app-engine-go, right? 

Unfortunately, I get this message when I try to do that.

```
> gcloud components install app-engine-go
You cannot perform this action because this Cloud SDK installation is
managed by an external package manager.  If you would like to get the
latest version, please see our main download page at:

https://cloud.google.com/sdk/

ERROR: (gcloud.components.install) The component manager is disabled for this installation
```

**Comment by pongad** [comment]
> Unfortunately, I get this message when I try to do that.

Ah yes you're right. Go SDK doesn't seem to have a package in the [list](https://cloud.google.com/sdk/downloads#deb-extras).

> I didn't add any files

Looking at the message more closely. It looks like something is trying to build test data of the Go compiler: https://github.com/golang/go/tree/master/src/go/build/testdata/multi . @jba Do you think I'm reading this right?

**Comment by jba** [comment]
I'm not familiar with appengine. @broady ?

**Comment by broady** [comment]
@quangv can you run `gcloud components update` and try again?
