### ISSUE TITLE
storage: media downloads

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#588]
Currently, reading uses the object URL directly (ordinary GET). Instead specify `alt=media` to get resumable, chunked downloads.

Expose a field in `Reader` to specify the chunk size.

Provide intelligent generation-pinning for downloads (i.e., doesn't start downloading generation 1234, stop for whatever reason and resume, but accidentally get generation 2345 for the remainder).

Validate CRC32c of chunks.

**Comment by bradfitz** [comment]
What do you mean by resumable, chunked downloads? You don't need alt=media to do a `Range` request.

**Comment by jba** [comment]
I was confused.
