### ISSUE TITLE
Failed to decode "google.rpc.debuginfo-bin" (noisy logs)

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/google-cloud-go#591]
I'm seeing this in the logs a lot for the Pub/Sub client. It's new, I think?

```
2017/04/03 18:39:33 Failed to decode ("google.rpc.debuginfo-bin", "Q2xkamIyMHVaMjl2W<snip>RBPQ"): illegal base64 data at input byte 2004
```

/cc @jba @pongad

**Comment by pongad** [comment]
Grepping my `$GOPATH/src` reveals that this message is generated by `google.golang.org/grpc/transport/http_util.go` deserializing a header. Another grep for `google.rpc.debuginfo` doesn't show any result.

Is it possible that the service itself is sending us bad headers...?

**Comment by cristiangraz** [comment]
There's a ticket on this issue with some additional information here: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/555

You can base64 decode the message twice to see the stack trace. It seems to happen when the API returns grpc error codes.

**Comment by broady** [comment]
Dupe.
