### ISSUE TITLE
request feature of Resume Upload, with WriterAt interface (or request documentation)

### ISSUE THREAD

**Issue by c0b** [GoogleCloudPlatform/google-cloud-go#596]
from https://godoc.org/cloud.google.com/go/storage I'm doing uploading by this `NewWriter` interface

```go
w := obj.NewWriter(ctx)
// Write some text to obj. This will overwrite whatever is there.
// ...
if n, err := io.Copy(w, r); err != nil {
    // TODO: Handle error.
}
```

but I met some cases the returned `err` is nil but `n` is not the same size of input `r`; since my input `r` is seekable, I seek it to offset 0; and call `obj.NewWriter` to get another writer, retry io.Copy for the whole buffer, this is to copy the whole thing since beginning

I found io.WriterAt interface https://golang.org/src/io/io.go?s=8275:8351#L220 wonder if obj Writer has that?

I'm not seeing in the source code https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/writer.go ; or if you do, this can also be a documentation request please have examples how to retry if the first io.Copy is a partial success

**Comment by c0b** [comment]
https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload#example_uploading_the_file

is the resumable upload in multiple chunks implemented? the WriterAt interface looks like a good mapping to the Content-Range request; some times my upload file could be too big, I would like to do upload in multiple chunks

```console
PUT https://www.googleapis.com/upload/storage/v1/b/myBucket/o?uploadType=resumable&upload_id=xa298sd_sdlkj2 HTTP/1.1
Content-Length: 524288
Content-Type: image/jpeg
Content-Range: bytes 0-524287/2000000

[BYTES 0-524287]
```

**Comment by jba** [comment]
This file contains the resumable upload implementation: https://github.com/google/google-api-go-client/blob/master/gensupport/resumable.go.

We do call it from the Writer: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/writer.go#L84.

You can set `Writer.ChunkSize` to whatever value works for you before starting the write.

**Comment by c0b** [comment]
what I ask for is a starting offset, like the whole file size may be 2.5GB, and first io.Copy returned with 1.1GB, and then I should have a `WriteAt` interface to resume uploading the remaining 1.4GB, do you have example code how to do it?

the ChunkSize looks like to specify maximum transfer chunk size which is low level implementation and I do not care; as long as it can finish writing the whole 2.5GB file content,

```go
    // ChunkSize controls the maximum number of bytes of the object that the
    // Writer will attempt to send to the server in a single request. Objects
    // smaller than the size will be sent in a single request, while larger
    // objects will be split over multiple requests. The size will be rounded up
    // to the nearest multiple of 256K. If zero, chunking will be disabled and
    // the object will be uploaded in a single request.
    //
    // ChunkSize will default to a reasonable value. Any custom configuration
    // must be done before the first Write call.
    ChunkSize int
    // contains filtered or unexported fields
```

**Comment by c0b** [comment]
this is a request of GCloud Storage objects to have a WriterAt interface, to allow overwrite from any particular offset

https://golang.org/pkg/io/#WriterAt

**Comment by jba** [comment]
OK, I now understand what you're asking for. Will add this to my queue.

**Comment by jba** [comment]
> I met some cases the returned err is nil but n is not the same size of input r

Did you see if `w.Close()` returned an error? I think it would have in this case. If we don't upload your whole file, we should not succeed.

**Comment by jba** [comment]
What you're proposing is retrying the resumable upload at a higher level. But we already have retry logic built in to the upload (see the link in my April 6 comment). Instead of adding another layer of retry, we should understand why your upload is failing, and improve the existing logic to handle your case.

So can you provide more information about the errors you are seeing? (As I said above, if you're not seeing an error, even from `Writer.Close`, then we have a different bug.)

**Comment by c0b** [comment]
```log
2017/06/01 21:43:09 unable to close gcs file "gs://ox-perf-data/path/to/.../20170602/044200.1496378520.1496378580.avro":
googleapi: Error 503: Backend Error, backendError &googleapi.Error{Code:503, Message:"Backend Error", Body:

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }
}

```

**Comment by c0b** [comment]
sorry that was only the last error, but the system indeed has some partially written some times

```go
n, err := io.Copy(gcsFile, buf)
// at this time err is nil but  n != buf.Len()
```

**Comment by jba** [comment]
> Error 503

This shouldn't happen:
```go
func shouldRetry(status int, err error) bool {
	if 500 <= status && status <= 599 {
		return true
	}
...
```
(from https://github.com/google/google-api-go-client/blob/master/gensupport/retry.go#L71).

I'll try to understand better tomorrow. 

> n, err := io.Copy(gcsFile, buf)
> // at this time err is nil but  n != buf.Len()

I'll look into this too.

**Comment by jba** [comment]
One thing I forgot to ask: are you using the most recent version of the client? If not, what commit are you pinned to?

**Comment by Solen-Win** [comment]
#596

**Comment by jba** [comment]
OK, I think I got it. https://code-review.googlesource.com/13657

For the curious: the `shouldRetry` logic quoted above applies to the upload itself, but not the initial POST that gets the URI for the upload. My theory is that that initial call was failing.

Coincidentally, this just happened in a recent [Travis run](https://travis-ci.org/GoogleCloudPlatform/google-cloud-go/jobs/240793222#L2202).
