### ISSUE TITLE
storage: compute hash on write dynamically

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#597]
If the user doesn't supply a crc32c hash, compute one during the write and include it in the trailer.

See Google-internal doc "Unified Upload Protocols" for how to write a trailer.

**Comment by odeke-em** [comment]
I've mailed CL https://code-review.googlesource.com/16010.

**Comment by jba** [comment]
As I noted on the CL, I don't think it solves the problem. 

Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
