### ISSUE TITLE
logging: automatically detect resource

### ISSUE THREAD

**Issue by zombiezen** [GoogleCloudPlatform/google-cloud-go#598]
Right now, the logging package just uses the "global" resource.  It would be nice to have the logging package auto-detect some of the common cases, like running on GCE.

**Comment by alixMougenot** [comment]
GCP has a log export sink feature. It filters on the logs metadata to chose what data to export. If you change these fields by default, this breaks the sink that where using type:global as a filter. Is there a way not to have this change a default option or maybe create an option to ignore the autodetect ?

**Comment by zombiezen** [comment]
You can always override the resource back to type:global using [`CommonResource`](https://godoc.org/cloud.google.com/go/logging#CommonResource).

**Comment by alixMougenot** [comment]
Indeed, this change makes the doc confusing: it says that you get global if you don't pass the option. Maybe the doc needs an update as well to reflect the change. It was pretty difficult to understand what changed for us, where adapting to the change was easy. I think this patch is an improvement but deserves a bit more doc around it.

It is especially confusing to understand what is going on if the code lives in a container cluster, not directly in a VM. When in a container you expect type:container, and the usual labels (pod_id, cluster_name, container_name, namespace_id) to be set, and not type:gce_instance.

**Comment by zombiezen** [comment]
My mistake, I will fix the doc.

**Comment by zombiezen** [comment]
As for the container part, mind opening up a separate issue about that?

**Comment by alixMougenot** [comment]
I'll do that. Thank you.

**Comment by alixMougenot** [comment]
Than you, change request is here: https://github.com/GoogleCloudPlatform/google-cloud-go/issues/650.
