### ISSUE TITLE
bigquery: Unable to upload rows with float64 values greater than or equal to 2e+19 and less than 1e+21

### ISSUE THREAD

**Issue by BlueMonday** [GoogleCloudPlatform/google-cloud-go#601]
Uploading floating point values greater than or equal to `2e+19` and less than `1e+21` to Big Query using Golang does not seem to work. I don't know what the exact range of numbers which fail to upload is but that range seems to reproduce the problem. I am using Go 1.8, I have not tried it with other versions.

```
2017/04/10 11:45:59 googleapi: Error 400: Invalid JSON payload received. Unable to parse number.
[{"json":{"MyFloat":50000000000000000000
```

The following code reproduces the problem:

```golang
package main

import (
	"context"
	"log"

	"cloud.google.com/go/bigquery"
)

type Row struct {
	MyFloat float64
}

func (r *Row) Save() (map[string]bigquery.Value, string, error) {
	m := map[string]bigquery.Value{
		"MyFloat": r.MyFloat,
	}

	return m, "", nil
}

func main() {
	ctx := context.Background()
	bqClient, err := bigquery.NewClient(ctx, "myproject")
	if err != nil {
		log.Fatal(err)
	}

	uploader := bqClient.Dataset("dogs").Table("pugs").Uploader()

	r := &Row{MyFloat: 5e+20}
	err = uploader.Put(ctx, r)
	if err != nil {
		log.Fatal(err)
	}
}
```

Schema:

![2017-04-10-122034_347x135_scrot](https://cloud.githubusercontent.com/assets/3181677/24878488/27a35d52-1de8-11e7-88c0-647b483726a2.png)

**Comment by BlueMonday** [comment]
I am not sure if this is relevant but `1e+21` is where the Golang JSON encoder starts encoding numbers using exponential notation.

Golang JSON Marshal `5e+20`:
500000000000000000000

Golang JSON Marshal `5e+21`:
5e+21

**Comment by BlueMonday** [comment]
I tested with Go 1.7.5, and uploading floats between 2e+19 and 1e+21 works in 1.7.5. 

The problem really seems to be specific to Go 1.8 and an implementation detail of Big Query?

**Comment by jba** [comment]
This was indeed a change to Go, made deliberately to align with other implementations. See golang/go#20033.

The workaround is to encode the float as a string. 

A couple of notes about your sample program: as written, you don't need the Save method, because the BigQuery client has built-in support for structs. In fact, your code doesn't call Row.Save, because you pass a `Row` to Put instead of a `*Row`.

But to encode the float as a string, you will need Save. Change the middle of Save to read
```go
"MyFloat": fmt.Sprint(r.MyFloat),
```
and change the Put call to
```go
err = uploader.Put(ctx, &r)
```

**Comment by BlueMonday** [comment]
> The workaround is to encode the float as a string.

Thanks for the workaround @jba ! 

> A couple of notes about your sample program: as written, you don't need the Save method, because the BigQuery client has built-in support for structs. In fact, your code doesn't call Row.Save, because you pass a Row to Put instead of a *Row.

Oops. I will update the sample program.

**Comment by BlueMonday** [comment]
@jba: If you open a bug against the Big Query issue tracker can you post a link here (so I can track the status of the bug)?
