### ISSUE TITLE
Update grpc trace support for latest grpc changes

### ISSUE THREAD

**Issue by Cedric-Venet** [GoogleCloudPlatform/google-cloud-go#605]
grpcUnaryInterceptor should use metadata.FromOutgoingContext instead of metadata.FromContext
as it is, it
* overwrite outgoing context thus overwritting any metadata already set there
* propagate received metadata (which defeat the purpose of splitting metadata context

**Comment by rakyll** [comment]
Fixed by https://code-review.googlesource.com/#/c/12550/.
