### ISSUE TITLE
trace: GRPCServerInterceptor behavior is not coherent with HTTPHandler 

### ISSUE THREAD

**Issue by Cedric-Venet** [GoogleCloudPlatform/google-cloud-go#606]
HTTPHandler always create a span, GRPCServerInterceptor only create a span if the metadata is present.
I find the behavior of HTTPHandler more practical and  I think GRPCServerInterceptor do the same.

In addition, GRPCServerInterceptor does not fill the name of the span. It should probably use info.FullMethod to mirror the client interceptor

**Comment by rakyll** [comment]
Sent out https://code-review.googlesource.com/c/14051/.
