### ISSUE TITLE
trace.grpcUnaryInterceptor: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by Cedric-Venet** [GoogleCloudPlatform/google-cloud-go#609]
When calling several grpc service concurrently from the same context which contains some grpc metadata, we get a fatal error: concurrent map writes.

The issue is at trace/grpc.go:49:
md[grpcMetadataKey] = []string{header}

since md is a map shared between the various call. it should probably be cloned before been modified.

**Comment by rakyll** [comment]
Sent out https://code-review.googlesource.com/#/c/12550/.

**Comment by Stilgar84** [comment]
Thanks, I see you fixed #605 at the same time
