### ISSUE TITLE
BigQuery Working with Google App Engine

### ISSUE THREAD

**Issue by Peteratrapporr** [GoogleCloudPlatform/google-cloud-go#616]
Is there a way to have the BigQuery Go Library with a version that works with Google App Engine.  Have it working with the flexible model, but want to have it work with the standard model as well.

**Comment by bradfitz** [comment]
You'll likely have to wait for App Engine Standard to upgrade past Go 1.6.

**Comment by adams-sarah** [comment]
I don't think this has to do with the go version. All of the client libraries should support go 1.6.

+ @jba @zombiezen

**Comment by Peteratrapporr** [comment]
Looked further and believe the problem is more to do with the http call. AppEngine requires "urlfetch" to be used while the normal calls use the standard http client

**Comment by zombiezen** [comment]
@Peteratrapporr Can you please provide the exact error you are seeing from your application and how you are creating your `*bigquery.Client`? [dial.go](https://github.com/google/google-api-go-client/blob/16ab375f94503bfa0d19db78e96bffbe1a34354f/transport/dial.go#L79) should be autodetecting that you're in the App Engine Standard environment and use `urlfetch`.

**Comment by Peteratrapporr** [comment]
The error is generated within this call. The code works perfectly with the Flexible environment
client, err := bigquery.NewClient(ctx, "appname")


        ctx := context.Background()
	log.Printf("UrlSessionA")
	client, err := bigquery.NewClient(ctx, "appname")
	log.Printf("UrlSessionB")
	if err != nil {
		log.Printf("Logging error %v", err)
	}
	log.Printf("UrlSessionC")
	t := client.Dataset("sessionlogging").Table("app").Uploader()
	log.Printf("Client %s", t)


I get a panic attack in the code on the NewClient call.
 Dump below

2017/05/08 22:30:48 UrlSession
2017/05/08 22:30:48 UrlSessionA
2017/05/08 22:30:48 http: panic serving 127.0.0.1:54872: runtime error: invalid memory address or nil pointer dereference
goroutine 13 [running]:
net/http.(*conn).serve.func1(0xc820375a00)
	/Users/petertippett/go/goroot/src/net/http/server.go:1389 +0xc1
panic(0x81e680, 0xc82000a070)
	/Users/petertippett/go/goroot/src/runtime/panic.go:443 +0x4e9
google.golang.org/appengine/internal.fullyQualifiedAppID(0xf335d0, 0xc8201967e0, 0x0, 0x0)
	/Users/petertippett/go/src/google.golang.org/appengine/internal/identity_classic.go:27 +0x4f
google.golang.org/appengine/internal.FullyQualifiedAppID(0xf335d0, 0xc8201967e0, 0x0, 0x0)
	/Users/petertippett/go/src/google.golang.org/appengine/internal/api_common.go:74 +0xe2
google.golang.org/appengine/internal.AppID(0xf335d0, 0xc8201967e0, 0x0, 0x0)
	/Users/petertippett/go/src/google.golang.org/appengine/internal/identity.go:13 +0x37
google.golang.org/appengine.AppID(0xf335d0, 0xc8201967e0, 0x0, 0x0)
	/Users/petertippett/go/src/google.golang.org/appengine/identity.go:20 +0x37
golang.org/x/oauth2/google.FindDefaultCredentials(0xf335d0, 0xc8201967e0, 0xc8203cacc0, 0x1, 0x1, 0xc8203cacc0, 0x0, 0x0)
	/Users/petertippett/go/src/golang.org/x/oauth2/google/default.go:86 +0x5a8
golang.org/x/oauth2/google.DefaultTokenSource(0xf335d0, 0xc8201967e0, 0xc8203cacc0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/petertippett/go/src/golang.org/x/oauth2/google/default.go:43 +0x6b
google.golang.org/api/transport.NewHTTPClient(0xf335d0, 0xc8201967e0, 0xc8204331b8, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/petertippett/go/src/google.golang.org/api/transport/dial.go:74 +0x669
cloud.google.com/go/bigquery.NewClient(0xf335d0, 0xc8201967e0, 0x96ac40, 0xa, 0x0, 0x0, 0x0, 0xc8203e50b0, 0x0, 0x0)
	/Users/petertippett/go/src/cloud.google.com/go/bigquery/bigquery.go:54 +0x448
bigquery.UrlSession(0xc820388fc0)
	bigquery/bigquery.go:22 +0x120
analytics.getconnectUsageV3(0xf38d88, 0xc8203f8750, 0xc820388fc0)
	analytics/getconnect.go:239 +0xbe0
net/http.HandlerFunc.ServeHTTP(0xaf5cd0, 0xf38d88, 0xc8203f8750, 0xc820388fc0)
	/Users/petertippett/go/goroot/src/net/http/server.go:1618 +0x3a
mux.(*Router).ServeHTTP(0xc82000cf50, 0xf38d88, 0xc8203f8750, 0xc820388fc0)
	mux/mux.go:116 +0x57a
net/http.(*ServeMux).ServeHTTP(0xc82000ea80, 0xf38d88, 0xc8203f8750, 0xc820388fc0)
	/Users/petertippett/go/goroot/src/net/http/server.go:1910 +0x17d
appengine_internal.handleFilteredHTTP(0xf38d88, 0xc8203f8750, 0xc820388fc0)
	/Users/petertippett/go/goroot/src/appengine_internal/api_dev.go:105 +0x44c
net/http.HandlerFunc.ServeHTTP(0xaf5da0, 0xf38d88, 0xc8203f8750, 0xc820388fc0)
	/Users/petertippett/go/goroot/src/net/http/server.go:1618 +0x3a
net/http.serverHandler.ServeHTTP(0xc820374700, 0xf38d88, 0xc8203f8750, 0xc820388fc0)
	/Users/petertippett/go/goroot/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc820375a00)
	/Users/petertippett/go/goroot/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
	/Users/petertippett/go/goroot/src/net/http/server.go:2137 +0x44e

**Comment by zombiezen** [comment]
Ah, you need to be passing the App Engine context to `NewClient`. This is actually just #523 from a different angle.  You should run `go get -u google.golang.org/appengine` to see the better error message.

**Comment by Peteratrapporr** [comment]
This generates an error if you do this

cannot use context (type "appengine".Context)
as type context.Context in argument to "cloud.google.com/go/bigquery".NewClient:

**Comment by adams-sarah** [comment]
@rakyll @broady do you know if there's a way to convert btwn appengine context and std context?

**Comment by rakyll** [comment]
App Engine request context is a context.Context, see https://godoc.org/google.golang.org/appengine#NewContext.

@Peteratrapporr, are you sure that you are using the latest version of the appengine package? Please run the following if not:

```
go get -u google.golang.org/appengine/...
```

**Comment by Peteratrapporr** [comment]
Yes, running the latest version of everything.

When you look at the big query code, it doesn't import "app engine urlfetch".  Same problem happens with any data writing as well as expecting the Background Context and using the standard http client model.

You get an error of "not an App Engine context" and when you pass the App Engine context you get the other error type which also flows on to the "put" command to write the data.

**Comment by adams-sarah** [comment]
Hey @Peteratrapporr I'm not sure what you're running into here. Can you paste some code snippets?

For reference, this works for me:

```go
package main

import (
	"fmt"
	"net/http"

	"cloud.google.com/go/bigquery"
	"google.golang.org/api/iterator"
	"google.golang.org/appengine"
)

func init() {
	http.HandleFunc("/", handle)
}

func handle(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)

	client, err := bigquery.NewClient(ctx, "<MY-PROJECT-ID>")
	if err != nil {
		panic(err)
	}

	q := client.Query(`
    SELECT year, SUM(number) as num
    FROM [bigquery-public-data:usa_names.usa_1910_2013]
    WHERE name = "William"
    GROUP BY year
    ORDER BY year
`)
    // ... iterate
    fmt.Fprint(w, values)
}
```

**Comment by Peteratrapporr** [comment]
I did a full delete and rebuild yesterday and did the change on the code again to do appengine.NewContext and now fully working where before when I did that it errored.  Something with the normal updating of code hadn't updated something which has now been updated.

Can now close this

**Comment by broady** [comment]
Late to the party, but see this, too:

https://github.com/GoogleCloudPlatform/golang-samples/tree/master/appengine/bigquery
