### ISSUE TITLE
Bigtable: Intermittent stream terminated/timeout at high throughput

### ISSUE THREAD

**Issue by jonomacd** [GoogleCloudPlatform/google-cloud-go#617]
We are running a backfill of our data from AWS to GCP. We have written something using the Golang bigtable lib to push the data in multiple goroutines to increase throughput. This uses ApplyBulk and sends batches of about 1000 mutations at a time. Initially (for the first 1.6 million records) everything goes fine. we run in 50 threads and get about 1,000,000 records per minute.  We scaled bigtable to a larger number of nodes and keep an eye on the latency and CPU statistics to make sure it isn't stressed. BigTable looks fine. 

After a few minutes, our timings suddenly jump up and we start to exceed our 10 second context deadline. Bigtable statistics still show CPU at acceptable levels (on the cluster and the hottest node) and latencies, according to bigtable metrics, have not changed.  On the client side they certainly have as the logs and our own metrics prove we are hitting out 10 second timeout. The library starts to spit out these errors (a lot of these errors):

```
Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 3.288435ms
Retryable error: rpc error: code = 4 desc = context deadline exceeded, retrying in 97.498156ms
```

It is hard to know what is going on as we only have so much visibility into bigtable itself but it appears to be a client side issue as all the metrics we can see on bigtable show that the cluster is not particularly stressed.

The client machine running the backfill was using a large amount of the CPU before the issue happened. When the issue does happen the CPU drops but the timings do not recover indicating this might not be a simple case of under provisioning the client. 

Restarting the binary and the backfill causes us to hit the issue immediately.  We don't get the grace period of 1.6 million records which implies it might be an issue on the bigtable side or perhaps something to do with how grpc deals with clients. Again there are no metrics that we can see from bigtable that point to a problem.  

We tried again later in the day and we did not hit the issue indicating it is perhaps something transient. Even still this is a pretty big blow for our confidence in bigtable. 

I wish I could narrow it down more but having such low visibility into our BT cluster makes that challenging. Have you seen anything like this in the past? Is this even the right place to be asking?

**Comment by jonomacd** [comment]
Few more details.  If I stop the backfill, wait a short period (~5 minutes), and restart it on 1 thread then I do not get context timeouts.  I only get these errors:

```
Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 48.579045ms
```

This is under relatively low load as the thread needs to read from our current datastore and then push it to Bigtable. This is somewhat slow.

**Comment by garye** [comment]
Sorry to hear about these problems. Are you setting a number of gRPC channels to use in the connection pool when you create your client? You might want to try to increase that number as a first attempt. Something like:

```
option.WithGRPCConnectionPool(32)
```
`RST_STREAM with error code: 7` usually means that the Google frontend servers were refusing new streams being created, which could be because a particular gRPC connection was overloaded. 1000 mutations at a time is also relatively high (depends on how big each one is), so it might make sense to lower that an add more parallelism via more thread/larger connection pool.

In parallel, we'll need more information about your project to debug any issues that could be happening on the server side. If you have a support account please enter a support ticket. If not, we'll figure out how to have an offline chat to get more information.

**Comment by jonomacd** [comment]
Thanks for the reply.  I looked at the connection pool option. I noticed this comment and was a bit scared away.

```
WithGRPCConnectionPool returns a ClientOption that creates a pool of gRPC connections that requests will be balanced between. This is an EXPERIMENTAL API and may be changed or removed in the future.
```

Is this production ready?  What does it do exactly?

**Comment by garye** [comment]
Yes, it's production ready and probably shouldn't have that comment. Each new RPC initiated by the client goes to one of the gRPC connections in the connection pool, chosen by round-robin. The client uses a pool of size 4 by default. Each connection can have ~100 outstanding RPCs at a time so, for a back fill job sending many potentially time consuming mutations, I could see you bumping up against this limit.

**Comment by jonomacd** [comment]
Great. Thanks, I'll try that out and see if it helps.

**Comment by jonomacd** [comment]
I've tried upping the pool to 32 and lowering the batch size. Unfortunately, it is still complaining. It seems highly transient. I had a few good runs but now it is failing even at relatively low load. The metrics on bigtable still indicate it should be behaving fine... I suspect that something is going on on the client interface.  Any other insight on the connection?

**Comment by garye** [comment]
This is still `RST_STREAM with error code: 7`, no deadlines being exceeded?

**Comment by jonomacd** [comment]
Both. Though it tends to get timeouts for some time before the `RST_STREAM` error kicks in.

**Comment by jonomacd** [comment]
In the latest run I get timeouts for about 5 minutes then I start getting both RST_STREAM errors and timeouts for a short time, then the timeouts go away and I only get RST_STREAM errors. 
Now the backfill is moving fairly swiftly but it is retrying like crazy

```
2017/05/03 17:02:40 Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 1.919421ms
2017/05/03 17:02:40 Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 87.995967ms
2017/05/03 17:02:40 Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 6.193201ms
2017/05/03 17:02:40 Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 8.668856ms
2017/05/03 17:02:40 Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 96.753153ms
2017/05/03 17:02:40 Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 38.258707ms
2017/05/03 17:02:40 Retryable error: rpc error: code = 14 desc = stream terminated by RST_STREAM with error code: 7, retrying in 50.212526ms
```

It seems once it gets in this state it just never recovers.

**Comment by jonomacd** [comment]
And it is timing out again. The timeouts seems to cause the RST_STREAM as they come first but the timeouts seem to happen periodically whether the RST_STREAM is happening or not

**Comment by garye** [comment]
If you're seeing timeouts then we really need to look at what's happening on the server side, as the metrics exposed via the web console don't always tell the whole story. The client library itself seems to be responding sanely given the errors it's receiving.

To debug further it's best to open a support ticket and make sure they loop me in. If that's not possible you can find my email address from commits to the bigtable directory in this repo and get in touch that way.

**Comment by jonomacd** [comment]
Alright, I'll try to start a support ticket and loop you in. Thanks for the help.

**Comment by garye** [comment]
Sure, thanks for your patience.

**Comment by jonomacd** [comment]
After searching around the console I have no idea how to open a support ticket. I think you might need gold level support? Is that right?

**Comment by jonomacd** [comment]
Hi Garye, 
I've opened a case under 12663587 and posted this same question over here: http://stackoverflow.com/questions/43782052/bigtable-intermittent-stream-terminated-timeout-at-high-throughput

Not sure which is the more appropriate place to ask.

**Comment by garye** [comment]
Thanks for opening the case, hopefully this can be resolved quickly.

**Comment by ymdotm** [comment]
did you find a solution to this error?

**Comment by garye** [comment]
@jonomacd Are you running the backfill job from AWS or GCE? Basically it doesn't seem to me like bigtable is very stressed out by the workload and there isn't a ton that the client can do by itself to make things so slow, so I'm wondering if there's a network/frontend problem.

**Comment by garye** [comment]
This has been closed internally.
