### ISSUE TITLE
Using a BigQuery StructSaver causes infinite recursion on AppEngine

### ISSUE THREAD

**Issue by darrenmcc** [GoogleCloudPlatform/google-cloud-go#619]
Attempting to create a StructSaver with a custom InsertID within my application and do a Put to BigQuery causes an infinite recursion loop that will quickly consumes all available memory and terminates the instance. This occurs regardless of the struct I'm attempting to save or whether or not a previously inferred Schema is given. 

Saving the item without wrapping it in a StructSaver works fine.

**Comment by jba** [comment]
Use a pointer to a `StructSaver`, and provide a schema, as I show below.

I'll fix the infinite recursion and make the schema optional in upcoming CLs.

```
type S struct {
    Num int
    Str string
}

func main() {
    // ...
    sch, err := bigquery.InferSchema(S{})
    if err != nil {
        log.Fatal(err)
    }
   ss := bigquery.StructSaver{
        InsertID: "moo",
        Struct:   S{4, "boo"},
        Schema:   sch,
    }
    if err := u.Put(ctx, &ss); err != nil {
       // ...
    }
}
```

**Comment by jba** [comment]
https://code-review.googlesource.com/12850
