### ISSUE TITLE
trace: Google Endpoints and gRPC tracing not using same header

### ISSUE THREAD

**Issue by vishen** [GoogleCloudPlatform/google-cloud-go#620]
Google Endpoints adds `x-cloud-trace-context` as a header in the grpc metadata, which is similar to the HTTP header `X-Cloud-Trace-Context` [1] that the tracing library uses for HTTP requests. However in the grpc part of the library it uses a different header name `stackdriver-trace-context` [2]. 

I was wondering if the grpc section will ever use `x-cloud-trace-context` (It would mean that you would get tracing right out of the box when using Google Endpoints as well) or will I need to write a custom grpc inteceptor?

[1] https://github.com/GoogleCloudPlatform/google-cloud-go/blob/152f6052050bfd9f6a25da387647d8448e5e60f0/trace/trace.go#L171
[2] https://github.com/GoogleCloudPlatform/google-cloud-go/blob/152f6052050bfd9f6a25da387647d8448e5e60f0/trace/grpc.go#L26

**Comment by bradfitz** [comment]
@jba, what's the status of unifying tracing? Somebody had mentioned http://opentracing.io/ at one point. Are there efforts to standardize any of this?

**Comment by jba** [comment]
@rakyll is handling that.

**Comment by rakyll** [comment]
@vishen, I have a proposal to standardize the gRPC key across Google's client libraries for Stackdriver Trace. Until we reach consensus, we can switch to `x-cloud-trace-context` for compatibility with Endpoints.

@bradfitz, broader standardization is yet another story. I will update golang-dev next week about the status of that work.

**Comment by rakyll** [comment]
cc/ @bogdandrutu for key standardization.

**Comment by rakyll** [comment]
FYI, we switched to a new binary encoding/decoding standard via https://github.com/GoogleCloudPlatform/google-cloud-go/commit/c2e00bbd8f3e634946157a55f32b9629a6249ef8. Endpoints are also moving to the new standard.
