### ISSUE TITLE
Bigtable Emulator has different behavior for checkAndPut with null value

### ISSUE THREAD

**Issue by zzorba** [GoogleCloudPlatform/google-cloud-go#621]
According to the documentation, if you pass in a null array to 'value when calling `checkAndPut`, it should serve as an existence check. This seems to be the behavior exhibited by the production cloud bigtable service.  

However when using emulator it seems like this behavior only works if you specify compareOp=CompareOp.EQUAL.  Passing any other value for compareOp does not result in an update.

```
   try (Table table = connection.getTable(tableName)) {
      boolean noExistResult = table.checkAndPut("rowKey".getBytes(), 
          "cf1".getBytes(), "column1".getBytes(),
          CompareFilter.CompareOp.GREATER, null,
          new Put("rowKey".getBytes())
             .addColumn(
                "cf1".getBytes(), "column1".getBytes(), bb.array()));

      // This line fails on emulator, works on real big table
      assertTrue(noExistResult);

      Result getResult = table.get(new Get("rowKey".getBytes()));
      assertNotNull(
            getResult.getColumnLatestCell(
                "cf1".getBytes(), "column1".getBytes()));
      // This line fails on emulator, works on real big table
      assertTrue(Arrays.equals(
          bb.array(),
          getResult.getColumnLatestCell("cf1".getBytes(), 
               "column1".getBytes()).getValueArray()));
    } catch (IOException e) {

    }
```

**Comment by igorbernstein2** [comment]
I think there are 2 possible issues here:
1. The bigtable-hbase layer silently ignores nonequality checks when the value is null:
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/5c3ee47e208b4efbfaa5badceff8b403c02cb6d4/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/adapters/CheckAndMutateUtil.java#L113. 
Instead it should throw an error or try to be clever in converting the condition

2. If I'm right about point 1, then the actual behavior difference is that the emulator differs in behavior when dealing with an empty predicate and a non-existent row

**Comment by sduskis** [comment]
The Java code was updated.  Basically, the CheckAndMutate will look like this:

```
precondition:
   - family: '..'
   - qualifier: '..'
   - value: '.*'
false-mutations
   - something...

**Comment by sduskis** [comment]
Here's the full representation of the java code in the OP:

```
table_name: "projects/project/instances/instance/tables/table"
row_key: "rowKey"
false_mutations {
  set_cell {
    family_name: "cf1"
    column_qualifier: "column1"
    timestamp_micros: -1
    value: "bb"
  }
}
predicate_filter {
  chain {
    filters {
      chain {
        filters {
          family_name_regex_filter: "cf1"
        }
        filters {
          column_qualifier_regex_filter: "column1"
        }
      }
    }
    filters {
      cells_per_column_limit_filter: 1
    }
  }
}
```

**Comment by jba** [comment]
I'm confused. That precondition matches the row, so the true mutations will run. And that is what I observe in both implementations.

In Go, I'm applying
```
 cmut := bigtable.NewCondMutation(
        bigtable.ChainFilters(
            bigtable.FamilyFilter("cf1"),
            bigtable.ColumnFilter("column1"),
            bigtable.ValueFilter(".*")),
        tmut, fmut)
```
which translates to
```
predicate_filter: <
  chain: <
    filters: <
      family_name_regex_filter: "cf1"
    >
    filters: <
      column_qualifier_regex_filter: "column1"
    >
    filters: <
      value_regex_filter: ".*"
    >
  >
>
```
and I see the true mutations applied in both cases.

However, if I change the column filter to `"column"` (omitting the final `1`), the real service runs the false mutations and the emulator runs the true ones.

**Comment by jba** [comment]
We crossed in the mail. I just changed my repro to match your proto exactly, and the results are the same.

So we don't have a repro of the original error but we do of a different error. Or, they're the same error.

**Comment by sduskis** [comment]
@jba: The user intent here is to add a new row if one does not exist.  In that case, the implementation is to use a `false_mutation`, not a `true_mutation`.  We should probably sync up offline about the nuances of this issue.

**Comment by jba** [comment]
I tried that conditional mutation on a non-existent row. I got a new row with the false mutations in both the real service and the emulator.

**Comment by sduskis** [comment]
W00T!  I just realized that I should run the java client integration tests against the emulator.

**Comment by sduskis** [comment]
I ran the Java tests against the emulator, which includes a bunch of checkAndPut scenarios.  All of the checkAndPut scenarios passed.  There were some other issues that popped up that ought to be fixable in the emulator.

@jba, can we close this issue and open another one for the new issues?  The SLA on this issue is past due.
