### ISSUE TITLE
gRPC metadata.NewContext and metadata.FromContext should not be used

### ISSUE THREAD

**Issue by dfawley** [GoogleCloudPlatform/google-cloud-go#624]
After some recent changes in grpc-go, `metadata.NewContext` now assumes you are accessing the _outgoing_ metadata, and `metadata.FromContext` assumes you are retrieving the _incoming_ credentials.  We are planning on removing these functions due to this ambiguity and the fact that the behavior was changed to avoid unintentional forwarding of metadata when a server makes outgoing grpc calls.

For more information, please see:

https://github.com/grpc/grpc-go/issues/1219
https://github.com/grpc/proposal/pull/25
https://groups.google.com/forum/#!topic/grpc-io/-qM_UnYFHJs

**Comment by dfawley** [comment]
I can make this conversion, but in the process, I've run into a handful of auto-generated files with an "insertXGoog" function that does this.  E.g.

https://github.com/dfawley/google-cloud-go/blob/master/speech/apiv1beta1/doc.go

What generates these files, and how can I update that?

**Comment by dfawley** [comment]
Note that insertXGoog is currently broken (due to grpc/grpc-go#1157), and it will overwrite the existing outgoing metadata in the context.  It should be using FromOutgoingContext instead of FromContext.

**Comment by pongad** [comment]
@dfawley It is generated from [here](https://github.com/googleapis/toolkit/blob/master/src/main/resources/com/google/api/codegen/go/doc.snip#L23). I can make this change pretty easily.

One question though, you said that it will "overwrite the existing outgoing metadata", but its goal is to change the outgoing metadata. Did you mean it will inadvertently overwrite *incoming* metadata? Just wanted to make sure I understand this right.

**Comment by dfawley** [comment]
It's attempting to add a field to the outgoing metadata, but with the current grpc behavior, it will instead delete the existing outgoing metadata, then merge the additional field with the _incoming_ metadata and use that as the new outgoing metadata.

**Comment by pongad** [comment]
Ah I get it now. I'll make this fix.

**Comment by dfawley** [comment]
Fixed via googleapis/toolkit#1262 and dc9545a.
