### ISSUE TITLE
ci: enable APIs for smoke testing

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-go#625]
https://code-review.googlesource.com/#/c/12650/ adds "smoke testing" to make sure our auto-generated libraries aren't dead on arrival. Unfortunately many smoke tests [fail](https://travis-ci.org/GoogleCloudPlatform/google-cloud-go/jobs/230950536) because
- error reporting
- monitoring
- speech
- trace

APIs are not enabled on the test project. I don't have the permission to enable them.

**Comment by adams-sarah** [comment]
I'm confused what you're saying.

The `fail` link in your post links to a passing CI build.
All of the APIs above are enabled..

Am I misunderstanding? I'm happy to help if I can - I've got the *power* to enable APIs :p. Can probably add you to the project too if you want.

**Comment by jba** [comment]
I enabled them recently. Mystery solved.
