### ISSUE TITLE
logging: write correlation-id with log entry metadata

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-go#626]
By writing a correlation-id into the logging metadata, users can get request-correlated logs in pantheon. See https://gist.github.com/JustinBeckwith/43dd04cfbc4551ddd8996a5b803da0b0 for details.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.

**Comment by derekperkins** [comment]
@JustinBeckwith your gist is gone. What specific field and format does that correlation id need to go in?

**Comment by derekperkins** [comment]
See https://github.com/GoogleCloudPlatform/google-cloud-go/issues/448#issuecomment-352132523 for implementation details.
