### ISSUE TITLE
Pubsub: Go Get Error

### ISSUE THREAD

**Issue by enkoder** [GoogleCloudPlatform/google-cloud-go#630]
Getting an error during pubsub get. 
```go get -u cloud.google.com/go/pubsub```

Looks like the something changed in protobuf output and client has not updated to use the new hotness? 
```
# cloud.google.com/go/pubsub
/home/enkoder/go/src/cloud.google.com/go/pubsub/service.go:527: snap.ExpirationTime undefined (type *"google.golang.org/genproto/googleapis/pubsub/v1".Snapshot has no field or method ExpirationTime)
```

**Comment by enkoder** [comment]
Opened CR: https://code-review.googlesource.com/#/c/13090/

**Comment by adams-sarah** [comment]
Thanks for the CL!

**Comment by adams-sarah** [comment]
Fixed by https://code-review.googlesource.com/#/c/13090/

**Comment by enkoder** [comment]
Noice! Quick turn around. 🙏
