### ISSUE TITLE
container: deprecate and then remove the handcrafted package

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#631]
The [container](cloud.google.com/go/container) package is an incomplete and unmaintained client of the GKE API. It has been contributed in the earlier days of this package and hasn't been touched since then. 

In the past years, we haven't seen any interest in this package by the users or any motivation to have a handcrafted API surface for GKE.

We should deprecate this package and plan sunsetting it.

/cc @jba

**Comment by jba** [comment]
Agreed. We'll coordinate with the changes to cloud.google.com/go/vision.

**Comment by rakyll** [comment]
Great, I will send a CL to add a deprecation notice.

**Comment by rakyll** [comment]
Sent out https://code-review.googlesource.com/#/c/13213/.

**Comment by rakyll** [comment]
Closed via https://github.com/GoogleCloudPlatform/google-cloud-go/commit/c203866c32a0f3c347e4e2cdc58edf275882bd03.
