### ISSUE TITLE
bigquery: improve doc for using ReaderSource for load job

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/google-cloud-go#635]
I have newline delimited json that I'm trying to load into a table using the Loader with a ReaderSource, but it's not working and I'm having trouble getting any info to debug it with.

### BigQuery job load error
```
Error encountered during job execution:
Too many errors encountered.
Failure details:
 - file-00000000: Too many values in row starting at position: 0.
```

### Generating newline json
```
buf := &bytes.Buffer{}
enc := json.NewEncoder(buf)
loadData := map[string]interface{}{}

for i, kw := range data {
   loadData["field1"] = data1
   loadData["field2"] = data2

   if err = enc.Encode(loadData); err != nil {
      return err
   }
}

src := bigquery.NewReaderSource(buf)
```

### output of `buf`
```
{"device":"d","geo":"usa","groups":["non-brand","non-Geo","non-transactional","tail"],"keyword_id":"10000251184248049962","locale":"en_us","schedule_id":503,"team_id":271}
{"device":"d","geo":"usa","groups":["non-brand","non-Geo","tail","transactional"],"keyword_id":"10001375335325553075","locale":"en_us","schedule_id":503,"team_id":271}
{"device":"d","geo":"usa","groups":["Geo","non-brand","tail","transactional"],"keyword_id":"10001513748181573317","locale":"en_us","schedule_id":503,"team_id":271}
{"device":"d","geo":"usa","groups":["Geo","non-brand","tail","transactional"],"keyword_id":"1000153673757522635","locale":"en_us","schedule_id":503,"team_id":271}
{"device":"d","geo":"usa","groups":["brand","Geo","tail","transactional"],"keyword_id":"10002357467434638259","locale":"en_us","schedule_id":503,"team_id":271}
```

**Comment by derekperkins** [comment]
Never mind, I missed the `FileConfig` option on the `ReaderSource`. It feels like `FileConfig` should be configurable from the `Loader`, since those options are independent of the source of the data.

**Comment by jba** [comment]
> It feels like FileConfig should be configurable from the Loader, since those options are independent of the source of the data.

I see what you mean, but I disagree: not all load sources are necessarily files. Imagine loading data from a bigtable or other structured data source, for example; most of `FileConfig` wouldn't make sense.

I'm reopening so I can improve the doc for this use case.

**Comment by derekperkins** [comment]
>  Imagine loading data from a bigtable or other structured data source, for example; most of FileConfig wouldn't make sense.

That is what I'm doing here, moving data from MySQL to BigQuery. I'm pulling it out of the db, marshaling it into json one record at a time and appending to the `bytes.Buffer`. Since I'm using JSON, the multiple CSV specific fields in `FileConfig` aren't valuable to me, but these 4 fields are ones that I have used in the past and will probably continue to use, regardless whether I'm loading from a file or from a `ReaderSource`.

    // SourceFormat is the format of the GCS data to be read.
    // Allowed values are: CSV, Avro, JSON, DatastoreBackup.  The default is CSV.
    SourceFormat DataFormat

    // MaxBadRecords is the maximum number of bad records that will be ignored
    // when reading data.
    MaxBadRecords int64

    // IgnoreUnknownValues causes values not matching the schema to be
    // tolerated. Unknown values are ignored. For CSV this ignores extra values
    // at the end of a line. For JSON this ignores named values that do not
    // match any column name. If this field is not set, records containing
    // unknown values are treated as bad records. The MaxBadRecords field can
    // be used to customize how bad records are handled.
    IgnoreUnknownValues bool

    // Schema describes the data. It is required when reading CSV or JSON data,
    // unless the data is being loaded into a table that already exists.
    Schema Schema

**Comment by jba** [comment]
I've added some doc in https://code-review.googlesource.com/15850.

I don't think tweaking the location of these config options is worth the churn.
