### ISSUE TITLE
CONTRIBUTING.md confusing

### ISSUE THREAD

**Issue by waprin** [GoogleCloudPlatform/google-cloud-go#636]
This is kind of a friction log to guide some improvements.

Made a PR with 1 commit on a different branch, told to use Gerrit.

waprin-macbookpro:go waprin$ git codereview change bigtable_autoscaler_sigterm
/Users/waprin/gocode/bin//git-codereview: cannot branch from work branch; change back to master first.

Then tried putting the commit on master and it complained maser was ahead of origin/master.

Eventually I ran the command on master with it matching origin/master, and that made me switch to the original branch.

Then I needed the change-id hoko which requires commit --amend. When I run that I get:

```
git-codereview: gofmt needs to format these files (run 'git gofmt'):
	bigtable/cmd/loadtest/loadtest.go
```

Now I have go fmt installed and ran that, but I still see the error. I'm guessing I need some sort of git-gofmt command in my BIN but unclear of how I'm supposed to install that.

**Comment by waprin** [comment]
I originally tried adding [this](https://golang.org/misc/git/pre-commit) into my ~/.git/hooks command and making it executable which didn't solve anything. Then I ran commands from [this repo](https://github.com/chibiegg/git-gofmt) and things seem to work.

**Comment by adams-sarah** [comment]
Hi! I'm sorry you've run into this.
So a nuance with the git-codereview tool is that the error messages assume you have set up aliases for its commands. In other words, it assumes that you've set up your `.gitconfig` such that *gofmt* is an alias for *codereview gofmt*, and so `git gofmt` really means `git codereview gofmt`.

Had you run `git codereview gofmt`, the cmd should have worked as the error message describes.
I will add a note about the aliasing in CONTRIBUTING.md.

I think the reason noone else has run into this before you is the vast majority of go programmers run gofmt on save (plugged into their editor). I highly encourage you to set this up.

**Comment by adams-sarah** [comment]
The docs for `git-codereview` explain the aliasing, fyi: https://godoc.org/golang.org/x/review/git-codereview
