### ISSUE TITLE
bigquery: Uploader errors discard data

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/google-cloud-go#637]
I'm getting errors on my `Uploader.Put` call, but this is the error that is returned: `(bigquery.PutMultiError) (len=1 cap=1) 1 row insertion failed`. Having worked directly with the json api before, I know that there are typically much more detailed errors in a sub-array, but it seems like that data is being discarded. The way it is now, I literally have no way to debug why my upload is failing.

![image](https://cloud.githubusercontent.com/assets/3588778/26420617/57ec65e8-4080-11e7-9a1c-7bf7d5fbf9c2.png)
*from api reference* https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll

**Comment by derekperkins** [comment]
I just started logging out inside the google-gen code and found the real error data. This would be very helpful as a part of the actual error response.

![image](https://cloud.githubusercontent.com/assets/3588778/26428619/fa42a996-409f-11e7-8c95-0df1ea564ba9.png)

**Comment by BlueMonday** [comment]
The error returned is a PutMultiError (https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/error.go#L73) which is a slice. The slice will generally contain a RowInsertionError (https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/error.go#L60) for each row that failed to insert. RowInsertionError has an Errors field which is a slice containing all the errors that occurred while inserting that row. The Errors field of the RowInsertionError struct will generally be a slice of pointers to bigquery.Error (https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/error.go#L24). 

Its a bit like a [Matryoshka doll](https://en.wikipedia.org/wiki/Matryoshka_doll) but you can get more information by iterating through the slices.

You probably want to do something fancier but you could for example do something like this to extract more information from the returned error:

```go
err := uploader.Put(ctx, rowsToUpload)
if err != nil {
	if pmErr, ok := err.(bigquery.PutMultiError); ok {
		for _, rowInsertionError := range pmErr {
			log.Println(rowInsertionError.Errors)
		}
		return
	}

	log.Println(err)
}
```

**Comment by derekperkins** [comment]
@BlueMonday I saw that, but when I dumped the entire struct, the underlying errors weren't included.

**Comment by jba** [comment]
@derekperkins I don't see what information we're failing to pull out. We [get all the fields mentioned in the doc](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/error.go#L33) (except debugInfo), and [store them](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/service.go#L304
) in a `PutMultiError`. Using some bad data and code like @BlueMonday's, I was able to display location, message and reason for each failed row.

Can you provide a repro?

**Comment by derekperkins** [comment]
I tried searching my historical logs quickly, but wasn't able to find that error dump. My case here was an empty required field. I was calling `spew.Sdump` on the returned `PutMultiError` (https://github.com/davecgh/go-spew), and it didn't seem to dump the sub-fields. If you're confident that the data is being retrieved properly, you can close this issue. Now that I got the schema working, it'll probably be a while before I deal with this again.

**Comment by BlueMonday** [comment]
@derekperkins: I tested it out using the steps you described and I think I understand what you were describing now.

I used this to test:

```go
package main

import (
	"log"

	"cloud.google.com/go/bigquery"
	"github.com/davecgh/go-spew/spew"
)

func main() {
	pmErr := bigquery.PutMultiError{
		bigquery.RowInsertionError{
			InsertID: "test",
			RowIndex: 1,
			Errors: bigquery.MultiError{
				&bigquery.Error{
					Location: "testing",
					Message:  "testing",
					Reason:   "testing",
				},
			},
		},
	}

	log.Printf(spew.Sdump(pmErr))
}
```

The output was `2017/06/05 13:41:19 (bigquery.PutMultiError) (len=1 cap=1) 1 row insertion failed` exactly as you described. It seems like spew calls the Error method of PutMultiError which doesnt seem to contain much useful information at the moment: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/error.go#L81

If you were to do the same thing but call spew.Sdump on the individual elements of the PutMultiError you get much better errors (since the Error method for RowInsertionError includes a lot more information: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigquery/error.go#L67):

```go
package main

import (
	"log"

	"cloud.google.com/go/bigquery"
	"github.com/davecgh/go-spew/spew"
)

func main() {
	pmErr := bigquery.PutMultiError{
		bigquery.RowInsertionError{
			InsertID: "test",
			RowIndex: 1,
			Errors: bigquery.MultiError{
				&bigquery.Error{
					Location: "testing",
					Message:  "testing",
					Reason:   "testing",
				},
			},
		},
	}

	for _, rowInsertionError := range pmErr {
		log.Printf(spew.Sdump(rowInsertionError))
	}
}
```

Output:
```
2017/06/05 13:41:19 (bigquery.RowInsertionError) insertion of row [insertID: "test"; insertIndex: 1] failed with error: {Location: "testing"; Message: "testing"; Reason: "testing"}
```


It seems like you should update your code to not log PutMultiError directly but the individual errors inside the slice (unless the Error method for PutMultiError is updated to return more information).
