### ISSUE TITLE
trace: drop HTTPClient in favor of http.Client

### ISSUE THREAD

**Issue by dlsniper** [GoogleCloudPlatform/google-cloud-go#639]
Hi,

After playing around with the ` trace ` package, I've realized that as it is today, ` *HTTPClient ` can't be used anywhere where the ` *http.Client ` is used.

By looking at it, all that the current ` HTTPClient ` does it to proxy the ` Do() ` method to the underlying ` *http.Client `. The ` NewHTTPClient ` method also could be changed to return a ` standard ` *http.Client ` instead of the custom one given that the trace happens at the transport not the client itself.

Doing this would allow instrumenting virtually all applications that use ` *http.Client ` without having to change anything or resort to things like: https://github.com/nlopes/slack/blob/c86337c0ef2486a15edd804355d9c73d2f2caed1/misc.go#L23...L25 in order to abstract the clients away from the library.

I'd be ok to send the CL if approved.

**Comment by adams-sarah** [comment]
cc @rakyll

**Comment by rakyll** [comment]
I am fine with just exporting the RoundTripper, please send a CL.

**Comment by dlsniper** [comment]
I've opened this: https://code-review.googlesource.com/#/c/13490/ not sure how to link it to here unfortunately.

**Comment by adams-sarah** [comment]
At the end of the commit message, before the "Change-Id" line, you can write:
"Fixes #639" 
and gerrit will link to this gh issue.

**Comment by dlsniper** [comment]
@adams-sarah sorry, I feel stupid now, how does one do that? I'm familiar with git itself but this `codereview` tool is not really helpful unfortunately :( As far as I can see: https://godoc.org/golang.org/x/review/git-codereview#hdr-Rebase_work is not present as a command in the tool but it's mentioned in the docs.

**Comment by adams-sarah** [comment]
Oh no problem! Ya, it's confusing at first.

So if you haven't set up aliases (eg you ran `git codereview change`) initially, you can run `git codereview change` again and you'll get an editor where you can modify the commit message. Saving buffer will update the commit. And then `git codereview mail` again to push the changes up to the CL.

If you had modified files, you'd need to `git add` them as usual before running `git codereview change` again.

If you've set up aliases as described at the top of https://godoc.org/golang.org/x/review/git-codereview, (eg you ran `git change`) initially, then just `git change` again.

**Comment by adams-sarah** [comment]
Also, to rebase against master, `git codereview sync`.

**Comment by dlsniper** [comment]
Awesome! Thanks, _that_ should be in the description of how to use the tool.

**Comment by adams-sarah** [comment]
^ is in CONTRIBUTING.md in this project root.
it's also in the documentation of the tool, just not spelled out very explicitly. It's in paragraph form at the top of the godoc.

CLs welcome for both docs!
