### ISSUE TITLE
tests: remove usage of pretty.Diff and reflect.DeepEqual

### ISSUE THREAD

**Issue by zombiezen** [GoogleCloudPlatform/google-cloud-go#641]
Our tests use `reflect.DeepEqual` and `pretty.Diff` in a number of places.  Neither of these are guaranteed to work based on the protobuf compatibility promise, so we ought to clean these usages out.

**Comment by jba** [comment]
I think pretty can easily be fixed, rather than replaced.

**Comment by jba** [comment]
No, it can't. Although only because of extensions, and I don't think any new-style Google API uses extensions. I think unknown fields are OK.

Can you describe the exact failure modes of reflect.DeepEqual?

**Comment by jba** [comment]
What if pretty.Diff diffed the proto.MarshalText output for the two protos? 

Another way to put it: is it true that `proto.Equal(p1, p2)` iff `proto.MarshalTextString(p1) == proto.MarshalTextString(p2)`?

**Comment by adams-sarah** [comment]
Jonathan - Ross can correct me if I'm wrong, but I think the main argument for not using reflect.DeepEqual is the flakiness of the test over time - especially when the structs you're comparing have fields of types declared in other packages. If an unexported field is added to the struct, which is filled in perhaps by the 3rd package as your test runs, but not by your test for the comparison, your test will then start failing.
You are also then comparing many things which are perhaps not relevant to the test. (eg. a cache field or some metadata or something).

The downside to not using reflect.DeepEqual is that you have to compare each field manually. I'm not sure if Ross has an elegant solution for this or not.

**Comment by jba** [comment]
@adams-sarah That is a good argument, but there is something specific about protos.

**Comment by adams-sarah** [comment]
It is the same argument, I am fairly sure. But @zombiezen can confirm.

**Comment by zombiezen** [comment]
@jba Message structs can have arbitrary implementation-specific fields added over time.  `proto.Equal` is guaranteed to do the right thing, but we make no such guarantee about `reflect.DeepEqual`.
