### ISSUE TITLE
How to unit-test with datastore

### ISSUE THREAD

**Issue by junghoahnsc** [GoogleCloudPlatform/google-cloud-go#644]
Hello,

Is there any way to run unit tests with datastore?
I know there is a datastore emulator, but it's not trivial to run it in CI testing environment.

Thanks,

**Comment by jba** [comment]
At present, the best choice is to write your own application-specific interface with one implementation using cloud.google.com/go/datastore and another with your test double.

Closing this because it is subsumed by #592.
