### ISSUE TITLE
bigquery: NULLABLE support for StructSaver?

### ISSUE THREAD

**Issue by BlueMonday** [GoogleCloudPlatform/google-cloud-go#647]
## Problem

At the moment, using `bigquery.StructSaver` results in every field in a struct being serialized and sent over the network to Big Query regardless of whether or not they were set. This can result in quite a bit of unnecessary overhead for tables with a lot of fields which are `NULLABLE`.

## Potential solution

This is just an idea but... One possible solution is to add a `nullable` struct tag. The tag would only be valid for pointer, slice, and map type fields. The struct tag would cause the field to not be serialized and sent over the wire if it is not set (`nil`). I don't think it would make sense for other types since for example not sending a boolean type if it is `false` (kind of like the JSON `omitempty` struct tag) would result in the column being set to `null` instead of `false` in Big Query. This would make it hard to distinguish between a field that was set to a false value and a field that was not set at all. This is assuming that an `omitempty` struct tag doesn't make as much sense in the context of Big Query (maybe it does?).

The InferSchema function currently assumes every field is required.  It could instead use the proposed `nullable` struct tag to determine if the field is or is not required. 

The main downside I can think of is that the struct tag only working with pointers, slices, and maps might confuse some people.

### Example

```go
type Dog struct {
   Name string `bigquery:"name"`
   Friendly *bool `bigquery:"friendly,nullable"`
}
```

Dog.Friendly would be null if we don't know if the dog is friendly or not friendly. It would be set to true if we know it is friendly and false if we know it is not friendly. If Dog.Friendly is null we would not send the field to Big Query and Big Query would set its value to `null` for that row.

Other ideas welcome!

**Comment by jba** [comment]
See https://code-review.googlesource.com/c/gocloud/+/21632.

**Comment by BlueMonday** [comment]
Hey @jba,

I looked at https://code-review.googlesource.com/c/gocloud/+/21632 and it seemed fine to me. It seems like you went with https://code-review.googlesource.com/#/c/gocloud/+/22010/ instead though. I am finding the approach taken in https://code-review.googlesource.com/#/c/gocloud/+/22010/ a bit hard to use.

I think my use case is fairly simple. 

1. I read some JSON
1. I unmarshal it into an instance of a struct type in order to validate the data
1. I create the table if it does not exist 
1. I load the validated data into Big Query

One of the requirements is I need to be able to distinguish when a field in a Big Query table is set to an empty string and when it is not set at all. This has led me down the path of fields which are not required.

The main inconvenience is I can't use the same struct type to create the table, deserialize the JSON, and send data to Big Query. I now need at least two structs with the same field names but different types.

```golang
type JSONStruct  struct {
        FieldOne string `json:"field_one"`
        FieldTwo int    `json:"field_two"`
}

type BigQueryStruct struct {
        FieldOne bigquery.NullString
        FieldTwo bigquery.NullInt64
}
```

In this example I would be using `JSONStruct` to deserialize the JSON and `BigQueryStruct` to create the table and insert a row into the table. In order to do so I would have to convert `JSONStruct` into `BigQueryStruct` part way through. Having two structs for every Big Query table and having to convert between the two can be very tedious if there are many types. 

Do you have any suggestions on how I could achieve my end goal without the duplication and conversions?

**Comment by BlueMonday** [comment]
The only thing I have thought of so far is to add `UnmarshalJSON` methods to the `NullXXX` types which deserialize the data into the Value field and set Valid to true.

**Comment by jba** [comment]
We can't represent a nullable field with a non-nullable type like `string`. There would be no way to indicate the difference between absence and the zero value.

I do like your idea of adding marshalling methods. I created #866.

**Comment by lenaten** [comment]
> We can't represent a nullable field with a non-nullable type like string. 

How about marshal *string?

**Comment by jba** [comment]
We considered using pointers, but decided to use NullXXX types to match the sql and spanner packages.
