### ISSUE TITLE
Int overflow in pubsub/topic.go

### ISSUE THREAD

**Issue by kjlubick** [GoogleCloudPlatform/google-cloud-go#648]
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/d2bf9ead8d595b9347434a2bcbaec6395862adab/pubsub/topic.go#L338 overflows when ints are 32 bits

I discovered this while cross compiling for a Raspberry PI.

**Comment by bradfitz** [comment]
Thanks. Yeah, `BufferedByteLimit` shouldn't be of type `int` if it expects to have values like `MaxInt64`. But 2 GB of buffering seems like a lot, and `int` is the normal type we use for the size of in-memory things, so it seems like the mistake is that `MaxInt64` should be `int(^uint(0) >> 1)`

```go
const maxInt = int(^uint(0) >> 1)
```
