### ISSUE TITLE
Clarify if pubsub Topics are shareable.

### ISSUE THREAD

**Issue by michael-stevens** [GoogleCloudPlatform/google-cloud-go#649]
It's not clear from the docs if pubsub Topics are shareable. 

For example the client makes the explicit statement:

    Clients should be reused rather than being created as needed. A Client may
    be shared by multiple goroutines.

There is no similar statement for Topics, either positive or negative.

Various other comments such as:

    Avoid creating many Topic instances if you use them to publish.

*suggest* they are shareable, but it's never made explicit either way that I can find.

**Comment by pongad** [comment]
Apart from `PublishSettings` which can only be set before calls to `Publish`, Topic may be used concurrently. Perhaps the doc should say `methods may be called concurrently by multiple goroutines`? @jba WDYT?

Of course, if you call `Delete` concurrently with `Exists`, you might get weird behaviors but the client itself will work OK.

**Comment by jba** [comment]
https://code-review.googlesource.com/13658
