### ISSUE TITLE
logging: automatically detect GKE and GAE Flex resources

### ISSUE THREAD

**Issue by alixMougenot** [GoogleCloudPlatform/google-cloud-go#650]
The creation of a new Logger can automatically set ressources for GCE instances, but it cannot do it yet for GKE Containers. Having type:gce_instance can be confusing for code running inside a container. You end up with logs from the containers appear as if the hosting machine was producing them.

Proposed behaviour:
* When code runs inside a Google Container Engine
  * the type is set to 'container',
  * the labels: pod_id, cluster_name, container_name, namespace_id, are populated as well.

**Comment by zombiezen** [comment]
From some internal discussion, k8s may not give all the necessary information to the pod by default. The [C# client libraries](https://github.com/googleapis/gax-dotnet/blob/2ae771d2b0344a8834967ccded4a5da5c5e50b3a/src/Google.Api.Gax/Platform.cs#L190) make a best-effort attempt from the metadata server.  We could take the same approach until there's better GKE support.

**Comment by jba** [comment]
I'm assuming this isn't high-priority, because it's just a convenience: the user can set the resource themselves. Correct me if I'm wrong.

**Comment by alixMougenot** [comment]
You are assuming right, from my point of view at least. This is to correct a source of confusion for stack driver users : the tool will show that the VM running the containers is outputting logs when it is the pods.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
