### ISSUE TITLE
datastore: retry RPCs

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-go#652]
According to the [docs](https://cloud.google.com/datastore/docs/concepts/errors), we should retry on UNAVAILABLE, DEADLINE_EXCEEDED, and ABORTED (presumably only for idempotent calls).

**Comment by pongad** [comment]
Looking at the [datastore proto definition](https://github.com/googleapis/googleapis/blob/master/google/datastore/v1/datastore.proto), all RPCs use the POST verb which is generally not idempotent. Perhaps the doc means we can retry even though it's not idempotent...?

Interestingly, Ruby client was also thinking about this a while back, but I think they decided not to retry non-idempotent calls.

**Comment by jba** [comment]
I think all the calls (which are over gRPC) are either idempotent or harmlessly non-idempotent. I'm going to retry them all.
