### ISSUE TITLE
iam: [question] how to initialize an IAM client and get project policy?

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#655]
The documentation for exported methods of iam package (http://godoc.org/cloud.google.com/go/iam) does not look like I can initialize it with a projectID, or oauth2.TokenSource.

- `func InternalNewHandle(conn *grpc.ClientConn, resource string) *Handle` --> says internal
- `func InternalNewHandleClient(c client, resource string) *Handle` --> requires unexported "client"

I am trying to get the response of `gcloud projects get-iam-policy <..>` or do a `gcloud iam service-accounts list` however I can't seem to find out how someone would use this package.

cc: @jba

**Comment by jba** [comment]
You shouldn't be calling either of those methods directly. `cloud.google.com/go/iam` is intended to be used in conjunction with other clients that provide resource-specific IAM functionality. For example, see [pubsub.Subscription.IAM](https://godoc.org/cloud.google.com/go/pubsub#Subscription.IAM).

For accessing the IAM service directly, use the package [cloud.google.com/go/iam/admin/apiv1](https://godoc.org/cloud.google.com/go/iam/admin/apiv1).
