### ISSUE TITLE
Generate code for servicemanagement

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#658]
I am trying to use the Service Management API: https://github.com/google/go-genproto/blob/master/googleapis/api/servicemanagement/v1/servicemanager.pb.go

However the corresponding generated package is not present in google-cloud-go.

**Comment by jba** [comment]
Use https://godoc.org/google.golang.org/api/servicemanagement/v1. I don't think we'll be generating anything nicer than that in the near future, but hopefully that is nice enough for your needs.
