### ISSUE TITLE
bigtable: Allow the cbt tool to set the expiration time to "never"

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/google-cloud-go#660]
Right now, `cbt setgcpolicy` doesn't support setting the expiration time to "never." In contrast, you can do this with the HBase shell. It'd be good for `cbt` to support this option.

**Comment by Solen-Win** [comment]
good

**Comment by hegemonic** [comment]
The change in d84cd321885bb5799adca4df58b23d64d5586a4e is a step in the right direction, but unless I'm missing something, I don't think it's quite what's needed. Cloud Bigtable supports garbage-collection policies like "keep _only 2 versions_ of each value, and never garbage-collect values based on their timestamps." In contrast, if you set this argument to `never`, you're saying "keep _all versions_ of each value, and never garbage-collect values based on their timestamps."

I think users need a way to tell cbt that values should never expire _or_ that all versions of each value should be retained, but not both. (Apologies for not noticing the `maxversions` issue before I filed my original bug report. It's a very similar issue: You should be able to set `maxversions=Inf`, and that shouldn't force you to set `maxage` at the same time.)

Could you please reopen the bug and take another shot at this?

**Comment by jba** [comment]
@sduskis What's the right syntax for this?

**Comment by sduskis** [comment]
@hegemonic, let's discuss this offline.

**Comment by sduskis** [comment]
@hegemonic, we have not been able to agree on the requirements internally.  I'm going to close this until that happens.
