### ISSUE TITLE
[iam/admin/apiv1/] cannot use func literal ... as type gax.APICall in argument to gax.Invoke

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#664]
I'm getting the following compilation error:

```
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:229: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:255: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:271: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:290: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
...
```

My guess, `google.golang.org` and `cloud.google.com/go` packages are somehow conflicting. I found similar issue #578, however it doesn't solve my problem as I'm fetching master branch of everything freshly.

The way I vendored my dependencies was as follows:

- remove previously go-get'ted package (rm -rf ~/go)
- remove everything in $GOPATH/src but my project
- rm -rf $GOPATH/{pkg,bin}
- no `vendor/` or lockfiles exist
- run `dep init`
- `go build -v`

Here's the dep output:

```
$ dep init
Searching GOPATH for projects...
Following dependencies were not found in GOPATH. Dep will use the most recent versions of these projects.
  golang.org/x/oauth2
  google.golang.org/api
  cloud.google.com/go
  github.com/gorilla/mux
  github.com/pkg/errors
```

<details>
<summary>click here for full **go build -v** output </summary>
<pre>
github.com/ahmetb/gcb-dashboard/vendor/github.com/golang/protobuf/proto
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/http2/hpack
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/text/transform
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/text/unicode/bidi
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/internal/timeseries
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/trace
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/codes
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/credentials
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/grpclog
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/internal
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/keepalive
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/metadata
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/naming
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/peer
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/stats
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/tap
github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/internal/version
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/iterator
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/oauth2/internal
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context/ctxhttp
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/oauth2/jws
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/googleapi/transport
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/oauth2
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/text/secure/bidirule
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/text/unicode/norm
github.com/ahmetb/gcb-dashboard/vendor/github.com/gorilla/mux
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/oauth2/jwt
github.com/ahmetb/gcb-dashboard/vendor/github.com/pkg/errors
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/googleapi/internal/uritemplates
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/googleapi
github.com/ahmetb/gcb-dashboard/vendor/github.com/golang/protobuf/protoc-gen-go/descriptor
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/grpclb/grpc_lb_v1
github.com/ahmetb/gcb-dashboard/vendor/github.com/golang/protobuf/ptypes/any
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/genproto/googleapis/rpc/status
github.com/ahmetb/gcb-dashboard/vendor/github.com/golang/protobuf/ptypes/empty
github.com/ahmetb/gcb-dashboard/vendor/github.com/golang/protobuf/ptypes/timestamp
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/status
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/genproto/protobuf/field_mask
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/genproto/googleapis/api/annotations
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/gensupport
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/idna
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/cloudbuild/v1
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/sourcerepo/v1
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/lex/httplex
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/http2
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/transport
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/genproto/googleapis/iam/v1
github.com/ahmetb/gcb-dashboard/vendor/github.com/googleapis/gax-go
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/internal
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/option
github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/iam
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/genproto/googleapis/iam/admin/v1
github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/internal
github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/compute/metadata
github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/oauth2/google
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/grpc/credentials/oauth
github.com/ahmetb/gcb-dashboard/vendor/google.golang.org/api/transport
github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/iam/admin/apiv1
# github.com/ahmetb/gcb-dashboard/vendor/cloud.google.com/go/iam/admin/apiv1
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:229: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:255: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:271: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:290: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:304: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:316: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:332: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:348: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:362: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:374: cannot use func literal (type func("github.com/ahmetb/gcb-dashboard/vendor/golang.org/x/net/context".Context) error) as type gax.APICall in argument to gax.Invoke
vendor/cloud.google.com/go/iam/admin/apiv1/iam_client.go:374: too many errors
</pre>
</details>

<details>
<summary>Gopkg.toml</summary>
<pre>
[[constraint]]
  name = "cloud.google.com/go"
  version = "0.7.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"
</pre>
</details>

<details>
<summary>Gopkg.lock</summary>
<pre>
# This file is autogenerated, do not edit; changes may be undone by the next 'dep ensure'.

[[projects]]
  name = "cloud.google.com/go"
  packages = ["compute/metadata","iam","iam/admin/apiv1","internal","internal/version"]
  revision = "2e6a95edb1071d750f6d7db777bf66cd2997af6c"
  version = "v0.7.0"

[[projects]]
  branch = "master"
  name = "github.com/golang/protobuf"
  packages = ["proto","protoc-gen-go/descriptor","ptypes/any","ptypes/empty","ptypes/timestamp"]
  revision = "e325f446bebc2998605911c0a2650d9920361d4a"

[[projects]]
  branch = "master"
  name = "github.com/googleapis/gax-go"
  packages = ["."]
  revision = "84ed26760e7f6f80887a2fbfb50db3cc415d2cea"

[[projects]]
  name = "github.com/gorilla/context"
  packages = ["."]
  revision = "1ea25387ff6f684839d82767c1733ff4d4d15d0a"
  version = "v1.1"

[[projects]]
  name = "github.com/gorilla/mux"
  packages = ["."]
  revision = "bcd8bc72b08df0f70df986b97f95590779502d31"
  version = "v1.4.0"

[[projects]]
  name = "github.com/pkg/errors"
  packages = ["."]
  revision = "645ef00459ed84a119197bfb8d8205042c6df63d"
  version = "v0.8.0"

[[projects]]
  branch = "master"
  name = "golang.org/x/net"
  packages = ["context","context/ctxhttp","http2","http2/hpack","idna","internal/timeseries","lex/httplex","trace"]
  revision = "dfe83d419c9403b40b19d08cdba2afec27b002f7"

[[projects]]
  branch = "master"
  name = "golang.org/x/oauth2"
  packages = [".","google","internal","jws","jwt"]
  revision = "f047394b6d14284165300fd82dad67edb3a4d7f6"

[[projects]]
  branch = "master"
  name = "golang.org/x/text"
  packages = ["internal/gen","internal/triegen","internal/ucd","secure/bidirule","transform","unicode/bidi","unicode/cldr","unicode/norm","unicode/rangetable"]
  revision = "3491b61b9edc56653ad4333e605e2908e46a036b"

[[projects]]
  branch = "master"
  name = "google.golang.org/api"
  packages = ["cloudbuild/v1","gensupport","googleapi","googleapi/internal/uritemplates","googleapi/transport","internal","iterator","option","sourcerepo/v1","transport"]
  revision = "324744a33f1f37e63dd1695cfb3ec9a3e4a1cb05"

[[projects]]
  name = "google.golang.org/appengine"
  packages = [".","internal","internal/app_identity","internal/base","internal/datastore","internal/log","internal/modules","internal/remote_api","internal/socket","internal/urlfetch","socket","urlfetch"]
  revision = "150dc57a1b433e64154302bdc40b6bb8aefa313a"
  version = "v1.0.0"

[[projects]]
  branch = "master"
  name = "google.golang.org/genproto"
  packages = ["googleapis/api/annotations","googleapis/iam/admin/v1","googleapis/iam/v1","googleapis/rpc/status","protobuf/field_mask"]
  revision = "aa2eb687b4d3e17154372564ad8d6bf11c3cf21f"

[[projects]]
  name = "google.golang.org/grpc"
  packages = [".","codes","credentials","credentials/oauth","grpclb/grpc_lb_v1","grpclog","internal","keepalive","metadata","naming","peer","stats","status","tap","transport"]
  revision = "d8960bd63c6743defa6d54926e5edfa8e4a28e43"
  version = "v1.4.0"

[solve-meta]
  analyzer-name = "dep"
  analyzer-version = 1
  inputs-digest = "70d226ce6a717a687efcbe9f8448b1489dcf422ebabb0945794c40c16dbf46a1"
  solver-name = "gps-cdcl"
  solver-version = 1

</pre>
</details>

**Comment by broady** [comment]
Another case where partial vendoring leads to incompatible function
signatures.

**Comment by ahmetb** [comment]
I am not sure I understand the reason. How can I resolve this? Should I be downgrading one of the packages to a prior commit?

**Comment by broady** [comment]
Easiest way:
rm -rf ./vendor

Will add more explanation tomorrow.

On Jun 13, 2017 9:50 PM, "Ahmet Alp Balkan" <notifications@github.com>
wrote:

I am not sure I understand the reason. How can I resolve this? Should I be
downgrading one of the packages to a prior commit?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/google-cloud-go/issues/664#issuecomment-308318933>,
or mute the thread

**Comment by ahmetb** [comment]
It worked. I've never seen this, amazing.

**Comment by ahmetb** [comment]
@jba is there another issue tracking this problem? if not we can convert this into something that tracks the vendoring issue.

**Comment by jba** [comment]
Related to #595, #434 and google/google-api-go-client#198.

**Comment by jba** [comment]
I just tagged the current master as v0.8.0, so if I understand dep correctly, if you re-run from scratch everything should work. At least with respect to this repo.
