### ISSUE TITLE
[iam] testing whether current account has permission to APIs/operations

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#665]
This question is not Go-specific: I am trying to find out if my current credentials have permission to do certain API calls before actually making the calls (so that I can tell my users what permissions are missing on their Service Accounts).

I found this [Testing Permissions](https://cloud.google.com/iam/docs/testing-permissions) article, it tells me to use the TestIamPermissions call. It takes a list of permissions, returns back a list of granted permissions. (Is there a better way of doing this, I appreciate if you can show.)

```go

import iam "cloud.google.com/go/iam/admin/apiv1"
import iampb "google.golang.org/genproto/googleapis/iam/v1"

...
scopes := []string{
	"sourcerepo.repos.get",
	"container.clusters.get",
}
p, err := iamCl.TestIamPermissions(ctx, &iampb.TestIamPermissionsRequest{
	Resource:    fmt.Sprintf("projects/%s", project),
	Permissions: scopes})
if err != nil {
	log.Fatal(errors.Wrap(err, "failed to test iam permissions"))
}
log.Println(p.GetPermissions())
```

(I normally copied scopes from [API explorer](https://developers.google.com/apis-explorer/#search/container/container/v1/), and it was in form e.g. `sourcerepo.projects.repos.get` but IAM doesn't allow that. It says `It must be in the form "service.resourceType.verb".`)

This gives error:

> `rpc error: code = InvalidArgument desc = The name should be in the form "projects/{project_id}/serviceAccounts/{account}".`

So I update the `Resource` to the Service Account I am using (though I am not sure how can I find the email/ID of the current account in runtime):

```go
p, err := iamCl.TestIamPermissions(ctx, &iampb.TestIamPermissionsRequest{
	Resource:    fmt.Sprintf("projects/%s/serviceAccounts/test-sa@ahmetb-starter.iam.gserviceaccount.com", project),
	Permissions: scopes})
```

Running this gives error:

> `rpc error: code = InvalidArgument desc = Permission sourcerepo.repos.get is not valid for this resource.`

Unfortunately the [testing permissions](https://cloud.google.com/iam/docs/testing-permissions) article doesn't even describe a `Resource` in the call (see Java tab). If I omit Resource field, I get:

> `rpc error: code = InvalidArgument desc = The name should be in the form "projects/{project_id}/serviceAccounts/{account}".` again.

What's the best way to test if the current account has permissions to particular APIs or operations?

**Comment by ahmetb** [comment]
Updated the issue title, sorry for sending it empty initially.

**Comment by jba** [comment]
There is a level of meta here that you have to appreciate first.

IAM operations like TestIamPermissions are designed to be part of each Google API. For instance, there is the [IAM service baked into pubsub](https://cloud.google.com/pubsub/docs/reference/rpc/google.iam.v1#google.iam.v1.IAMPolicy.TestIamPermissions).

You use those methods on the pubsub API to do IAM things with pubsub resources like Topics. (The Go pubsub client [makes this easy](https://godoc.org/cloud.google.com/go/pubsub#Topic.IAM).)

Now for the meta part: the  [IAM API](https://cloud.google.com/iam/reference/rest/) itself manages IAM operations on _its_ resources, which are service accounts and only service accounts.

So to do IAM things with containers, use the TestIamPermissions method of the container API. Unfortunately that doesn't seem to exist yet. But that is a question for the maintainers of that API.

**Comment by ahmetb** [comment]
Thanks, I understand and appreciate that part. I assume what I was looking for was more in line with was whether I can test capabilities of a Service Account with roles.

As an example, a service account with `roles/container.developer` can do `container.clusters.get` but not  `container.clusters.delete`. But I take your answer as _there is no way to find this out without actually executing the query in runtime.

**Comment by jba** [comment]
You want the mapping from role to permissions, and yes, AFAIK there is no API call that will give you that.
