### ISSUE TITLE
Speech Recognition API: Create complete example for streaming

### ISSUE THREAD

**Issue by PhillippOhlandt** [GoogleCloudPlatform/google-cloud-go#666]
Hey, 

I would like to use the golang SDK for the speech recognition streaming API. But I can't find a complete example. Neither in the official documentation nor [here](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/speech/apiv1/speech_client_example_test.go#L90).

**Comment by jba** [comment]
@broady @rakyll Do we have one somewhere?

**Comment by PhillippOhlandt** [comment]
In case it was not clear. I talk about streaming from a file in realtime.

**Comment by rakyll** [comment]
@PhillippOhlandt, we have a live caption sample that reads from os.Stdin, see https://github.com/GoogleCloudPlatform/golang-samples/blob/master/speech/livecaption/livecaption.go. You can modify it read from an os.File.

**Comment by PhillippOhlandt** [comment]
Thanks! Will try to modify it to my needs!

**Comment by PhillippOhlandt** [comment]
Hey, I almost got it working. I get my text but the last thing I get is an error.

```
Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 199.99940844543744 second(s). Required at least: 201 second(s).
```

I used this as blueprint, so it's basically the same, except that it reads from a file.
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/speech/livecaption/livecaption.go

How can I set the GRPC deadline?
