### ISSUE TITLE
bigtable: gRPC message too large error while using go bigtable client

### ISSUE THREAD

**Issue by emembrives** [GoogleCloudPlatform/google-cloud-go#667]
Hello,

I tried to read a largish row with the Bigtable go client on a Google Cloud Bigtable instance. The row is written *many times* as follows:
```
keys := []string{"medium-write-unique-key"}
datum := strings.Repeat("#", 1024*70+5)
muts := make([]*bigtable.Mutation, 1)
muts[0] = bigtable.NewMutation()
muts[0].Set(columnFamilyName, columnName, bigtable.Now(), []byte(datum))
_, err := bb.table.ApplyBulk(ctx, keys, muts)
```

Then read back:
```
filter := bigtable.RowFilter(bigtable.ColumnFilter(columnName))
_, err := bb.table.ReadRow(bb.ctx, keys[0], filter)
```

This works fine when `datum` is small, but when it is larger (as in this example), I get the following error:
```
Could not read row with key medium-write-unique-key: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4230274 vs. 4194304)
```

Am I holding it wrong? Is there something I can configure to make it work?

**Comment by garye** [comment]
Out of curiosity, are you hitting the live service or the emulator/inmem fake server?

**Comment by emembrives** [comment]
It is on the live service.

**Comment by garye** [comment]
Try creating the client with this option:
`option.WithGRPCDialOption(grpc.WithDefaultCallOptions(grpc.MaxCallSendMsgSize(100<<20), grpc.MaxCallRecvMsgSize(100<<20)))`

I think this needs to become the default in the client.

**Comment by garye** [comment]
Fixed by I58f6cac56caf4741059550de969275419e9accb6
