### ISSUE TITLE
bigtable: `Error resolving project` when working with emulated bigtable instance.

### ISSUE THREAD

**Issue by codingtwinky** [GoogleCloudPlatform/google-cloud-go#673]
According to the bigtable emulator [doc](https://cloud.google.com/bigtable/docs/emulator), we should be able to use any project and instance ID but I'm receiving `error resolving project`.

> you can connect to it using any project and instance name to create tables and read or write data.

### steps to reproduce:

1. run local bigtable emulator `gcloud beta emulators bigtable start`
2. new terminal, configure bigtable env `gcloud beta emulators bigrtable env-init`
3. run below code and receive `2017/06/19 15:36:11 Couldn't write a rowrpc error: code = InvalidArgument desc = Error resolving project (devproject) : Invalid Id`

```go
package main

import (
	"context"
	"log"

	"cloud.google.com/go/bigtable"
)

const (
	col1   = "col1"
	col2   = "col2"
	colFam = "f1"
)

var (
	client *bigtable.Client
	ctx    context.Context
)

func main() {
	ctx = context.Background()

	client, err := bigtable.NewClient(
		ctx,
		"devproject",
		"devinstance",
	)
	if err != nil {
		log.Fatal("Couldn't get client", err)
	}

	btTable := client.Open("test-table")

	write(btTable, "abc.1", "a", "b") // add row 1
	if err != nil {
		log.Fatal("Couldn't write a row", err) // <-- go kaboom here
	}
}

func write(table *bigtable.Table, row string, val1 string, val2 string) error {
	mut := bigtable.NewMutation()
	mut.Set(colFam, col1, bigtable.Now(), []byte(val1))
	mut.Set(colFam, col2, bigtable.Now(), []byte(val2))
	return table.Apply(ctx, row, mut, nil)
}
```

**Comment by garye** [comment]
I've never gotten the `env-init` stuff to automatically set the environment variable, either. Try manually exporting `BIGTABLE_EMULATOR_HOST` in the terminal that you run the application code in and it should work.

Try reporting this with `gcloud feedback`, though, if you can.

**Comment by codingtwinky** [comment]
I can confirm setting `BIGTABLE_EMULATOR_HOST` works.  Perhaps, [doc](https://cloud.google.com/bigtable/docs/emulator) should be changed?
