### ISSUE TITLE
all: batch Requests For API  Calls

### ISSUE THREAD

**Issue by RC1140** [GoogleCloudPlatform/google-cloud-go#675]
Hi

I either do not have a full grasp of the library (entirely possible) or I cant find out how to batch requests in the same manner that the python and other google client libraries do. The batching that I am reffering to can be found at the link below 

https://developers.google.com/api-client-library/python/guide/batch

Can someone please either direct me to the correct location (and I will update the documentation and samples later) or indicate if this is completely missing and need to be implemented still.

Thanks

**Comment by jba** [comment]
It's missing, and we're unlikely to add it to a particular client unless the underlying service provides a batch RPC. (Otherwise there's no gain.)

I will point out that the first sentence of the page you link to, "each HTTP connection that your application makes results in a certain amount of overhead", doesn't apply to Go. We don't create separate HTTP (or gRPC) connections for each request. So it may be that Python's batching is needed to achieve the performance that we already have in Go.

@RC1140, the best way to proceed is for you to provide a specific example where lack of batching is slowing you down. Then we can see how we can help.

**Comment by RC1140** [comment]
Hi
I am using the natural language api and making multiple requests for each sentence/tweet that I need to analyze. The number of requests is quite high and it seems quite heavy to make 1000 individual vs 1 request with 1000 items batched.

**Comment by pongad** [comment]
@RC1140 I assume you're using [language/apiv1](https://godoc.org/cloud.google.com/go/language/apiv1)? You said you make multiple requests for the same sentence. Do you make multiple calls to Analyze* methods? I believe AnnotateText method can perform multiple analysis types in one call. Will this help?

I could be wrong, but I don't think the language RPC itself provides any batching functionality beyond that.

**Comment by RC1140** [comment]
@pongad Yup that is the api end point I am using (specifically the analyze sentiment), its not multiple requests for the same sentence but rather multiple different sentences. I saw the anotatetext method but that is simple for different types of calls , I am making calls only to the sentiment endpoint, I just have a lot of data that I want to analyze.

**Comment by jba** [comment]
> it seems quite heavy to make 1000 individual vs 1 request with 1000 items batched

What do you mean by "heavy"? Do you mean "takes a long time if done sequentially"? That's true, but you can do them in parallel. Do you mean "causes a lot of network traffic"? The total number of bytes is not that much larger. 

The best way to convince us that something is wrong is to provide a sample program that behaves poorly compared to one that batches.

**Comment by RC1140** [comment]
Hi
I was simply looking for a way to make fewer api calls , doesnt seem like its possible though.

**Comment by paulmwatson** [comment]
Yes just wanted to +1 this idea. I want to classifyText of hundreds of documents which requires a separate call for each at the moment. A batch method would make it quicker.

**Comment by abdullahonden** [comment]
Hey there, 

I'm having the same issue here. I have nearly 250.000 tweets and I'd like to get their sentiment results only. So other services like [sentiment140](http://help.sentiment140.com/api#TOC-Bulk-Classification-Service-CSV-) or [Vivekn](http://sentiment.vivekn.com/docs/api/) gives the oppurtunity to send thousands of tweets in one request and returns the result in the same way. 

Here it's [documented](https://developers.google.com/drive/api/v3/batch#example) we can use batching but it doesn't seem to implement easy as the services I mentioned above.

**Comment by ingmferrer** [comment]
+1, boto3 (AWS library which includes NLP) have this batch solution. I don't want to make hundred of thousands requests to get sentiment analysis.
