### ISSUE TITLE
trace: add (Client*).Close to flush all buffered spans

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#678]
For short-lived programs, the existing non-blocking solution doesn't always work well. Short-lived programs may exist before the buffer is uploaded to the Stackdriver backend. Add a Close to flush the buffered span queue.

**Comment by jba** [comment]
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).
