### ISSUE TITLE
gax redeclared as imported package name

### ISSUE THREAD

**Issue by jcgregorio** [GoogleCloudPlatform/google-cloud-go#681]
This CL https://github.com/GoogleCloudPlatform/google-cloud-go/commit/cb384886300b62db8215238ce2ab5d269fe599de introduced a second 'gax' definition in the file:

  https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/service.go#L31

Now importing this package gives:

../../cloud.google.com/go/pubsub/service.go:31: gax redeclared as imported package name 	previous declaration at ../../cloud.google.com/go/pubsub/service.go:25

**Comment by jba** [comment]
Probably due to a bad merge.

Fixed by 2cbf161fc57d9dda2921f3d7841e0b683fa09d3e.

**Comment by jcgregorio** [comment]
Thanks!
