### ISSUE TITLE
internal: move bundler from google.golang.org/api/support/bundler

### ISSUE THREAD

**Issue by zombiezen** [GoogleCloudPlatform/google-cloud-go#685]
@jba AFAICT, bundler is only used inside cloud.google.com/go/, not in the generated APIs.  Especially since the API is unstable, it makes more sense to me to move it into this repository as a private package.

**Comment by jba** [comment]
@mcgreevy Just making sure you're OK with this, since we made it visible for another project you were working on.

**Comment by mcgreevy** [comment]
We are still using it in the chrome infra code, so it would be good if it could remain public.

(FYI I'll be OOO for 2 weeks, so may not reply further on this thread for a while).

**Comment by jba** [comment]
Leaving things as they are.

**Comment by zombiezen** [comment]
This is definitely a P2-ish issue, but we should decide to either:

a) Make this a stable API, in which case I'm not sure it belongs where it is.
b) Make it internal-only and copy it into places that need it.

There aren't that many folks depend on it right now (<10 based on public GitHub data), so it would be easier to do sooner rather than later.

**Comment by jba** [comment]
Moving it and making it stable are mostly orthogonal. Why can't it be world-visible (to avoid code duplication) and marked experimental/alpha? 

I'm not entirely ready to mark the API stable.

**Comment by zombiezen** [comment]
I'm not saying we should do it now, but we should have a plan for its future.  The world-visible part isn't that bad except that you have to update the rest of the API client with it if you want to get a fix.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
