### ISSUE TITLE
Document how to authorize requests on GAE Standard

### ISSUE THREAD

**Issue by ImJasonH** [GoogleCloudPlatform/google-cloud-go#687]
GAE Standard requires HTTP requests to be made through a `urlfetch.Client`. But that means that requests can't also be easily use a token source (e.g., `AppEngineTokenSource`), because has `option.WithHTTPClient` documents:

> When used, the WithHTTPClient option takes precedent over all other supplied options.

So this doesn't apply credentials as you would expect:

```
client, _ := storage.NewClient(ctx,
  option.WithHTTPClient(urlfetch.Client(ctx)),
  option.WithTokenSource(google.AppEngineTokenSource(ctx, scope)))
```

Requests are made over `urlfetch`, but without credentials provided by the token source. So the `AppEngineTokenSource` is effectively unusable with these clients, since you need to be able to use it with the `urlfetch.Client`.

**Comment by broady** [comment]
No need. The storage client uses urlfetch by default.

Just use `client, err := storage.NewClient(ctx)`.
