### ISSUE TITLE
Bigquery load jobs submitted with Golang client do not appear in BigQuery UI

### ISSUE THREAD

**Issue by 4d55397500** [GoogleCloudPlatform/google-cloud-go#688]
BigQuery load jobs (for example loading cloud storage JSON files to a table) submitted with the Golang Bigquery client do not appear in the BigQuery console UI under 'Job History'.

There should be a consistent job history view in the UI.

**Comment by pongad** [comment]
I'm not sure this issue is on the client lib, since this looks like a request to the UI itself, not the client lib. I opened a request to BigQuery [here](https://issuetracker.google.com/issues/64546603)
