### ISSUE TITLE
spanner: support embedded structs

### ISSUE THREAD

**Issue by hkoske** [GoogleCloudPlatform/google-cloud-go#692]
Hello.

With the spanner package, it is currently impossible to write and retrieve structs that embedded other structs.

For example:

```go
type (
    RecordData struct{
        ID string
        CreatedAt, UpdatedAt time.Time
    }
    User struct{
        RecordData
        FirstName, LastName, Email string
     }
)
```

Whenever attempting to use the `toStruct` method of `spanner.Row`, the spanner package is unable to locate fields from an embedded struct.

The **go driver for Mongo DB**, [here](https://godoc.org/labix.org/v2/mgo/bson#Marshal), implemented this feature really well. Can something similar be developed for the spanner package?

**Comment by Solen-Win** [comment]
Readme_edits.

**Comment by hkoske** [comment]
@Solen-Win what do you mean?

**Comment by jba** [comment]
I believe this is fixed.  Anyway, I can no longer reproduce.
