### ISSUE TITLE
messages are not getting load balanced among subscribers

### ISSUE THREAD

**Issue by smothiki** [GoogleCloudPlatform/google-cloud-go#696]
Hi Guys,
Need help here, I don't know if this is the right channel. Please guide me to the right channel, if not. 
We are using Google pubusb and writing subscriber in Golang using V0.10.0. We have a single topic and single subscription on the topic.
We are running 3 subscribers, let's say sub1,sub2,sub3. Every time sub1 is receiving messages. Sub2 and sub3 are idle. Sub2 is receiving messages if I kill sub1.
We have a message ack deadline of 20 seconds and Most of the time we are sending ACK immediately as we receive the message.
The subscriber is using PULL mode.
Let me know if there is any setting that I'm missing to load balance the message. Or this is expected behavior.

**Comment by pongad** [comment]
This looks like https://github.com/GoogleCloudPlatform/google-cloud-go/issues/698 . Let's move discussions there? I'll close this for now as duplicate, but please reopen if you believe the issues are distinct.
