### ISSUE TITLE
pubsub: multiple subscribers not getting messages

### ISSUE THREAD

**Issue by raliste** [GoogleCloudPlatform/google-cloud-go#698]
After refactoring to sub.Receive we are seeing all messages being delivered to just one subscriber.

We are publishing to a topic that has one subscription with multiple subscribers.

Any thoughts?

**Comment by pongad** [comment]
To make sure I understand you right: Are these subscribers on one machine or spread across many?

If the former, this could be a problem with the client lib. I'm not sure what could be causing this. Though, `Receive` will spin up many goroutines to pull and process your messages, so creating multiple Subscription objects is probably not necessary.

If the latter, I'll reach out to folks with more mastery than I do :smile:

**Comment by raliste** [comment]
Spread across many (virtually). Specifically, we are deploying these as pods within a kubernetes cluster.

**Comment by cortesi** [comment]
It looks like this is yet more breakage from 927c81288027fdcd2bebdeac522c799440e988a4. Have a look at the following graph of CPU usage across a cluster of ours - every red vertical line is a deploy.


<img width="916" alt="pubsub" src="https://user-images.githubusercontent.com/22544/28252502-3640a642-6ae8-11e7-9d9c-6d73be2c7259.png">

We start with a well-behaved system with load shared about equally across workers. Then we make the mistake of deploying v10.0 of google-cloud-go. One or two systems now dominate and everything else drops to zero. We try a few different things, until we finally categorically set `ReceiveSettings.NumGoroutines = 1` across everything in production, and order is restored.

@raliste So, `ReceiveSettings.NumGoroutines = 1`  is the workaround that fixed things for us. I'd be interested to hear if it works for you too.

This single change broke both our CI environment by triggering a bug in the emulator, and has load sharing in production. I just don't feel the upstream impact was tested carefully enough before this made it into a release.

**Comment by pongad** [comment]
Thank you again for the analysis. I have created a CL https://code-review.googlesource.com/#/c/14750/ to default `NumGoroutines` to 1 so people don't see more of this. Could you let us know what your workload is like per message?

@kamalaboulhosn My current theory is that when we increase the number of puller goroutines, we make subscribers pull too eagerly. Each goroutine pulls `MaxOutstandingMessages` messages, so one machine ends up pulling many times more messages than it could concurrently process. We limit the number of concurrent worker goroutines among all pullers so machines don't run out of resources. Still, one machine has a lot of messages in backlog, and those messages cannot be processed by other machines.

A potential fix is to make each puller pull `MaxOutstandingMessages/NumGoroutines` at a time, but this won't work after we move to streaming pull right?

**Comment by cortesi** [comment]
For the graph I posted, the workload is heavy: each job requires about 0.5 of a CPU for ~15 seconds. We run about 8 concurrent processes per worker system, controlled with MaxOutstandingMessages. 

Another issue with the goroutine change is that it's changed the semantics of MaxOutstandingMessages in a major, major way. This was the only clear knob for controlling concurrency of queue consumers. However, this is a per-subscriber setting, and after 927c81288027fdcd2bebdeac522c799440e988a4 the library will silently fire up 10 x runtime.GOMAXPROCS subscribers by default. So, most users of the library that try to control concurrency in this way will get vastly different results than they expect after updating.

More broadly, I would love to have a built-in, consistent way to control concurrency of a running consumer. It would be great, for instance, to be able to dynamically tune concurrency based on CPU or memory load. The current API makes this un-necessarily clumsy - we have to set NumGoRoutines to 1, control MaxOustandingMessages, then fire up or kill Subscriptions.

**Comment by kamalaboulhosn** [comment]
@pongad @jba MaxOutstandingMessages should apply to the subscriber as a whole, not per goroutine. When using pull for the underlying requests, we should not be calling pull to get more messages if there are already MaxOutstandingMessages that are not acknowledged. Is this not how it is functioning? For streaming pull, this needs to hold true as well: regardless of the number of streams, we should not be exceeding MaxOutstandingMessages. We should also be setting flow control settings on the streams themselves to limit how many more messages we receive if there are too many outstanding already. As I recall, this is how the Java library operates.

**Comment by pongad** [comment]
`MaxOutstandingMessages` is per subscriber, not goroutine, in both Java and Go. In both languages, we create semaphores with MOM number of permits. However, in both languages, we call pull *before* we reserve semaphore permits. If the semaphore is full, each puller can call pull one more time before pausing. Each pull can receive at most MOM messages, so we can have the total of `MOM*NumPuller` messages in queue. This sounds a little bad.

I see a few ways to alleviate.
- Limit each pull to `MOM/NumPuller` messages.
  - We might be using RPCs inefficiently, and streaming pull doesn't let us limit number of messages.
- For each pull, figure out how many slots the semaphore have left, ask for at most that many
  - works for polling; streaming doesn't let us limit number
- Before pulling, reserve spot for 1000 messages (max number the api will return)
  - can this number change over time?

I might be missing something obvious. Please let me know what you think.

**Comment by kamalaboulhosn** [comment]
I talked with @davidtorres a little bit. This is expected to be less of a problem when we move to streaming pull. We use the flow control settings of the underlying channel and should in general be able to only get a small number of messages above MaxOutstandingMessages.

Since we only need to worry about this in the context of pull and shouldn't have to worry about it in terms of streaming pull, we could decide to not worry about it since we will be moving to streaming pull soon. Otherwise, I think the second solution is the best one. The first one could affect throughput when we aren't flow controlled and the third one might reserve too many slots since each underlying pull may not necessarily get back 1000 messages.

**Comment by raliste** [comment]
> Maybe our workload is not sufficiently representative.

We are actually running long-lived tesseract OCR jobs. We were maxing out our CPU capacity as multiple executions were running concurrently. Our workaround was setting `MaxOutstandingMessages` and `NumGoroutines` to 1, which is analogous to our usage of a subscription iterator before.

**Comment by pongad** [comment]
@davidtorres  @kamalaboulhosn I'm sorry I don't completely understand this. I assume you're talking about [`CallStreamObserver.request`](https://grpc.io/grpc-java/javadoc/io/grpc/stub/CallStreamObserver.html#request-int-)? IIUC, this only controls the number of gRPC messages, not Pubsub messages right? If we set MaxOutstandingMessages to 1, I don't think there's a way to ask pubsub not to give us 100 messages in one `StreamingPullResponse`?

**Comment by jba** [comment]
> the flow control settings of the underlying channel

Do you mean the http2 channel? If so, you can probably only express it in bytes. It might be hard to limit to messages without unnecessary throttling.

**Comment by jba** [comment]
Or maybe you're thinking of the MaxCallRecvMsgSize CallOption?

**Comment by mdietz94** [comment]
A StreamingPullResponse will contain a single batch as published. It is correct that that will not refer to PubSub user messages, though the upper limit will be 1000 user messages or 20 MB. StreamingPull however, unlike Pull, does not rebatch messages. So your load will be distributed much better since each StreamingPullResponse will be made of a single batch message, just as it was published.

**Comment by dwalker-va** [comment]
Posting to confirm we updated to 343e9553ad795722c97dfafc5622affdaf30d70b and this issue was fixed for us.

When I deployed the code with the previous default for goroutines (927c81288027fdcd2bebdeac522c799440e988a4) I was immediately greeted with this fantastic graph: 
![pubsub-goroutines](https://user-images.githubusercontent.com/7460285/28391970-3a6e3ac0-6c9d-11e7-940a-ba7ee5cba400.png)

We listen to hundreds of subscriptions spread over not nearly as many instances, so it affected us to say the least.

**Comment by rusenask** [comment]
I have also observed this issue, by default I expected that multiple subscribers will be receiving all messages that are published into the topic. Is it not the case?

In my case subscribers are different GKE clusters but in the same project.

**Comment by jba** [comment]
Each _subscription_ will receive all of the topic's messages. But if you have multiple subscriber applications for the same subscription, each application will get a subset of the messages. PubSub attempts to load-balance the messages across the subscriber applications.

**Comment by rusenask** [comment]
I am currently subscribing to events from GCR (https://cloud.google.com/container-registry/docs/configuring-notifications) and creating subscriptions with same name, I guess that's the problem. Each cluster should have create its own unique subscription name to receive all messages, correct?

**Comment by jba** [comment]
Correct.

**Comment by pongad** [comment]
We've scaled back the default `NumGoroutines` to 1 so we should no longer see this problem.
If your messages are easy to process and you're OK having more messages lying around on a machine (might increase your throughput since you need to wait less to get messages) you can increase it.
I'll close this, please reopen if problem persists.

**Comment by IvanProdaiko94** [comment]
@jba is there some way to provide all of the subscribers with all messages of subscription, rather than with subset of those messages?
