### ISSUE TITLE
datastore: support direct insert operation

### ISSUE THREAD

**Issue by pbzdyl** [GoogleCloudPlatform/google-cloud-go#699]
Hello,

I am just starting with Datastore and I noticed that Go Client doesn't support explicit Insert operation but instead [it checks if the key is incomplete or not and creates insert or upsert mutation](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/dc9545a2cb63b1739b9741b2507a6cda79437161/datastore/datastore.go#L555-L559).

[Java Client allows explicit creation with errors raised when trying to insert an entity for existing key
(example from the linked Javadoc)](http://googlecloudplatform.github.io/google-cloud-java/0.20.1/apidocs/com/google/cloud/datastore/Datastore.html#add-com.google.cloud.datastore.FullEntity...-):

```
String keyName1 = "my_key_name1";
String keyName2 = "my_key_name2";
Key key1 = datastore.newKeyFactory().setKind("MyKind").newKey(keyName1);
Entity.Builder entityBuilder1 = Entity.newBuilder(key1);
entityBuilder1.set("propertyName", "value1");
Entity entity1 = entityBuilder1.build();
 
Key key2 = datastore.newKeyFactory().setKind("MyKind").newKey(keyName2);
Entity.Builder entityBuilder2 = Entity.newBuilder(key2);
entityBuilder2.set("propertyName", "value2");
Entity entity2 = entityBuilder2.build();

try {
  datastore.add(entity1, entity2);
} catch (DatastoreException ex) {
  if ("ALREADY_EXISTS".equals(ex.getReason())) {
    // at least one of entity1.getKey() and entity2.getKey() already exists
  }
}
```

It looks like a useful tool for implementing a distributed lock that I would need.

Would it be possible to extend Go Datastore Client to support a direct insert operation?

Best regards,
Piotr

**Comment by odeke-em** [comment]
I've retitled this bug a little, for easy searchability.

**Comment by deckarep** [comment]
I just recently implemented some wrapper logic around my code to do an insert just like you’re describing with the use of a Get followed by a Put within a Transaction.  It seems to be working well for my purposes and I can likely reimplement it for the actual Datastore api of there’s interest?

Ping me directly if there is and I’ll take a crack at it.

**Comment by jba** [comment]
With the release of [Firestore](https://godoc.org/cloud.google.com/go/firestore), we're focusing our efforts there. @deckarep, feel free to post your wrapper code on this issue (and elsewhere).
