### ISSUE TITLE
cbt read failed immediately

### ISSUE THREAD

**Issue by swangsc** [GoogleCloudPlatform/google-cloud-go#700]
This is the error information I got when try to use cbt read. I think it's related to the duploicate proto type. I have updated gcloud commands but the error is still there.
2017/07/18 10:55:17 proto: duplicate proto type registered: google.rpc.Status
2017/07/18 10:55:17 -creds flag unset, will use gcloud credential
2017/07/18 10:55:17 Retryable error: rpc error: code = Unavailable desc = grpc: the connection is closing, retrying in 47.77941ms

**Comment by garye** [comment]
When you see this I think the operation is actually retried and will succeed. Otherwise you'd see different / additional logging. Can you confirm that's the case?

**Comment by garye** [comment]
Please re-open if the read doesn't work after the transient error
