### ISSUE TITLE
spanner: use 1 connection per client when running on App Engine standard

### ISSUE THREAD

**Issue by namusyaka** [GoogleCloudPlatform/google-cloud-go#704]
Hi,
I've been considering using cloud spanner from gae/se now.
However, to realize that, we need to use [the socet API](https://github.com/google/google-api-go-client/blob/master/transport/grpc/dial_appengine.go#L31).

Based on those, I'm facing two problems.

1. Connection pool on GAE/SE

A connection based Socket API seems not to work without appengine Context, so I guess the feature cannot be using session pooling. Maybe we must create new connection for each request, I think. Do I understand things correctly?

Please let me know if there is more reasonable approach.

2. Socket API cannot be used locally

Socket API cannot be connected from local dev_appserver so I sent [a patch](https://code-review.googlesource.com/#/c/14950/).
Could you review this?

Thanks

**Comment by adams-sarah** [comment]
@zombiezen @jba

**Comment by zombiezen** [comment]
Reducing down to one connection per App Engine instance seems like the right approach.  It would be nice for our library to change the defaults for App Engine so that customers don't have to remember to do this.

I reviewed the patch you sent; it looks good.  Thanks!

**Comment by albertog** [comment]
that mean you can use spanner directly from GAE standard and due to only use one connections what about performance?

**Comment by zombiezen** [comment]
@namusyaka After some discussion with @broady, I'm wondering whether there might be a problem in dev_appserver.py.  Can you help us by providing more information about what failure mode you're seeing when you're using the socket API?

@albertog Yes, this will add some overhead because the gRPC call is going through the Socket API instead of URL Fetch.  We are aware that this is an issue not just for Spanner on GAE Standard, but any gRPC client on GAE Standard.  We are working on the issue, but it's a complicated issue that will require some time to address properly.  In the meantime, if after profiling you find that this is having significant performance impact in your application, you can work around this by either (a) use the REST API directly on the impacted call sites or (b) migrate to App Engine Flex, which allows you to set up persistent network connections in your process.

**Comment by namusyaka** [comment]
There is not a problem in dev_appserver.py, but it's a problem of the socket API.
Timeout will be occured in my local, the socket API is only available in paid GAE instance, right?

Of course, the spanner client library can be used in dev_appserver.py if using netcontext.

**Comment by zombiezen** [comment]
@namusyaka Right, what we're trying to discern is whether the Socket API is not working for you in local development (which could be a dev_appserver.py bug).  Can you show us the timeout error message you're seeing?

**Comment by namusyaka** [comment]
I've tried to that, but message is not showing forever. And then, if I sent SIGINT to the process, the following error would be occured.

```
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 103, in <module>
    _run_file(__file__, globals())
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/dev_appserver.py", line 97, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 381, in <module>
    main()
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 377, in main
    dev_server.stop()
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 212, in stop
    self._running_modules.pop().quit()
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 317, in quit
    super(APIServer, self).quit()
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 408, in quit
    server.quit()
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 264, in quit
    self.requests.stop(timeout=1)
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 97, in stop
    self._shutdown_connection(connection)
  File "<My Workspace>/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/wsgi_server.py", line 102, in _shutdown_connection
    connection.socket.shutdown(socket.SHUT_RD)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 57] Socket is not connected
```

If I set timeout to my context (created by `appengine.NewContext`), the following error is occured.

```
spanner: code = "DeadlineExceeded", desc = "context deadline exceeded"
```

**Comment by namusyaka** [comment]
@zombiezen Receiving the advice of @jba, I've updated the patch set.
Could you review that?

**Comment by adams-sarah** [comment]
FYI @zombiezen is on vacation until Monday 8/7 :)

**Comment by namusyaka** [comment]
Omg, I'm sorry :(. Have a nice vacation!

**Comment by adams-sarah** [comment]
haha no problem. he won't even get the notification until he gets back.
just wanted to give you a heads up that it'll take him a while to respond.
cheers.

**Comment by zombiezen** [comment]
dev_appserver CL submitted.  Thanks, @namusyaka!

AFAIK, the only work that remains here is possibly updating the Spanner client to use a 1-connection per client default when running under App Engine Standard.  @vkedia, could you look into this?

**Comment by vkedia** [comment]
So what exactly is the issue with using multiple channels on AppEngine? Is it just that they will never be used since on AppEngine a new client will be created for each request? Or does having multiple channels make the client unusable?

**Comment by zombiezen** [comment]
It is a performance issue.  The client has to be created for every request, since the [Socket API](https://cloud.google.com/appengine/docs/standard/go/sockets/) requires access to the App Engine request context.  Therefore, each TCP connection the client creates has per-request cost.

**Comment by ksimir** [comment]
Just a comment about this change. At each TCP connection a new Spanner client is created with, by default, 4 gRPC connections to Spanner.
I'd like to understand the real impact on performance of reducing it to 1 gRPC connection since the Spanner client still has to be created at each TCP connection. In GAE SE, through the Socket API, 4 gRPC connections are overkill but do you agree that the overall performance of Spanner from GAE SE won't change much? Is the cost of making 4 gRPC connections instead of 1 significant?

**Comment by odeke-em** [comment]
I've retitled this bug a little to reflect the work that's left as per @zombiezen's comment from https://github.com/GoogleCloudPlatform/google-cloud-go/issues/704#issuecomment-320721696 since the dev_appserver CL was submitted.
