### ISSUE TITLE
Content disposition is not set in ObjectAttrs

### ISSUE THREAD

**Issue by daniellowtw** [GoogleCloudPlatform/google-cloud-go#705]
I'm trying to use the cloud storage API to read the metadata of a bucket object but it seems like the content-disposition is never set.

To reproduce: 
```
attr, _ := bucketHandler.Object(objectPath).Attrs(ctx)
// attr.ContentDisposition is always ""
```

It seems like the culprit is 
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/storage.go#L814
From what I can tell, the ContentDisposition field of the raw object should be propagated to the returned ObjectyAttr. Is there any reason why that is not the case?

**Comment by adams-sarah** [comment]
+1 seems like we should populate `ContentDisposition`. @jba @pongad ?
