### ISSUE TITLE
Provide method to retrieve project ID configured on gcloud

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/google-cloud-go#707]
It looks like Go client libraries do not provide a method do to this. I've been shelling out to `gcloud` myself but not sure what's the way guaranteed to work. It would be great if this library can provide a method that will keep working.

Looks like:
- `gcloud config config-helper --format json`
- `gcloud -q config list core/project --format=json`

are the ways the following libraries do this task.

- Python: https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/d020426e170d9d8ab5f9d8d37626c278fed4770c/google/auth/_cloud_sdk.py#L111-L133

- Node.js: https://github.com/google/google-auth-library-nodejs/blob/bd13376281a3af6e73fb729ea867950739c3c899/ts/lib/auth/googleauth.ts#L157-L160

**Comment by rakyll** [comment]
Doesn't https://godoc.org/golang.org/x/oauth2/google#DefaultCredentials ProjectID work for you? 

Btw, we should keep the convo on the [x/oauth2/google](https://github.com/golang/oauth2/issues) issue tracker, we do not have any auth bits under cloud.google.com/go.

**Comment by ahmetb** [comment]
I don't think determining project ID should rely on whether ADC is activated or not.

Also, `ProjectID` field comes empty for me even though `FindDefaultCredentials()` returns a non-empty object and nil for error. I'll move the issue.
