### ISSUE TITLE
trace: grpc-go does not allow 'grpc-trace-bin' for metadata key

### ISSUE THREAD

**Issue by atetubou** [GoogleCloudPlatform/google-cloud-go#709]
This change drops grpc metadata for trace.
https://github.com/grpc/grpc-go/commit/3ddcdc268d88595eb2f3721f7dc87970a6c3ab6e

Which one needs to be fixed, grpc-go or trace metadata key?

**Comment by adams-sarah** [comment]
@rakyll this is the same bug emailed earlier by @jba which is breaking our travis builds.
i think you have the most state, if you could take a look that'd be awesome!

**Comment by rakyll** [comment]
I am looking at this since yesterday.

**Comment by rakyll** [comment]
The change is being reverted for now and will be revised. Please see https://github.com/grpc/grpc-go/pull/1400 to track the status of the revert.

**Comment by rakyll** [comment]
The breaking change has been reverted, please `go get -u` this package and it should work.
