### ISSUE TITLE
bigtable: support to scale instance nodes

### ISSUE THREAD

**Issue by julianvmodesto** [GoogleCloudPlatform/google-cloud-go#710]
With the bigtable.InstanceAdminClient, users should be able to both get and change the number of nodes an instance has.

**Comment by julianvmodesto** [comment]
@garye anything i could do to help here? Happy to take assignee, but this initially looks like we need a corresponding bigtable RPC, so i'd need some coaching if i took a shot at this ticket.

**Comment by garye** [comment]
Sorry that we haven't worked on this yet. I'll try to get to it in the next week or so. Thanks for your patience.

**Comment by sduskis** [comment]
@garye is this still an issue?

**Comment by julianvmodesto** [comment]
Yep! Closed by:
https://github.com/GoogleCloudPlatform/google-cloud-go/commit/c0822307f5df87d8243dc9e4babcc68dd7b1ea31
https://github.com/GoogleCloudPlatform/google-cloud-go/commit/70c2de4bba3c3dc0bd2927e3e3739704a5693e69
