### ISSUE TITLE
consider autoclosing pull requests

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-go#715]
This repo uses gerrit so we can't accept github PRs. We should consider a bot to close PRs and providing instructions on how to use gerrit to contribute. The Go repo already [has this](https://github.com/golang/go/pulls) so there's some precedence.

@jba, I'm not sure if this is appropriate for fixit; please feel free to remove the milestone.

**Comment by adams-sarah** [comment]
a big fat
### +1

**Comment by rakyll** [comment]
I have a CL waiting for this at https://code-review.googlesource.com/c/11596.

**Comment by pongad** [comment]
@rakyll Nice! I didn't know about this. I don't think there is an issue tracking this, so I'm inclined to leave this here for now and close when the CL is merged. Feel free to close if you disagree though.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
