### ISSUE TITLE
errors: errors.(*Client).Close panics if withLogging=true

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/google-cloud-go#717]
the loggingSender type calls Close on an apparently unused field that is never set (client).

**Comment by rakyll** [comment]
@tmc, do you want to open a Gerrit CL or I can land a fix? Follow https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/CONTRIBUTING.md, it is similar to Go's contribution process. And please let me know if you prefer me doing it.

**Comment by rakyll** [comment]
Ah, I saw your CL at https://code-review.googlesource.com/c/15490/ just now.
