### ISSUE TITLE
pubsub: TestAckerStop is failing

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#719]
```
--- FAIL: TestAckerStop (0.00s)
	acker_test.go:162: acker.Stop never returned
```

See the logs at  https://console.cloud.google.com/storage/browser/go-cloud-kokoro-build-logs/logs/prod/gocloud/gcp_ubuntu/presubmit/882/20170803-133743.

**Comment by adams-sarah** [comment]
looks like a flake. @jba is it too late for fixit?

**Comment by jba** [comment]
No, but it's not worth fixing because the acker will vanish soon, once the streaming pull implementation comes on line in a week or two.
