### ISSUE TITLE
Google Cloud CDN

### ISSUE THREAD

**Issue by sahilm** [GoogleCloudPlatform/google-cloud-go#725]
When will Google Cloud CDN be supported? Are you willing to accept pull requests? Thank you.

**Comment by sahilm** [comment]
I'm unable to find a published HTTP/gRPC API for Google Cloud CDN. Is this why there's no support in this SDK?

**Comment by jba** [comment]
There doesn't seem to be a CDN API (I couldn't find one on the [doc page](https://cloud.google.com/cdn/docs), so we can't really make a client for it.

**Comment by sahilm** [comment]
Understood. Thank you.
