### ISSUE TITLE
"bigquery.InferSchema" should allow optional fields.

### ISSUE THREAD

**Issue by danjacques** [GoogleCloudPlatform/google-cloud-go#726]
From [bigquery.InferSchema](https://godoc.org/cloud.google.com/go/bigquery#InferSchema) documentation:

```go
// InferSchema tries to derive a BigQuery schema from the supplied struct value.
// NOTE: All fields in the returned Schema are configured to be required,
// unless the corresponding field in the supplied struct is a slice or array.
```

It is useful to be able to infer a schema with optional fields from a struct. Can we extend the struct tag notation to allow this, something like:

```go
type MySchema struct {
  ReqField string `bigquery:"req_field"`
  OptField string `bigquery:"opt_field,optional"`
  DefaultNameOpt string `bigquery:",optional"`
}
```

**Comment by adams-sarah** [comment]
@jba @pongad

**Comment by danjacques** [comment]
One other thing that came up during development: The required-by-default operation is suboptimal, since fields added during schema changes [must be optional/nullable](https://cloud.google.com/bigquery/docs/tables#update-schema). It seems more reasonable that `InferSchema` would make a field optional by default w/ a tag allowing it to be required.

```go
type MySchema struct {
  ReqField string `bigquery:"req_field,req"`
  OptField string `bigquery:"opt_field"`
}
```

Since this silently breaks API, could add a boolean parameter to `InferSchema`, `requiredByDefault`?

**Comment by jba** [comment]
The approach I took in https://github.com/GoogleCloudPlatform/google-cloud-go/commit/6856ba47182f3481aad44ac8469409663fddaf80 is broken: it allowed you to declare a field as nullable even though you couldn't use the field to read or write NULLs.

See https://code-review.googlesource.com/c/gocloud/+/21632, which uses pointer types instead.
