### ISSUE TITLE
errors: Client should take additional settings in a config object

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#727]
Similar to other Google Cloud Cloud clients, additional settings can be passed in a config object to keep the consistency between cloud packages.

```
func NewClient(ctx context.Context, projectID, serviceName, serviceVersion string, useLogging bool, opts ...option.ClientOption) (*Client, error)
```

can be 

```
func NewClient(ctx context.Context, projectID, cfg Config, opts ...option.ClientOption) (*Client, error)
```

Service name is the only non optional configuration according to the godoc, but Cloud libraries in other languages (such as [Node](https://cloud.google.com/error-reporting/docs/setup/nodejs)) pre-populate this field if not given. I am happy to implement similar behavior if no one is strongly against of it.

/cc @jba

**Comment by zombiezen** [comment]
SGTM

**Comment by antoniojrod** [comment]
There appears to be a bug in the errorreporting documentation.
`
errorsClient.Report(ctx, er.Entry{Error: err})
 `
I believe this call should not have the ctx as a parameter.

**Comment by zombiezen** [comment]
@antoniojrod I'll take a look, thanks for the find!
