### ISSUE TITLE
errors: package should be able to report errors

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#728]
errors package only provides reporting of log messages and recovery and report of panics. The package instead should provide APIs that can report Go errors.

I suggest to change the Report API to work against an error:

```
func (c *Client) Report(ctx context.Context, r *http.Request, err error)
```

Then, we can also remove the Reportf and users can use fmt.Errorf if they want to include more context to the error messages.

/cc @jba @zombiezen

**Comment by zombiezen** [comment]
SGTM, especially if there's more error introspection that we can do (integrate with github.com/pkg/errors, maybe?).

**Comment by rakyll** [comment]
I am happy to recognize github.com/pkg/errors errors and attach stack trace to the report if available.

**Comment by zombiezen** [comment]
I was thinking more long-term.  For now, let's just make the change to the function signature.
