### ISSUE TITLE
errors: rename Catch to ReportPanic

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#729]
Error reporting client is exporting a "catcher" even though the right terminology for the behavior is "recovering". I am suggesting to rename the API to ReportPanic:

```
func (c *Client) ReportPanic(ctx context.Context, opt ...Option)
```
I also suggest changing the recovery behavior to favor crashing by default. The following deferred recovery can report the error and avoid the panic. ReportPanic by default reports the errors and repanics. 

```
defer errorsClient.ReportPanic(ctx, errors.RecoverPanic())
```

Given it is best practice to report panics not at the application but by consuming logs, I am not 100% confident that we should keep supporting this API. But if we are doing it, let's make it handle less by default.

/cc @jba @zombiezen

**Comment by zombiezen** [comment]
We should probably look at panic-handling in this package wholecloth. (Including deciding whether it's best done out-of-band.)

**Comment by rakyll** [comment]
I am in favor of removing panic handling from this package all together and documenting the use of logs to report panics. Please let me know how we should proceed debating this. Given the package is alpha, we can tolerate such a significant breakage.
