### ISSUE TITLE
Snapshotting instances using golang

### ISSUE THREAD

**Issue by MovieStoreGuy** [GoogleCloudPlatform/google-cloud-go#731]
Hi,

I am trying to see if it is possible to snapshot running instances using some go api but I don't see an obvious way to do it. I know it can be done with the gcloud cli tool but I wondered if there was a public api that could be use that would do the same affect.

Thank you,

Sean.

**Comment by adams-sarah** [comment]
@broady

**Comment by BlueMonday** [comment]
I think by snapshotting instances you meant snapshotting a persistent disk (please correct me if I misinterpreted)?

I don't believe you can snapshot persistent disks using the Go packages currently available in this repository. You can however snapshot disks using the [Google API client libraries for Go](https://github.com/google/google-api-go-client). 

Here is an example of how to snapshot a persistent disk using the Google API client libraries for Go:

```golang
package main

import (
	"context"
	"log"

	"golang.org/x/oauth2/google"
	compute "google.golang.org/api/compute/v1"
)

func main() {
	ctx := context.Background()
	client, err := google.DefaultClient(ctx, compute.ComputeScope)
	if err != nil {
		log.Fatal(err)
	}

	computeService, err := compute.New(client)
	if err != nil {
		log.Fatal(err)
	}

	snapshot := &compute.Snapshot{
		Description: "Snapshot of my-disk",
		Name:        "my-disk-snapshot",
	}
	disksService := compute.NewDisksService(computeService)
	_, err = disksService.CreateSnapshot("my-project", "us-central1-a", "my-disk", snapshot).Do()
	if err != nil {
		log.Fatal(err)
	}
}
```

For more information see:
* [https://godoc.org/google.golang.org/api/compute/v1#DisksService.CreateSnapshot](https://godoc.org/google.golang.org/api/compute/v1#DisksService.CreateSnapshot)
* [https://godoc.org/google.golang.org/api/compute/v1#Snapshot](https://godoc.org/google.golang.org/api/compute/v1#Snapshot)

**Comment by MovieStoreGuy** [comment]
You are correct @BlueMonday, thank you for advice!

Is it worth adding this as a feature of the gcp go lang library?

**Comment by jba** [comment]
Currently, the client that is referred to above is the only Go client planned for the Google Cloud Compute service.

**Comment by broady** [comment]
Just a couple minor changes to the code above.

https://gist.github.com/b5bd067449cb0ac3c2a553b93e0e77bf

No need to call NewDisksService, and you probably want to do something with the operation that was returned. (wait for it, log the operation ID somewhere, etc).

**Comment by MovieStoreGuy** [comment]
Just as an aside, if you repeat the same action more than once and use the same snapshot name, there is no feedback to the client that the operation wasn't completed.

**Comment by VivekDevops** [comment]
@MovieStoreGuy did you find a workaround for this? repeating the action more then once is still not handled well. The progress says Progress though. However there is no new snapshot generated
