### ISSUE TITLE
Max rows in RowList?

### ISSUE THREAD

**Issue by tomwilkie** [GoogleCloudPlatform/google-cloud-go#732]
(Sorry if this is the wrong channel for support questions, I couldn't find a mailing list)

Whats the maximum number of rows that can be fetched by a bigtable ReadRow on a RowList?  I'm getting `rpc error: code = InvalidArgument desc = Request contains an invalid argument.` when I try and do a fetch in the 1000s.

**Comment by garye** [comment]
There is a 1MB limit on the size of the serialized row set in the request. Is there any additional information in the error message that would help us figure out if that's what you're running up against?

**Comment by tomwilkie** [comment]
> There is a 1MB limit on the size of the serialized row set in the request.

I'd suggest putting this here, under "Size Limits": https://cloud.google.com/bigtable/docs/schema-design.

> Is there any additional information in the error message that would help us figure out if that's what you're running up against?

Thats all I got when I printed the message `%+v` - is there a way I can get more info from the message?

**Comment by garye** [comment]
Thanks for the suggestion, I'll open a documentation bug for this, and will also add to the GoDoc.

Unfortunately that error message doesn't seem like it is generated from Cloud Bigtable itself and is the most generic possible description of an InvalidArgument error.

If you want, click through my commits to this repository to find my @google.com address and send over your project information so I can dig further.

**Comment by garye** [comment]
I added a bit of information to the GoDoc about API limitations in f6cfc02a21fc175fcfe1f3279eb90c8fe0f4cefa. Please re-open or reach out separately if we can help more with this.

**Comment by tomwilkie** [comment]
Thanks!
