### ISSUE TITLE
bigtable: Expose hard limits for bulk size

### ISSUE THREAD

**Issue by aseure** [GoogleCloudPlatform/google-cloud-go#733]
As of `v0.11.0`, there is no way to know what is the maximum number of objects or the maximum size for a valid bulk when using `bigtable.Table.ApplyBulk`. Our team discovered in production that actually there are two hard limits:

 - 100'000 mutations can be sent at max (Bigtable limit)
 - The maximum size of the bulk shouldn't exceed 4'194'304 bytes (GRPC limit)

For the 100'000 mutations, we've hardcoded the value in our code and added a wrapper to cut our batches into smaller ones. However, for the maximum size of the bulk, we don't know how to evaluate/limit the size of our bulks? It would be very useful to abstract all of this within the `ApplyBulk` method so that the final user won't have to deal with those limits when they are appearing/changing.

**Comment by garye** [comment]
Thanks for bringing this up, I think there are a few takeaways:

- We will add the 100,000 limit to the Go doc
- We will increase the maximum size to correspond to the max size supported on the server (100MB)
- 100k mutations in a single bulk write is probably way more than you want. It's a maximum but it's not the recommended number. The right number is, unfortunately, very dependent on your workload and can be determined via some experimentation.
- Consider using the `Bundler` class here: https://godoc.org/google.golang.org/api/support/bundler. It takes the batching mechanics mostly out of your hands.
- For highest throughput consider multiple smaller batches being sent out in parallel (if you aren't doing this already). I don't think `Bundler` does this natively, though...

**Comment by aseure** [comment]
Thank you for the `Bundler` idea, we'll probably give it a try. In the meantime, we have just reduce the size of our batches under a certain threshold so that they are now submitted correctly. No issue with the throughput so far though.

**Comment by garye** [comment]
Added some docs via f6cfc02a21fc175fcfe1f3279eb90c8fe0f4cefa and changed the maximum send/receive size to 100MiB via 1bde8d1ff6c3607528e49930816511b73c0c460f.
