### ISSUE TITLE
BigQuery: improve handling of null records in structLoader

### ISSUE THREAD

**Issue by yanickbelanger** [GoogleCloudPlatform/google-cloud-go#735]
Issue https://github.com/GoogleCloudPlatform/google-cloud-go/issues/734 identified a bug where `structLoader` panics when trying to map a null record to a struct pointer. As a fix, and to be consistent with how null fields are handled, null records will return an error.

A better behaviour would be to set the struct pointer to nil instead. Persisting rows with null records (mapped to nil structs pointers) are common in multiple use-cases. Also, the read operation would be symmetric with what the write operation can do: it is totally possible to write nil struct pointers using the `StructSaver` (as long a the field is marked as nullable), thus it should be possible to read them using the `structLoader`.

**Comment by jba** [comment]
If we do this, I think we should be consistent:
- Support pointer fields of any type, setting the value to `nil` if the column is NULL.
- Allow uploading structs with pointer fields.
- For consistency, have struct inference work with pointer fields as well. See #726.

/cc @pongad @zombiezen @adams-sarah

**Comment by jba** [comment]
Also see #647.

**Comment by yanickbelanger** [comment]
Thank you Jonathan, I totally agree: supporting pointer fields of any type would be even better. In our experience with designing tables in BigQuery, most of the time we end-up de-normalizing our data model, and merging different data structure together, which results in a lot of fields having null values.

For example: let's say we need to write user-generated events, with multiple type of events. It is not practical to create one table per type of event, so we merge all fields of all events in one table. So when writing a row for an event of type A, all fields of type B will be null. In our last project, we have designed the table to have one sub-record per type of event. In any row, only one of the sub-record will be populated, the others will be null.

**Comment by adams-sarah** [comment]
@jba i'm not super familiar with this api, but are there other nil-able types that should support this?
(slice, interface, map, ..)

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
