### ISSUE TITLE
errorreporting: don't provide logging

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#736]
As a result of https://github.com/GoogleCloudPlatform/google-cloud-go/issues/728, errorreporting package will work specifically against the errors. The package currently logs to Stackdriver Logging if it is configured so, but we should remove this functionality and allow users to depend on the logging package to report the error message instead. By doing so, we are also giving them opportunity to add more context to the log message.

/cc @zombiezen

**Comment by rakyll** [comment]
/cc @jba @broady 

Please provide input, I can remove the logger as a part of https://code-review.googlesource.com/c/gocloud/+/16090.

**Comment by jba** [comment]
Fixed by 8b7329737d25d127f266bb594f4fa98937a92d48.
