### ISSUE TITLE
PubSub: Delayed messages

### ISSUE THREAD

**Issue by sroze** [GoogleCloudPlatform/google-cloud-go#737]
I'm migrating some of my node & PHP clients to Go, and I'm hitting a barrier using the ack mechanism of the Go client. I've implemented delayed messages by using a `delayed_until` attribute containing the date when the message should be processed. When my workers receive such messages, they extend the deadline until this moment (or 600s if it's too far away) and don't ack or nack the message.

Because the Go client is extending the deadline automatically before we `.Ack()` or `.Nack()` on the message, I can't easily reproduce this mechanism. Do you have any idea how I should approach this?

**Comment by jba** [comment]
You should have a look at #691. tl;dr: the `cloud.google.com/go/pubsub` client doesn't support what you're trying to do. You can try the Cloud Tasks alpha (link at the bottom of that issue) or use the lower-level client at `cloud.google.com/go/pubsub/apiv1`.

**Comment by sroze** [comment]
I'm not sure to follow why a refusal of a `.Forget` API in the client, as that would be the simplest way to solve this problem. I'll have to go for the lower-level version then I guess. Thanks at least for your answer @jba !

**Comment by edevil** [comment]
@sroze Did you manage to solve your problem?

**Comment by sroze** [comment]
yes, did by using the lower-level library.

**Comment by michaelfreund** [comment]
@sroze would you mind to share a short "how" :)

**Comment by jba** [comment]
https://code-review.googlesource.com/c/gocloud/+/33250 is adding a `Forget` method that may help you.
