### ISSUE TITLE
logging: logs are not sent to cloud logging with no errors

### ISSUE THREAD

**Issue by yanc0** [GoogleCloudPlatform/google-cloud-go#743]
Hi,

We are facing a strange behaviour with the logging library. It works well on our machines but in docker container (on GKE) it doesn't. 

We cannot reproduce the bug locally even if we export all env vars from cluster and load the same service account key.

We create the client ike this:

```golang
	var err error
	if conf.DevMode {
		client, err = logging.NewClient(context.Background(), conf.ProjectId)
	} else {
		account := option.WithCredentialsFile(conf.Account)
		client, err = logging.NewClient(context.Background(), conf.ProjectId, account)
	}

	if err != nil {
		log.Fatalf("Failed to create logging client: %s\n", err.Error())
		return
	}
```
And send logs this way:
```golang
	l := client.Logger("late-debugging")
	ctx := context.Background()

	err := l.LogSync(ctx, logging.Entry{
		Payload:   "i'm a debug",
	})
	fmt.Printf("sync log: %+v\n", err)
```

No logs are shown on the cloud logging console when running on the cluster but they are when the application runs locally. The strangest this is that `client.Ping(ctx)` function works everywhere !

Thanks a lot !

**Comment by zombiezen** [comment]
The only I could imagine being different between these two environments is the presence of the GCE metadata server.  Related to this, `Ping` writes to the global monitored resource while `LogSync` writes to the autodetected resource by default.  #650 is tracking that the logging package detects GKE as if it is GCE.

Try this when creating your logger:

```go
l := client.Logger("late-debugging", logging.CommonResource(&mrpb.MonitoredResource{
  Type: "global",
  Labels: map[string]string{"project_id": conf.ProjectId},
}))
```

Also, check which log resource you are filtering by in the viewer.

![Log viewer UI with resource dropdown menu highlighted](https://user-images.githubusercontent.com/181535/29832442-1e4c0e2e-8c9d-11e7-9d3f-00dca0ced335.png)

**Comment by yanc0** [comment]
Thank you ! It works well.
