### ISSUE TITLE
Upload to gcs using go client doesn't error but uploads zero bytes

### ISSUE THREAD

**Issue by dneralla** [GoogleCloudPlatform/google-cloud-go#746]
Hi  We are facing a issue where the uploader is uploading 0 bytes.

Per @jba comment
https://github.com/GoogleCloudPlatform/google-cloud-go/issues/724#issuecomment-321873549

That goes through that path when the content being uploaded is greater than chunksize per
https://github.com/google/google-api-go-client/blob/master/storage/v1/storage-gen.go#L8751

And MediaBuffer is only created when content is greater than chunk size for resumable upload, per
https://github.com/google/google-api-go-client/blob/master/gensupport/media.go#L191

What happens on retries when it doesn't go through resumable upload ?

**Comment by dneralla** [comment]
Was able to simulate by doing so as I mentioned in 

https://github.com/GoogleCloudPlatform/google-cloud-go/issues/724#issuecomment-325745895

**Comment by jba** [comment]
I can reproduce, and I think I know what the problem is. Working on a fix. Meanwhile, you can work around by setting `Writer.ChunkSize` small.

**Comment by dneralla** [comment]
I worked around with using media buffer for everything, changed a line of code in our vendor libs directory. Thanks though

**Comment by jba** [comment]
How did you do it with one line? It took me a few (https://code-review.googlesource.com/c/google-api-go-client/+/16570).

**Comment by dneralla** [comment]
I just ignored the EOF error.

`func PrepareUpload(media io.Reader, chunkSize int) (r io.Reader, mb *MediaBuffer) {
	if chunkSize == 0 { // do not chunk
		return media, nil, true
	}
	mb = NewMediaBuffer(media, chunkSize)
	mb.Chunk()
        return nil, mb
}`

**Comment by jba** [comment]
That's fine. You'll do an extra call to the server for one-chunk uploads, which I try to avoid, but otherwise it should work.
