### ISSUE TITLE
datastore: is there a plan to support GqlQuery?

### ISSUE THREAD

**Issue by nshmura** [GoogleCloudPlatform/google-cloud-go#747]
Hi,

Is there a plan to support `GqlQuery` which is provided by Datastore's [gRPC API](https://cloud.google.com/datastore/docs/reference/rpc/google.datastore.v1#gqlquery)? 

I've been developping command line tool for Datastore, and it would be helpful if `google-cloud-go/datastore` supports GqlQuery.

Thanks.

**Comment by nshmura** [comment]
### Motivation: 

I had been developping [a command line tool for Cloud Datastore](https://github.com/nshmura/dsio), and this tool uses `google-clould-go/datastore` library.

This tool has `query` command which:
1. reads GQL string from command line
2. parses GQL string by hand-made parser written with [goyaml](https://github.com/go-yaml/yaml)
3. builds `Query` struct and runs this `Query`

To write GQL parser is complicated and will amazingly be simplified by supporting GqlQuery in `google-clould-go/datastore` library. 

[GqlQuery API](https://cloud.google.com/datastore/docs/reference/rpc/google.datastore.v1#gqlquery) parses GQL, queries by GQL and returns both of the result set of entities and the result of parsing GQL. So I can remove hand-made GQL parser.


### Pros (Why it's useful for me and others): 

 - Easy to build custom Cloud Datastore UI (GUI and CLI) that accepts arbitray GQL written by user.

 - Datastore client libraries such as  [Java](https://googlecloudplatform.github.io/google-cloud-java/0.23.1/apidocs/index.html),  [PHP](https://googlecloudplatform.github.io/google-cloud-php/#/docs/google-cloud/v0.39.0/datastore/query/gqlquery) and  [Ruby](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.41.0/google/cloud/datastore/dataset?method=gql-instance) support GqlQuery, so supporting GqlQuery will increases compatibility with these libraries.


### Cons

 - Increases code-base of this client library
 - To keep compatibility, we should do same changes to [AppEngine Client Library](https://godoc.org/google.golang.org/appengine/datastore).

**Comment by adams-sarah** [comment]
Hm..
This seems like a great tool, cool idea.
So while I perhaps see the benefit for your GQL-specific tool, I am still not convinced that this addition will add value for our typical user. There is no query (that I can think of) which one can write in GQL but not in the kind-based query DSL existing in the client lib already.

We should keep this issue open, however. If there are more users who have other use-cases for this, we can reconsider.

In the meantime, I recommend forking the API and adding your GQL changes. 
If I remember correctly, they were generally contained to their own [new] GQL-specific files, so updating w/ patches from upstream shouldn't be difficult for you.

cc @zombiezen as FYI

**Comment by nshmura** [comment]
@adams-sarah Thank you for considering. I understood. GQL-specific tool is maybe rare use-case, so I will fork this API or make small library for this purpose.

Thanks!

**Comment by adams-sarah** [comment]
No problem! Cheers

**Comment by jba** [comment]
I'm going to close this issue. We aren't going to be adding this feature to the datastore client.

Consider switching from Datastore to Firestore.
