### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by antonkhabaiev** [GoogleCloudPlatform/google-cloud-go#748]
I've just tried to build a project having pubsub client as dependency and I get this:
vendor/cloud.google.com/go/pubsub/apiv1/publisher_client.go:36: undefined: gax.MustCompilePathTemplate
vendor/cloud.google.com/go/pubsub/apiv1/publisher_client.go:37: undefined: gax.MustCompilePathTemplate
vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:36: undefined: gax.MustCompilePathTemplate
vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:37: undefined: gax.MustCompilePathTemplate
vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:38: undefined: gax.MustCompilePathTemplate
vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:39: undefined: gax.MustCompilePathTemplate

Due to this most likely: https://github.com/googleapis/gax-go/commit/2cadd475a3e966ec9b77a21afc530dbacec6d613

**Comment by pongad** [comment]
@antonkhabaiev The class were removed since https://github.com/GoogleCloudPlatform/google-cloud-go/commit/e08da2b906e55a135acb4c335baefd7422ea35b0 makes it unnecessary. Could you update the client libs? If this isn't possible, I can revert the change to gax for now and redo the deletion at a later date?

**Comment by antonkhabaiev** [comment]
@pongad I'm using glide as my package manager. I did `glide get cloud.google.com/go/pubsub`, and then `glide update`. That pulled `0.12.0` version of the package, and it fails to build with above message. Is there anything I can do on my side to fix that?

**Comment by pongad** [comment]
@antonkhabaiev You're right. I forgot we haven't tagged a new release for google-cloud-go, so glide pulled the latest tagged version that still depended on path templates. I'll revert the gax-go change for now.

**Comment by antonkhabaiev** [comment]
On version v0.12 and v.0.11 build is failing again since Friday:
`# github.com/fubotv/auth0-sync/vendor/cloud.google.com/go/pubsub/apiv1
../vendor/cloud.google.com/go/pubsub/apiv1/publisher_client.go:36: undefined: gax.MustCompilePathTemplate
../vendor/cloud.google.com/go/pubsub/apiv1/publisher_client.go:37: undefined: gax.MustCompilePathTemplate
../vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:36: undefined: gax.MustCompilePathTemplate
../vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:37: undefined: gax.MustCompilePathTemplate
../vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:38: undefined: gax.MustCompilePathTemplate
../vendor/cloud.google.com/go/pubsub/apiv1/subscriber_client.go:39: undefined: gax.MustCompilePathTemplate`

**Comment by arthurgustin** [comment]
I encounter the same issue. In my glide I set version: `0.11.0` and it was fine until I ran `glide update` today

**Comment by jba** [comment]
You'll need to either update everything to the most recent release, or keep cloud.google.com/go at 0.11.0 and pin github.com/googleapis/gax-go to 1.0.0.

**Comment by matzika** [comment]
for me this worked only when I set `github.com/googleapis/gax-go` to 1.0.0. **not** cloud.google.com/go
