### ISSUE TITLE
all: remove HTML tags from the autogenerated clients

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#750]
As an example, [ReportErrorEvent](https://godoc.org/cloud.google.com/go/errorreporting/apiv1beta1#ReportErrorsClient.ReportErrorEvent) has the following HTML escaped godoc:

```
ReportErrorEvent report an individual error event.

This endpoint accepts <strong>either</strong> an OAuth token, <strong>or</strong> an <a href="https://support.google.com/cloud/answer/6158862">API key</a> for authentication. To use an API key, append it to the URL as the value of a key parameter. For example:<pre>POST https://clouderrorreporting.googleapis.com/v1beta1/projects/example-project/events:report?key=123ABC456</pre>
```
It would be preferable to use a non-HTML description if discovery service is providing one. Otherwise, we can filter the HTML tags.

/cc @pongad

**Comment by pongad** [comment]
Thank you for letting me know. These HTMLs are embedded into the [protobuf comments](https://github.com/googleapis/googleapis/blob/master/google/devtools/clouderrorreporting/v1beta1/report_errors_service.proto#L35). I'll investigate this.

**Comment by broady** [comment]
Looks like there's also Markdown:
https://github.com/googleapis/googleapis/blob/master/google/devtools/clouderrorreporting/v1beta1/report_errors_service.proto#L49

Surely there's a style guide? :)

**Comment by pongad** [comment]
The style guide encourages markdowns, but we [strip them out](https://github.com/googleapis/toolkit/pull/1449).

**Comment by pongad** [comment]
Assigning @andreamlin since she's taking over Go codegen

**Comment by jba** [comment]
This bug shouldn't be on this repo. @andreamlin Can you file an issue in the appropriate place and close this?
