### ISSUE TITLE
ServingURL support for Cloud Storage

### ISSUE THREAD

**Issue by philipithomas** [GoogleCloudPlatform/google-cloud-go#751]
The [official docs for "images"](https://cloud.google.com/appengine/docs/standard/go/images/) states that it supports creating ServingURLs for both Blobstore and Cloud Storage: 

> The Images API provides the ability to serve images directly from Google Cloud Storage or Blobstore, and to optionally resize or crop those images on the fly.

However, only blobstore seems to [support ServingURLs](https://cloud.google.com/appengine/docs/standard/go/images/reference). 

So, there are two questions:

1. Are the docs correct? Can Serving URLs be created from Cloud Storage?

2. If yes, can we add it to the google-cloud-go package?

**Comment by jba** [comment]
The images API client is for appengine. It's not part of this repo.

/cc @zombiezen

**Comment by adams-sarah** [comment]
The issue tracker for the appengine client libs is here: https://github.com/golang/appengine/issues
