### ISSUE TITLE
bigtable: document connection pool

### ISSUE THREAD

**Issue by michael-stevens** [GoogleCloudPlatform/google-cloud-go#752]
Hi,

I'm using bigtable from go. After about a week spent debugging and talking to support before I worked out what was going on, please document the connection pool setting in the bigtable client.

In particular this code in `bigtable.go` NewClient:

```
        // Default to a small connection pool that can be overridden.
        o = append(o,
                option.WithGRPCConnectionPool(4),
```
I was baffled by throughput issues before realising the client was limiting me to 4 connections internally.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.
