### ISSUE TITLE
storage: build is broken against tip

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#754]
Go 1.10 is not a valid constraint tag yet. It breaks the build if devel version is used.

```
$ go version
go version devel +e21ebcb0ed Tue Sep 5 13:34:26 2017 -0700 darwin/amd64

$ go build cloud.google.com/go/storage
# cloud.google.com/go/storage
./not_go110.go:26:29: shouldRetry redeclared in this block
	previous declaration at ./go110.go:21:29
```

/cc @jba

**Comment by jba** [comment]
CL is out to you.

**Comment by d4l3k** [comment]
I'm running into a similar error with tip.

```
$ go get -v -t ./...

...

# cloud.google.com/go/storage
../../../cloud.google.com/go/storage/invoke.go:31:6: undefined: shouldRetry
```

**Comment by jba** [comment]
What version of Go are you using?

**Comment by d4l3k** [comment]
@jba tip

**Comment by jba** [comment]
Oh, I see, sorry.

Does renaming `go110.go.pending` to `go110.go` fix it?

**Comment by rakyll** [comment]
The storage build is broken now, there is no shouldRetry.

not_go110.go still uses a 1.10 build constraint which doesn't exist yet:

`// +build !go1.10`

```
$ go test cloud.google.com/go/storage/...
# cloud.google.com/go/storage
storage/invoke.go:31:6: undefined: shouldRetry
```

**Comment by jba** [comment]
@rakyll What version of go are you using? It seems to work except at tip, where that build constraint excludes the file. Until go1.10 is defined I don't know a fix except the file rename I mentioned above.

**Comment by ikrabbe** [comment]
The rename solved the issue, but I think there should be an easy way to define such a tag, when you run against tip anyway, it should be quite simple to add that tag to you go root build.

**Comment by anthmgoogle** [comment]
Looks like the original issue is solved.

I'd suggest creating a new issue for the follow-on suggestion.
