### ISSUE TITLE
storage: Thread unsafety and correctness of (*Client).Close()

### ISSUE THREAD

**Issue by lhecker** [GoogleCloudPlatform/google-cloud-go#756]
Currently calling `Close()` will set the internal `*http.Client` to `nil` [in a thread-unsafe manner](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/437696f7242d578d08e1820a482f0878e42f3c08/storage/storage.go#L113).
Furthermore wouldn't setting it to `nil` cause panics whenever this member is used elsewhere in the code? 🙂
And as it currently stands, couldn't the `Close()` method actually be removed?

**Comment by jba** [comment]
`Close` is there for backwards-compatibility. Some day, the client might have a different backend that requires closing.

It's technically thread-unsafe, but if you are using the client in one goroutine and closing it in another, your code is already broken. 

That said, we'll remove the line, because it doesn't do anything useful.

**Comment by lhecker** [comment]
> but if you are using the client in one goroutine and closing it in another, your code is already broken

Well I guess that is technically correct, since the `Close()` method is currently not thread-safe, but, after you've removed that line, please don't make it etc. thread-unsafe again, because thread-unsafety by default is not idiomatic for Go library code - especially for closing methods. 🙂

**Comment by jba** [comment]
No, even if `Close` is thread-safe, your code is still broken if you have a race condition between `Close` and some other use of the client.

**Comment by jba** [comment]
I mean, not in the current implementation, of course. But that is the contract of `Close`: don't use the client after you call it.

**Comment by jba** [comment]
(current implementation after removing the `hc = nil` line, I mean)

**Comment by jba** [comment]
We actually "fixed" this by going in the opposite direction: now Close sets both `hc` and `raw` to nil, so it's basically impossible to use a closed client without getting a panic. We consider that a feature, because it alerts you to a bug in your code.
