### ISSUE TITLE
StreamingPull begin called on Subscription.Recieve()

### ISSUE THREAD

**Issue by johan-lejdung** [GoogleCloudPlatform/google-cloud-go#758]
Hi!

I'm kind of stumped by this problem, since I have the near exact same setup on two other projects that both seem to work fine (there is a slight difference in the revision used).

I'm writing a GoLang backend, the vendor file looks like this (using govendor):
```
{
    "checksumSHA1": "2YVcVcItP/jQuBW5/u2Ojzy6FVY=",
    "path": "cloud.google.com/go/pubsub",
    "revision": "437696f7242d578d08e1820a482f0878e42f3c08",
    "revisionTime": "2017-09-14T03:19:08Z"
},
{
    "checksumSHA1": "0WV3r0bk7nCBORBLZK4OpQxfz6s=",
    "path": "cloud.google.com/go/pubsub/apiv1",
    "revision": "437696f7242d578d08e1820a482f0878e42f3c08",
    "revisionTime": "2017-09-14T03:19:08Z"
},
```

First create a new client:
```
ctx := context.Background()
c, err := pubsub.NewClient(ctx, os.Getenv("GOOGLE_CLOUD_PROJECT"))
if err != nil {
    log.Fatal(err)
}
```
I then want to subscribe to the topics being used by the producer.
```
err := sub.Receive(ctx, func(ctx context.Context, m *pubsub.Message) {
    log.Print("works!")
    m.Ack() // Acknowledge that we've consumed the message.
})
if err != nil {
    log.Fatalf("PubSub sub FAILED to initialize: %v", err)
}
```

It is here that is fails. My log has this message in it:
```
PubSub sub FAILED to initialize: rpc error: code = Unimplemented desc = Method not found: google.pubsub.v1.Subscriber/StreamingPull
```

My other service seem to be able to post on the pubsub emulator just fine, using the same topics.

I've tried to look in the library code too see if StreamingPull could be called somehow, but I am unable to spot any places where that would be the case. I have not been able to find any similar cases online.

Any of you have any idea of what might be occurring?

**Comment by johan-lejdung** [comment]
Weirdly enough, after manually editing my govendor file and replacing the above with:
```
{
    "checksumSHA1": "avdpmG011rrwRckVKE6mpZAc/GA=",
    "path": "cloud.google.com/go/pubsub",
    "revision": "558c9e581ae27126106c951d4a6a8e96c05e997f",
    "revisionTime": "2017-08-10T12:43:02Z"
},
{
    "checksumSHA1": "/G2UXqr9pNCGmTHudjcXkixq8qU=",
    "path": "cloud.google.com/go/pubsub/apiv1",
    "revision": "558c9e581ae27126106c951d4a6a8e96c05e997f",
    "revisionTime": "2017-08-10T12:43:02Z"
},
```

And adding:
```
{
    "checksumSHA1": "YrR/d1vgCwi8Xax7TsJNGuh2Aks=",
    "path": "github.com/googleapis/gax-go",
    "revision": "84ed26760e7f6f80887a2fbfb50db3cc415d2cea",
    "revisionTime": "2017-06-10T00:42:46Z"
},
```

Everything works, just fine... Just like in my other projects.

I would love to get an explanation to this, since I originally just used `govendor fetch cloud.google.com/go/pubsub` when i received the faulty one.

**Comment by jba** [comment]
I'm not familiar with govendor, but it seems like you had an older version of `google.golang.org/genproto/googleapis/pubsub/v1`, which is the code generated from the proto files.
