### ISSUE TITLE
gcs upload fails with  "io: read/write on closed pipe"  error when using x/net/http2 client 

### ISSUE THREAD

**Issue by dneralla** [GoogleCloudPlatform/google-cloud-go#759]
when we create storage client created as specified in the default documentation like 

```  client := storage.NewClient(ctx) ```

we were receiving lot of http2: stream closed. (aka : REFUSED_STREAM due to max concurrent streams) errors due to the bug in the golang's net/http library as they do some optimistic checks and can open more concurrent streams than the maximum.

So we started using the x/net/http2 directly and passed that client as an option when while creating the storage client, code we used to create the client looks some thing like this 

```go
    ts, err := google.DefaultTokenSource(ctx)
    if err != nil {
         return nil, err
    }
    tr := &http.Transport{
         Proxy: http.ProxyFromEnvironment,
         DialContext: (&net.Dialer{
             Timeout:   30 * time.Second,
             KeepAlive: 30 * time.Second,
             DualStack: true,
         }).DialContext,
         MaxIdleConns:          100,
         IdleConnTimeout:       90 * time.Second,
         TLSHandshakeTimeout:   10 * time.Second,
         ExpectContinueTimeout: 1 * time.Second,
     }
    if err := http2.ConfigureTransport(tr); err != nil {
         return nil, err
    }
    hc := &http.Client{
         Transport: &oauth2.Transport{
             Source: ts,
              Base:   tr,
          },
    }
    gcs, err := storage.NewClient(ctx, option.WithHTTPClient(hc))
    if err != nil {
          return nil, err
    }
```
And when we do this we get  errors like 

```{"error":"Post https://www.googleapis.com/upload/storage/v1/b/<bucket>/o?alt=json\u0026projection=full\u0026uploadType=multipart: io: read/write on closed pipe","status":"failed"}```

Access pattern from our service is something like lots of concurrent uploads and few which can be cancelled and when some are cancelled the subsequent requests fail with this kind of errors.

**Comment by dneralla** [comment]
@jba ^^

**Comment by jba** [comment]
We fixed the REFUSED_STREAM error a while ago in the client. Have you tried it lately?

**Comment by dneralla** [comment]
@jba Is the fix added checking for that error and retrying ? I am using the latest storage client and regards to Http client we are using go 1.8 an storage client uses bundled net/http so the reason i tried using x/net/http2 directly. But then got io pipe errors.

**Comment by jba** [comment]
The latest storage client retries on that error. https://code.googlesource.com/gocloud/+/master/storage/not_go110.go#36

**Comment by dneralla** [comment]
Yeah We have the latest storage client and its not helping.

**Comment by jba** [comment]
Sorry we haven't responded on this.

Instead of getting you working with the `net/x/http2` package, I'd like to revisit using the default under Go 1.10. I just wrote a program that wrote 100 objects of 1M each concurrently. Half of the uploads were canceled in the middle. I saw all of the remaining ones succeed.

Could you try with Go 1.10 and see what happens? If it's still not working, can you provide some code to reproduce, or suggest how my attempted repro falls short?

**Comment by jba** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.
