### ISSUE TITLE
profiler: rename InstanceName to Instance, ZoneName to Zone

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#763]
InstanceName and ZoneName are both very mouthful, and represented as Instance and Zone at the metadata package: https://godoc.org/cloud.google.com/go/compute/metadata#Zone.

For consistency and simplicity, please rename Config.InstanceName to Config.Instance and Config.ZoneName to Config.Zone.

**Comment by jqll** [comment]
Fixed with https://code-review.googlesource.com/17030
