### ISSUE TITLE
bigquery: retrieve total rows and schema from query results

### ISSUE THREAD

**Issue by raphael** [GoogleCloudPlatform/google-cloud-go#765]
Hopefully I'm missing something obvious but I can't figure out how to retrieve the total number of rows and the schema returned by BigQuery when running queries (as returned by the [getQueryResults](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults) API).

The row iterator that is returned by `Query` or `Job.Read()` only makes it possible to iterate and neither the [JobStatistics](https://godoc.org/cloud.google.com/go/bigquery#JobStatistics) nor the [QueryStatistics](https://godoc.org/cloud.google.com/go/bigquery#QueryStatistics) objects seem to explicitly expose that information. 

`QueryStatistics` does have `Schema` but the comment notes that it is:
```go
// Present only for successful dry run of
// non-legacy SQL queries.
```
If the comment is correct then one has to first run a dry run just to get the schema then the actual query which doesn't work. Thanks!

**Comment by raphael** [comment]
Just figured out that this information is only available after the query has completed which explains the current design :-) Would it make sense to add e.g. a `Summary` method to the `Job` struct that would make the `getQueryResults` API request and return the information?  Right now there seems to be a gap where a client cannot get to the schema or total number of rows returned by a query.

**Comment by jba** [comment]
We should be able to expose both the schema and the total rows for you. I think I see how to do that. The schema will definitely be available early; the total rows, maybe not until the end of the iteration.

**Comment by jba** [comment]
I did this by adding `Schema` and `TotalRows` fields to `RowIterator`. Note that `TotalRows` will be zero before calling `Next`, and may still be zero or incorrect if rows were just streamed into the table or inserted with DML.

**Comment by raphael** [comment]
Great, thank you! and understand the caveats wrt `TotalRows`.

**Comment by idan3** [comment]
Is it still the case?
Can't I get total rows without using the iterator?
