### ISSUE TITLE
datastore: ErrFieldMismatch decoding NullValue into a slice

### ISSUE THREAD

**Issue by dsansot** [GoogleCloudPlatform/google-cloud-go#767]
`NullValue` in Datastore doesn't decode into a slice correctly, or at least not how I would expect it to.

Suppose I have the following data structures:
```
type Pet struct {
	Name string
	Type string
}

type Person struct {
	Name string
	Pets []Pet
}
```

and an Entity in Datastore where `Pets` is set to `NullValue`. When I try to get the data

```
p := &Person{}
err = client.Get(ctx, key, p)
```

an `ErrFieldMismatch` error is returned:

> datastore: cannot load field "Pets" into a "main.Person": type mismatch: empty versus main.Pet

Obviously, I can ignore the error, but I find the error kind of weird. I would expect `Pets` to be `nil`, or, at the very least, an empty slice (well, I guess `Pets` is still `nil` since it started that way).

The error message is also a bit weird. It seems to indicate that it can't load `NullValue` into `main.Pet`, not `[]main.Pet`.

To explore this a bit farther, I changed the data structure to 

```
type Person struct {
	Name string
	Pets []*Pet
}
```

Now, I don't get an error, but `Pets` ends up having a length of 1 and a `nil` as its only element. Further, if I change the type of `Pets` to `[]string` or `[]int`, I get a slice of length 1 with the type's zero value as the only element.

**Comment by dsansot** [comment]
Here is the code I was playing with:

```
package main

import (
	"cloud.google.com/go/datastore"
	"fmt"
	"golang.org/x/net/context"
	"os"
)

type Pet struct {
	Name string
	Type string
}

type Person struct {
	Name string
	Pets []Pet
}

func slice_test(projectID string) error {

	ctx := context.Background()

	client, err := datastore.NewClient(ctx, projectID)
	if err != nil {
		return err
	}

	key := datastore.NameKey("person", "david", nil)

	// This doesn't write the null at Pets, so go do it manually.
	// _, err = client.Put(ctx, key, &Person{Name: "David"})

	p := &Person{}
	err = client.Get(ctx, key, p)
	if err != nil {
		return err
	}

	fmt.Println(p)
	fmt.Println(len(p.Pets))

	return nil
}

func main() {
	if len(os.Args) != 2 {
		fmt.Println("Usage: slice_test <google-cloud-project>")
		os.Exit(1)
	}

	projectID := os.Args[1]

	err := slice_test(projectID)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}
```

**Comment by adams-sarah** [comment]
Hey @dsansot, thanks for the report. Yea, the error message is not great. 
I'd like to better understand your use-case before I dive into a solution.

So the client will never write a `NullValue` slice to Datastore (as you discovered). This makes the reading and loading back into a struct work fine if you've also *written* with the Go client (which you haven't, obvi).

Anyway, can you explain why you need this? I don't think it's a good idea to have the client *write* NULL for a nil-valued slice (b/c backwards compatibility), so I'm a little reluctant to add the reading functionality.

**Comment by adams-sarah** [comment]
cc @jba

**Comment by dsansot** [comment]
Hi @adams-sarah,

You are correct in guessing that another application is writing the data to Datastore. In our case, it is a python application. We use Datastore as a communication/caching layer between our backend business app (written in django) and our front end servers (go).

I see some of the other types (ints, strings, etc.) have checks for `NullValue` before returning a mismatch reason. In those cases the zero value gets loaded. I guess I'm arguing for the same behavior for slices.

I think the problem stems from the fact that sometimes the code looks at the Datastore data to handle slices and sometimes it looks at the struct into which the data should be loaded. Specifically, the code in `load` looks at the data from Datastore to branch to some slice handling, but the code in `loadOneElement` looks at if the receiver is a slice. These aren't guaranteed to always both be true. For example, the code as it currently stands will gladly load a `StringValue` into a `[]string` as the slice's first element.

**Comment by zhaomoloco** [comment]
It would be great if there is a chance to introduce an option to override this unexpected behavior for slice fields. Ideally it should be deserialized into the zero value of a slice, which should be a nil. To deserialize into a one element slice with element type's zero value doesn't make sense, IMHO.
