### ISSUE TITLE
logging: provide wrapper http.Handler that logs requests

### ISSUE THREAD

**Issue by cybrcodr** [GoogleCloudPlatform/google-cloud-go#768]
It'll be useful for the logging library to have a method that wraps http.Handler to produce request logs.  Log request and response status as well as latency (how long it took).

API signature wise, it can be something similar to [trace.Client.HTTPHandler](https://godoc.org/cloud.google.com/go/trace#Client.HTTPHandler), but probably at the Logger level.

**Comment by jba** [comment]
That is a useful feature, but not really in scope for the logging package.
