### ISSUE TITLE
logadmin: read entry payload into original struct type

### ISSUE THREAD

**Issue by buchanae** [GoogleCloudPlatform/google-cloud-go#769]
I have some code that uses a protobuf message as the entry payload when writing entries to Stackdriver. While writing code to read this payload back into the original type, I realized this isn't straightforward, because the payload is now a `structpb.Struct`.

Is it possible to read/convert this type into my original message type? Maybe there's an existing helper library for this that I'm not seeing? Or am I stuck manually decoding the `structpb.Struct`?

I'm used to marshaling/unmarshaling a `[]byte`. Is that a potential enhancement of this library, or is there a limitation in Stackdriver that prevents this?

**Comment by buchanae** [comment]
I have just discovered this, which tackles the same topic: https://www.jkawamoto.info/blogs/get-log-entries-from-stackdriver-logging-2/

**Comment by jba** [comment]
You could use the code in that article, or you could use the [jsonpb](https://godoc.org/github.com/golang/protobuf/jsonpb) package to first marshal the `structpb.Struct` to JSON, then unmarshal it into the proto.
