### ISSUE TITLE
trace: sampling policy per trace source

### ISSUE THREAD

**Issue by zombiezen** [GoogleCloudPlatform/google-cloud-go#772]
Right now, the sampling policy applies to the entire client.  This works for most applications, but sometimes there is a segmentation of trace span sources, and it would be nice to have sampling policies be applicable to different subsets.  For instance, if a server is taking in user requests and also running background tasks, I would want the user requests and the background task runs to be considered separate buckets for sampling.

**Comment by zombiezen** [comment]
@rakyll suggested offline that a workaround is to create a `Client` per each trace "population".  Does create more buffers/TCP conns than strictly needed, but a good enough workaround for what we want.

**Comment by jba** [comment]
This package is deprecated, so I'll close this. @zombiezen if you still think the feature is valuable, open an issue at https://github.com/census-instrumentation/opencensus-go/issues/new.

**Comment by rakyll** [comment]
We addressed this in OpenCensus by allowing users to set a sampling policy when they are creating new spans.
