### ISSUE TITLE
setgcpolicy not updating maxversions

### ISSUE THREAD

**Issue by iros** [GoogleCloudPlatform/google-cloud-go#774]
I am unable to set a maxversions on my column families using setgcpolicy at this time. Here are the steps I am taking:

```
$ cbt --project myProject --instance myBigtableInstance \
setgcpolicy myTableName myColFamilyName  maxversions=1
```

Then, in my hbase console I run:
```
base(main):003:0> put 'myTableName', 'r', 'myColFamilyName:colName', 'test1'
0 row(s) in 0.4870 seconds

hbase(main):004:0> put 'myTableName', 'r', 'myColFamilyName:colName', 'test2'
0 row(s) in 0.3480 seconds

hbase(main):005:0> put 'myTableName', 'r', 'myColFamilyName:colName', 'test3'
0 row(s) in 0.3040 seconds
```

Examining the table, I still have all 5 versions of these values:

```
$ cbt --project myProject --instance myBigtableInstance read myTableName count=1

----------------------------------------
r
  myColFamilyName:colName                                   @ 2017/09/29-12:01:17.925000
    "test3"
  myColFamilyName:colName                                   @ 2017/09/29-12:01:16.169000
    "test2"
  myColFamilyName:colName                                   @ 2017/09/29-12:01:14.307000
    "test1"
```

Can you advise?
If this is helpful:
```
$ gcloud --version
Google Cloud SDK 173.0.0
app-engine-python 1.9.60
beta 2017.09.15
bq 2.0.26
cbt
core 2017.09.25
gsutil 4.27

$ cbt version
2017/09/29 12:17:08 proto: duplicate proto type registered: google.rpc.Status
0.2.2 7d132fe 2017-06-09 14:30:04
```

**Comment by garye** [comment]
The GC policy doesn't immedaitely affect the number of versions that are returned from a read. Rather, garbage collection is applied during a major compaction. Unfortunately this means that you will need to limit the number of versions you want returned using a filter instead of relying on `maxversions`.

**Comment by iros** [comment]
Thank you @garye. Good to know. Would be handy to add it to the docs somehow? I've been chasing 👻 s for a while :)

**Comment by garye** [comment]
Yeah it really should be documented somewhere. Would it have been helpful to have it [here](https://cloud.google.com/bigtable/docs/managing-tables)?

**Comment by iros** [comment]
Yep. Though I have been using the Python API, so also here? https://googlecloudplatform.github.io/google-cloud-python/latest/bigtable/column-family.html
