### ISSUE TITLE
New const StringerFieldType proposal

### ISSUE THREAD

**Issue by vbauerster** [GoogleCloudPlatform/google-cloud-go#776]
I know that there is `bigquery.StringFieldType`, but it does not call a `String()` method of underlying type.

Consider this [example](https://play.golang.org/p/31p_6CR2N6)
[![Prson-proto.png](https://s25.postimg.org/qrq3o64hr/Prson-proto.png)](https://postimg.org/image/67l9pooqj/)

When inserting `Person` struct with [StructSaver](https://godoc.org/cloud.google.com/go/bigquery#StructSaver), field `addressbook.friends.Phones_Type` reflects a number:
```go
&bigquery.FieldSchema{
	Name:     "Phones",
	Type:     bigquery.RecordFieldType,
	Repeated: true,
	Schema: bigquery.Schema{
		&bigquery.FieldSchema{Name: "Number", Type: bigquery.StringFieldType},
		// following StringFieldType will infer underlying type,
		// whereas I'd like it to call type's String() method directly,
		// without any inferring
		&bigquery.FieldSchema{Name: "Type", Type: bigquery.StringFieldType},
	},
}
```
So I propose to add one more const `StringerFieldType`, which will not reflect underlying field, but call its `String()` method directly. So one can use it like this:
```go
&bigquery.FieldSchema{Name: "Type", Type: bigquery.StringerFieldType} // means call String(), no need to reflect
```

**Comment by jba** [comment]
This seems like a reasonable idea. The problem is that it would have to round-trip, so you'd need to specify a companion function to parse the string coming from the service into an int. It's probably going to be more complicated than it's worth, since you can just write a custom `ValueLoader` and `ValueSaver` to do whatever you want.
