### ISSUE TITLE
Json Logging in App Engine Flexible Environment

### ISSUE THREAD

**Issue by anshul35** [GoogleCloudPlatform/google-cloud-go#781]
I am dumping json logs on stdout, stderr, using Golang, on app engine flexible environment. However, the default stackdriver logging on google cloud console, is showing them as "textPayload". 

How can I configure the logging to interpret the log payload as Json and not text?

**Comment by anthmgoogle** [comment]
This question does not appear to be able google-cloud-go. Should we direct this to a different repository?

**Comment by Bankq** [comment]
@anshul35 [Don't work for google, not official answer] Not sure if it's supported via fluentd/stdout. Our solution is calling stackdriver logging api directly.

**Comment by zombiezen** [comment]
IIUC this is an issue with App Engine Flex, specifically with the configuration in the [sidecar image](https://github.com/GoogleCloudPlatform/appengine-sidecars-docker/blob/master/fluentd_logger/managed_vms.conf).  App Engine Flex does not parse stderr for JSON payloads, unlike [in GKE](https://cloud.google.com/kubernetes-engine/docs/logging#best_practices).

/cc @igorpeshansky

**Comment by igorpeshansky** [comment]
https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/89 (but, as @zombiezen says, this is ultimately an App Engine Flex issue).

**Comment by zombiezen** [comment]
Thanks, closing this issue in favor of the google-fluentd issue.
