### ISSUE TITLE
Is passing checksum to gcs writer necessary

### ISSUE THREAD

**Issue by nikunjy** [GoogleCloudPlatform/google-cloud-go#785]
Hey, there is an option to pass checksum to a gcs writer.
1. Is it necessary to make sure that the uploads are done correctly ? 
2. Can I pipe the stream into gcs writer with the SendChecksum option on and then send the checksum before the time of closing the writer.

```
checksumWriter:= crc32.New(crc32.MakeTable(crc32.Castagnoli)),
rd, wr :=io.Pipe()
go func() error {
 // do something with wr
}()
writer := bucketHandle.Object("...").NewWriter(ctx)
writer.SendCRC32 = true

scanner := bufio.NewScanner(rd)
for scanner.Scan() {
     data := myFunction(scanner.Bytes())
     checksumWriter.Write(data)
     writer.Write(data)
}
writer.CRC32 = checksumWriter.Sum()
return writer.Close()
```

Wil this work ?

**Comment by jba** [comment]
Unfortunately not. You must set `writer.CRC32` before the first byte is sent. The underlying RPC wants the checksum at the beginning of the call.

**Comment by nikunjy** [comment]
@jba don't you think that is a pretty big restriction. Because now I have to buffer memory, and then checksum it rather than piping.
