### ISSUE TITLE
[bigquery] Now Standard SQL is the default, I have to support UseLegacySQL parameter

### ISSUE THREAD

**Issue by nomoth** [GoogleCloudPlatform/google-cloud-go#786]
I tried to set UseStandardSQL explicitly to false without success. 
The parameter seems to be ignored.
I have to update my code to use UseLegacySQL.

**Comment by jba** [comment]
That is correct. Please see https://groups.google.com/d/topic/google-api-go-announce/mQBh_t9x3fE/discussion. We recommend you subscribe to that list.

The reason setting `UseStandardSQL` to false doesn't help is that Go cannot distinguish explicitly setting a field to the zero value from not setting it at all.
