### ISSUE TITLE
ServiceAccounts.Keys.Create return nil and error 404 just after create

### ISSUE THREAD

**Issue by sebglon** [GoogleCloudPlatform/google-cloud-go#787]
A few time ago, when i  use service `clientIAM.Projects.ServiceAccounts.Keys.Create`
it return serviceAccountKey = nil and error = nil...

When i have this error, i create one on google console and have an error.
Is it possible to have an operation object or solve async task?

Because create finish in 200 but if you make get just after we have 404 with the generated key name.
If i wait 10 sec under create and get, i have get 200.

**Comment by jpharaoh-google** [comment]
This user is actually using a different project, and has raised an issue there. I suggest this issue should be closed.

https://github.com/google/google-api-go-client/issues/234

I have been assisting the user who raised this issue in my role for Google Cloud Platform Support.
