### ISSUE TITLE
trace: emit an error when setting up the trace client when user doesn't have trace API turned on

### ISSUE THREAD

**Issue by shantuo** [GoogleCloudPlatform/google-cloud-go#789]
Currently it only gives error when it trys to upload spans.

**Comment by rakyll** [comment]
Is there a way to check this without uploading any traces? Unfortunately the same problem exists for other clients as well and in the past we couldn't find a good solution to improve the developer experience.

/cc @jba

**Comment by jba** [comment]
This package has been obsoleted by  [go.opencensus.io/trace](https://godoc.org/go.opencensus.io/trace).
