### ISSUE TITLE
bigtable: Warning logged for all commands

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/google-cloud-go#798]
Whenever I run a `cbt` command, I get a line of log output similar to the following:

```
2017/10/31 13:15:59 proto: duplicate proto type registered: google.rpc.Status
```

I'm using `cbt 0.2.2 7d132fe 2017-06-09 14:30:04`, installed via the Cloud SDK.

**Comment by garye** [comment]
A fix will go out in next week's Cloud SDK release.

**Comment by anthmgoogle** [comment]
This seems to be a bug about the Cloud SDK, not the Go client library. Closing out here.
