### ISSUE TITLE
bigtable: inmem ReadModifyWrite won't return cell timestamp.

### ISSUE THREAD

**Issue by uschen** [GoogleCloudPlatform/google-cloud-go#800]
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigtable/bttest/inmem.go#L907

comparing to:

https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.ReadModifyWriteRowResponse

**Comment by uschen** [comment]
it seems this will fix it:

```go
f.Columns = append(f.Columns, &btpb.Column{
			Qualifier: []byte(qual),
			Cells: []*btpb.Cell{{
				TimestampMicros: cell.ts,
				Value:           cell.value,
			}},
		})
```

**Comment by uschen** [comment]
is PR welcomed?

**Comment by garye** [comment]
Yes, absolutely! We don't use github for that, though. See CONTRIBUTING.md for details.

**Comment by uschen** [comment]
@garye saw it... seems too much hassle for one line of code changes :) 

wonder if priority of this can be bumped, since it blocks using inmem for testing.

**Comment by garye** [comment]
Are you using the inmem stuff from Go or from the Cloud SDK emulator?

**Comment by garye** [comment]
I have a fix out for review. Thanks for the bug report and suggested change.

**Comment by uschen** [comment]
@garye for go.
