### ISSUE TITLE
pubsub: acking published batches in latest client

### ISSUE THREAD

**Issue by schmohlio** [GoogleCloudPlatform/google-cloud-go#802]
A common scenario of using the pubsub message bus is to receive and process messages from one topic and publish them to another topic. Often a client will want to publish messages to the next topic before Acking the received messages (to guarantee their transmission). Publishing usually has higher latency than receiving, thus the batching.

Using the previous pubsub API, I created my own buffer, and used a max buffer size + a Ticker to publish batches to a topic and then Ack() each message of the batch.

Are there any recommended patterns or code samples for accomplishing something similar with the latest version (which publishes implicitly for the client)?  For instance, I could keep a stack of all `PublishResult` objects and wait until it's of a certain size before popping each off and calling `PublishResult.Get()`. But there are considerations for how large my stack size should be vs the implicit buffer size on the client.

**Comment by jba** [comment]
The current client batches both publishes and acks. So it isn't critical that you ack a bunch of published messages at once.

My first thought is this: write each `PublishResult` to a channel. A single goroutine ranges over the channel, calling `Get` and then acking. You still need to buffer the channel, but as long as it's large enough it shouldn't make much of a difference. To be concrete, start with `PublishSettings.CountThreshold` and increase if you find that you often block sending to the channel.

**Comment by schmohlio** [comment]
@jba thanks so much, that's like a great simple soln.
