### ISSUE TITLE
storage: Reader needs ContentEncoding method

### ISSUE THREAD

**Issue by ernsheong** [GoogleCloudPlatform/google-cloud-go#803]
Following this [change](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/657767d66680dbb53f5e6bf677e37d88b221c31b) for issue https://github.com/GoogleCloudPlatform/google-cloud-go/issues/449, I think we need to update storage.Reader's public and private methods to include `ContentEncoding`. If we are agreeable on this I can submit a CL soon.

**Comment by jba** [comment]
Can you describe in more detail what you propose to do, and why?

**Comment by ernsheong** [comment]
So with the new `ReadCompressed` method, retrieving an object looks like this:

```
reader, err := storageBucket.Object(objName).ReadCompressed(true).NewReader(ctx)
```

From https://cloud.google.com/storage/docs/transcoding:

> If the request for the object includes an Accept-Encoding: gzip header, the object is served as-is in that specific request, along with a Content-Encoding: gzip response header.

I am under the impression that with `Accept-Encoding: gzip` in the header I may be getting an object that is either `Content-Encoding: gzip` or none ("as-is"). From the Reader object I now have no way of telling what is the Content-Encoding of the retrieved object in the Reader. 

I guess the problem is that the client does not know beforehand what encoding the object is in on retrieval. At the moment, it looks like the use of `Accept-Encoding: gzip` requires foreknowledge of what encoding the object is in in the first place.

**Comment by jba** [comment]
OK, got it.

It seems this method already exists: https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/storage/reader.go#L73.

**Comment by ernsheong** [comment]
@jba not quite, that's ContentType, I'm proposing ContentEncoding. Right now I am getting Content-Type of `text/html` but encoding is `gzip`. But I have no way of telling that the encoding is `gzip`.

**Comment by jba** [comment]
Oh, right, sorry. Please go a head an make a CL for ContentEncoding.

**Comment by ernsheong** [comment]
Thanks, raised https://code-review.googlesource.com/c/gocloud/+/19390/
