### ISSUE TITLE
Bigtable Emulator produces unexpected/incorrect results when using predicate filters

### ISSUE THREAD

**Issue by steveniemitz** [GoogleCloudPlatform/google-cloud-go#804]
When using the Bigtable emulator, requests with filters that have chained predicates seem to return incorrect results.

See [here](https://github.com/tc-dc/bt-emulator-repro) for a full reproduction case, when run against bigtable proper the request returns 12 rows, when run against the emulator it returns all 240.

**Comment by mbrukman** [comment]
Thanks for a complete repo case, @steveniemitz!

@garye, can you please take a look at this? Thanks!

**Comment by garye** [comment]
Thanks for the great test case. I have a CL out with a fix:

https://code-review.googlesource.com/#/c/gocloud/+/19590

```
INFO: Enabling the use of null credentials. This should not be used in production.
Nov 13, 2017 9:25:35 AM com.google.cloud.bigtable.grpc.BigtableSession info
INFO: Opening connection for projectId ecnext-devel, instanceId integration-testing, on data host 127.0.0.1, table admin host 127.0.0.1.
Nov 13, 2017 9:25:35 AM com.google.cloud.bigtable.grpc.BigtableSession info
INFO: Bigtable options: BigtableOptions{dataHost=127.0.0.1, tableAdminHost=127.0.0.1, instanceAdminHost=127.0.0.1, projectId=ecnext-devel, instanceId=integration-testing, userAgent=repro-test, credentialType=None, port=8086, dataChannelCount=20, retryOptions=RetryOptions{retriesEnabled=true, allowRetriesWithoutTimestamp=false, statusToRetryOn=[UNAVAILABLE, INTERNAL, DEADLINE_EXCEEDED, ABORTED, UNAUTHENTICATED], initialBackoffMillis=5, maxElapsedBackoffMillis=60000, backoffMultiplier=2.0, streamingBufferSize=60, readPartialRowTimeoutMillis=60000, maxScanTimeoutRetries=3}, bulkOptions=BulkOptions{asyncMutatorCount=2, useBulkApi=true, bulkMaxKeyCount=25, bulkMaxRequestSize=1048576, autoflushMs=0, maxInflightRpcs=1000, maxMemory=381786521, enableBulkMutationThrottling=false, bulkMutationRpcTargetMs=100}, callOptionsConfig=CallOptionsConfig{useTimeout=false, shortRpcTimeoutMs=60000, longRpcTimeoutMs=600000}, usePlaintextNegotiation=true}.
[main] INFO Repro - Read 12 rows


BUILD SUCCESSFUL in 2s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by steveniemitz** [comment]
ah amazing, thanks for the quick turnaround!

**Comment by garye** [comment]
@steveniemitz Do you use the emulator through the cloud sdk or built from this repository? It will take time for the fix to make it's way into cloud sdk/gcloud once it lands.

**Comment by steveniemitz** [comment]
I was previously testing it through the gcloud SDK, I can give it another run by building it from here though once it lands.

**Comment by garye** [comment]
Ok great. If you need any help running from this repo let me know. 

`go run bigtable/cmd/emulator/cbtemulator`
