### ISSUE TITLE
errorreporting: accept user provided stacktrace

### ISSUE THREAD

**Issue by derekperkins** [GoogleCloudPlatform/google-cloud-go#806]
We handle our errors similarly to https://github.com/pkg/errors/, where we wrap them from where they enter our app and return them up the stack. We capture a stacktrace on the first wrap and add additional context at each return site. We aren't shipping errors until after our handlers return through a middleware stack. By forcing the stack capture to be done by this package (which is a fine default), the only reported error comes from my middleware, defeating the purpose of error reporting.

**Comment by Bankq** [comment]
+1.

Yep, we had the same issue. The solution now is not using `errors` package but `logging`. As long as you set severity >= logging.ERROR and contains a stack, StackDriver errorreporting will pick it up. However you need to form you stack yourself this way, which we found it trivial and flexible.

**Comment by jba** [comment]
Moved to the [Feature Backlog page of the wiki](https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog).

**Comment by derekperkins** [comment]
@jba Would you accept a PR adding this functionality?

**Comment by rakyll** [comment]
Yes, I can review.

**Comment by derekperkins** [comment]
@rakyll Here's the CL https://code-review.googlesource.com/#/c/gocloud/+/20270/ Thanks!

_first time Gerritter_

**Comment by derekperkins** [comment]
Fixed in 1c4a3ef0e89741b941ce0954012eb61f0478f2cc
