### ISSUE TITLE
Glide "Unable to checkout cloud.google.com/go"

### ISSUE THREAD

**Issue by antonkhabaiev** [GoogleCloudPlatform/google-cloud-go#808]
All of a sudden my build started to fail with message:
`
[WARN]  Unable to checkout cloud.google.com/go
[ERROR] Update failed for cloud.google.com/go: Unable to get repository
[ERROR] Failed to do initial checkout of config: Unable to get repository
`

my glide looks like
- package: cloud.google.com/go
  version: v0.13.0
  subpackages:
  - pubsub

Was there a recent change that broke this, or I'm doing something wrong?
Everything worked fine till today.

**Comment by jba** [comment]
Nothing changed as far as we know. It could be a transient error somewhere in the network. Can  you dig through logs for a more specific error message?

**Comment by pongad** [comment]
If `cloud.google.com/go` fails, I'd expect Travis runs to unconditionally fail.
I will close this issue for now since I believe this ought to be a transient issue.
Please reopen if the problem persists.
