### ISSUE TITLE
f redeclared in this block

### ISSUE THREAD

**Issue by nicolasStevenin** [GoogleCloudPlatform/google-cloud-go#809]
Hello,
When I try to test the  testmetada in the project cloud.google.com/go/internal/readme/testdata  in version 0.16.0 it fails with

# _/builddir/build/BUILD/golang-cloud-google-googlecloudplatform-google-cloud-0.16.0/_build/src/cloud.google.com/go/internal/readme/testdata
./bad-no-open.go:17: f redeclared in this block
        previous declaration at ./bad-no-name.go:19
./bad-unclosed.go:19: f redeclared in this block
        previous declaration at ./bad-no-open.go:17
./snips.go:22: f redeclared in this block
        previous declaration at ./bad-unclosed.go:19

Thank you for your help

**Comment by jba** [comment]
That code is never supposed to be run. As the directory name implies, it's actually data for tests.
