### ISSUE TITLE
Go datastore: WithGrpcDialOptions are not applied when dialing emulator

### ISSUE THREAD

**Issue by ianrose14** [GoogleCloudPlatform/google-cloud-go#810]
For example if you make a call like this:

    datastore.NewClient(ctx, "my-project",
      option.WithGRPCDialOption(grpc.WithUnaryInterceptor(myInterceptor))

That works when running on real GCE, but if you run it with `DATASTORE_EMULATOR_HOST` set, [this line](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/datastore/datastore.go#L61) is invoked, which ignores any dial options that you passed:

    conn, err := grpc.Dial(addr, grpc.WithInsecure())

**Comment by jba** [comment]
Which dial options did you want to use?

**Comment by ianrose14** [comment]
In my specific case, `grpc.WithUnaryInterceptor`  (specifically because I want to track our datastore usage and, afaik, Go doesn't provide API hooks like python: http://blog.notdot.net/2010/04/Pre--and-post--put-hooks-for-Datastore-models)

**Comment by jba** [comment]
This should have been fixed by 0533e22fa71728e9e042e858c2e2d49d14bae0e8.
