### ISSUE TITLE
Storage: http2 transport graceful shutdown

### ISSUE THREAD

**Issue by Bankq** [GoogleCloudPlatform/google-cloud-go#811]
Seen
```
https://www.googleapis.com/upload/storage/v1/b/snallery-m/o?alt=json&projection=full&uploadType=multipart: http2: Transport: peer server initiated graceful shutdown after some of Request.Body was written; define Request.GetBody to avoid this error
``` 
error when calling `storage.Writer.Close()`

Edit: title change to align with other issues

**Comment by jba** [comment]
I haven't seen that before. Are you seeing it often?

As a workaround, I recommend retrying your write.

**Comment by Bankq** [comment]
@jba no, this morning is the first and only time. In general, do you recommend retrying operations on top of `storage`'s internal retry?

**Comment by bradfitz** [comment]
@jba, the storage library should still be defining the new GetBody on its Requests, though, at least when it's safe to do so. (when you know the operation is idempotent or safely de-duped server-side).

**Comment by jba** [comment]
Yes: the internal retry isn't perfect. This is a case where it should be safe to rewrite the object.

**Comment by jba** [comment]
@bradfitz OK, will do.

**Comment by Bankq** [comment]
Ok makes sense thanks!
