### ISSUE TITLE
pubsub: Receive never calls callback

### ISSUE THREAD

**Issue by mediocregopher** [GoogleCloudPlatform/google-cloud-go#812]
We previously were using the `v0.11.0` version of this package due to having had some issues upgrading to the later versions once streaming pulls were added. We're currently trying to upgrade again but are running into problems. We have multiple subscriptions which see several hundred publishes a second, and multiple instances of the same process running across multiple nodes, all using `v0.11.0`, which read these publishes. If I pull in the latest google-cloud-go/gax-go and deploy out an instance of this process with them, changing nothing else, it just sits idle not consuming anything. The v11 processes continue consuming normally.

Package versions which aren't working:
```
cloud.google.com/go e943e4a
github.com/googleapis/gax-go 317e000
google.golang.org/grpc 2ef021f
```

And here's a partial goroutine dump from the process which is just idling (I edited out ones which aren't related):

```
goroutine profile: total 85
11 @ 0x42f31c 0x42f40e 0x406624 0x4062cb 0x948c2f 0x964ed2 0x9874ee 0x9829f4 0x982d78 0x97e4ac 0x9858ce 0x987757 0x97c817 0x45e631
#       0x948c2e        google.golang.org/grpc/transport.(*Stream).RecvCompress+0xa4e                                   /home/mediocregopher/src/go/src/google.golang.org/grpc/transport/transport.go:256
#       0x948c2e        google.golang.org/grpc.(*clientStream).RecvMsg+0xa4e                                            /home/mediocregopher/src/go/src/google.golang.org/grpc/stream.go:428
#       0x964ed1        google.golang.org/genproto/googleapis/pubsub/v1.(*subscriberStreamingPullClient).Recv+0x61      /home/mediocregopher/src/go/src/google.golang.org/genproto/googleapis/pubsub/v1/pubsub.pb.go:1581
#       0x9874ed        cloud.google.com/go/pubsub.(*streamingPuller).fetchMessages.func1+0x3d                          /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/service.go:462
#       0x9829f3        cloud.google.com/go/pubsub.(*streamingPuller).call+0x1b3                                        /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/service.go:427
#       0x982d77        cloud.google.com/go/pubsub.(*streamingPuller).fetchMessages+0x57                                /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/service.go:460
#       0x97e4ab        cloud.google.com/go/pubsub.(*streamingMessageIterator).receive+0xdb                             /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/iterator.go:158
#       0x9858cd        cloud.google.com/go/pubsub.(*Subscription).receive+0x35d                                        /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/subscription.go:368
#       0x987756        cloud.google.com/go/pubsub.(*Subscription).Receive.func2+0x56                                   /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/subscription.go:334
#       0x97c816        golang.org/x/sync/errgroup.(*Group).Go.func1+0x56                                               /home/mediocregopher/src/go/src/golang.org/x/sync/errgroup/errgroup.go:58

11 @ 0x42f31c 0x42f40e 0x406624 0x4062cb 0x9877c8 0x45e631
#       0x9877c7        cloud.google.com/go/pubsub.(*Subscription).receive.func1+0x47   /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/subscription.go:360

11 @ 0x42f31c 0x42f40e 0x440754 0x440379 0x474ea2 0x97c681 0x9852eb 0x98b85d 0x98c132 0x45e631
#       0x440378        sync.runtime_Semacquire+0x38                                                    /usr/lib/go/src/runtime/sema.go:56
#       0x474ea1        sync.(*WaitGroup).Wait+0x71                                                     /usr/lib/go/src/sync/waitgroup.go:131
#       0x97c680        golang.org/x/sync/errgroup.(*Group).Wait+0x30                                   /home/mediocregopher/src/go/src/golang.org/x/sync/errgroup/errgroup.go:41
#       0x9852ea        cloud.google.com/go/pubsub.(*Subscription).Receive+0x4ca                        /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/subscription.go:337
#       0x98b85c        bitbucket.org/levenlabs/llib/ldb.(*PubSubConsumer).consume+0x91c                /home/mediocregopher/src/go/src/bitbucket.org/levenlabs/llib/ldb/pubsub.go:473
#       0x98c131        bitbucket.org/levenlabs/llib/ldb.(*PubSubConsumer).refreshTopics.func1+0xa1     /home/mediocregopher/src/go/src/bitbucket.org/levenlabs/llib/ldb/pubsub.go:382

11 @ 0x42f31c 0x43f588 0x94d1ad 0x45e631
#       0x94d1ac        google.golang.org/grpc.newClientStream.func4+0x1cc      /home/mediocregopher/src/go/src/google.golang.org/grpc/stream.go:284

11 @ 0x42f31c 0x43f588 0x97ee8d 0x45e631
#       0x97ee8c        cloud.google.com/go/pubsub.(*streamingMessageIterator).sender+0x55c     /home/mediocregopher/src/go/src/cloud.google.com/go/pubsub/iterator.go:196
```

From looking through the driver code and adding some debug logs it seems like the driver is simply hanging on receiving from grpc. I'm not really sure where to go from here, it seems odd that we'd be the only ones to have this issue but it does seem like all routines are blocked outside of our code. If there's any other information needed to help debug I'd be happy to provide it. Thanks!

**Comment by jba** [comment]
What are the commits of gax-go and grpc that are working?

**Comment by jba** [comment]
I tried to reproduce but couldn't. I ran a publishing process that published 100,000 messages as quickly as possible. Guessing that maybe the new binary was getting starved, I started 10 receiving processes using v0.11.0, and one from e943e4a. The new one got most of the messages. That makes sense, because streaming pull accepts messages more aggressively.

I don't know what's going on, but there have been several changes since v0.11.0. Could you try it at v0.12.0?

Are both the old and new receivers using the same subscription?

**Comment by jba** [comment]
It might also help to know where your code is running (GCE, GKE, Amazon, etc.) We had a similar issue (#740), but that should have been fixed.

**Comment by jba** [comment]
Actually, the fix for #740 didn't happen until v0.14.0, so if you are running on GCE you might try that version.

**Comment by mediocregopher** [comment]
gax-go: 8c160ca
grpc: 6253aa9
and then google-cloud-go/go is the v0.11.0 tag

**Comment by mediocregopher** [comment]
So apparently when I was setting up my test case I configured it wrong, it wasn't reading from the correct subscription and our logging was printing out the sub names ambiguously. Really sorry for wasting your time.

**Comment by jba** [comment]
Not at all, I'm very relieved it wasn't us!

Please let us know if you encounter any issues with streaming pull. There have certainly been some in the past, but we think it should be working smoothly now.
