### ISSUE TITLE
cloud.google.com/go/internal/fields fails at go tip

### ISSUE THREAD

**Issue by hyangah** [GoogleCloudPlatform/google-cloud-go#813]
As discussed in golang.org/issue/21357 (golang/go#21357)
json unmarshal will ignore embedded pointers to unexported types in go1.10.
This test is obviously unhappy about it. 

\cc @zombiezen @jba @dsnet

$  go version
go version devel +84f941ad4c Mon Nov 27 21:56:05 2017 -0500 darwin/amd64
$ go test
--- FAIL: TestAgainstJSONEncodingNoTags (0.00s)
	fields_test.go:151: got
		{Exported:1 unexported:0 Shadow:3 embed1:{Em1:4 Dup:0 Shadow:0 embed3:{Em3:0 embed5:{x:0}}} embed2:0xc420095dd0 Anonymous:15}
		want
		{Exported:1 unexported:0 Shadow:3 embed1:{Em1:4 Dup:5 Shadow:0 embed3:{Em3:7 embed5:{x:0}}} embed2:<nil> Anonymous:15}
FAIL
exit status 1
FAIL	cloud.google.com/go/internal/fields	0.041s

**Comment by jba** [comment]
encoding/json is still broken. I reopened golang/go#21357. Holding off until that is fixed.

**Comment by zombiezen** [comment]
That issue is now fixed.  What remains on this issue?

**Comment by dsnet** [comment]
https://code-review.googlesource.com/#/c/20672/ was merged not long ago. I'll need to be imported internally.

**Comment by zombiezen** [comment]
Marking fixed here and I'll do the cherrypick.
