### ISSUE TITLE
FEATURE: bigquery - inferSchema support nested structs & not required.

### ISSUE THREAD

**Issue by kurtmaile** [GoogleCloudPlatform/google-cloud-go#814]
Hi all,

I am exploring using the go libraries to stream our microservice event data to bigQuery.  In essence we want to persist our raw, nested (key) events into BQ unaltered.

Ive run into some issues pretty quickly with the go library, using a non-trivial, real world event schema.  This event schema is of course nested, where the nesting is often a composition of other structs (resued) to form such a the higher order structs. 

e.g orderEvent struct contains an order struct (amongst other things)

And of course the library needs to support this on creating tables and inserting rows.  I love the idea of dynamic schema inference (awesome), however the inferSchema feature seems quite limited, to primitive types and arrays - unless I am missing soemthing!

Does anyone know of any work to make this more flexible to recursive structs?  Or is there another way to explore enabling such nested data?

I would also suggest as a feature to enable an option of blanket required or nullable - currently it is requried, Id argue it should at least be the other way around.  The reason being, often your schemas are predefined up-front, and often they are loosesly constrained and 'wide' to support different instance population for different use cases.  So it is 'wide' in the sense that not all the *possible* values for a struct are always populated.  Could be a handful of them, could be all - but the point is to reuse an existing wide schema, make everyting optional, and just populate what your use case needs.

Just some feedback based on some initial usage.  Only just started to play with this library as an alternative to java.

Thanks!

**Comment by jba** [comment]
We do infer schemas for nested structs (though not recursive ones&mdash;a struct type referring to itself). Let us know how it failed for you and we'll fix it.

We've had the request for optional fields before (#726). We see its value. We'll consider it again.

**Comment by kurtmaile** [comment]
Hi,

Thanks for the reply - on the recursive issue I found what I was doing wrong (some experimental
struct that did recurse), as you say its fine thanks.

As to the nullability, this is quite a big one for the reasons described.  Be awesome to see this addressed soon, freeing up any structural constraints on teh schema.

Suggest either allowing the bigquery tag to have similar to json tag 'omitempty' (i.e 'nullable'), or be able to toggle the 'blanket' (applies to everything across theboard in a schema) setting either required and nullable.  Gives all the options and freedom :)  

Awesome, loving it so far anyway, great stuff!

Kurt

**Comment by jba** [comment]
My plan is to use a per-field tag "nullable" (since that's what BigQuery calls it).

**Comment by kurtmaile** [comment]
Awesome!!

**Comment by jba** [comment]
Please see See https://code-review.googlesource.com/c/gocloud/+/21632. It does support the "nullable" tag option, but only for `[]byte` and struct pointer. Otherwise, it uses pointer types. If you declare a field of type `*int`, for example, then it infers a nullable field of type INTEGER.

**Comment by kurtmaile** [comment]
Hi,

Just catching up on this.

So for example then basedon above, does this mean that 'int' cannot be used with the nullable tag, but *int can, or have I missed something?   

We have a large codebase we could not rewrite our structs and code -  sorry I dont quite have time just now to look at all the tests for the detail, will do tomorrow, but still (really hoping) this feature can still be used as its super key.  Had started some dev with it and was working nicely.

Thanks for the update Jonathan

Cheers
Kurt

**Comment by jba** [comment]
@kurtmaile We'll probably switch from pointers to NullXXX structs, like cloud.google.com/go/spanner and database/sql do.

It would be impossible (or very broken) to support nullable columns with an ordinary type like `string` or `int`. What would happen if you read a NULL into a `string` or `int` field? Using the zero value of the type for NULL would be dangerously misleading. (It wouldn't round-trip, for one thing.)

**Comment by kurtmaile** [comment]
Hi,

Thanks Jonathan for the explaination makes sense much appreciated.

Is this a V2 feature then and if so any timelines?

Cheers

**Comment by jba** [comment]
Days or weeks, not months.
