### ISSUE TITLE
trace: how to dump trace data from a client?

### ISSUE THREAD

**Issue by junghoahnsc** [GoogleCloudPlatform/google-cloud-go#818]
Hello,

We're trying to add tracing to a server, but there seems to be no way to dump trace data from a client. Is this true? Should I use google API to fetch a trace data?

Thanks,

**Comment by rakyll** [comment]
We are not considering to continue development on this package and switching users to the new [OpenCensus tracing package](https://godoc.org/go.opencensus.io/trace). It provides raw access to the collected data via the exporters.

And Stackdriver is already supported, see https://godoc.org/go.opencensus.io/exporter/trace/stackdriver.

**Comment by junghoahnsc** [comment]
@rakyll Thanks for the info! 
Is there any document that this package is going to be deprecated?

**Comment by rakyll** [comment]
We haven't decided the steps for this package and will make an announcement if anything changes. For now,  I can say that we are not actively developing it and no significant new features will be added.

**Comment by junghoahnsc** [comment]
@rakyll btw, https://github.com/census-instrumentation/opencensus-go says

This project is still at a very early stage of development and a lot of the API calls are in the process of being changed and might break your code in the future.

Is this package too early to use?

**Comment by rakyll** [comment]
We may break the APIs, that's the only concern. The Stackdriver exporter for the tracing package is at a reasonable state. Bug reports are welcome. Please vendor it if you are considering to depend on it.
