### ISSUE TITLE
FEATURE: BigQuery TimePartitioning Update

### ISSUE THREAD

**Issue by kurtmaile** [GoogleCloudPlatform/google-cloud-go#819]
Hi,

In the underlaying v2 API, there is an experimental feature based on having  a custom partition field (so true event time for partitining not ingest time) within the row data.  This is called 'field'

The TimePartitioning struct has new attribute call 'Field'.  I am part of an alpha trial of this, and although it is in the undlying API (google.golang.org/api/bigquery/v2/bigquery-gen.go), its not present in this library.

```
type TimePartitioning struct {
	// ExpirationMs: [Optional] Number of milliseconds for which to keep the
	// storage for a partition.
	ExpirationMs int64 `json:"expirationMs,omitempty,string"`

	// Field: [Experimental] [Optional] If not set, the table is partitioned
	// by pseudo column '_PARTITIONTIME'; if set, the table is partitioned
	// by this field. The field must be a top-level TIMESTAMP or DATE field.
	// Its mode must be NULLABLE or REQUIRED.
	Field string `json:"field,omitempty"`

	// Type: [Required] The only type supported is DAY, which will generate
	// one partition per day.
	Type string `json:"type,omitempty"`
```

Its clearly an easy thing to add, but was wondering if this is more to do with the gcp release process (this is an alpha feature after all).  If so when does this happen (beta?)

**Comment by jba** [comment]
No reason we can't add that now.

**Comment by kurtmaile** [comment]
Awesome, thanks for the fast turnaround. Huge feature we are testing!

Appreciated

**Comment by jba** [comment]
https://code-review.googlesource.com/#/c/gocloud/+/20290
