### ISSUE TITLE
The Firestore API does not work together with AppEngine

### ISSUE THREAD

**Issue by nibarius** [GoogleCloudPlatform/google-cloud-go#822]
When working with AppEngine all outbound HTTP requests [must](https://cloud.google.com/appengine/docs/standard/go/issue-requests) use the urlfetch.Client http client. However it seems like the Firestore API does not support using a custom http client.

When trying to create a Firestore client like this
```
options := option.WithHTTPClient(urlfetch.Client(appengine.NewContext(r)))
firestoreClient, err = firestore.NewClient(ctx, "project-id", options)
```
The error `unsupported HTTP client specified` is returned.

**Comment by jba** [comment]
Firestore uses gRPC, not HTTP.

@zombiezen or @broady can tell you how to use gRPC-based APIs from AppEngine.

**Comment by nibarius** [comment]
When I don't provide an HTTP client, calls to functions like `DocumentRef.Set()` returns the error `rpc error: code = Unavailable desc = all SubConns are in TransientFailure`.

I initially posted on Stackoverflow about that problem:  https://stackoverflow.com/questions/47663044/using-cloud-firestore-with-appengine-go-standard-environment-returns-rpc-error-w

**Comment by broady** [comment]
You shouldn't need to specify any options to use firestore on GAE.

However, you must create a new client for each incoming request.

The client library will automatically plumb the network connections through the [Socket API](https://godoc.org/google.golang.org/appengine/socket).

**Comment by nibarius** [comment]
If that's the case, do you have any idea why the call to DocumentRef.Set() returns the error `rpc error: code = Unavailable desc = all SubConns are in TransientFailure` when running on GAE? In the GAE dev_appserver locally it works just fine.

``` go
type testData struct {
	TestData string `firestore:"myKey,omitempty"`
}

func init() {
	http.HandleFunc("/test", testHandler)
}

func testHandler(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)
	firestoreClient, err := firestore.NewClient(ctx, "my-project")
	if err != nil {
		fmt.Fprintf(w, "Failed to create a new firestore client: %v", err)
		return
	}

	data := testData{"my value"}
	_, err = firestoreClient.Collection("testCollection").Doc("testDoc").Set(ctx, data)
	if err != nil {
		fmt.Fprintf(w, "Failed to create a firestore document: %v", err)
		return
	}
	firestoreClient.Close()
	fmt.Fprint(w, "Data stored in Firestore successfully")
}
```

**Comment by nibarius** [comment]
After some more reading I saw https://cloud.google.com/appengine/docs/standard/go/sockets/ which say that "Sockets are available only for paid apps." My app is a free app, so that is probably the source for the error I'm getting.

I assume this means that the Firestore API can not be used together with AppEngine for free apps.

**Comment by zombiezen** [comment]
@nibarius It means that you will need to enable billing to enable sockets, but from that same page:

> traffic from sockets is billed as outgoing bandwidth

And from https://cloud.google.com/appengine/quotas#Requests, the first 1 GB of outgoing bandwidth is free.

**Comment by nibarius** [comment]
Unfortunately, as a citizen of a country in the European Union, working on a small private project with no real potential for economic benefit in the foreseeable future I'm apparently [not allowed to enable billing](https://cloud.google.com/free/docs/frequently-asked-questions).

> If you are located in the European Union and the sole purpose for which you want to use Google Cloud Platform services has no potential economic benefit you should not use the service. If you have already started using Google Cloud Platform, you should discontinue using the service. See Create, modify, or close your billing account to learn how to disable billing on your projects.

I guess I have to give the [Firestore REST API](https://firebase.google.com/docs/firestore/use-rest-api) a try instead.

**Comment by zombiezen** [comment]
That is accurate, @nibarius, sorry.

Either a change in App Engine's networking or a change in this library to use the REST API (perhaps selectively) would fix this issue.

**Comment by jba** [comment]
We don't have plans for cloud.google.com/go/firestore to support the REST API.

**Comment by nibarius** [comment]
Thanks for the help. At least I know what's expected and using the REST API manually by making http requests to it from my App Engine works well enough for me. So I'm still able to use Firestore with App Engine and Go even if it's not using this library.
