### ISSUE TITLE
bigquery: add SchemaUpdateOptions to load config

### ISSUE THREAD

**Issue by kurtmaile** [GoogleCloudPlatform/google-cloud-go#823]
Hi,

Using the BQ 'job' loading mechanism which goes via GS, (i.e not streaming inserts that use 'insertAll), there  is options to enable dynamic schema evolution using the setting /  options below within the job load/insert request:  

JobConfigurationLoad.SchemaUpdateOptions []string

ALLOW_FIELD_ADDITION: allow adding a nullable field to the schema.  ALLOW_FIELD_RELAXATION: allow relaxing a required field in the original  schema to nullable.  

This is super powerful for easily allowing backward compat changes to occur dynamically with no downtime.   We are looking to move to the streaming inserts model using go, but seems this  feature is not supported?  Ive had a look at the TableData API for insert but appears this is not an option using this method? 

Am I missing something here or is this not supported in the table insertAll method?  If not, how are peeps managing schema evolution in this model?  Any advice welcome.

Thanks

**Comment by jba** [comment]
There are two separate issues here:
1. The Go client doesn't support SchemaUpdateOptions for loading from GCS.
2. The BigQuery service doesn't support those options for streaming inserts.

We can address (1) here, but not (2); that is a question for the BigQuery service itself.

**Comment by kurtmaile** [comment]
Hi Jonathan,

Thanks for the reply.

1. OK thanks for letting me know and labelling it as a feature request.

2. I will ask on the BQ google groups then given its a service level feature gap.

Once again, cheers for replying, much appreciated!
Kurt

**Comment by zacharya19** [comment]
This can be closed:
https://github.com/GoogleCloudPlatform/google-cloud-go/commit/63a470402311c59796d6603a081f96a8b79e0b8d

**Comment by jba** [comment]
Thanks for the CL, @zacharya19!
