### ISSUE TITLE
Spanner requires "unsafe" code. AppEngine can't execute "unsafe"

### ISSUE THREAD

**Issue by clanstyles** [GoogleCloudPlatform/google-cloud-go#827]
Spanner seems to depend on ```go.opencensus.io/internal/tagencoding/tagencoding.go```. This contains unsafe code and AppEngine wont let us run unsafe code.

**Comment by odeke-em** [comment]
Thanks for cross reporting this @clanstyles. We are also tracking this issue on the mothership here at https://github.com/census-instrumentation/opencensus-go/issues/239. When it is fixed in opencensus-go, we'll ping here too. /cc @rakyll @jcd2.

**Comment by clanstyles** [comment]
This has been fixed in opencensus

**Comment by jba** [comment]
Closing. Reopen if it still breaks after `go get -u`.
