### ISSUE TITLE
Cloud Spanner App Engine Context

### ISSUE THREAD

**Issue by clanstyles** [GoogleCloudPlatform/google-cloud-go#829]
```panic: not an App Engine context```

```
func main() {
	var err error
	if database, err = spanner.NewClient(context.Background(), "..."); err != nil {
		panic(err)
	}
	defer database.Close()

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {})

	appengine.Main()
	return
}
```

This produces App Engine context error. I'm unsure how you're supposed to connect to Spanner without an AppEngine context. Do you do it per request? That seems very funky for a database connection.

EDIT:
It seems to only occur if you run it through ```dev_appserver.py``` If you run it stand alone, it doesn't occur.

**Comment by clanstyles** [comment]
I've dug into this more, it seems that it might be an unintentional bug in the OAuth driver? Please see https://github.com/golang/oauth2/issues/260

**Comment by zombiezen** [comment]
The Spanner client uses gRPC, which uses the [Sockets API](https://cloud.google.com/appengine/docs/standard/go/sockets/) on App Engine Standard.  Sockets must have a valid App Engine context in order to open.  As you say in your opening comment, you must create a Spanner client per request, passing in the request context.

This is a limitation of App Engine Standard.  We are looking at options on how to improve the situation, but I don't have anything concrete to share right now.

**Comment by clanstyles** [comment]
Ah gotcha. So we should migrate to Flexiable?

**Comment by zombiezen** [comment]
Flex allows long-lived TCP connections, yes.  However, depending on your application, a TCP connection per request performance might be acceptable.

**Comment by clanstyles** [comment]
@zombiezen I've seen that most databases have some sort of connection pool. With spanner, we're using it for an API, Web frontend and backend services. What is the recommended approach with Spanner? These services will be under heavy load daily.

**Comment by derekperkins** [comment]
@clanstyles if you're under heavy load and you want to use connection pools, there's no way to make that work with GAE Standard, so you'll want to migrate those services. If they're under heavy load, it'll probably save you money anyways. What we do run on GAE Standard is our devops chatbot, where we're not worried about the extra latency of creating a new connection per request.

**Comment by clanstyles** [comment]
@derekperkins thank you

**Comment by zombiezen** [comment]
See also #704

**Comment by danoscarmike** [comment]
Closing this issue. @clanstyles if you have oustanding, unanswered questions please LMK and we can reopen/address.
