### ISSUE TITLE
Unable to retrieve the values  based on struct field from datastore using golang

### ISSUE THREAD

**Issue by kasireddy002** [GoogleCloudPlatform/google-cloud-go#831]
Hi everyone,

i am writing a service for search functionality .
when i pass the USERNAME in the body to get the data based on that USERNAME .
but i am unable to get the values.

func searchValue (res http.ResponseWriter, req *http.Request){
log.Printf("%#v Getting values url - x ", "called search")
patient := &PatientData{}
if err := json.NewDecoder(req.Body).Decode(patient); err != nil {
panic(err)
}
ctx := appengine.NewContext(req)
ctx, err := appengine.Namespace(ctx, NAMESPACENAME)
if err != nil {
panic(err)
}
m := patient.Phone
i, err := strconv.ParseInt(m, 10, 64)
log.Printf("%#v Getting values m ", m)
log.Printf("%#v Getting values url -yyy ",i)

key := datastore.NewKey(ctx, "Patient","" , i, nil)
log.Printf("%#v Getting values url - key ", key)
   err = datastore.Get(ctx, key, patient)
	if err := json.NewEncoder(res).Encode(patient); err != nil {
		panic(err)
	}		
}
In these code i am passing PHONE to get the full struct values.
i don't want to use the newkey to generate the keyname and to get values.
please i need a help .

**Comment by zombiezen** [comment]
I believe you are looking for [queries](https://cloud.google.com/datastore/docs/concepts/queries).

```go
q := datastore.NewQuery("Patient").Filter("Username =", patient.Username).Limit(1)
var results []PatientData
keys, err := q.GetAll(ctx, &results)
if err != nil {
  // handle error
}
if len(results) == 0 {
  http.NotFound(res, req)
}
// use results[0]
```

You appear to be using the App Engine version of the library, although the ideas are the same, as the ones in the Cloud Libraries here.

**Comment by jba** [comment]
Closed due to lack of activity.
