### ISSUE TITLE
firestore: support firestore.Delete with Set

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/google-cloud-go#832]
Support field deletion:

```
client.Set(ctx, map[string]interface{}{
    "field": firestore.Delete,
})
```

**Comment by jba** [comment]
This correctly returns an error, because Set without a merge option completely replaces the document, so Delete doesn't make sense. Pass a Merge option to Set if you want to delete a field.

A forthcoming CL clarifies the doc for `DocumentRef.Set`.
