### ISSUE TITLE
Transaction Interface

### ISSUE THREAD

**Issue by clanstyles** [GoogleCloudPlatform/google-cloud-go#833]
Is there not a standardized ReadWrite/ReadOnly transaction interface? How can we abstract away the unit of work/transactions without this?

**Comment by jba** [comment]
Which API are you referring to?

**Comment by clanstyles** [comment]
Sorry, I was referring to the Google Spanner APIs.

Spanner seems to have the following APIs:

https://godoc.org/cloud.google.com/go/spanner

1. func (c *Client) Single() *ReadOnlyTransaction
2. func (c *Client) ReadOnlyTransaction() *ReadOnlyTransaction
3. func (c *Client) ReadWriteTransaction(ctx context.Context, f func(context.Context, *ReadWriteTransaction) error) (commitTimestamp time.Time, err error)

Single seems to wrap ReadOnly or vise versa. However, because the transaction API isn't standardized, unless you pass around that explicit type of transaction you want it's hard to support them. I can't find a pattern that works otherwise.

During the context of a request or controller, if I say do users.Get(ctx...) I can't provide a transaction to multiple of these without knowing ahead of time which type it would be.

Is there a better way to do this?

**Comment by jba** [comment]
It's true that the spanner package doesn't have an interface with the common methods of read-only and read-write transactions. But you can define one yourself:
```
interface {
    Query(context.Context, Statement) *RowIterator
    Read(ctx context.Context, table string, keys KeySet, columns []string) *RowIterator
    ReadRow(ctx context.Context, table string, key Key, columns []string) (*Row, error)
    ReadUsingIndex(ctx context.Context, table, index string, keys KeySet, columns []string) *RowIterator
}
```

Define your `Get` method to take that type, or even an interface that has just the methods you need to implement `Get`.
