### ISSUE TITLE
bigtable: block_all() filter not supported by emulator?

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-go#839]
I might be using the filters incorrectly, but creating a request like this:

```C++
google::bigtable::v2::ReadRowsRequest request;
request.mutable_filter()->set_block_all(true);
// ... other stuff here ...
```

produces different results in the emulator vs. the production Bigtable.  The emulator returns all the cells, while the production Bigtable returns none.

**Comment by garye** [comment]
Here is the list of currently supported filters:
https://cloud.google.com/bigtable/docs/emulator

**Comment by sduskis** [comment]
@coryan, as far as we can tell, block_all seems to work.  We should get someone to confirm.

**Comment by coryan** [comment]
Confirmed: `block_all` works for me.  I am sending a PR for Bigtable to remove the workaround.
