### ISSUE TITLE
bigtable: row_sample() filter not supported by emulator?

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-go#840]
I might be using the filters incorrectly, but creating a request like this:

```C++
google::bigtable::v2::ReadRowsRequest request;
request.mutable_filter()->set_row_sample(0.75);
// ... other stuff here ...
```

produces different results in the emulator vs. the production Bigtable. The emulator returns all the cells, while the production Bigtable returns around 75% of them.

**Comment by sduskis** [comment]
`SampleRowKeys` is implemented, but has some issues as per [this issue found in the google-cloud-cpp repo](https://github.com/GoogleCloudPlatform/google-cloud-cpp/issues/441).

**Comment by coryan** [comment]
As you know,  `SampleRowKeys` and `set_row_sample()` are different things.  This bug is about the filter expression `ReadRows()`.
