### ISSUE TITLE
bigtable: apply_label_transformer() not supported in the emulator?

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-go#841]
I might be using the filters incorrectly, but creating a request like this:

```C++
google::bigtable::v2::ReadRowsRequest request;
request.mutable_filter()->set_apply_label_transformer("foo");
// ... other stuff here ...
```

produces different results in the emulator vs. the production Bigtable. The emulator does not change any labels, while the production Bigtable modifies any returned cells by adding the `"foo"` label.

**Comment by sduskis** [comment]
@enocom, this ought to be relatively quick, and worth doing.
