### ISSUE TITLE
datastore: Query.Get not supported?

### ISSUE THREAD

**Issue by Ellmen** [GoogleCloudPlatform/google-cloud-go#844]
In NDB for python, the best practice for getting one result from a query is the get method. I'm not sure if this is a design decision but currently the go datastore supports GetAll but not Get.

**Comment by jba** [comment]
We didn't feel that getting one result from a query was common enough to warrant its own method. You can use `Client.Run` and `Iterator.Next` to get one query result. That's what a `Get` method would do anyway.
