### ISSUE TITLE
go build fails with google-cloud-go v1.7.0

### ISSUE THREAD

**Issue by a27kash** [GoogleCloudPlatform/google-cloud-go#846]
console output

# bitbucket.org/superkinglabs/hercules/vendor/cloud.google.com/go/bigquery
../vendor/cloud.google.com/go/bigquery/load.go:54:20: unknown field 'TimePartitioning' in struct literal of type bigquery.JobConfigurationLoad
../vendor/cloud.google.com/go/bigquery/load.go:67:49: q.Load.TimePartitioning undefined (type *bigquery.JobConfigurationLoad has no field or method TimePartitioning)
../vendor/cloud.google.com/go/bigquery/table.go:164:8: unknown field 'Field' in struct literal of type bigquery.TimePartitioning
../vendor/cloud.google.com/go/bigquery/table.go:174:16: q.Field undefined (type *bigquery.TimePartitioning has no field or method Field)

**Comment by jba** [comment]
I think you must mean v0.17.0.

Anyway, the `Field` field is certainly [present](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/v0.17.0/bigquery/table.go#L154). Something in your workspace must be inconsistent or out of date.
