### ISSUE TITLE
pubsub: nil Duration

### ISSUE THREAD

**Issue by Bo0mer** [GoogleCloudPlatform/google-cloud-go#847]
# Environment
```
$ go version
go version go1.9.2 darwin/amd64

$ git rev-parse HEAD
166a315629914c5562c6b111cab2f80c4ea9a2ea

$ git remote -v
origin	https://code.googlesource.com/gocloud (fetch)
origin	https://code.googlesource.com/gocloud (push)
```

# What I'm trying to do

I'm trying to receive messages on a subscription. See code below. I'm using the pubsub emulator:
```bash
$ gcloud beta emulators pubsub start
```
with the following program:
```go
package main

import (
	"context"
	"log"

	"cloud.google.com/go/pubsub"
	xcontext "golang.org/x/net/context"
)

func main() {
	ctx := context.Background()
	pubsubClient, err := pubsub.NewClient(ctx, "nil_duration_test")
	if err != nil {
		log.Fatal(err)
	}

	topic, err := pubsubClient.CreateTopic(ctx, "events")
	if err != nil {
		topic = pubsubClient.Topic("events")
	}
	c := pubsub.SubscriptionConfig{Topic: topic}
	sub, err := pubsubClient.CreateSubscription(ctx, "topic-subscription", c)
	if err != nil {
		log.Fatal(err)
	}

	msgChan := make(chan *pubsub.Message, 1)
	errChan := make(chan error, 1)
	go func() {
		if err := sub.Receive(ctx, func(_ xcontext.Context, m *pubsub.Message) {
			msgChan <- m
			m.Ack()
		}); err != nil {
			errChan <- err
		}
	}()

	select {
	case err := <-errChan:
		log.Fatal(err)
	case <-msgChan:
		// OK.
	}
}
```

# What I expect to see
The program hangs until a message is received.

# What I see instead
```text
2018/01/02 16:08:59 duration: nil Duration
exit status 1
```
If I configure the `RetentionDuration` field of the `SubscriptionConfig` struct passed to `CreateSubscription` to a non-zero duration, the problem seems to disappear. However, according to the documentation of `RetentionDuration`, it has a default value of 7 days:

https://github.com/GoogleCloudPlatform/google-cloud-go/blob/166a315629914c5562c6b111cab2f80c4ea9a2ea/pubsub/subscription.go#L137-L141

This value is used in the test and integration tests, but I'm not able to find it populated in the non-test code.
```bash
$ ag defaultRetentionDuration
subscription_test.go
114:const defaultRetentionDuration = 168 * time.Hour
134:		RetentionDuration:   defaultRetentionDuration,
151:		RetentionDuration:   defaultRetentionDuration,

integration_test.go
308:		RetentionDuration:   defaultRetentionDuration,
```

This problem did not appear with earlier version of the library. I have not checked whether the `RetentionDuration` field is introduced lately, or setting the default value has been removed for some reason.

Please let me know if any more information is needed.

Thanks for your awesome work!
Cheers,
Ivan

**Comment by fastest963** [comment]
We're having this issue as well. Is it just a problem with the emulator? Do we have to set this now?

**Comment by pongad** [comment]
Problem timeline:
The field was added a while back and we updated the client lib to include it.
However, the field used to be populated only if your project is in the whitelist for this feature.
Knowing this, we added a nil-check so that the client works for people not in the whitelist.
At this time, it's OK that the emulator didn't set this field: we have the nil-check.

Recently, the feature becomes available to everyone, and the field is always populated.
So, we remove the nil-check, thinking that the check is just dead code.
We didn't realize at the time that the emulator isn't updated to populate this field.

So, this is a problem on the emulator and I'll work on this.
It might take a while to roll out however. Are you OK with manually setting the duration in your test code for the time being?

**Comment by fastest963** [comment]
Yup, we can set this in test mode only for the time being.

**Comment by pongad** [comment]
This change has been submitted to Google internal repo. I'll leave this open until the emulator makes its way out.

**Comment by gordallott** [comment]
is there any update on a new emulator coming out? 
using the latest master of `cloud.google.com/go` setting the `RetentionDuration` does nothing to help the issue, with the supplied test program i get `2018/01/30 18:19:22 duration: nil Duration` even when modified to set the `RetentionDuration` in the code. this basically makes the emulator totally unusable which is pretty bad. it's also a pretty terrible error message

**Comment by jba** [comment]
https://code-review.googlesource.com/#/c/gocloud/+/22570 will fix.
