### ISSUE TITLE
Add PubSub support for accessing subscriptions in multiple projects

### ISSUE THREAD

**Issue by thobrla** [GoogleCloudPlatform/google-cloud-go#849]
I'd like to refer to two subscriptions in different projects from google-cloud-go/pubsub.  Currently, I can see only two fairly inefficient ways to do this:

1. Create two Clients
2. Create two Topics via TopicInProject, then iterate over all Subscriptions on each topic and find the matching Subscription.

It seems like the only thing missing is a way to supply the project part of the subscription's name.  A function like this would do the trick, and seems easy enough to implement:

`func (c *Client) SubscriptionInProject(id, projectID string) *Subscription`

**Comment by jba** [comment]
@pongad

**Comment by thobrla** [comment]
Any sense on an ETA for this?

**Comment by jba** [comment]
I'll put it on my schedule for the next two weeks.

**Comment by jadekler** [comment]
@thobrla Hello! You're correct, this is an easy feature :) Just want to check, how would you go about authing to the second project? Is it a public project, or perhaps do you have a serivce account that's authorized across multiple projects?

**Comment by thobrla** [comment]
Correct, running as a service account that it is authorized to access resources in multiple projects.

Note this doesn't necessarily mean the service account has access to the projects in their entirety.  Our particularly use case involves having access to a limited number of topics and subscriptions that live in different projects.

**Comment by jadekler** [comment]
Great, thanks! @thobrla
