### ISSUE TITLE
Spanner LIKE query

### ISSUE THREAD

**Issue by clanstyles** [GoogleCloudPlatform/google-cloud-go#851]
I'm having a hard time finding any information on the syntax for the following query.

```
SELECT * FROM Table WHERE lower(name) LIKE lower(@param)
```
How can I append % to the beginning of the param? I've tried the following combinations:

```'%' @param '%'```
```'%'+@param+'%'```
```% @param %```

And everything in between.

**Comment by jba** [comment]
Try `CONCAT('%', @param, '%')`. I don't think `+` is string concatenation. https://cloud.google.com/spanner/docs/functions-and-operators#operators

**Comment by clanstyles** [comment]
Thank you jba, works perfectly!
