### ISSUE TITLE
pubsub: Messages acked after 30 minutes are duplicated

### ISSUE THREAD

**Issue by fastest963** [GoogleCloudPlatform/google-cloud-go#860]
I'm currently working with support (Case 14709699) but thought I'd post here in case it's a problem with the driver. We've having an issue where every single message on a subscription is duplicated immediately. The messages on this subscription take a longer time than our other subscriptions so I'm inclined to think that the time it takes to ack is causing the problem. Additionally, when we ack it for the second time (in milliseconds because we already received it) it doesn't get duplicated anymore.

I added a log at the top of our receive callback and another at the end with a "success" int indicating if it was ack'd or nack'd.

First example: took 33 minutes and 4 seconds to ack and then immediately received same message again). This was verified by publishing a single message to the topic and monitoring the backlog via Stackdriver to ensure that there was ever only 1 message in the subscription. Then we immediately got it again with the same messageID. We nack'd the second message because of an application error on our side.
```
Jan 17 22:56:47: ~ INFO -- Got pubsub message -- messageID="22585984507129" messageSubscription="gce-us-east1_deferrer_Replicator.Replicate_deferrer_worker" messageTopic="gce-us-east1_deferrer_Replicator.Replicate"
Jan 17 23:29:52: ~ INFO -- Finished pubsub message -- duration="33m4.901046089s" messageID="22585984507129" messageSubscription="gce-us-east1_deferrer_Replicator.Replicate_deferrer_worker" messageTopic="gce-us-east1_deferrer_Replicator.Replicate" success="1"
Jan 17 23:29:52: ~ INFO -- Got pubsub message -- messageID="22585984507129" messageSubscription="gce-us-east1_deferrer_Replicator.Replicate_deferrer_worker" messageTopic="gce-us-east1_deferrer_Replicator.Replicate"
```

We then immediately got the message again and nack'd it again (because of that same error), but then never received the message again and Stackdriver shows that it was removed from the backlog (despite being nack'd).
```
Jan 17 23:29:52: ~ INFO -- Got pubsub message -- messageID="22585984507129" messageSubscription="gce-us-east1_deferrer_Replicator.Replicate_deferrer_worker" messageTopic=
"gce-us-east1_deferrer_Replicator.Replicate"
```

This was tested with:
```
sub.ReceiveSettings.MaxOutstandingMessages = 1
sub.ReceiveSettings.MaxExtension = time.Hour * 5
```
The receive function simply just makes an HTTP request with the payload and then either ack's or nack's based on the response. We're not setting any options or anything special on the client. This was tested running the latest master version of this package:
```
cloud.google.com/go (git) - 31bbc66 pstest: misc small changes
```

Let me know if there's any more information I can provide.

**Comment by fastest963** [comment]
I'm not sure if this is the same problem as #778 but considering we're using the latest version with MOD_ACK's I didn't think it was the same issue. Support has confirmed as well that the MOD_ACK's are being received and handled.

**Comment by fastest963** [comment]
I've updated the above logs to correct an original copy/paste error. It looks like this might be affected by our receive callback taking more than 30 minutes. The support rep for that ticket said that GCP automatically closes idle TCP connections after 30 minutes but that this driver was fixed in 4b5faa47331c50b3f75616de199da5fea9c50bea.

**Comment by jba** [comment]
Thanks for the clear information. We'll look into it.

**Comment by fastest963** [comment]
Not sure if this helps at all but I added some debug logging to `streamingMessageIterator.send` and it looks like after we call `Ack` on the message, it did successfully send a req with a single id in `ack_ids` and that call didn't error. I was trying to determine if it was a server-side problem or a problem with this driver. If there's anything in particular that I can look into on my end, let me know!

**Comment by jadekler** [comment]
Hi @fastest963. We believe your issue is related to firewalls closing long-lived connections after 30m. When a long-lived connection is closed, the server considers the message nacked, even if you had set the deadline to 5 hours from now.

Our recommendation for messages that take >30m to process is to use the lower-level client in a pull model instead of the higher-level client's stream model. [Here's an example of that](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/internal/pubsub-pull-example/main.go).

**Comment by fastest963** [comment]
@jadekler thanks for the clarification. That does sound like the issue. Does the firewall still close the connection even if there's traffic over it? I would've thought the continuous ModAck packets would keep the connection alive.

**Comment by fastest963** [comment]
@jadekler thanks for adding the example, I've taken your example and worked it into one of our applications. Is that model not intended to be a long term solution? If it is, is there any chance of getting it more integrated with the pubsub driver and not relying on the underlying v1 implementation? We lose a lot of functionality (in NewClient and Message in particular) that needs to be duplicated because of it using the v1 package.

**Comment by jba** [comment]
I'm sorry, we don't have plans to integrate it into the main client.

Your application might be more suited to Cloud Tasks than PubSub. You can sign up for the Cloud Tasks alpha [here](https://docs.google.com/forms/d/1g6yRocQ3wtdTArfO4JX8DoqOhYmsoTVgrlFnS0mV1bo/viewform?edit_requested=true).
