### ISSUE TITLE
firestore: document how to tell "not exists" error from other errors in DocumenRef.Get()

### ISSUE THREAD

**Issue by kjk** [GoogleCloudPlatform/google-cloud-go#861]
From https://godoc.org/cloud.google.com/go/firestore#example-DocumentRef-Get, example for Get:
```
ctx := context.Background()
client, err := firestore.NewClient(ctx, "project-id")
if err != nil {
    // TODO: Handle error.
}
defer client.Close()

docsnap, err := client.Doc("States/Ohio").Get(ctx)
if err != nil {
    // TODO: Handle error.
}
```

In JavaScript SDK, result of Get() has `exists` field.

As far as I can tell in Go SDK I can't distinguish "document doesn't exist" error from e.g. network connection error.

I hacked a heuristic function:
```
func dbIsNotFoundError(err error) bool {
	s := err.Error()
	return strings.Contains(s, "code = NotFound")
}
```
but I would prefer a supported and documented way of doing that.

**Comment by jba** [comment]
Try
```
import (
    "google.golang.org/grpc"
    "google.golang.org/grpc/codes"
)

if grpc.Code(err) != codes.NotFound
```

**Comment by kjk** [comment]
Thanks, I've tested it and it worked.

That being said, I imagine it's a common thing to do and impossible to figure out hence 2 suggestions:
* expand https://godoc.org/cloud.google.com/go/firestore#example-DocumentRef-Get doc to show this pattern (as well https://firebase.google.com/docs/firestore/query-data/get-data which was my primary documentation when learning the SDK)
* add a helper function so that I can call e.g. `firestore.IsNotFoundError(err)`. It's not to save few import lines but to improve discoverability of this functionality

**Comment by automaticalldramatic** [comment]
I now face the same error in 2019. There is an Exists() method, but if the document is not found, the Firestore client will throw an error, this error consists of only the message and no way of telling this one apart from a network error - the grpc error code detection works but if one does not find this particular thread, there is a slim chance of figuring this out.

**Comment by automaticalldramatic** [comment]
Also, minor edit, the error codes are now part of status, so one has to :

```
import (
    "google.golang.org/grpc/status"
)
```

**Comment by makuc** [comment]
However, if we determene existence of a document based on an error, why do we even have a method Exists() on type DocumentSnapshot?

**Comment by Setheck** [comment]
seems kind of redundant to use the Exists() method. 
Since you have to call `Get()` handle a possible error, then call the Exists() method. If the error from the Get() is a not found you would need to explicitly ignore a not found error then call Exists()
am i missing something?

**Comment by tbpg** [comment]
I can imagine situations where it's more convenient to call an `Exists()` method. But, that's a good question. :)

If `Get()` returns an error with `grpc.Code(err) == codes.NotFound`, you don't have to call `Exists()`. At that point, you already know the document you were trying to get does not exist.

**Comment by hoshitocat** [comment]
`grpc.Code(err)` is deprecated.
but, we can use `status.Code(err)`. 
https://pkg.go.dev/google.golang.org/grpc/status#Code

import (
    "google.golang.org/grpc/codes"
    "google.golang.org/grpc/status"
)

// deprecated
// if grpc.Code(err) == codes.NotFound
if status.Code(err) == codes.NotFound

**Comment by ShalomPrinz** [comment]
> If `Get()` returns an error with `grpc.Code(err) == codes.NotFound`, you don't have to call `Exists()`. At that point, you already know the document you were trying to get does not exist.

@tbpg Could there be a situation that getting a document will not return an error and a not found status code, but still calling the Exists method will return false? Should I handle this case too? I don't understand the purpose of having both of those methods

**Comment by tbpg** [comment]
Not that I can think of, but I'm not 100% sure. Another maintainer might think of one.

One situation `Exists` could be helpful is a long-lived `DocumentRef` with concurrent operations - you may want to call `Exists` to see if/when the document is deleted.
