### ISSUE TITLE
Writer.Write() with Checksum example is broken

### ISSUE THREAD

**Issue by fejta** [GoogleCloudPlatform/google-cloud-go#865]
https://godoc.org/cloud.google.com/go/storage#Writer.Write the `Example (Checksum)` suggests the following:

```
wc := client.Bucket("bucketname").Object("filename1").NewWriter(ctx)
wc.CRC32C = crc32.Checksum(data, crc32.MakeTable(crc32.Castagnoli))
```

I believe what you actually want is `wc.ObjectAttrs.CRC32C = crc32.Checksum(...`

**Comment by rogerhub** [comment]
At a glance, it seems like both are acceptable since ObjectAttrs is an anonymous member.

**Comment by jba** [comment]
The examples are compiled along with tests, so I'm pretty confident it's correct.
