### ISSUE TITLE
errorreporting: Give option to pass User for ErrorContext

### ISSUE THREAD

**Issue by someone1** [GoogleCloudPlatform/google-cloud-go#867]
The [ErrorContext](https://godoc.org/google.golang.org/genproto/googleapis/devtools/clouderrorreporting/v1beta1#ErrorContext) allows the error report to be associated with a user. This has been a useful feature for me to add more context so I can traceback and replay sections of my code where external data for the specific user impacts the operation of the code. 

Perhaps the [Entry ](https://godoc.org/cloud.google.com/go/errorreporting#Entry) type can be updated to include a User string property to be [copied into the ErrorContext](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/errorreporting/errors.go#L179)?

**Comment by zombiezen** [comment]
@shantuo Mind taking a look?

**Comment by tmc** [comment]
refs https://github.com/GoogleCloudPlatform/google-cloud-go/issues/471
