### ISSUE TITLE
datastore: Support insert and update

### ISSUE THREAD

**Issue by apstndb** [GoogleCloudPlatform/google-cloud-go#872]
Cloud Datastore API have support of `insert` and `update` as primitive mutation
but `google-cloud-go` support `upsert` and `delete` only.
https://cloud.google.com/datastore/docs/reference/rpc/google.datastore.v1?hl=en#mutation

We often implement `insert` or `update` using transaction.
It can be avoided by support primitive `insert` and `update`.

Ruby and Node.js and .NET client library already support it.
https://github.com/GoogleCloudPlatform/google-cloud-ruby/pull/680
https://cloud.google.com/nodejs/docs/reference/datastore/1.3.x/DatastoreRequest#save
http://googlecloudplatform.github.io/google-cloud-dotnet/docs/Google.Cloud.Datastore.V1/api/Google.Cloud.Datastore.V1.Mutation.html

I guess the reason may be that AppEngine SDK haven't support of the mutation options and it can be confusing.

(Added) I noticed that Java and PHP client library also support it.

**Comment by jba** [comment]
Moved to https://github.com/GoogleCloudPlatform/google-cloud-go/wiki/Feature-Backlog.

**Comment by jba** [comment]
This was done in 02a2d936c7c22d0d585fb1e86ac05043bacb3a13.
