### ISSUE TITLE
Clarification: Can you list all IAM users inside a gcp project?

### ISSUE THREAD

**Issue by MovieStoreGuy** [GoogleCloudPlatform/google-cloud-go#873]
I am trying to read through all the apis and but I don't see a clear cut way to list all Iam Users for a given gcp project that I have access to.

Is it possible to do this?

**Comment by MovieStoreGuy** [comment]
According to GCP, the items I am after is `members` that is shown under `IAM & admin/Iam` tab on console.cloud.google.com

**Comment by jba** [comment]
I think you want https://cloud.google.com/resource-manager. The Go client for that is at [google.golang.org/api/cloudresourcemanager/v1](https://godoc.org/google.golang.org/api/cloudresourcemanager/v1). Try Projects.GetIamPolicy.

**Comment by MovieStoreGuy** [comment]
Thank you, Is there a reason why these two are in seperate projects?

**Comment by jba** [comment]
I'm not sure what two things you're referring two exactly, but if you mean why are some cloud clients at google.golang.org/api and some at cloud.google.com/go, the answers are historical and technical and not very interesting. The ultimate goal is to have them all at cloud.google.com/go, but that is a work in progress.

**Comment by MovieStoreGuy** [comment]
All history is interesting.
If I could help at all, I am more than happy to.
