### ISSUE TITLE
allow logging prebuilt json

### ISSUE THREAD

**Issue by DrRibosome** [GoogleCloudPlatform/google-cloud-go#877]
It would be nice if the logging package allowed users to log prebuilt json strings. The use case would be using google cloud logging as a sink for an existing structured logger (such as uber's zap) that already creates properly formatted json log messages efficiently.

**Comment by jba** [comment]
Wrap your JSON string in a json.RawMessage and use that as the payload. I'll document that in a forthcoming CL.
