### ISSUE TITLE
Questions about go import "golang.org/x/net/context"

### ISSUE THREAD

**Issue by smothiki** [GoogleCloudPlatform/google-cloud-go#878]
We have recent updated out go code base to go1.9 from go 1.6 and found out that context is still being used as "golang.org/x/net/context" istead of go library "context".  We found a compilation issue and fixed the dependencies. But any plans on moving to go lib "context"

**Comment by jba** [comment]
We do want to do that, but are held back by some systems and customers that still need Go 1.6. In Go 1.9 and higher, the two `context.Context` types are identical (thanks to type aliases), so feel free to mix and match.
