### ISSUE TITLE
datastore: if context was canceled, there is no way to identify if changes were actually persisted

### ISSUE THREAD

**Issue by piotrkowalczuk** [GoogleCloudPlatform/google-cloud-go#882]
**version:** v0.18.0

In my app termination is solved by global context, that when certain signal is received from the system it is canceled. Child of this context is passed into `datastore.Client.RunInTransaction`:
```go
var job Job
_, err := storage.RunInTransaction(ctx, func(tx storage.Transaction) error {
	if err := tx.Get(key, &job); err != nil {
		return err
	}
	switch {
	case job.IsFinished, job.InProgress, job.IsSkipped:
		return datastore.ErrNoSuchEntity
	}

	job.InProgress = true
	job.PickedAt = time.Now()
	_, err := tx.Put(key, &job)
	return err
}, datastore.MaxAttempts(3))
```

As expected context cancelation cause function to fail. What is unexpected is that it happens that changes are persisted. It makes entire idea of this function pointless. Error needs to be checked afterwards anyway.

**Comment by piotrkowalczuk** [comment]
@jba Atm I have dirty hack right after this piece of code. But im wondering if Datastore service sends any additional details in `status.Status` error object, so I can rollback changes only when they truly occur?

**Comment by jba** [comment]
This is not hard to reproduce, and I understand why it is frustrating. But I'm not sure how it can be fixed. If the context is cancelled while the function you passed to `RunInTransaction` is running, you won't commit the transaction. And I can tell you that gRPC [checks for a done context](https://github.com/grpc/grpc-go/blob/d50734d1d6ca477a72646f3022216ec39639f4cd/stream.go#L235) just before it sends a message. But if the cancel happens while the RPC is in flight, it races with DataStore's internal commit process. It could be that DataStore doesn't notice the cancellation until after it has made changes. (You could argue that it should return success in that case, but maybe the cancellation affects other actions.)

Unfortunately, cancelling an in-flight RPC is inherently racy, and I think you'll have to continue compensating by doing a `Get`. 

When I printed the errors with `%#v`, I didn't see any additional information that would be helpful.

By the way, this problem doesn't make the "entire idea of this function pointless". It still provides atomicity: either all your changes happened, or none of them did. You just can't always be sure which of those two events occurred.

@pcostell, do you have any suggestions for a better way to deal with this?

**Comment by piotrkowalczuk** [comment]
@jba yes you are right. Sorry, my misunderstanding.

**Comment by jba** [comment]
I realized there is actually a better explanation for what you're seeing. It's probably not Datastore that is returning the Canceled error. If gRPC is waiting for the reply to an RPC and it sees that the context is canceled, it stops waiting and returns canceled right away, as it should. It can't know that a successful response is being returned.

Ultimately it's the same point, but the actual events are different, and it's clear that there's nothing Datastore could do to make it better.
