### ISSUE TITLE
Error when deploying to Google App Engine

### ISSUE THREAD

**Issue by danielfs** [GoogleCloudPlatform/google-cloud-go#885]
ERROR: (gcloud.app.deploy) Error Response: [9] Deployment contains files that cannot be compiled: Compile failed:
/work_dir/cloud.google.com/go/pubsub/go18.go:23: can't find import: "go.opencensus.io/plugin/grpc"
2018/02/06 11:03:41 go-app-builder: build timing: 91\xd7compile (41.107s total), 0\xd7link (0s total)
2018/02/06 11:03:41 go-app-builder: failed running compile: exit status 2

**Comment by zombiezen** [comment]
Sounds like you need to run `go get -u cloud.google.com/go/pubsub`.

**Comment by danielfs** [comment]
Thank you,

I just checkout v0.18.0 tag and it works.
