### ISSUE TITLE
BigQuery Destination table missing bug

### ISSUE THREAD

**Issue by arriqaaq** [GoogleCloudPlatform/google-cloud-go#887]
The latest build for bigquery always fails with the error saying that the destination table is missing. It is leading to a lot of errors in my project since migrating to the new build

I am running the bigquery client.query method

Sample code

package main

import (
	"cloud.google.com/go/bigquery"
	"golang.org/x/net/context"
	"log"
)

func main() {
	ctx := context.Background()
	client, err := bigquery.NewClient(ctx, "project-id")
	if err != nil {
		// TODO: Handle error.
		log.Println("error: ", err)
	}
	q := client.Query(`
		SELECT x,y,z 
		FROM [dataset]
`)
	_, rErr := q.Read(ctx)
	if rErr != nil {
		log.Println("read error: ", rErr)
	}
}

Please update on this

**Comment by jba** [comment]
There are two problems here. First, you can't select from a dataset, only from a table. So your query is wrong.

But the second problem is with the client: it should give you a better error message.

**Comment by tejasmanohar** [comment]
I think I'm still getting this error on master with the following code--
```
	var query = fmt.Sprintf("select count(x) from `%s` where %s", table, or("x", ids))
	var count int

	job, err := bq.client.Query(query).Run(ctx)
	if err != nil {
		return -1, err
	}

	iter, err := job.Read(ctx)
	if err != nil {
		fmt.Println("HERE IS THE ERROR", err)
		return -1, err
	}

	return count, iter.Next(&count)
```

How does the aforementioned commit https://github.com/GoogleCloudPlatform/google-cloud-go/commit/3ca7117cd4a26d5af7b7f8f841e17a3be49f5f7c fix it? Is it pushed to "cloud.google.com/go/"?

**Comment by jba** [comment]
Yes, the fix is at head.

I can't replicate from the information given. Can you provide a more complete example?

By the way, you can use `Query.Read` instead of `Query.Run` followed by `Job.Read`.

**Comment by jadekler** [comment]
When I run that against HEAD I get,

```
panic: googleapi: Error 400: Syntax error: Unexpected "[" at [3:10]. If this is a table identifier, escape the name with `, e.g. `table.name` rather than [table.name]., invalidQuery
```

Changing the name to `bigquerypublicdata` gives,

```
panic: googleapi: Error 400: Table name "bigquerypublicdata" cannot be resolved: dataset name is missing., invalid
```

**Comment by kecbigmt** [comment]
I solved my issue.
I got `bigquery: query job missing destination table` because my local SDK version was old.

In latest SDK, you got `panic: googleapi: Error 400: Syntax error: Unexpected "[" at [3:10]. If this is a table identifier, escape the name with `, e.g. `table.name` rather than [table.name]., invalidQuery` as @jadekler mentioned.

You should write query by Standard SQL instead of Legacy SQL. [godoc example](cloud.google.com/go/bigquery) is old.
This example should work fine.

```go
package main

import (
  "fmt"
  "log"
  "context"

  "google.golang.org/api/iterator"
  "cloud.google.com/go/bigquery"
)

func main(){
  ctx := context.Background()
  client, err := bigquery.NewClient(ctx, "my-project")
  if err != nil {
    log.Fatal(err)
  }
  q := client.Query("SELECT year, SUM(number) as num FROM `bigquery-public-data.usa_names.usa_1910_2013` WHERE name = 'William' GROUP BY year ORDER BY year")
  it, err := q.Read(ctx)
  if err != nil {
      log.Fatal(err)
  }
  for {
    var values []bigquery.Value
    err := it.Next(&values)
    if err == iterator.Done {
        break
    }
    if err != nil {
        log.Fatal(err)
    }
    fmt.Println(values)
  }
}
```

**Comment by alixhami** [comment]
As @kecbigmt mentioned, the sample is written using Legacy SQL instead of Standard SQL and needs to be updated because the library defaults to Standard SQL.

@shollyman can you update?

**Comment by shollyman** [comment]
Sure, I'll update these as I work through my backlog of items for the bigquery client.

**Comment by Lyon555** [comment]
Churr
