### ISSUE TITLE
Storage returns un-exported error when a bucket already exists

### ISSUE THREAD

**Issue by jimmiebtlr** [GoogleCloudPlatform/google-cloud-go#894]
Right now I have
```
bkt := client.Bucket(someBucket)
err := bkt.Create(ctx, projectID, nil)
if err != nil && !strings.Contains(err.Error(), "409") {
  // Handle real error
}
```

It would be much less brittle, and much nicer in general to be able to write something like
```
bkt := client.Bucket(someBucket)
err := bkt.Create(ctx, projectID, nil)
if err != nil && err != storage.ErrConflict {
  // Handle real error
}
```

Or `bkt.Exists(someBucket)`

Is there already a way to handle this?  Why are errors not exported?

**Comment by jadekler** [comment]
Hi @jimmiebtlr, our errors are standardized using https://godoc.org/google.golang.org/api/googleapi and you can use http status codes to categorize error types. For your given code, you could do the following:

```
bkt := client.Bucket(someBucket)
err := bkt.Create(ctx, projectID, nil)
if err2, ok := err.(*googleapi.Error); ok {
	if err2.Code == http.StatusConflict {
		// Handle conflict
	}
} else {
	// Handle err
}
```

**Comment by jimmiebtlr** [comment]
Thanks

**Comment by jimmiebtlr** [comment]
Definitely better than what I had.  I'm still not a fan of this though. 

Would something along the lines of this be better?
```
bkt := client.Bucket(someBucket)
err := bkt.Create(ctx, projectID, nil)
if err != nil && err != gcloud.ErrConflict {
  // handle it
}
```

The current way of handling it seems much more complex than it needs to be?

**Comment by jba** [comment]
I agree that the errors are not ideal. Aside from breaking compatibility, the reason your idea won't work is that the errors have more than just the HTTP status code. For one thing, they have the body of the result, which often contains useful information.
