### ISSUE TITLE
Implement SampleRowKeys in Bigtable client

### ISSUE THREAD

**Issue by garye** [GoogleCloudPlatform/google-cloud-go#896]
https://github.com/googleapis/googleapis/blob/546d3afd75187e65229a2670eb440e84a05f5d9d/google/bigtable/v2/bigtable.proto#L47

**Comment by sduskis** [comment]
This was fixed by [this commit](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/05c3c4174a1635eb36ecaf5be861bb514d513dbe).
