### ISSUE TITLE
Bigquery: query read try's to create a table?

### ISSUE THREAD

**Issue by jimmiebtlr** [GoogleCloudPlatform/google-cloud-go#897]
Very lost.  Why does a read result in what appears to be an attempt to create a table? (Table already exists... I'm trying to query it...)

```
queryStr := "SELECT [greet] FROM '" + dataset + "." + table + "`"

q := client.Query(queryStr)
q.DryRun = true
q.Dst = client.Dataset(dataset).Table(table)
_, err := q.Read(ctx)
if err != nil {
  fmt.Println("Error? ", err)
}
```

```
Error?  googleapi: Error 409: Already Exists: Table real_pid:ds.tablename, duplicate
```

**Comment by jba** [comment]
The destination table (`Dst`) is where the result is materialized, not the table you're reading. I'd suggest not setting it.

**Comment by jimmiebtlr** [comment]
I'm getting a 404 when I don't set that.

**Comment by jimmiebtlr** [comment]
Actually I am not now, sorry.  Thanks for the help.
