### ISSUE TITLE
Bigtable: Add opencensus spans to retries and auth token retrieval

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/google-cloud-go#898]
[Here's an example of using CBT with opencensus](https://github.com/maksharma/google-cloud-go/pull/2).

If users have problems, it would be great to get more information about how retries and auth token retrieval affect performance.  Adding opencensus spans around those items would be really useful.

**Comment by garye** [comment]
I think auth token retrieval is under the covers in gRPC and may not be possible to instrument with opencensus. Certainly retries could be since they are in our control, and I'd also like to see information in spans that show how many items we are sending in an `ApplyBulk` operation.

**Comment by maksharma** [comment]
[The change](https://code-review.googlesource.com/#/c/gocloud/+/24530/) to add annotation to `ReadRowsResponse` is being reviewed.

[This](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/92094f9a1ea4bed2d441d9278154d2580b21e132#diff-37c5fcab0ce692b50ec93dc86e7a09d3R665) has the count for the number of rows sent in `ApplyBulk`, which should be the same as the number of mutations. Please correct me if I am wrong about it.

**Comment by sduskis** [comment]
We did the best we could with this issue.  Closing it for now, since the rest of the work is not specific to CBT.
