### ISSUE TITLE
[Feature Request] Compute Instance Group Support

### ISSUE THREAD

**Issue by ericuldall** [GoogleCloudPlatform/google-cloud-go#899]
I'm currently looking for the best way to make changes to Instance Groups. Specifically trying to adjust autoscale settings (min, max, cpu, etc..).

Is this library going to support that or is there another option currently?

**Comment by jba** [comment]
The package [google.golang.org/api/compute/v1](https://godoc.org/google.golang.org/api/compute/v1) is currently the best client for GCE. It appears to support Instance Group operations.

**Comment by ericuldall** [comment]
Thank you.
