### ISSUE TITLE
Doc error on where Stackdriver logs show up

### ISSUE THREAD

**Issue by jeffmendoza** [GoogleCloudPlatform/google-cloud-go#900]
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/c250784705d8fa9884d3a1de0a716661e04b14f0/logging/doc.go#L111

This line is only correct for running outside of GCP. When running the example code from a VM the logs show up under "GCE VM Instance"

**Comment by jba** [comment]
Thanks for noticing that. See https://code-review.googlesource.com/#/c/gocloud/+/23590.
