### ISSUE TITLE
pubsub/pstest: server re-delivers outstanding messages

### ISSUE THREAD

**Issue by sivtsov** [GoogleCloudPlatform/google-cloud-go#903]
I've been using pstest and noticed that `Receive` keeps invoking callbacks on the same messages over and over again.

The easiest way to reproduce this is to change [this test](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/pstest_test.go#L67) a little: increase maximum count to, say, 20, and log message content. You'll notice that after counter reaches 10, messages will keep repeating, even though they've been ACKed.

First I thought that it is OK behaviour for at-least-once delivery, but it seems that pstest server just keeps re-delivering outstanding messages even if ACK deadline has not passed. I've added simple check [here](https://github.com/sivtsov/google-cloud-go/commit/4f8dcd930c96b5d733d3709a762e2d63f1beb44e), and it fixed this behaviour.

**Comment by jba** [comment]
Thanks, that is exactly the right fix. See https://code-review.googlesource.com/#/c/gocloud/+/24670.

And thanks for using `pstest`. Suggestions and contributions welcome.
