### ISSUE TITLE
Does go 1.6 truly need to be supported?

### ISSUE THREAD

**Issue by aalexand** [GoogleCloudPlatform/google-cloud-go#904]
I had a commit that broke go 1.6 continuous build: https://travis-ci.org/GoogleCloudPlatform/google-cloud-go/jobs/344163872. The breakage is because of using `run()` function on `testing.T` type which is not in go 1.6. While I can fix this, I was wondering whether it could be considered to drop the support for go 1.6?

**Comment by broady** [comment]
Yes, please. We want to support it as long as it's available/used on GAE
standard.

If you want to know more why, I can refer you to an internal email
thread/meeting where we decided this.

/cc @zombiezen

**Comment by aalexand** [comment]
That's fine, I'll just fix the code. Wanted to check if there is a low-hanging fruit here.
