### ISSUE TITLE
firestore: Handle protobuf Timestamp directly

### ISSUE THREAD

**Issue by Kunde21** [GoogleCloudPlatform/google-cloud-go#906]
When using protobuf message definitions, any Timestamp fields must be converted to `time.Time` in order for firestore to properly identify them as times.  The value is then converted right back to Timestamp proto type.  

Adding a way to directly handle protobuf Timestamp without the conversions would allow the compiled proto structs to be passed directly into firestore without timestamp fields mis-handled as structs.

**Comment by jba** [comment]
Your [CL](https://code-review.googlesource.com/c/gocloud/+/24190) is under review.

**Comment by Kunde21** [comment]
Merged in 49597cd and dbeaabb
