### ISSUE TITLE
pubsub: Inconsistent throughput/acks

### ISSUE THREAD

**Issue by arbarlow** [GoogleCloudPlatform/google-cloud-go#907]
I have a project where I regularly (a couple of times a day) use pubsub to process a semi large (30,000) amount of messages that are then consumed in Go.

The consumer puts messages into a database but that could be quick and cloud be slow, the function is blocking, we Ack if success and just return if there is an error. We have left the receive settings and subscriber settings to their defaults.

This is my implementation of subscribing https://github.com/lileio/pubsub/blob/master/google/google.go

What I'm seeing is blocks of work happening, without errors but with distinct pauses in processing. Here are some stackdriver graphs..

<img width="655" alt="screen shot 2018-02-26 at 20 31 44" src="https://user-images.githubusercontent.com/106357/36693754-2fa3b610-1b34-11e8-843b-0326e6460374.png">
<img width="654" alt="screen shot 2018-02-26 at 20 31 49" src="https://user-images.githubusercontent.com/106357/36693757-3144e304-1b34-11e8-83da-b059feefcb63.png">
<img width="656" alt="screen shot 2018-02-26 at 20 31 53" src="https://user-images.githubusercontent.com/106357/36693758-32e2fdfe-1b34-11e8-81a5-4f1b531fba56.png">
<img width="652" alt="screen shot 2018-02-26 at 20 31 59" src="https://user-images.githubusercontent.com/106357/36693762-34b049a2-1b34-11e8-9589-d7b01f0c3fd5.png">

I also see no errors in the google cloud API console or our subscriber.

It would be useful if there is more documentation about how the flow rate works with the Go client etc also, but I'm at a loss as to why the client isn't pulling constantly.

**Comment by arbarlow** [comment]
I should note, if you want to go through it on the project itself over call or similar, I'm happy to go help.

**Comment by jadekler** [comment]
Hi @arbarlow, thanks for the link - is it possible to see where you're handling these messages? I'd like to see the ack behavior.

Also, just as a note, you don't need to wrap `Receive` in a for loop. It blocks until ctx is done, or the service returns a non-retryable error.

**Comment by arbarlow** [comment]
@jadekler it's not open source, but I can post a snippet. Ah yes good point, I think I was planning to put an exponential backoff in there.

Effectively our code does this, which should be quick, but if the database is busy, could be ~30 seconds waiting for a transaction lock or similar

```
func (s *SomeSubscriber) Sync(ctx context.Context, r *service.Sync, _ *pubsub.Msg) error {
	if r.User == nil {
		return nil
	}

        // Proto user to DB user
	p, err := server.PBUserToDBUser(r.User)
	if err != nil {
		return err
	}

	return db.SyncUser(ctx, p)
}
```

It's important to note that if there is an error, we don't Ack or Nack. We just let it time out. However I can see from our metrics, that we aren't erroring.

I suspect that the client library isn't get a successful extension? That should be up to 10 minutes? Our whole operation of all the messages takes less than 10 minutes.

It's weird though that the client library isn't even sending a failed ack.

**Comment by jadekler** [comment]
So the graphs above seem to make sense to me. It looks as though you're getting `x` messages causing the flow controller to reach `MaxOutstandingMessages` and stop asking for more messages, then you ack `x` messages all around the same time, and then the flow controller asks for another batch of messages, and so on.

The default flow controller `MaxOutstandingMessages` is 1000. You can change the value with `Subscription.ReceiveSettings.MaxOutstandingMessages`; if you set it to -1, the flow control will be unlimited.

Does that answer your question, or is there another aspect of this that I can talk to?

**Comment by jba** [comment]
You might also try setting `MaxOutstandingMessages` to a smaller number. If each message results in a DB transaction, you might be contending with yourself. Start with 1 and ramp up to see if there's a sweet spot.

**Comment by arbarlow** [comment]
@jadekler @jba I'll do some more testing, but I think it would be suspicious that all my acks are at once. I might try to create a test case for you also.  If the client does error, what is the correct thing to do? Nack strait away? If the client can't process that message and there are few messages then that could result in an infinite loop quite quickly?

**Comment by jba** [comment]
What is the x axis for those graphs? E.g. how much time elapses between the first two peaks of "Streaming Pull Acknowledge Requests"?

If you have only one subscriber and it nacks, then yes, you'll see the same message again pretty soon thereafter. Depending on the error, you might sleep and retry, and/or publish it to another topic where you collect bad messages for later attempts or analysis. There is no feature that lets you publish or nack with a delay in (re-)delivery time.

**Comment by jba** [comment]
What is the x axis for those graphs? E.g. how much time elapses between the first two peaks of "Streaming Pull Acknowledge Requests"?

If you have only one subscriber and it nacks, then yes, you'll see the same message again pretty soon thereafter. Depending on the error, you might sleep and retry, and/or publish it to another topic where you collect bad messages for later attempts or analysis. There is no feature that lets you publish or nack with a delay in (re-)delivery time.

**Comment by jba** [comment]
You might want to log your ack calls:
```
Ack: func() {
        // log with a timestamp
	m.Ack()
}
```
Those times won't be perfectly accurate because we [batch acks into 100ms chunks](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/iterator.go#L64). If you don't mind editing our code, you could log [when we make the ack RPC](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/pullstream.go#L139).

**Comment by jba** [comment]
You might also want to take advantage of our OpenCensus integration for streaming pull, as described in [another issue](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/778#issuecomment-363571402).

**Comment by danoscarmike** [comment]
Hi @arbarlow, I'm going to close this issue due to inactivity.  If you're still experiencing this behavior please don't hesitate to raise it again. Thanks!
