### ISSUE TITLE
spanner: document how to use timestamps

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/google-cloud-go#910]
Timestamps should use `time.Time`, but it's not clear from the documentation. The general Spanner docs say to use a string in a particular format, but the Go type should not be a string since the client library handles the marshaling for you.

**Comment by jba** [comment]
It's documented at https://godoc.org/cloud.google.com/go/spanner#Row, but perhaps we can do better. Suggestions?

**Comment by tbpg** [comment]
Ah. I missed it. I searched for timestamp, but stopped too soon. So, I think this is OK to close as user error.
