### ISSUE TITLE
spanner: ToStruct fails silently if a timestamp field is a string

### ISSUE THREAD

**Issue by tbpg** [GoogleCloudPlatform/google-cloud-go#911]
It seems like when ToStruct fails to parse a field, it stops as soon as it hits that field. So, this means the order of fields when they're queried matters. I would expect `ToStruct` to return an error when this happens. If not an error, it should parse the remaining fields.

Basic example:

Schema:
```
CREATE TABLE MyTable (
	Id STRING(MAX) NOT NULL,
	Time TIMESTAMP,
) PRIMARY KEY (Id)
```

Go code:
```go
type MyType struct {
	Id string
	Time string // Note: This is wrong. It should be time.Time.
}
func query() {
	// ...
	iter := db.client.Single().Read(ctx, "MyTable", spanner.AllKeys(), []string{"Id", "Time"})
	// Id is not parsed with the following line:
	// iter := db.client.Single().Read(ctx, "MyTable", spanner.AllKeys(), []string{"Time", "Id"})

	defer iter.Stop()
	var values []*MyType
	for {
		row, err := iter.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return nil, err
		}
		var m MyType
		row.ToStruct(&m)
		values = append(values, &m)
	}
	// ...
}
```

**Comment by danoscarmike** [comment]
@tbpg it has been a while since this was submitted. Are you still experiencing the issue?

@jba is this a bug or a feature request?

**Comment by jba** [comment]
Investigating now.

**Comment by jba** [comment]
I think `ToStruct` does return an error, you're just not checking it in the above code. I'll add some tests to make sure.

The order-dependence in the presence of an error is unfortunate, but I don't see how to get around it unless we do some allocation or duplicate a bunch of code. This being Go, one typically should ignore any value if the function that produced it returns an error; I'll change the doc for `ToStruct` to make that clear.

https://code-review.googlesource.com/#/c/gocloud/+/28751
