### ISSUE TITLE
spanner: confusing doc comment about iterators

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/google-cloud-go#912]
> Stop terminates the iteration. It should be called after every iteration.

https://godoc.org/cloud.google.com/go/spanner

Shouldn't it be called when you want to stop iterating, rather than after every iteration?

/cc @jba

**Comment by danoscarmike** [comment]
@jba can you have a pass at this? Is this really a bug?

**Comment by jba** [comment]
Made a CL.
