### ISSUE TITLE
pubsub: tuning PublishSettings.NumGoroutines

### ISSUE THREAD

**Issue by bits01** [GoogleCloudPlatform/google-cloud-go#914]
[Apologies if this is not the right forum to ask this type of questions. I am aware of the announce group but could not find any other discussion forum/mailing list where I can ask this question]

Q: If one does not set `PublishSettings.NumGoroutines` on a `Topic`, it seems to default to `25 * num_cpus`. To me this feels a bit excessive, in particular when an app process uses ~100 topics that it publishes to, some of which are a lot more active than others. I know that Go can handle lots of goroutines and from looking at my GAE Flex VM it doesn't look like memory is a problem. Should I just not be concerned about it? Any documents/recommendations on how to tune `PublishSettings.NumGoroutines`?

Thanks for your help.

**Comment by jba** [comment]
Good question.

The Go PubSub client is tuned for high throughput. If you don't need that throughput and are worried about the number of active goroutines, then set `NumGoroutines` to a smaller number, like 1. If your message throughput is not adequate, increase the number until it is.

You should also adjust `MaxOutstandingMessages` and `MaxOutstandingBytes` to give you the throughput you want. These also affect the number of goroutines in your program, because they affect how many concurrent calls to the `Receive` callback function, each in its own goroutine, are active at once.

**Comment by jba** [comment]
Ah, I missed that you were talking about the Publish side.

I can't comment about the latency, but your throughput will be much higher if you don't confirm each publish with `PublishResult.Get` before doing the next. (I don't have any evidence you're doing that, but I just want to make sure you're holding it right.) If you do want to confirm publishes, do it in bulk, perhaps in another goroutine, so you don't slow down publishing.

**Comment by bits01** [comment]
I currently do confirm each publish as it happens in the context of an incoming HTTP request and it's nice for the client to get feedback and not just "lie" that everything is OK, but I'm thinking of maybe changing that.
Does the publishing side re-try to publish a message if it can't talk to the server or under other failure conditions or is that left to the caller?

**Comment by jba** [comment]
If you're using the same pubsub client across all the requests, then you're fine. The publishes will be batched across requests, each `PublishResult.Get` will only pause its own request's goroutine.

We do retry the Publish RPC on retryable errors, up to `PublishSettings.Timeout`.

**Comment by bits01** [comment]
The discussion here has been very helpful, thanks a lot. Not the right format though, it doesn't feel right to abuse github issues to have a threaded conversation :(
Moving on to optimizing the receiving side now ...

One more question please: any plans for the library to expose some aggregated metrics, how long it takes to publish messages, number of failures (and types), etc.?

**Comment by jba** [comment]
> One more question please: any plans for the library to expose some aggregated metrics, how long it takes to publish messages, number of failures (and types), etc.?

We recently added some OpenCensus instrumentation for subscriptions, but not for publishing.
