### ISSUE TITLE
How to convert nullable type of field as manipulable type? 

### ISSUE THREAD

**Issue by Festum** [GoogleCloudPlatform/google-cloud-go#915]
Ex: 
```
type Foo struct {
	Boo           bigquery.Bool  `bigquery:"boo" json:"boo,omitempty"`
}
```
After read in to the struct. How do I use it as normal type `s.VisitStartTime==False`?

**Comment by jadekler** [comment]
Hi @Festum. Is your type `bigquery.NullBool`? I'm not sure that we have a `bigquery.Bool` type, but I'm fairly new to the project.

If `VisitStartTime` is `bigquery.NullBool` you should be able to do `s.VisitStartTime.Bool == false`.

**Comment by jba** [comment]
And before you use any `NullXXX` value, check the `Valid` field to make sure it doesn't represent a BigQuery Null.
