### ISSUE TITLE
datastore: ignoring time zones

### ISSUE THREAD

**Issue by kemics** [GoogleCloudPlatform/google-cloud-go#916]
Hello,

I am using datastore in my project and emulator to test it locally (https://cloud.google.com/datastore/docs/tools/datastore-emulator). And when I put some structure with UTC field and after that get it from datastore its zone becomes my local.

I checked the source code of `datastore` package and founds some test cases with time zone, for example:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/42f89745cc30769fe3ebaa7633ec13ab05bda051/datastore/datastore_test.go#L1290-L1296
And if I print `got` value before `got` and `want` comparison, for example here:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/42f89745cc30769fe3ebaa7633ec13ab05bda051/datastore/datastore_test.go#L1986
They will have different locations (because I am not in UTC zone), but the test will pass.

It happens because time fields are compared via this function:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/42f89745cc30769fe3ebaa7633ec13ab05bda051/internal/testutil/cmp.go#L40-L45
And I found no words about time comparison and that it ignores time zone, but it does, such simple example proves it:
```
package testutil

import (
	"time"
	"fmt"
)

func ExampleEqualTime() {
	date := time.Date(2017, time.April, 12, 0, 0, 0, 0, time.FixedZone("CUSTOM", -3720))
	fmt.Println(Equal(date, date.UTC()))

	// Output: true
}
```

So I am wondering if it is a bug or not really well-documented feature.
It matters because it is now a challenge to create a location agnostic tests.

It is really easy to reproduce such behaviour, f.e this example fails because my time zone is not UTC:
```
func ExamplePutAndGetTime() {
	client, err := datastore.NewClient(context.Background(), "sample1213")
	if err != nil {
		panic(err)
	}
	defer client.Close()

	type Event struct {
		Time time.Time
	}
	key := datastore.IDKey("Event", 1, nil)

	date := time.Date(2017, time.April, 12, 0, 0, 0, 0, time.UTC)

	_, err = client.Put(context.Background(), key, &Event{date})
	if err != nil {
		panic(err)
	}

	var got Event
	if err := client.Get(context.Background(), key, &got); err != nil {
		panic(err)
	}

	fmt.Println(got.Time)

	// Output: 2017-04-12 00:00:00 +0000 UTC
}
```

**Comment by jba** [comment]
You're right, The Datastore client returns the local time. I don't know if that is the ideal behavior, but I'm concerned that changing it would break too much existing code. Call `t.UTC()` on a time returned from Datastore to convert it to UTC.

**Comment by kemics** [comment]
Thank you for the quick reply,

I got it, its a feature.
Such a workaround can be used to ensure that time fields are UTC:
```
// Time is an attempt to ensure that time is in UTC.
type Time struct {
	time.Time
}

// Load creates structure and sets time zone to UTC.
func (t *Time) Load(ps []datastore.Property) error {
	if err := datastore.LoadStruct(t, ps); err != nil {
		return err
	}
	t.Time = t.UTC()
	return nil
}

// Save sets time zone to UTC and prepares properties.
func (t *Time) Save() ([]datastore.Property, error) {
	t.Time = t.UTC()
	return datastore.SaveStruct(t)
}
```

I believe that that it should be documented better because it is really hard to figure out that you can't rely on time zone.

**Comment by kemics** [comment]
I realize that this problem is not a big deal to change the library, but anyway we could create an option for the datastore client `option.ClientOption` and name it for example `Option.UseTimeZone(zone *time.Location)` to make datastore client set zone for time fields before return, this would enable to not break API and would solve the problem.

It matters to me because we hold only UTC and it is important not to forget about setting time zone.

**Comment by kf6nux** [comment]
> And I found no words about time comparison and that it ignores time zone, but it does, such simple example proves it

This is consistent with stdlib which is well documented here: https://golang.org/pkg/time/#Time.Equal

I would find it confusing if a library tried to redefine `time.Equal()`

**Comment by rustyx** [comment]
How is this not a defect? Timezone is an important piece of information of any _date/time_ field. Timezone is only unimportant for _timestamps_. We're not talking about timestamps here.
It does not matter that the point in time is equal, the _locality_ of it is also important in some cases and it's irreplaceable piece information just like hours or minutes, and it's just lost.

We are forced to abandon the idea of using Google Cloud DataStore due to this.

**Comment by tbpg** [comment]
It may not be the best behavior, but it's the current behavior of the package. Unfortunately, at this point, we can't change it since it may break existing code (see @jba's comment above).

It seems there is a workaround -- is there a particular reason that doesn't work?
