### ISSUE TITLE
storage: ObjectHandle should provide access to bucket/object or URL

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/google-cloud-go#917]
When writing functions that work with Cloud Storage, it would be useful to be able to get the URL or bucket/object for a `*storage.ObjectHandle`. Today, functions either need to take `(client *storage.Client, bucket string, object string)`, or call `ObjectHandle.Attrs()` and make a network request.

As a specific example, I am currently writing a function that uploads local data into BigQuery. My first attempt function signature was:

```go
func uploadCSVToBigQuery(tempObject *storage.ObjectHandle, localPath string, table *bigquery.Table) error
```

However, since I can't get the location for this object, I changed it to:

```go
func uploadCSVToBigQuery(gcs *storage.Client, bucket string, tempObject string, localPath string, table *bigquery.Table) error
```

## Proposal

Add `Bucket() string`, `Object() string`, and maybe also `URL() string` accessor functions to `ObjectHandle`. Other  types have similar accessors, such as `bigquery.Table.FullyQualifiedName()`

**Comment by jadekler** [comment]
https://code-review.googlesource.com/c/gocloud/+/32730
