### ISSUE TITLE
Authenticate using string instead of file

### ISSUE THREAD

**Issue by jimmiebtlr** [GoogleCloudPlatform/google-cloud-go#918]
Is it possible to authenticate using an already read in service account file?  From the docs, I'm only seeing default credentials and using a string for the filename.

Specifically, I'm trying to setup clients from more than one project for use in a single microservice.

**Comment by jba** [comment]
Not yet, but we are working on that.

**Comment by jba** [comment]
This is ready. Use like so:
```
creds, err := google.CredentialsFromJSON(ctx, jsonData, scope1, scope2)
if err != nil { ... }
opt := option.WithCredentials(creds)
```
where `google` is `golang.org/x/oauth2/google` and `option` is `google.golang.org/api/option`.
