### ISSUE TITLE
PubSub subscription.Receive stops receiving messages

### ISSUE THREAD

**Issue by ChrisBartonLC** [GoogleCloudPlatform/google-cloud-go#919]
Hi, we are having a problem where one of our subscriptions stops receiving messages with no errors reported. Other subscriptions in the same app continue to work but these are not heavily used. Is there anyway to debug the issue? We are considering adding a scheduled closing of the PubSub client and re-creating it as a workaround. We are using v0.19.0. Thanks in advance for any advice

**Comment by jba** [comment]
Does this happen with v0.18.0?

One way to debug would be to look at the OpenCensus instrumentation, described [here](https://github.com/GoogleCloudPlatform/google-cloud-go/issues/778#issuecomment-363571402). You could also add logging to the client to figure out what might be happening. A good place to start would be [`pullstream.go`](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/pullstream.go).

**Comment by ChrisBartonLC** [comment]
We never saw this with v0.18.0. I try those suggestions and maybe try downgrading to v0.18.0 as a test

**Comment by ChrisBartonLC** [comment]
Unfortunately downgrading is not attractive to us because we have stared using the mutate and pointer support in v0.19.0 so instead we are going to restart the pubsub client on a schedule

**Comment by ChrisBartonLC** [comment]
Is it related to gRpc version gRPC? See https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438#issuecomment-371659486

**Comment by jadekler** [comment]
Hi @ChrisBartonLC. Is your app running in GKE? Also, how long does your receive handler process before acking messages?

**Comment by jba** [comment]
Python/Node and Go use different gRPC codebases, so offhand I'd say they're not related.

We'll look carefully at the diffs between 0.18.0 and 0.19.0, but instrumentation or logging would help.

**Comment by ChrisBartonLC** [comment]
We are using Appengine Flex

**Comment by ChrisBartonLC** [comment]
Go 1.10

**Comment by ChrisBartonLC** [comment]
Stackdriver monitoring

![screen shot 2018-03-09 at 12 45 12 pm](https://user-images.githubusercontent.com/31261535/37182786-c6bc3822-2397-11e8-91e0-a2c9d0ba0e73.png)

**Comment by ChrisBartonLC** [comment]
No really sure how long things run. Messages arrive in batches and not very often so trying to determine whether it falls over when the batch arrives or sometime after. Yep I am tying to add logging to the PubSub library. 

Do you have anything similar to the environments variables used by gRPC when used from Node.js?

      process.env.GRPC_TRACE = 'tcp'
      process.env.GRPC_VERBOSITY = 'DEBUG'

**Comment by jadekler** [comment]
Yep, you can use `GRPC_GO_LOG_SEVERITY_LEVEL=info`.

**Comment by ChrisBartonLC** [comment]
thanks

**Comment by ChrisBartonLC** [comment]
Do I just set that as a Docker env variable?

**Comment by jadekler** [comment]
That should work, yes.

**Comment by ChrisBartonLC** [comment]
Well no luck, just see all our normal logs. We print the env on startup with os.Environ() and the variable is there

![screen shot 2018-03-09 at 4 52 39 pm](https://user-images.githubusercontent.com/31261535/37189672-6f475a72-23ba-11e8-995e-266052c83aa5.png)
![screen shot 2018-03-09 at 4 53 15 pm](https://user-images.githubusercontent.com/31261535/37189673-6f71dc02-23ba-11e8-863e-b2fcb3ba6ae0.png)

**Comment by jadekler** [comment]
Turns out I was wrong - I double checked, and it looks like for AppEngine there's a specific config you have to use: https://cloud.google.com/appengine/docs/flexible/nodejs/configuring-your-app-with-app-yaml#Node.js_app_yaml_Defining_environment_variables

Sorry! I did just check locally, and that environment variable should be the one:

<img width="823" alt="screen shot 2018-03-08 at 8 23 43 pm" src="https://user-images.githubusercontent.com/3584893/37190446-a4f12be6-230e-11e8-8220-46f3ac516a46.png">

(note the many INFO logs above)

Thanks for continuing to debug. By the way - as jba@ mentioned, putting some OpenCensus instrumentation in would help a lot. I'm wondering whether you're hitting the flow controller limits, since your messages come in batches and you're unsure how long it takes to process them. Instrumentation would give us a better idea of what's going on. If it is the flow controller, you can adjust `subscription.ReceiveSettings.MaxOutstandingMessages` and `subscription.ReceiveSettings.MaxOutstandingBytes`.

**Comment by ChrisBartonLC** [comment]
Actually my fault, I can see entires like this in the logs 'pickfirstBalancer' so it's fine just adding this to the dockerfile
ENV ENV=dev \
    GCP_PROJECT_ID=localcover-55 \
    DEBUG=true \
    GRPC_GO_LOG_SEVERITY_LEVEL=info

**Comment by ChrisBartonLC** [comment]
Today it happened in our dev env after a while where there only occasional messages. We deploy alot to dev and so it was chance we haven't do so for a while an could therefore see it (assuming it is related to running for a while)

We are most likely doing something wrong but in the off chance we aren't 

https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438
"Actually yes, there was one PR specifically (#2627) where we updated the gRPC version from 1.3 to 1.6 and started observing the gRPC channel state when opening streams."

**Comment by ChrisBartonLC** [comment]
BTW is the log attached normal?

![screen shot 2018-03-09 at 6 00 49 pm](https://user-images.githubusercontent.com/31261535/37191353-e09bf968-23c3-11e8-94f2-ab4508fa6bd5.png)

**Comment by ChrisBartonLC** [comment]
Well it probably is, it's only every few minutes or so

**Comment by ChrisBartonLC** [comment]
See attached, the app is happily pulling messages which are just returned to the queue because the conditions required for them to be ACK'ed are not met. Then the client suddenly stops receiving messages. Notice there are just 11 messages and they have been around for a while so this behaviour is not related to a sudden influx of messages. We still receive this in the logs every few minutes:

A  INFO: 2018/03/10 01:01:24 pickfirstBalancer: HandleSubConnStateChange: 0xc4203ac330, READY
A  INFO: 2018/03/10 01:01:24 pickfirstBalancer: HandleSubConnStateChange: 0xc4203ac330, CONNECTING
A  INFO: 2018/03/10 01:01:24 pickfirstBalancer: HandleSubConnStateChange: 0xc4203ac330, TRANSIENT_FAILURE

I've added opencensus now which will deploy and start message processing again and so next time the processing hangs I'll post an update. FYI the imports have changed from "https://gist.github.com/jba/08cff600886fc42f66af41471f1c2496" they are now:

    	"go.opencensus.io/exporter/stackdriver"
	"go.opencensus.io/plugin/ocgrpc/grpcstats"
	"go.opencensus.io/stats/view"
	"go.opencensus.io/trace"

![screen shot 2018-03-10 at 1 56 54 pm](https://user-images.githubusercontent.com/31261535/37236436-40536ce4-246c-11e8-9bc3-35b051ed676d.png)

**Comment by ChrisBartonLC** [comment]
This is the code I am using to gather the statistics:

	"go.opencensus.io/exporter/stackdriver"
	"go.opencensus.io/plugin/ocgrpc/grpcstats"
	"go.opencensus.io/stats/view"
	"go.opencensus.io/trace"

    	// See https://github.com/GoogleCloudPlatform/golang-samples/blob/master/opencensus/opencensus_spanner_quickstart/main.go
	stackdriverExporter, err := stackdriver.NewExporter(stackdriver.Options{ProjectID: os.Getenv("GCP_PROJECT_ID")})
	if err != nil {
		share_log.Logger.Fatal(ctx, "Failed initializing statistics - opencensus", share_log.Logger.FmtError(err))
	}
	view.RegisterExporter(stackdriverExporter)
	trace.RegisterExporter(stackdriverExporter)
	for _, v := range []*view.View{
		grpcstats.RPCClientRequestCountView,
		grpcstats.RPCClientErrorCountView,
		pubsub.PullCountView,
		pubsub.AckCountView,
		pubsub.NackCountView,
		pubsub.ModAckCountView,
		pubsub.StreamOpenCountView,
		pubsub.StreamRetryCountView,
		pubsub.StreamRequestCountView,
		pubsub.StreamResponseCountView,
	} {
		if err := v.Subscribe(); err != nil {
			log.Fatal(err)
		}
		log.Printf("subscribed to %s", v.Name())
	}
	share_log.Logger.Info(ctx, "Initialized statistics - opencensus")

**Comment by ChrisBartonLC** [comment]
and this is how we create the subscription:

    	subscription, err := pusubClient.CreateSubscription(ctx, SubscriptionOrderProvision, pubsub.SubscriptionConfig{Topic: topicOrderProvision, AckDeadline: share_pubsub.SubscriptionDefaultAckDeadline})
	if err != nil {
		log.Logger.Info(ctx, "Ignoring error from 'pusubClient.CreateSubscription'. We will always get 'already exists', if there are other fatal errors then the first use will fail and errors can be handled there")

		subscription = pusubClient.Subscription(SubscriptionOrderProvision)
		if subscription == nil {
			return nil, errors.Wrap(err, "Failed getting reference to subscription after subscription creation failed")
		}
	}

	// Implement a 'delay requeue', see comments @share_pubsub.SubscriptionReceiveSettingsMaxExtension
	subscription.ReceiveSettings.MaxExtension = share_pubsub.SubscriptionReceiveSettingsMaxExtension

**Comment by ChrisBartonLC** [comment]
I wonder if it is something to do with "subscription.ReceiveSettings.MaxExtension" because we set this to 1 sec in order to disable the auto extending of the lease? We don't want the lease extended, we want to use AckDeadline.

**Comment by ChrisBartonLC** [comment]
OK failed quite quickly this time. What data do you need in addition to that attached? 

![screen shot 2018-03-10 at 6 39 40 pm](https://user-images.githubusercontent.com/31261535/37238775-7e311ae0-2492-11e8-8665-10e8b862ebdd.png)
![screen shot 2018-03-10 at 6 40 02 pm](https://user-images.githubusercontent.com/31261535/37238776-7e608d2a-2492-11e8-9b43-a5b550cf602e.png)

**Comment by ChrisBartonLC** [comment]
BTW we have two other environments which have the same deployment. These environments are still working. The difference between these environments and the one that fails is that they do not have unacknowledged messages. These other environments have exhibited the same behaviour in the past, perhaps because at that time they had unacknowledged messages?

**Comment by ChrisBartonLC** [comment]
FYI there are two instances active in the environment that failed but other environments with one instance also fail, as mentioned above. This is a worker model.

**Comment by ChrisBartonLC** [comment]
Additional data showing retry also failing for both instances

![screen shot 2018-03-10 at 7 34 27 pm](https://user-images.githubusercontent.com/31261535/37239101-176d758a-249a-11e8-8ecf-b2630bdbaee2.png)

**Comment by jba** [comment]
Thank you for looking into this so thoroughly.

Looking at the diffs, pretty much the only change to pubsub between v0.18.0 and v0.19.0 was changing the flow control behavior. In v0.19.0 we only release the flow controller when Ack or Nack is called. I think the data is consistent with your application failing to ack/nack occasionally. The flow controller becomes saturated, no new messages are processed, and we stop calling Recv to get more messages (so stream_response_count goes to zero). The presence of unacknowledged messages is a symptom, not the underlying cause. I'm going to guess that those particular messages make you follow some code path that calls neither Ack or Nack.

We can test that by turning off flow control: set both MaxOutstanding fields to -1 and see if messages still get stuck.

Another theory is that you take too long to ack those messages, so they are resent, and this keeps happening. But if the same code was running fine on v0.18.0, that doesn't seem likely.

Some miscellaneous remarks:

- It's hard to interpret stream_retry_count as a rate; displaying it as a simple count might be clearer. (Setting Aggregation to none on the StackDriver graph for the metric should do it, I think.) At this point, I don't think stream re-openings are a factor.

- Your code looks correct, but you don't need the nil check on the 5th line: Client.Subscription will never return nil.

**Comment by ChrisBartonLC** [comment]
Thanks very much for the help. Yes we don't call Ack or Nack, sometimes for extended periods, let me explain... We process orders and some orders from some clients arrive in batches where there is a business rules that all or none must be processed. Each order is independently assessed against a set of criteria and can pass or fail. If all orders pass, the batch of orders is accepted. If an order fails we Ack it, if an order passes we don't Ack it until all orders in the batch pass. In order to avoid being swapped by Nack'ed messages being redelivered we don't Nack and instead rely on the lease expiry. This is basically simulating a delay queue. In addition we have orders involving items we have not seen before and in these cases we have some manual configuration work to do before they can be Ack'ed (subsequent orders involving the same items are automatically recognized and can be Ack'ed depending on batch rules). Once again if we Nack these orders there are immediately re-delivered in milliseconds and just swap us. Again we rely of the lease expiry to simulate a delay queue. Is there a better way to achieve our requirements without writing a lot of code because our current design is simple and works well, from a logical point of view at least?

**Comment by jba** [comment]
You are not alone in trying to use PubSub as a task queue. For your next version, you might consider our Task Queues API; you can sign up for the alpha at https://goo.gl/Ya0AZd.

For now, you can return to the v0.18.0 behavior by setting both MaxOutstanding parameters to -1, and using your own flow control. Our [flow controller](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/pubsub/flow_controller.go) uses two [weighted semaphores](https://godoc.org/golang.org/x/sync/semaphore), one for the count and one for the size. You may only need one, in which case the code change is only three or four lines: create the semaphore before calling Receive, acquire at the start of the callback, then defer the release. You will then be gated by the number of active callbacks, not the number of unacked messages, just like v0.18.0.

**Comment by ChrisBartonLC** [comment]
Ok thanks I have signed up and thanks for the information

**Comment by ChrisBartonLC** [comment]
Well we have implemented those changes but now we have a 10 min wait after a message is not ack'ed or nack'ed.

See below. 2 messages are published for processing. The consumer reads the first and processes it but deliberately doesn't Ack or Nack it because it is part of a batch. The consumer reads the second and processes and not because all other members of the batch have been processed it Ack'ed it. We expect the first message to be redelivered when its lease expires which is 60seconds however instead the consumer sees it 10minutes later.

----------
PUBLISH

2018-03-14 04:01:46.073 UTC
d0b2f3f9-8c07-42ac-9758-8e6ff7aa7fa6 # Published message # lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub.PublishMessages 113 /root/project/src/lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub/pubsub.go
-> { "topic": "projects/localcover-55/topics/lc-api-cover_order_provision", "messageID": "54757284444918" }

2018-03-14 04:01:46.073 UTC
d0b2f3f9-8c07-42ac-9758-8e6ff7aa7fa6 # Published message # lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub.PublishMessages 113 /root/project/src/lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub/pubsub.go
-> { "topic": "projects/localcover-55/topics/lc-api-cover_order_provision", "messageID": "54757284444917" }
----------


----------
RECEIVE 1

2018-03-14 04:01:46.485 UTC
baad03f6-f877-440f-9b65-6e45d53f4aaf;d0b2f3f9-8c07-42ac-9758-8e6ff7aa7fa6 # Received pubsub message # lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub.Unmarshal 140 /root/project/src/lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub/pubsub.go
-> { "topic": "lc-api-cover_order_provision", "subscription": "projects/localcover-55/subscriptions/lc-api-cover_order_provision_lc-api-cover", "msg.ID": "54757284444918", "msg.PublishTime": "2018-03-14T04:01:46Z", "dst": {"src":"lc-api-cover","order_id":"6b87a720-ef32-4258-bea6-d23e8207ba8c"} }

FAILS
2018-03-14 04:01:46.841 UTC
baad03f6-f877-440f-9b65-6e45d53f4aaf;d0b2f3f9-8c07-42ac-9758-8e6ff7aa7fa6 # Failed to process cover order due to order part of batch with orders still in-progress and merchant wants all orders processed or none, processing attempts will continue until all orders in the batch complete processing, one order in the batch is rejected or the message expires # lc-api-cover/event.(*ListenerOrderProvision).Subscribe.func1 105 /root/project/src/lc-api-cover/event/listener_order_provision.go
----------

----------
RECEIVE 2

2018-03-14 04:01:46.841 UTC
016eec22-b696-4ee3-9971-ba713ec1b2ee;d0b2f3f9-8c07-42ac-9758-8e6ff7aa7fa6 # Received pubsub message # lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub.Unmarshal 140 /root/project/src/lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub/pubsub.go
-> { "topic": "lc-api-cover_order_provision", "subscription": "projects/localcover-55/subscriptions/lc-api-cover_order_provision_lc-api-cover", "msg.ID": "54757284444917", "msg.PublishTime": "2018-03-14T04:01:46Z", "dst": {"src":"lc-api-cover","order_id":"e69f7900-7c4b-4756-8427-8983a6fadf55"} }

SUCCEEDS
2018-03-14 04:01:47.512 UTC
016eec22-b696-4ee3-9971-ba713ec1b2ee;d0b2f3f9-8c07-42ac-9758-8e6ff7aa7fa6 # Published message # lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub.PublishMessage 74 /root/project/src/lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub/pubsub.go
----------

----------
RECEIVE 3

2018-03-14 04:12:22.452 UTC
9fd03285-2eac-4408-89ac-bd20c1ab671c;d0b2f3f9-8c07-42ac-9758-8e6ff7aa7fa6 # Received pubsub message # lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub.Unmarshal 140 /root/project/src/lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub/pubsub.go
-> { "topic": "lc-api-cover_order_provision", "subscription": "projects/localcover-55/subscriptions/lc-api-cover_order_provision_lc-api-cover", "msg.ID": "54757284444918", "msg.PublishTime": "2018-03-14T04:01:46Z", "dst": {"src":"lc-api-cover","order_id":"6b87a720-ef32-4258-bea6-d23e8207ba8c"} }

SUCCEEDS
2018-03-14 04:12:22.861 UTC
9fd03285-2eac-4408-89ac-bd20c1ab671c;d0b2f3f9-8c07-42ac-9758-8e6ff7aa7fa6 # Published message # lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub.PublishMessage 74 /root/project/src/lc-api-cover/vendor/github.com/localcover/lc-lib-share/pubsub/pubsub.go
----------

**Comment by ChrisBartonLC** [comment]
Our code is basically:

    pusubClient.CreateSubscription(...
    ...
    subscription.ReceiveSettings.MaxExtension = 0
    subscription.ReceiveSettings.MaxOutstandingMessages = -1
    ...
    	flowControl := semaphore.NewWeighted(int64(ConcurrentMsgCount))

	if err := l.subscription.Receive(...) {
		ctx := context.WithValue(ctxMsg, share_context.CorrelationIDContextKey, uuid.New().String())

		if err := flowControl.Acquire(ctx, 1); err != nil {
			log.Logger.Error(ctx, "Failed acquiring flow control", log.Logger.FmtError(err))
		}
		defer flowControl.Release(1)
                ...

**Comment by ChrisBartonLC** [comment]
FYI or subscriptions showing their ack deadlines

![screen shot 2018-03-14 at 6 25 13 pm](https://user-images.githubusercontent.com/31261535/37384710-3dcaf022-27b5-11e8-884b-6ae00c7014c6.png)

**Comment by jba** [comment]
Apologies. The doc is wrong. Set `MaxExtension` to -1 instead of 0.

**Comment by ChrisBartonLC** [comment]
Thanks, super fast now :)

**Comment by jba** [comment]
Yay!

**Comment by jba** [comment]
@lc-chrisbarton: The pubsub client now supports a synchronous mode that may make more sense for your use case. See #1088 and https://godoc.org/cloud.google.com/go/pubsub#ReceiveSettings.Synchronous.

**Comment by lc-chrisbarton** [comment]
Thanks very much :)
