### ISSUE TITLE
Datastore: v0.19.0 support nil bool values

### ISSUE THREAD

**Issue by lc-chrisbarton** [GoogleCloudPlatform/google-cloud-go#920]
We only want to set an Agreed bool to true or false after a user has agreed or disagreed and if neither has happened we want the field null in datastore i.e. omitted. Since v0.19.0 this kind of use case works for strings and numbers but doesn't seem to work for bool.

**Comment by jba** [comment]
Are you using `NullBool` to represent the nullable boolean?

**Comment by ChrisBartonLC** [comment]
we use *bool, is that incorrect?

**Comment by CaiGwatkinLC** [comment]
We were expecting *bool to work after the v0.19.0 release which introduced "Support pointer struct fields."

**Comment by jba** [comment]
That's a slightly different feature. You need `NullXXX` for a nullable basic type (string, bool, int, float, etc.).

**Comment by ChrisBartonLC** [comment]
Thanks we'll do that

**Comment by CaiGwatkinLC** [comment]
After attempting to implement this, I still don't quite understand. First of all, I couldn't find the `NullXXX` types (such as `NullBool`). I noticed other packages, such as BigQuery, have that stored in a `nulls.go` file, but that doesn't appear to exist in the datastore package.

My solution to this was to use a pointer to a primitive type without the `omitempty` flag in the datastore portion of the flags, which does work. However, this was not immediately obvious as I am used to how the `omitempty` flag affects pointers when using the built-in go JSON package.

I believe datastore handles pointers to primitive types with `omitempty` flag in an unexpected way when compared to JSON encoding/decoding in go. Please let me know if it's just a user error!

Take the following structure:

```go
type SomeStruct struct {
	OmitEmpty    *bool `json:"omit_empty,omitempty" datastore:"omit_empty,omitempty"`
	PersistEmpty *bool `json:"persist_empty" datastore:"persist_empty"`
}
```

With the following go instantiation:

```go
someZeroValue := false
someStruct := SomeStruct{
	OmitEmpty:    &someZeroValue,
	PersistEmpty: &someZeroValue,
}
```

When saving that object to datastore, the resulting entity would have the following values:

```json
{
	"persist_empty": false
}
```

Conversely, when sending that structure in a JSON encoded response, the blob contains:

```json
{
	"omit_empty": false,
	"persist_empty": false
}
```

Seeing as the datastore package uses the same flag `omitempty` as the built-in go JSON package, I made the assumption that properties flagged with `omitempty` would be treated the same as in the JSON package.

**Comment by jba** [comment]
My apologies: in Datastore you do use pointers, not NullXXX types.

I'll look into the omitempty issue shortly.

**Comment by jba** [comment]
Sorry this took us so long. You're quite right, this behavior is inconsistent with `encoding/json` and it is incorrect. Fix coming.
