### ISSUE TITLE
spanner: (*Row).ToStruct(p) fails if p does not cover all column names

### ISSUE THREAD

**Issue by lhecker** [GoogleCloudPlatform/google-cloud-go#924]
The documentation for `(*Row).ToStruct(p)` is not incorrect, but it does make it seem like `p` can cover a subset of the columns requested in a query:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/171fbd8d179037ae0a6670719b65dd7c5d11455d/spanner/row.go#L282-L283

But if you do a
```sql
SELECT a, b, c FROM ...
```
and you passed in a struct of e.g. type
```go
type P struct {
    A string `spanner:"a"`
    B string `spanner:"b"`
}
```
this will fail with an error like:
```
spanner: code = "InvalidArgument", desc = "Go struct &{A: B: }(type *P) has no or duplicate fields for Cloud Spanner STRUCT field c"
```

Can you please either change the documentation to state that behaviour clearly or possibly even change the behaviour itself? In my personal opinion it's not necessary at all for `ToStruct` to enforce the existence of the struct fields. 🙂

**Comment by jba** [comment]
@vkedia Should we change the behavior to allow structs to omit fields? My main concern is data loss on round trip.

**Comment by vkedia** [comment]
I agree. The current behavior is safer. We can just fix the documentation.

**Comment by lhecker** [comment]
> We can just fix the documentation.

That's fine for me. 🙂

<details>
<summary>On a side note...</summary>
It would be awesome if the official Spanner documentation had a "warning" section of sorts at the beginning. I once was quite badly tripped up by the fact that you can't change the length limit of primary key columns (which is unusual compared to other DBs), because I missed to read that one bullet point down <a href="https://cloud.google.com/spanner/docs/schema-and-data-model#supported_schema_updates">here</a> at the beginning. 😕
</details>

**Comment by ashoda** [comment]
This would be pretty helpful especially during schema migrations where a new deployment adds a new column that a currently running server doesn't handle. Would it be possible to add another method to make opting into this behavior more explicit?

@lhecker, how'd you end up get around this?

This is along the lines of what we're doing as an initial cut. The following would need to be deployed before a second deployment with the schema migration (adding column `c`) is deployed.

```go
type Model struct {
  A string `spanner:"a"`
  B string `spanner:"b"`
}

type spannerRecord struct {
  *Model
  C string `spanner:"c"`
}

func (m *Model) ScanRow(src *spanner.Row) {
    record := spannerRecord { Model: m }
    row.ToStruct(&record)
}
```

**Comment by lhecker** [comment]
@ashoda By explicitly stating all requested fields in SQL queries (e.g. `SELECT a, b, c` instead of `SELECT *`).

**Comment by jon-whit** [comment]
I'm having a similar issue here and could use some help.. I have a permissions table in Spanner that looks like this:

```
definition | description | only_in_predefined_roles
iam.roles.create | Create a role for your organization. | True
```

In Go I have a struct for this model:
```
  type Permission struct {
          // The string representation of this Permission.
          Definition string `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"`
          // A brief description of what this Permission is used for.
          Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
          // This permission can ONLY be used in predefined roles.
          OnlyInPredefinedRoles bool     `protobuf:"varint,4,opt,name=only_in_predefined_roles,json=onlyInPredefinedRoles,proto3" json:"only_in_predefined_roles,omitempty"`
  }
```

I get an error when running this code:
```
 func (db *SpannerDB) ListPermissions() ([]*pb.Permission, error) {
         stmt := spanner.NewStatement("SELECT definition, description, only_in_predefined_roles FROM iam_permissions")
 
         ctx := context.Background()
         iter := db.Single().Query(ctx, stmt)
         defer iter.Stop()
 
         permissions := make([]*pb.Permission, 0)
         for {
                 row, err := iter.Next()
                 if err == iterator.Done {
                         break
                 }
                 if err != nil {
                         return nil, err 
                 }
 
                 permission := pb.Permission{}
                 if err := row.ToStruct(&permission); err != nil {
                         return nil, err 
                 }
 
                 permissions = append(permissions, &permission)
         }
 
         return permissions, nil 
}
```

What am I doing wrong here?

**Comment by jba** [comment]
Just glancing at your code, it looks like your column name is `only_in_predefined_roles` and the struct field name is `OnlyInPredefinedRoles`. As the [documentation for Row.ToStruct](https://godoc.org/cloud.google.com/go/spanner#Row.ToStruct) says, in the absence of a `spanner` tag the column and field names must be equal ignoring case. Those names aren't.

**Comment by jba** [comment]
Oh, perhaps you thought the `name` field in the `protobuf` tag would be used? The spanner client ignores all tags except the one named `spanner`.

**Comment by jon-whit** [comment]
@jba Yeah, I was assuming the `name` field in the protobuf tag was the one being used. The documentation uses the word name without clarification. I'd suggest updating the documentation to make it more clear.
