### ISSUE TITLE
pubsub: simplify initial error return from topic.Publish

### ISSUE THREAD

**Issue by bits01** [GoogleCloudPlatform/google-cloud-go#925]
When a message is published via `topic.Publish` there can be an immediate error which can occur if the message cannot be queued up. The code that handles it looks something like this:
```
result := topic.Publish(ctx, &pubsub.Message{Data: data, Attributes: attrs})
		
select {
case <-result.Ready():
	if _, err := result.Get(ctx); err != nil {
		// log, metric, or do something here
		return err
	}
default:
}
```

Could it be simplified so that `topic.Publish` returns `(result, error)` where error is immediately available if something went wrong during the `topic.Publish` call?

I realize this is an API breaking change, but perhaps now's the time to do it given the 0.x version of the lib.

**Comment by jba** [comment]
Adding an error return would simplify your code, but in the general case when one doesn't care whether the error was immediate or not, it would make things more complicated, and probably confuse people.
