### ISSUE TITLE
Unmarshal from bigquery can't handle pointers in destination struct

### ISSUE THREAD

**Issue by jimmiebtlr** [GoogleCloudPlatform/google-cloud-go#927]
When requesting from bigquery using a struct with a pointer in it.

I get something like the following back

```
someField of type STRING is not assignable to struct field SomeField of type *string
```

I'd like to be able to unmarshal optional fields into *fieldType, rather than needing to have every field in the struct non-pointers.

**Comment by jba** [comment]
Use the `NullXXX` types to represent optional fields.
