### ISSUE TITLE
Not able to implement ValueSaver with a Record field

### ISSUE THREAD

**Issue by jimmiebtlr** [GoogleCloudPlatform/google-cloud-go#929]
Probably missing something in the docs, but I'm not having luck implementing ValueSaver with a Record field.

I have a table with the following field in the schema.
![screenshot 2018-03-09 at 13 59 24](https://user-images.githubusercontent.com/1325560/37224730-525a3e2e-23a2-11e8-8570-924b18ba9489.png)

My value saver interface returns the following
```
(string) (len=10) "properties": (export.Saver) (len=1) {                                                                           
  (string) (len=5) "hello": (string) (len=5) "world"                                                                                
 }
```

I've also tried a other options
```
(string) (len=10) "properties.hello": (string) (len=5) "world"
```

I get the following error on the insert with each of the attempts
```
(bigquery.RowInsertionError) insertion of row [insertID: "a5b112be-3848-4938-900a-3fee73f90585"; insertIndex: 0] failed with error:
{Location: "properties"; Message: "no such field."; Reason: "invalid"}
```

**Comment by jba** [comment]
First, have you tried writing a Go struct to match your schema, so you won't need a custom `ValueSaver`?

Second, I don't understand how to convert the output you are displaying into a `map[string]Value`, which is what a `ValueSaver` returns. I don't think I've ever seen that format before.

But we represent records as `[]Value`s, so you should try
```
map[string]Value{
    "properties": []Value{"world"},
}
```
However, I think my first suggestion is best: write a Go struct. Something like this (untested):
```
type Foo struct
    Properties *Properties `bigquery:"properties,nullable"`
}

type Properties struct {
    Hello string `bigquery:"hello"`
}
```
You can call `InferSchema` on a `Foo{}` to see if you get the same schema that you defined by hand.

**Comment by jimmiebtlr** [comment]
We're using a map in the struct that contains user-specific data (don't know it beforehand). Pretty messy, but basically trying to update the schema then push the document when a new field is present.

```
type Foo struct {
  Properties map[string]interface{}{"hello": "world"}
}
```

Which my saver implementation converts to 
```
map[string]Value{
  "properties: Value(map[string]Value{ 
    "hello": Value("world")
  })
}
```

**Comment by jimmiebtlr** [comment]
Hmm, seems to be working now

May have had
```
map[string]Value{
  "properties: map[string]Value{ 
    "hello": Value("world")
  }
}
```

instead of 
```
map[string]Value{
  "properties: Value(map[string]Value{ 
    "hello": Value("world")
  })
}
```

**Comment by jba** [comment]
Glad you got it. You were right about using a nested map.
