### ISSUE TITLE
Datastore: Filtering with equality fails with FailedPrecondition desc = no matching index found

### ISSUE THREAD

**Issue by ChrisBartonLC** [GoogleCloudPlatform/google-cloud-go#930]
According to the docs:

https://cloud.google.com/datastore/docs/concepts/queries#datastore-equal-and-inequality-range-go
"Note that a query can combine equality (EQUAL) filters for different properties, along with one or more inequality filters on a single property. Thus the following is a valid query:"

    query := datastore.NewQuery("Task").
        Filter("Priority =", 4).
        Filter("Done =", false).
        Filter("Created >", time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC)).
        Filter("Created <", time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC))

However when I create the simple table in the attached screenshot the following code from the docs fails:

	q := datastore.NewQuery("Task").Namespace("test").
		Filter("Priority =", 4).
		Filter("Done =", false).
		Filter("Created >", time.Date(1990, 1, 1, 0, 0, 0, 0, time.UTC)).
		Filter("Created <", time.Date(2018, 3, 9, 0, 0, 0, 0, time.UTC))

	var t []*task
	if _, err := datastoreClient.GetAll(ctx, q, &t); err != nil {
		log.Printf("Failed reading: %v", err)
	}

Error is:

    2018/03/10 09:24:16 Failed reading: rpc error: code = FailedPrecondition desc = no matching index 
    found. recommended index is:
    - kind: Task
      properties:
      - name: Done
      - name: Priority
      - name: Created

![screen shot 2018-03-10 at 9 21 59 am](https://user-images.githubusercontent.com/31261535/37228308-09ef8358-2445-11e8-9d62-80b964996a3f.png)

**Comment by jba** [comment]
I think you'll need to define an index for that query. See https://cloud.google.com/datastore/docs/concepts/indexes#index_configuration.

**Comment by ChrisBartonLC** [comment]
Thanks very much!
