### ISSUE TITLE
Firestore, JSON interop issue

### ISSUE THREAD

**Issue by hiranya911** [GoogleCloudPlatform/google-cloud-go#931]
I'm having an issue with JSON/Firestore interoperability.

I have a webapp that receives JSON POST requests:

```
{
   "name": "Peter",
   "age": 20
}
```

I have a struct that I use to unmarshal these payloads:

```
type User struct {
  Name string `json:"name,omitempty"`
  Age int     `json:"age,omitempty"`
}
```

Once unmarshal'ed  I may want to save the struct to Firestore. But to handle this properly I need a struct that has `firestore:""` options. Otherwise the values gets saved with incorrect field names (`Name` and `Age` instead of `name` and `age`). How do we handle such use cases where JSON and Firestore support need to be used together?

**Comment by hiranya911** [comment]
Similarly what if I want to unmarshal a struct populated from Firestore into JSON?

**Comment by jba** [comment]
You can have multiple key-value pairs in a tag (https://golang.org/pkg/reflect/#StructTag). So write
```
Name string `json:"name,omitempty" firestore:"name"`
```
