### ISSUE TITLE
bigtable: emulator does not validate DeleteFromColumn time range.

### ISSUE THREAD

**Issue by coryan** [GoogleCloudPlatform/google-cloud-go#932]
It is possible to create an invalid (or empty) time range when using `google.bigtable.v2.DeleteFromColumn`.  The production server rejects such requests, but the emulator accepts them.  Ideally both should have the same behavior.

**Comment by alok-ch** [comment]
@jba I think this was closed

**Comment by jba** [comment]
@alok-ch Are you saying it was fixed? What is the commit?

**Comment by alok-ch** [comment]
@jba https://github.com/GoogleCloudPlatform/google-cloud-go/commit/2bc5ce7068b721f658f2752a5056e542be229cf4

**Comment by jba** [comment]
That CL checks that each timestamp is valid, but does not check that the range is valid. According to this issue, the emulator should return an error if start time >= end time. Please test against the real service to confirm and to determine the error code to return.

**Comment by sduskis** [comment]
Just saw that [f05ab16](https://github.com/GoogleCloudPlatform/google-cloud-go/commit/f05ab167efe4a7a9b334f85ed0195500a5847150) fixed this.
