### ISSUE TITLE
firestore: build is broken

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-go#934]
```
GOPATH=/tmp/a go get cloud.google.com/go/...
cd # cloud.google.com/go/firestore
/tmp/a/src/cloud.google.com/go/firestore/order.go:86:44: a.ValueType undefined (type "google.golang.org/genproto/googleapis/firestore/v1beta1".isValue_ValueType has no field or method ValueType)
```

/cc @jba @jadekler

**Comment by jadekler** [comment]
Thanks @rakyll . jba@ is on it already! :)

**Comment by jadekler** [comment]
Relevant CL since it isn't linked in the CL (race condition): https://code-review.googlesource.com/c/gocloud/+/25050

**Comment by jadekler** [comment]
Fixed in https://github.com/GoogleCloudPlatform/google-cloud-go/commit/4fbeceac687c13e25446c72edd980fd259cffac3
