### ISSUE TITLE
bigquery: api respones code

### ISSUE THREAD

**Issue by kurtmaile** [GoogleCloudPlatform/google-cloud-go#937]
Hi Jonathan,

Making great progress with the library thanks so much for all your help.

Quick (hopefully simple) question.

Is there a structured way to access the http response code from bq.  e.g 404 for a table not existing?

Or would I need to parse a string to do so?

Cheers!

**Comment by jba** [comment]
Usually you can type-assert to `googleapi.Error`. For example, see [this check in our integration test](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/ada5c911bc7ed125d88d725d368eb5b4f0f731ea/bigquery/integration_test.go#L1059).

(General tip: reading the integration tests is a good way to learn how to use these clients.)
