### ISSUE TITLE
Block forever on uploading file to GCS is GCS server return status code other the 2XX

### ISSUE THREAD

**Issue by zakyke** [GoogleCloudPlatform/google-cloud-go#940]
(delete this for feature requests)

## Client

e.g. Storage

## Describe Your Environment
Go 1.10 on Linux 

## Expected Behavior
Retry to upload file should not be automatic. Let the user decide about retry.
Or, set a default timeout

## Actual Behavior
```
ctx := context.Background()
gsclient, err := storage.NewClient(ctx, opt...)
uploader := gsclient.Bucket(bucket)
wc := uploader.Object(key).NewWriter(ctx)
 wc.Write(bufCopy.Bytes())
wc.Close() // Block forever if GCS service return status code > 299
```

## Workaround
Use context with timeout.
```
ctx, cancel := context.WithTimeout(context.Background(), s.config.HTTPClientTimeout)
defer cancel()
```

**Comment by jba** [comment]
That's not merely a workaround. All our client libraries are designed to retry indefinitely. Setting a timeout on the context is the intended way to stop them.

**Comment by zakyke** [comment]
I find it hard to believe that any client wants to retry indefinitely, but leaving that aside, this should be documented some where and should be mandatory in the examples.

**Comment by jba** [comment]
Good points. Repurposing this issue.
