### ISSUE TITLE
Reference JWTConfigFromJSON example in the README?

### ISSUE THREAD

**Issue by DallanQ** [GoogleCloudPlatform/google-cloud-go#95]
You might want to consider pointing people directly to the JWTConfigFromJSON example in the oauth2 docs: https://godoc.org/golang.org/x/oauth2/google#example-JWTConfigFromJSON

Currently the README just points people to the root of the oauth2 docs, and it's difficult to realize that the procedure you want to follow if you are using a service account is the one outlined in the JWTConfigFromJSON example.

**Comment by jba** [comment]
@rakyll, assigning you back since I believe there's been some movement in this area. 

The real question is, Does the README give good auth guidance?

/cc @broady

**Comment by rakyll** [comment]
We should probably add an auth section and mention application-default credentials and WithServiceAccountFile from the README.

We already have these snippets in the godoc but there are at a very visible level.

https://godoc.org/cloud.google.com/go#example-package--ApplicationDefaultCredentials
https://godoc.org/cloud.google.com/go#example-package--ServiceAccountFile
