### ISSUE TITLE
DataStore Client unable to reach Cloud DataStore API when running inside Alpine 3.7 container

### ISSUE THREAD

**Issue by drausin** [GoogleCloudPlatform/google-cloud-go#952]
## Client

DataStore

## Describe Your Environment

[Alpine 3.7 Docker](https://github.com/gliderlabs/docker-alpine/blob/61c3181ad3127c5bedd098271ac05f49119c9915/versions/library-3.7/x86_64/Dockerfile)

## Expected Behavior

Application can communicate with Cloud DataStore API. 

## Actual Behavior

Application cannot communicate with Cloud DataStore API. Requests hang.

I have a Golang application that intends to use DataStore. It is able to communicate with the public DataStore when I'm running directly on my local machine (go1.9.2 darwin/amd64), but when I built it statically via
```
GOOS=linux go build -ldflags "-extldflags '-lpthread -static'" -a -installsuffix cgo -o app pkg/main.go
```
and then ran inside an Alpine 3.7 Docker container, it hangs (no error other than the eventual timeout) on the request. If I change the base container to [Alpine 3.7 + Golang](https://github.com/docker-library/golang/blob/906e04de73168f643c5c2b40dca0877a14d2377c/1.10/alpine3.7/Dockerfile), the same static binary talks with DataStore just fine. 

Not sure exactly what's going on here under the covers, since I assumed that the static binary would include all the libraries it needs. Perhaps there are additional non-golang libs included with the golang container that DataStore client lib requires? If this is the case, perhaps we could add some documentation somewhere about this limitation so that other users know use containers with these libs. 

I'd be happy to update the docs but am not sure where the appropriate places are.

**Comment by jadekler** [comment]
Hello @drausin! Try `apk add ca-certificates`, and let me know if that solves the problem? If so, it is because of [this issue](https://github.com/grpc/grpc-go/issues/1768) (ca-certificates are not installed by default in alpine, and grpc retries-and-fails-without-certificates endlessly).

**Comment by jadekler** [comment]
Closing, feel free to re-open if that does not solve your problem.

**Comment by drausin** [comment]
Doh! Should have thought of that myself. I figured it'd be something stupid like that. I can confirm that `apk add ca-certificates` fixes the problem. Thanks @jadekler

**Comment by jadekler** [comment]
No prob - you got it!
