### ISSUE TITLE
Use of internal package not allowed

### ISSUE THREAD

**Issue by sethvargo** [GoogleCloudPlatform/google-cloud-go#954]
## Client

Storage

## Describe Your Environment

Mac OS X

## Expected Behavior

```
$ GOCACHE=off go test ./...
PASS
```

I should be able to vendor the library.

## Actual Behavior

```
$ GOCACHE=off go test ./...
vendor/cloud.google.com/go/storage/acl.go:21:2: use of internal package not allowed
```

https://github.com/GoogleCloudPlatform/google-cloud-go/commit/ff2b4e26e6465e78ac37248cf3e6355f4a935b37

Refs to internal package errors

## Repro

- https://github.com/sethvargo/internal-package-ref-repro

**Comment by broady** [comment]
You need to vendor the internal/trace package too.

**Comment by sethvargo** [comment]
So would you say this is a bug in govendor then? It's not pulling in internal/* packages when I pull in `cloud.google.com/go/storage...`

**Comment by broady** [comment]
Seems like it. Any vendoring system should vendor every transitive
dependency.

**Comment by jadekler** [comment]
@sethvargo Try pulling in `cloud.google.com/go/...` instead of `cloud.google.com/go/storage/...`. It probably didn't pull in that package because internal is at `cloud.google.com/go/internal/...`, if I had to guess (although it would be nice if it were smarter).

**Comment by broady** [comment]
Yeah, that's pretty strange. It did bring in other dependencies (like `google.golang.org/api/transport`) and even other packages under `cloud.google.com/go/internal`.

Marking as closed, but please do follow up with `govendor`.
