### ISSUE TITLE
List links to other language doc pages in alphabetical order (and add link to C++)

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-go#956]
Please update drop down menu of [Go docs page](https://googlecloudplatform.github.io/google-cloud-go/#/)

## Expected Behavior
.NET, C++, Go, Java, Node.js , PHP, Python, Ruby

## Actual Behavior
.NET, Java, Go, Node.js, PHP, Python, Ruby

![image](https://user-images.githubusercontent.com/3130752/38265876-fc0ebf48-372b-11e8-917f-88d2c562b624.png)

**Comment by jadekler** [comment]
Might be good one for @tbpg ? Also, I'd like to know where the codebase for that page lives heh

**Comment by tbpg** [comment]
@jba, do you have the source for this site? Looks like you're the only one who's edited the gh-pages branch and it's all minified.

**Comment by jba** [comment]
I think it's https://github.com/GoogleCloudPlatform/google-cloud-common/tree/master/site.

**Comment by tbpg** [comment]
Order was fixed in GoogleCloudPlatform/google-cloud-common#254.
