### ISSUE TITLE
Allow users to specify user-agent in compute package

### ISSUE THREAD

**Issue by sethvargo** [GoogleCloudPlatform/google-cloud-go#957]
## Client

Compute

## Describe Your Environment

Mac OS X

## Expected Behavior

I should be able to set a custom user agent, either directly or via options like other packages.

## Actual Behavior

The userAgent is hard coded to gcloud-golang/0.1 in [metadata.go](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/compute/metadata/metadata.go).

**Comment by jadekler** [comment]
Seems reasonable to me. @broady any objections?

**Comment by broady** [comment]
No objections. The most straightforward way would be to set a package-level variable. That is:

```
metadata.UserAgent = "myapp/0.1"
```

Exposing options would mean a bigger overhaul of the package (adding a `Client` type, probably).

What's the use case?

**Comment by sethvargo** [comment]
My argument against global values like that (especially in a client library) is that it creates a "race to the finish" with whichever importer sets it last.

The use case is tracking usage and requests. Right now, all requests to the metadata server from this library are completely indistinguishable, and users have no way of customizing the header.

**Comment by broady** [comment]
How do you track requests to the metadata server? I understand the general need for good user agents, but don't understand why it matters for metadata requests.

**Comment by jba** [comment]
Thank you for filing this issue. We asked some clarifying questions or suggested a course of action a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to comment with more information and we will re-open this issue.

**Comment by jba** [comment]
See https://code-review.googlesource.com/c/gocloud/+/29031.
