### ISSUE TITLE
runtime/pprof CPU profiler does not capture any samples under cloud debugger

### ISSUE THREAD

**Issue by zeroflaw** [GoogleCloudPlatform/google-cloud-go#960]
## Client
Compiled on: 
golang 1.10.1 
"cloud.google.com/go/profiler" v0.21.0

## Describe Your Environment
busybox:1.28.0-glibc Docker on GKE

## Expected Behavior
See CPU & Contention statistics captured from profiler agent, in the Stackdriver developer console.

## Actual Behavior
Can see Heap & Threads working.

I enabled debug logging and saw lots of:
2018-04-10 19:29:17.088 BST successfully created profile CPU
2018-04-10 19:29:27.133 BST start uploading profile

However nothing is ever available to view in the Stackdriver developer console.

Let me know if you need anything extra.
fyi, I did run: gcloud services enable cloudprofiler.googleapis.com

**Comment by zeroflaw** [comment]
I would like to add, I ran this on my local machine. And I got CPU stats working, still no contention.

**Comment by jba** [comment]
@nolanmar511

**Comment by aalexand** [comment]
@zeroflaw What does the profiler UI looks like when you open it / refresh it? Does it have the CPU choice in the profile type combo-box?

**Comment by zeroflaw** [comment]
This is what I see

![myscreen](https://user-images.githubusercontent.com/37941815/38580090-f790e114-3d00-11e8-991f-49698799bb99.jpg)

**Comment by zeroflaw** [comment]
I forgot to mention I use the stackdriver debugger (go-cloud-debug)
Which might be part of the problem because I think it was last compiled on go 1.7 which maybe part of the problem. Are you able to easily generate a go 1.10.1 build, which I try?

I've done the following tests:

Without debugger
base docker image busybox:1.28.0-glibc = failed
base docker image busybox:1.28.3-glibc = failed
base docker image alpine-3.7 = failed
base docker image golang:1.10.1-alpine3.7 = failed
base docker image bitnami/minideb:latest = Worked!!

with debugger
base docker image bitnami/minideb:latest = failed

I'm not sure if the above is helpful, but at no point is the debug logging from the profiler telling me anything other than its all good. So is something not being processed correctly on the stackdriver endpoint? should I go ahead a capture the messages and compare them?

**Comment by aalexand** [comment]
One possible reason of not seeing any data is that there is little (i.e. ~zero) CPU usage in your service. What's the CPU utilization of the service process according to `top` command?

**Comment by zeroflaw** [comment]
basically zero, i'll throw in some code to generate some extra, load. 
I'll get back to you in a moment.

**Comment by zeroflaw** [comment]
With some additional load busybox:1.28.3-glibc without debugger, is working.
Nothing works with the debugger attached.

**Comment by zeroflaw** [comment]
I've done plenty of tests going debugger on/off and none of them have worked using go-cloud-debug.
I'm going try rebuilding go-cloud-debug with 1.10.1

**Comment by aalexand** [comment]
Stackdriver Profiler uses Go's runtime/pprof package to get CPU profiles. The debugger agent runs the program under a debugger, see https://code.googlesource.com/gocloud/+/master/cmd/go-cloud-debug-agent/debuglet.go#108 - I wonder if running under debugger makes runtime/pprof CPU profiling not working.

**Comment by aalexand** [comment]
The issue is not specific to the Stackdriver Profiler profiling agent, but rather to runtime/pprof CPU profiling in general. To reproduce, save the example code below as a `pprof-profile.go` file, then:

```
# Build the example
$ go build pprof-profile.go

# Run the example without debugger.
# This works as expected, collects some data.
$ ./pprof-profile
profile collected with 343 samples

# Download the debugger agent per instructions at
# https://cloud.google.com/debugger/docs/setup/go
$ wget -O go-cloud-debug https://storage.googleapis.com/cloud-debugger/compute-go/go-cloud-debug
chmod 0755 go-cloud-debug

# Run the example under debugger.
# This doesn't work as expected, zero samples are collected.
$ ./go-cloud-debug ./pprof-profile 
profile collected with 0 samples
```

Example source:
```go
package main

import (
  "bytes"
  "compress/gzip"
  "fmt"
  "log"
  "math/rand"
  "runtime"
  "runtime/pprof"
  "time"

  "github.com/google/pprof/profile"
)

// busywork continuously generates 1MiB of random data and compresses it
// throwing away the result.
func busywork() {
  for {
    busyworkOnce()
  }
}

func busyworkOnce() {
  const size = 1024 * 1024

  data := make([]byte, size)
  rand.Read(data)

  var b bytes.Buffer
  gz := gzip.NewWriter(&b)
  if _, err := gz.Write(data); err != nil {
    log.Fatalf("Failed to write to gzip stream", err)
  }
  if err := gz.Flush(); err != nil {
    log.Fatalf("Failed to flush to gzip stream", err)
  }
  if err := gz.Close(); err != nil {
    log.Fatalf("Failed to close gzip stream", err)
  }
  // Throw away the result.
}

func main() {
  runtime.GOMAXPROCS(2)
  go busywork()

  var b bytes.Buffer
  pprof.StartCPUProfile(&b)
  time.Sleep(5 * time.Second)
  pprof.StopCPUProfile()

  p, err := profile.Parse(&b)
  if err != nil {
    log.Fatalf("failed to parse collected profile: ", err)
  }
  fmt.Printf("profile collected with %d samples\n", len(p.Sample))
}
```

**Comment by aalexand** [comment]
Update: https://go-review.googlesource.com/c/debug/+/107675 should solve the issue.

**Comment by zeroflaw** [comment]
👍 how would I go about taking this change? is it the go-cloud-debug or my app that needs updating?

**Comment by jba** [comment]
This change should be in the [Go debug agent at head](https://code.googlesource.com/gocloud/+/master/cmd/go-cloud-debug-agent).

**Comment by zeroflaw** [comment]
Works. Good job :)

**Comment by zeroflaw** [comment]
okay so, I'm sometimes getting the error: 
`"standard_init_linux.go:178: exec user process caused "exec format error"` on startup of Kubernetes pods. It sometimes works (nothing is changing, image is the same as the time it worked)

Not sure how I can provide any more details, but I'm happy to help.
