### ISSUE TITLE
Logging: Entry struct is missing SourceLocation

### ISSUE THREAD

**Issue by maxannear** [GoogleCloudPlatform/google-cloud-go#963]
As documented here: 
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry

The log entry supports a `LogEntrySourceLocation` which has a JSON body of 
```
{
  "file": string,
  "line": string,
  "function": string
}
```

Looks like this hasn't been implemented yet on the Entry struct

Would be a great feature, especially considering how easy is it get `file` and `line` by calling `runtime.Caller()`

**Comment by ashi009** [comment]
(um... it's almost 3 months for a p1 bug) 

@jba It seems a minor issue to fix. If there is no preference on how this proto message should presented in the logging package (eg. by aliasing the message in logging package), I can take this one.
