### ISSUE TITLE
Adding a struct to collection time.Time field is missing

### ISSUE THREAD

**Issue by mblasi** [GoogleCloudPlatform/google-cloud-go#974]
(delete this for feature requests)

## Client

golang-firestore-client

## Describe Your Environment

App Engine Flexible environment, Go

## Expected Behavior

Docuemented created, with its creation time:

type Offer struct {
Created time.Time
User string
}

offer := Offer{Created: time.Now(), User: "username"}

store.Collection("offers").Add(ctx, offer)

I hope to have a new object in offers collection with created time and user fields.

## Actual Behavior

The object in the firestore database, has only the user filed, the created time is lost.

If I do this:

doc:= store.Collection("offers").NewDoc()

doc.Create(ctx, map[string]interface{}{"created": offer.Created, "user": offer.User})

I have the document with both fields: Created and User.

**Comment by mblasi** [comment]
If that works, I close this issue... I'll try upgrading dependency... I actually changed all my .Add() to .NewDoc().Create().... don't know what could be...

Thangs again!

**Comment by nicolasparada** [comment]
I'm getting this issue now using `.Create()`.

**Comment by nicolasparada** [comment]
As a workaround, I'm using firestore `DocumentSnapshot` `CreateTime`.
But still...
