### ISSUE TITLE
bigtable: In the cbt help, use imperatives in command descriptions, and fix the listclusters description

### ISSUE THREAD

**Issue by hegemonic** [GoogleCloudPlatform/google-cloud-go#977]
For the cbt command, most of the [command descriptions](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/05862f1a656dcf9aefbefad9443ee8ad79670697/bigtable/cmd/cbt/cbt.go#L196) start with imperatives, such as "Create" and "Update." However, the descriptions of a few commands start with descriptors, such as "Deletes." We should update these commands to use imperatives instead:

+ [`deleteinstance`](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/05862f1a656dcf9aefbefad9443ee8ad79670697/bigtable/cmd/cbt/cbt.go#L260)
+ [`deletecluster`](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/05862f1a656dcf9aefbefad9443ee8ad79670697/bigtable/cmd/cbt/cbt.go#L267)
+ [`waitforreplication`](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/05862f1a656dcf9aefbefad9443ee8ad79670697/bigtable/cmd/cbt/cbt.go#L392)

We should also fix the description of [`listclusters`](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/05862f1a656dcf9aefbefad9443ee8ad79670697/bigtable/cmd/cbt/cbt.go#L325), which currently says "List instances within an instance." (The fix is `s/instances/clusters/`.)

**Comment by danielhultqvist** [comment]
This has been fixed in `master` and issue should be closed
