### ISSUE TITLE
Missing HTTP method and request body?

### ISSUE THREAD

**Issue by mblasi** [GoogleCloudPlatform/google-cloud-go#978]
(delete this for feature requests)

## Client

google-cloud-golang

## Describe Your Environment

A google cloud app engine flexible envinroment, running a golang appication serving a rest api.

## Expected Behavior

I trace thre requests with golang-stackdriver-api (https://cloud.google.com/trace/docs/reference/)
I hope to see HTTP Method for each request, and also the request body.

## Actual Behavior

I just see the request and its elapsed time:

![image](https://user-images.githubusercontent.com/40089/39090861-e130442e-45bf-11e8-9643-dc70700107d5.png)

Here is my code (for each span):
``
import (
"go.opencensus.io/trace"
"go.opencensus.io/exporter/stackdriver"
)

func init() {
        exporter, err := stackdriver.NewExporter(stackdriver.Options{ProjectID: projectID})
        if err != nil {
                panic()
        }
        trace.RegisterExporter(exporter)
        trace.SetDefaultSampler(trace.AlwaysSample())
}

func StartSpan(ctx context.Context, name string) (context.Context, *trace.Span) {
        return trace.StartSpan(ctx, name)
}

func NewSpan(name string) (context.Context, *trace.Span) {
        return trace.StartSpan(context.Background(), name)
}
``

**Comment by jba** [comment]
Sorry we haven't responded. Are you still having this issue?

Note that the trace package is obsolete.

@ramonza @rakyll

**Comment by jba** [comment]
We haven't heard back from you in a while, so we're closing this issue.

**Comment by mblasi** [comment]
Hi, sorry for the delay. First of all thank you for take it up!
I'm still seeing this issue in the trace screen: no http method specified neither response code is informed for every traced request.
Though, you say that this package is obsolete, my question is: what is the current package for handling this?

Best regards,
Matías.

**Comment by mblasi** [comment]
Is this the last way: https://cloud.google.com/trace/docs/setup/go ?

**Comment by rakyll** [comment]
https://cloud.google.com/trace/docs/setup/go is the new canonical way. Please feel free to file bugs at https://github.com/census-instrumentation/opencensus-go.
