### ISSUE TITLE
Build failure: cloud.google.com/go/bigquery

### ISSUE THREAD

**Issue by h8liu** [GoogleCloudPlatform/google-cloud-go#979]
(delete this for feature requests)

## Client

e.g. cloud.google.com/go/bigquery

## Describe Your Environment

e.g. alpine docker, go 1.10.1

## Expected Behavior

`go get -u` builds

## Actual Behavior

# cloud.google.com/go/bigquery
src/cloud.google.com/go/bigquery/query.go:166:22: cannot use true (type bool) as type *bool in assignment
src/cloud.google.com/go/bigquery/query.go:168:22: cannot use false (type bool) as type *bool in assignment
src/cloud.google.com/go/bigquery/query.go:199:15: cannot use qq.UseLegacySql (type *bool) as type bool in field value
src/cloud.google.com/go/bigquery/query.go:200:22: invalid operation: ! *bool

// https://smallrepo.com/builds/20180424-010626-4b0ed4e0

Breakage found by [smallrepo.com](https://smallrepo.com)

**Comment by jba** [comment]
Reproduced. Looking into it.

**Comment by jba** [comment]
Until it gets submitted, you can patch in https://code-review.googlesource.com/#/c/gocloud/+/26730.
