### ISSUE TITLE
Speech Client support for using enhanced models (phone_call)

### ISSUE THREAD

**Issue by raja** [GoogleCloudPlatform/google-cloud-go#985]
Just curious what the status of updating the client to support the enhanced recognition models. I noticed the speech protobuf package has been updated with v1p1beta that seems to support this in the option struct.

https://github.com/google/go-genproto/blob/master/googleapis/cloud/speech/v1p1beta1/cloud_speech.pb.go

## Client
Speech

**Comment by jba** [comment]
@pongad, should we start generating these?

**Comment by pongad** [comment]
Java is already doing it so I suppose we should too.

**Comment by snktagarwal** [comment]
https://godoc.org/cloud.google.com/go: When do the client libraries get generated? Is there a cron or something doing this? I am not seeing v1p1beta1 generated yet.

**Comment by pongad** [comment]
redirects are published: https://godoc.org/cloud.google.com/go/speech/apiv1p1beta1
