### ISSUE TITLE
Cannot get rows from bigtable

### ISSUE THREAD

**Issue by smousa** [GoogleCloudPlatform/google-cloud-go#991]
## Client
bigtable

## Describe Your Environment
go microservice making queries against bigtable running on gcp 

## Expected Behavior
Get rows from bigtable

## Actual Behavior
```
< HTTP/1.1 500 Internal Server Error
< Server: nginx
< Date: Fri, 04 May 2018 14:47:13 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
<
{
"code": 2,
"message": "could not read rows from bigtable: rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html; charset=UTF-8\"",
"details": [
 {
  "@type": "type.googleapis.com/google.rpc.DebugInfo",
  "stackEntries": [],
  "detail": "internal"
 }
]
}
```

**Comment by smousa** [comment]
I figured it out.  When making requests to functions on the client, you have to use an empty context `context.Background()` and not the same context that you use to initialize the client.

**Comment by jadekler** [comment]
I was just about to label this - glad you figured it out though! :)

**Comment by smousa** [comment]
The context was coming from a curl call to cloud endpoints that passed the request to the service
