### ISSUE TITLE
Bigtable: support start_key_open, end_key_closed in RowRange 

### ISSUE THREAD

**Issue by bronze1man** [GoogleCloudPlatform/google-cloud-go#995]
The bigtable data rpc have start_key_open, end_key_closed in RowRange: https://cloud.google.com/bigtable/docs/reference/data/rpc/google.bigtable.v2#google.bigtable.v2.RowRange 
But this library do not have this feature.It can only have start_key_closed and end_key_open in RowRange.

**Comment by jba** [comment]
You can get those ranges by appending a zero byte to the keys:
```
NewRange(start, end)           // [start, end)
NewRange(start, end + "\x00")  // [start, end]
NewRange(start + "\x00", end)  // (start, end)
```

**Comment by bronze1man** [comment]
@jba thanks. 
That is a great idea.
