### ISSUE TITLE
go/httpreplay/internal/proxy go get status code 404

### ISSUE THREAD

**Issue by vsiv** [GoogleCloudPlatform/google-cloud-go#999]
(delete this for feature requests)

## Describe Your Environment

mac go get/glide

Seeing this error from go get or using glide... 

go get -v -u cloud.google.com/go/httpreplay/internal/proxy
Fetching https://cloud.google.com/go/httpreplay/internal/proxy?go-get=1
Parsing meta tags from https://cloud.google.com/go/httpreplay/internal/proxy?go-get=1 (status code 404)

Any help appreciated.
Thanks.

**Comment by jba** [comment]
This should be fixed.
